### ISSUE TITLE
right click on START crashes with Windows 10 taskbar style

### ISSUE THREAD

**Issue by gregkotsaftis** [valinet/ExplorerPatcher#2878] opened 2024-02-21 10:14 UTC
it happens in version 22621.3007.63.3 (and to older versions up to last month that i checked)

I was trying to right click on START and run Terminal as admin,

1) every second click the explorer crashes and refreshes
2) terminal/powershell does not start with admin privileges

clean installation of TINY11:

Edition	Windows 11 Pro
Version	23H2
Installed on	‎07/‎05/‎2022
OS build	22631.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by pyrates999** [comment] 2024-02-21 10:19
if you disabled tabs in windows file explorer, you must re-enable them, otherwise you will have crashes:

```
vivetool /reset /id:37634385

reboot

vivetool /disable /id:37634385

vivetool /enable /id:37634385

reboot
```

this is not a bug with EP

**Comment by gregkotsaftis** [comment] 2024-02-21 10:24
> if you disabled tabs in windows file explorer, you must re-enable them, otherwise you will have crashes:
> 
> ```
> vivetool /reset /id:37634385
> 
> reboot
> 
> vivetool /disable /id:37634385
> 
> vivetool /enable /id:37634385
> 
> reboot
> ```
> 
> this is not a bug with EP

i have not touched anything, it is a clean installation of tiny11.
explorer tabs are working i just checked.

also, if i change the taskbar style back to Windows 11 style, the right click open "terminal as admin" works and no more crashes !

**Comment by Amrsatrio** [comment] 2024-02-21 10:25
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2156

**Closed by Amrsatrio** 2024-02-21 10:25 UTC

**Comment by gregkotsaftis** [comment] 2024-02-21 10:35
I enabled the console.
When i right click on START with windows 10 taskbar style, the explorer restarts and the log output is below:

Running on Windows 11, OS Build 10.0.22631.3155.
Loaded symbols
Setup user32 functions done
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 47480
Patched taskbar transparency in newer OS builds
ITrayUIHost = 3BB318
explorer.exe!TrayUI_CreateInstance() = 1A447C
Setup explorer functions done
Setup uxtheme functions done
[AC] rcMonitorAssignment = 396C1
[AC] blockBegin = 396D6
[AC] blockEnd = 39787
[AC] Patched!
[CC] rcMonitorAssignment = 34CBB
[CC] rcWorkAssignment = 34D88
[CC] blockBegin = 34CD3
[CC] blockEnd = 34DA1
[CC] Patched!
[TC] rcMonitorAssignment = 355D0
[TC] blockBegin = 355EA
[TC] blockEnd = 3569F
[TC] Patched!
[TV] firstCallPrep = 24E35
[TV] firstCallCall = 24E3F
[TV] Patched!
[HC] match1 = 1D56D
[HC] match2 = 1D634
[HC] writeAt = 1D22E
[HC] cleanup = 1D645-1D65A
[HC] Patched!
PenMenuSystemTrayManager::GetDynamicSystemTrayHeightForMonitor() = 480A40
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
wil::details::FeatureImpl<__WilFeatureTraits_Feature_Servicing_TaskbarMultiMon_38545217>::__private_IsEnabled() = 110E68
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
[Positioning] Added settings for monitor 0000000000010001 : 0
Registered Win+A, Win+B, and Win+N
Progman: 459364
Progman hook: 786605
0 0
>>> Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.3007.63.3.7638f76208571b7c"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.3007.63.3.7638f76208571b7c" (valid).
[Updates] Local version obtained from hash is 22622.3007.63.3.
[Updates] No updates are available.

**Comment by pyrates999** [comment] 2024-02-21 11:08
tiny 11? as in you're using a custom version of windows 11 with some parts removed?

**Comment by gregkotsaftis** [comment] 2024-02-21 12:06
Yes, sorry i thought it was widely known...

[https://github.com/ntdevlabs/tiny11builder](url)
[https://www.tomshardware.com/news/tiny11-23h2-windows-released-with-greater-functionality-numerous-bugfixes](url)

**Comment by gregkotsaftis** [comment] 2024-02-23 09:16
just today this issue started occurring in my old Win11 pc that was a normal clean installation of original windows 11 (not tiny11)
and was working without problems for months...

**Comment by pyrates999** [comment] 2024-02-23 11:34
Scroll up and you'll see this is a duplicate issue and already known.
