### ISSUE TITLE
Brightness and Volume OSD not displaying on my second monitor

### ISSUE THREAD

**Issue by Shnxxx** [valinet/ExplorerPatcher#1790] opened 2023-08-06 18:56 UTC
Hi!

I'm using my laptop with a bigger monitor as the main display (using "**Second screen only**" mode). However, when I adjust the volume, the OSD appears only on my laptop's monitor, not the second monitor. It's a hassle to manually click the volume button on the taskbar.

I'm using the latest version of ExplorerPatcher (**22621.1992.56.1**).
Windows 11 Version 22H2 (OS Build 22621.1992)

Any help would be much appreciated!

**Comment by pyrates999** [comment] 2023-08-07 01:37
Try this: https://answers.microsoft.com/en-us/windows/forum/all/2-displays-extended-desktop-how-to-have-the-volume/127552ac-7732-4da9-b254-8565f1bcb7ad

**Comment by pyrates999** [comment] 2023-08-11 10:50
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1692

Please close this one.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:27
Duplicate of #1692

**Closed by Poopooracoocoo** 2023-08-22 10:27 UTC
