### ISSUE TITLE
Volume bar not appearing on screen anymore

### ISSUE THREAD

**Issue by negru13** [valinet/ExplorerPatcher#1964] opened 2023-08-30 10:42 UTC
Hi,
The volume and brightness bar stopped appearing on the screen when pressing the keyboard controls. 
Please fix this.

Regards

**Comment by ctitoc** [comment] 2023-08-30 12:46
Same here, also volume and brightness.

Btw thanks devs for the major crash after update solution.

**Comment by pyrates999** [comment] 2023-08-30 17:57
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

**Comment by rune5362** [comment] 2023-08-31 06:42
"Work around: set to use windows 11 taskbar instead of windows 10 taskbar."
applay =>
ExplorerPatcher restarted repeatedly and eventually got a warning suggesting deletion, so I deleted it.
------
This sentence was written using a translator.
I apologize if I was rude.

**Comment by Poopooracoocoo** [comment] 2023-08-31 09:02
Duplicate of #1692

**Closed by Poopooracoocoo** 2023-08-31 09:02 UTC
