### ISSUE TITLE
Volume Bar Windows 11 not showing on the screen

### ISSUE THREAD

**Issue by ElieAbb** [valinet/ExplorerPatcher#1983] opened 2023-09-03 12:23 UTC
Volume Bar Windows 11 not showing on the screen when I change the value from the keyboard shortcut.
Is there any fix?

**Comment by Poopooracoocoo** [comment] 2023-09-03 13:38
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1692

**Closed by Poopooracoocoo** 2023-09-03 13:38 UTC
