### ISSUE TITLE
Taskbar restarts Upon Using USB Volume control

### ISSUE THREAD

**Issue by Wontell** [valinet/ExplorerPatcher#783] opened 2022-02-04 20:46 UTC
So i have this strange issue, i even re-installed [22000.469.41.16] just to be sure. [Im on windows11 Insider preview, 22543.rs
When i use USB volume control, be it on my HyperX headset or on Razer Keyboard [has volume and mute], the taskbar just closes and re-opens [and volume is unafacted], it happens the second i move the wheel up or down or press the mute button, also my on screen volume is gone, before when i used USB volume mid game i would get a pop up in the top left corner of a screen, it would should the volume slider and my position on it, well its gone.

P.S. The Enable Symbols download option is enabled and after every PC reboot or Volume crash i get a pop up message that symbols downloaded please restart explorer
i have 6 new messages like this atm 19:35 [boot], 22:33, another one 22:33, 22:34, 22:35 [the volume crashes], 22:52 another volume crash ,had to verify

P.P.S I dont know if I should open another bug, but CTRL+X doesn't work, doesn't do anything

**Comment by DrDrrae** [comment] 2022-02-05 02:42
> P.S. The Enable Symbols download option is enabled and after every PC reboot or Volume crash i get a pop up message that symbols downloaded please restart explorer

This has something to do with commit 8119c5aa7c7a6427b43d8f464cf590ef6ef5406e. Going to a build before it, registry key CLauncherTipContextMenu::ShowLauncherTipContextMenu, is set to a usable value, going after it, the registry key is set to 0.
<img width="529" alt="image" src="https://user-images.githubusercontent.com/672350/152624951-bd426278-f9bb-4d13-b326-f21f018bd50f.png">
Once the value is set, it works fine.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/672350/152624996-368eee34-78cf-40ff-90bb-21343b2a01ea.png">

I most definitely don't know about C/C++ coding to be helpful, but I was able to compile a version that "works".
I removed the following lines from symbols.c:
https://github.com/valinet/ExplorerPatcher/blob/74204c7e84dc63d28fed0a6022225bcec3b60cdb/ExplorerPatcher/symbols.c#L244-L253
https://github.com/valinet/ExplorerPatcher/blob/74204c7e84dc63d28fed0a6022225bcec3b60cdb/ExplorerPatcher/symbols.c#L354-L361

**Comment by Wontell** [comment] 2022-02-05 02:48
> This has something to do with commit [8119c5a](https://github.com/valinet/ExplorerPatcher/commit/8119c5aa7c7a6427b43d8f464cf590ef6ef5406e). Going to a build before it, registry key CLauncherTipContextMenu::ShowLauncherTipContextMenu, is set to a usable value, going after it, the registry key is set to 0.

For now, after it downloaded symbols to the folder [dont rember the exact location] i disabled the Download Symbols option and it no longer bugs me with tens of messages that it downloaded symbols

**Comment by valinet** [comment] 2022-02-06 18:30
Should be fixed in the latest pre-release, it was an oversight on my part. Things like these can happen, no one checks the code besides me, and sometimes I may simply make mistakes. Thanks for the report, the additional info pointed me in the right direction.

**Closed** 2022-02-06 18:29 UTC

**Comment by Wontell** [comment] 2022-02-06 18:33
> Should be fixed in the latest pre-release, it was an oversight on my part. Things like these can happen, no one checks the code besides me, and sometimes I may simply make mistakes. Thanks for the report, the additional info pointed me in the right direction.

Hi,
I posted two bugs here [was my mistake that i posted them together]
Did you fixed the USB Volume crash issue or the Symbols always downloading after restarting explorer issues?

Regards

**Comment by valinet** [comment] 2022-02-06 18:41
The one regarding symbols. The other one I can't reproduce; I will test in a clean VM by adjusting the volume using the keyboard (that was basically it, right?). EP is not really supported on Insider Preview builds, as Microsoft may change stuff more often than I can keep pace with. Please do not open further issues. I have posted some rules that are constantly ignored [here](https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems) and they clearly states reports should be filled in Discussions. Thanks.

**Comment by valinet** [comment] 2022-02-06 18:41
> EDIT: Just updated to latest pre-release 469.42.5 and USB volume still crashes ExplorerPatcher Taskbar
SYMBLINK issue is fixed

Thanks for confirming regarding the symbols.

**Comment by Wontell** [comment] 2022-02-06 18:45
> The one regarding symbols. The other one I can't reproduce; I will test in a clean VM by adjusting the volume using the keyboard (that was basically it, right?). EP is not really supported on Insider Preview builds, as Microsoft may change stuff more often than I can keep pace with. Please do not open further issues. I have posted some rules that are constantly ignored [here](https://github.com/valinet/ExplorerPatcher/wiki/Reporting-problems) and they clearly state reports should be filled in Discussions. Thanks.

Yep, the moment I change volume the taskbar crashes and restarts, doesn't matter if its razer keyboard or HyperX headphone.
Also the on screen volume thingy is gone, when you use USB volume control you usually get a pop up in left top part of the screen, showing  virtual volume control and your position on it, it never pop ups.

**Comment by Wontell** [comment] 2022-02-06 18:57
> > EDIT: Just updated to latest pre-release 469.42.5 and USB volume still crashes ExplorerPatcher Taskbar
> > SYMBLINK issue is fixed
> 
> Thanks for confirming regarding the symbols.

Hey After updating to latest pre-release my windows folder text turned black and with black theme its invisible, 5 minutes ago on normal released version it was fine. Can it be some setting that changed?
