### ISSUE TITLE
Crash on right click on desktop

### ISSUE THREAD

**Issue by Luke-Software1024** [valinet/ExplorerPatcher#2627] opened 2023-12-27 14:24 UTC
Right-clicking on the desktop crashes Explorer (+ ExplorerPatcher report).

**Taskbar is a safe spot, and so is applications.**

**Comment by Amrsatrio** [comment] 2023-12-27 20:00
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218

**Closed by Amrsatrio** 2023-12-27 20:00 UTC
