### ISSUE TITLE
Conflict with KB5023774 in Windows 11

### ISSUE THREAD

**Issue by VV-SH** [valinet/ExplorerPatcher#1217] opened 2023-03-30 15:53 UTC
Hi!
Do you know about this conflict?

**Comment by VV-SH** [comment] 2023-03-30 18:02
This topic started a long time ago, and update KB5023774 was released on March 28, 2023
https://support.microsoft.com/en-gb/topic/march-28-2023-kb5023774-os-build-22000-1761-preview-67b4cfda-120a-422f-98c0-35124ddba839
==========
After installing this or later updates, Windows devices with some third-party UI customization apps might not start up. These third-party apps might cause errors with explorer.exe that might repeat multiple times in a loop. The known affected third-party UI customization apps are ExplorerPatcher and StartAllBack. These types of apps often use unsupported methods to achieve their customization and as a result can have unintended results on your Windows device.
==========

**Comment by VV-SH** [comment] 2023-03-31 08:56
The program StartMenuExperienceHost.exe version 0.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 8cc
 Start Time: 01d9626902348a10
 Termination Time: 4294967295
 Application Path: C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe
 Report Id: 8afb7136-c67b-48ad-99b9-eee6b70b2c26
 Faulting package full name: Microsoft.Windows.StartMenuExperienceHost_10.0.22000.778_neutral_neutral_cw5n1h2txyewy
 Faulting package-relative application ID: App
 Hang type: Cross-thread

**Comment by VV-SH** [comment] 2023-04-13 13:43
Will compatibility with updated Windows be restored or is it unrealistic?

**Comment by pyrates999** [comment] 2023-04-13 23:04
this appears to be a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1307

**Comment by VV-SH** [comment] 2023-04-25 14:57
I want to understand - is it possible to wait for a solution for this problem or should I look for other programs?

**Comment by VV-SH** [comment] 2023-04-29 16:27
https://support.microsoft.com/en-us/topic/april-11-2023-kb5025224-os-build-22000-1817-ebc75372-608d-4a77-a6e0-cb1e15f117fc
`If your Windows device is already experiencing this issue, you might need to contact customer support for the developer of the app you are using. If you are using StartAllBack, you might be able to prevent this issue by updating to the latest version (v3.5.6 or later).`

I want to know - will this problem be fixed in ExplorerPatch?

**Closed** 2023-09-23 04:52 UTC
