### ISSUE TITLE
Defect - 22621.4317.67.1 last used folder settings are ignored

### ISSUE THREAD

**Issue by explor202** [valinet/ExplorerPatcher#3891] opened 2024-11-05 18:37 UTC
Use case: AHK script runs and opens multiple folders on monitor 1. Next folder is opened, moved to monitor 2, then closed. Script opens that same folder again, expecting it to display on monitor 2. After updating to 22621.4317.67.1 though, all folders continue to open on monitor 1, even when script was killed, and folders manually opened and moved, closed and reopened. 

Rolled back to v22621.3880.66.6, folders opened on appropriate monitors as expected

Windows 11, 24H2

**Comment by Amrsatrio** [comment] 2024-11-06 07:59
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2243

**Closed by Amrsatrio** 2024-11-06 07:59 UTC
