### ISSUE TITLE
Photos Disappeared in Start Menu

### ISSUE THREAD

**Issue by rmz4ed** [valinet/ExplorerPatcher#1638] opened 2023-07-14 13:04 UTC
Hi,

Since a recent update, the Photos App no longer shows up on the Start Menu. I am wondering how I can bring it back. I tried searching for the app folder, but Windows 11 seems to have changed/removed the app folder location.

Thanks!

**Comment by Vipin2003** [comment] 2023-07-15 05:42
try this method #1591 if you are using win10 start

**Comment by pyrates999** [comment] 2023-07-15 13:11
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:11
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:11 UTC
