### ISSUE TITLE
Windows 11 Enterprise 22621.2134

### ISSUE THREAD

**Issue by Dragontamer333** [valinet/ExplorerPatcher#2005] opened 2023-09-05 19:09 UTC
Whenever I have this installed after the update the patcher crashes 3 times and closes.

**Comment by pyrates999** [comment] 2023-09-05 20:55
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Closed** 2023-09-05 23:58 UTC
