### ISSUE TITLE
Recommended section returns after unpinning an item on start menu 

### ISSUE THREAD

**Issue by BigWheelThaGod** [valinet/ExplorerPatcher#2754] opened 2024-01-27 04:01 UTC
So another new win 11 start menu problem has occurred, where if i unpin an item on the start menu, the recommended section will return. It fixes itself after closing start menu but is very odd and inconsistent

**Comment by pyrates999** [comment] 2024-01-27 15:07
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment] 2024-02-04 14:52
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2580

**Closed by Amrsatrio** 2024-02-04 14:52 UTC
