### ISSUE TITLE
[BUG] Weather / no internet connection

### ISSUE THREAD

**Issue by michaelmuselik** [valinet/ExplorerPatcher#1305] opened 2023-04-12 13:17 UTC
![image](https://user-images.githubusercontent.com/73330785/231469524-fa51c209-9676-49f3-8432-858216952f58.png)
Connection is ok.

**Comment by topia** [comment] 2023-04-12 14:06
Duplicate of: https://github.com/valinet/ExplorerPatcher/discussions/1301

**Comment by Vinz9900** [comment] 2023-04-12 15:33
Bekomme keine Wetteranzeige obwohl die Internetverbindung steht

**Comment by cjahn50** [comment] 2023-04-12 16:26
Just had the same issue after updating to version 22621.1555

**Comment by amirism** [comment] 2023-04-12 20:33
Same issue here. 

"**Unable to load weather information**
Make sure that the location you have entered is correct.
Verify that you are connected to the Internet.
"

**Comment by boogiepop** [comment] 2023-04-13 07:07
Same. Following the instructions to fix issue https://github.com/valinet/ExplorerPatcher/discussions/1301 did not fix this error.

**Comment by JZersche** [comment] 2023-04-13 21:35
I can confirm the Weather Widget is now bugged.

**Comment by TotemicWeevil** [comment] 2023-04-13 23:44
Same issue here. Removed and re-downloaded the Symbols download after following other advice. Didn't fix the issue.

**Comment by michguy2000** [comment] 2023-04-14 01:10
I also have the issue.  When I click the icon, I get the same error that [amirism](https://github.com/amirism) reported.  Clicking reload displays the weather briefly and then displays the error again.

**Comment by jw-mn** [comment] 2023-04-14 01:55
Got the same issue. Rolled back to 22621.1344.53.1. Uninstall and reinstall the older version. This fixed it for me.

Check here: https://github.com/valinet/ExplorerPatcher/issues/1310

**Comment by kevinmon91** [comment] 2023-04-14 03:01
Same issue here

**Comment by SamBukka** [comment] 2023-04-19 08:36
You can use 22621.1413.54.5 with the old "ep_weather_host.dll" from 22621.1344.53.1.

Just disable weather, replace the dll in "c:\Program Files\ExplorerPatcher\" and re-enable weather.

here is the dll: https://rg.to/file/d9ba10fc3f7640f1451ee5a1588204b7/ep_weather_host.dll.html

**Comment by valinet** [comment] 2023-04-24 11:52
Fixed in the latest version: 22621.1555.55.1.

**Closed** 2023-04-24 11:52 UTC
