### ISSUE TITLE
In the windows 10 start menu your are not able to see any uwp for some reason

### ISSUE THREAD

**Issue by HaloRage** [valinet/ExplorerPatcher#1676] opened 2023-07-26 07:58 UTC
In the windows 10 start menu your are not able to see any uwp i even tried downgrading still wont work in windows 11

**Comment by Vipin2003** [comment] 2023-07-26 08:36
try #1591

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:49
Duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:49 UTC
