### ISSUE TITLE
Windowsm volume slider is not showing 

### ISSUE THREAD

**Issue by eQuara** [valinet/ExplorerPatcher#1772] opened 2023-08-03 21:46 UTC
https://prnt.sc/rK0CWSDNQ4qd
this thingy is not showing up anymore, idk if i changed something (i think i didnt) i looked around here but couldnt find anything about it

**Comment by pyrates999** [comment] 2023-08-03 21:52
Please post windows version and build.
Please post explorer patcher version.

**Comment by eQuara** [comment] 2023-08-03 22:38
Windows 11 Pro 22H2 OS:22621.2070
Patcher version 22621.1992.56.1

**Comment by bubbismith** [comment] 2023-08-04 04:35
Same thing here. Been struggling with it for several days. My machine updates to 22H2, recently. Uninstalling Explorer Patcher brings it back.

EP: 22621.1992.56.1
Win11: 22H2; 22621.2070

Otherwise, great program, thanks very much!

**Comment by mamass** [comment] 2023-08-04 06:46
I confirm, i have the same problem since update KB5028254.

EP: 22621.1992.56.1
Win11: 22H2; 22621.2070

**Comment by TheToolGuy** [comment] 2023-08-04 07:40
I've got this problem too.

EP: 22621.1992.56.1
Win11: 22H2; 22621.2070

**Comment by GloryCiel** [comment] 2023-08-04 08:50
I have same issue.
EP : 22621.1992.56.1
Win11 : 22H2; 22621.2070

**Comment by Vipin2003** [comment] 2023-08-04 10:51
This is a bug with preview update... Get back to 1992

**Comment by bubbismith** [comment] 2023-08-04 19:21
<<Get back to 1992>>
Windows 11 or Explorer Patcher ?
Could you elaborate with a further sentence! :-)

**Comment by pyrates999** [comment] 2023-08-04 22:12
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by bubbismith** [comment] 2023-08-04 22:49
@pyrates999 

OK, great, thanks very much.
I had reinstalled EP as it's more important than that volume slider, but I now uninstalled that preview update (KB5028254)., and turned off the switch as you suggested also. I was happy to finally get 22H2 (from 21H2) about 10 days ago, I turned that on at some point to see if it might help in getting 22h2. Anyway, ExplorerPatcher is fantastic. Thanks again.

As I told my buddy regards EP and Open-Shell. I use them to make my Windows 11, more like Windows 10, which I had made to be more like Windows 7, which I had made to be more like Windows XP. And he said, so your Windows 11, is a souped-up Windows XP, I said, exactly. :-)

**Comment by icemessenger** [comment] 2023-08-05 05:49
u guys can try the modern flyouts to replace the default volume slider. google it for more info.

**Comment by Rainman67** [comment] 2023-08-08 06:12
Same problem here... 

EP: 22621.1992.56.1
Win11: 22H2; 22621.2070

**Comment by pyrates999** [comment] 2023-08-08 06:23
All you gotta do is uninstall the preview update (KB5028254).

**Comment by Rainman67** [comment] 2023-08-08 06:34
The update KB5028254 was offered me as an "regular update". See also here:

https://github.com/valinet/ExplorerPatcher/issues/1791#issuecomment-1668987297

**Comment by bubbismith** [comment] 2023-08-08 06:41
I almost reinstalled it to, but I spotted the key word...
![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/92797a25-dd7e-4eb5-b396-c7539f8ff1cc)

**Comment by Rainman67** [comment] 2023-08-08 06:44
Okay. I will uninstall it again and have a look when it will appear again! ;-)

**Comment by Rainman67** [comment] 2023-08-08 06:54
Just uninstalled the update and in my opinion it's a regular update (see screenshot):

![Screenshot 2023-08-08 085209](https://github.com/valinet/ExplorerPatcher/assets/141706132/bbd17034-675f-4d56-ae9c-02691da5875b)

**Comment by pyrates999** [comment] 2023-08-08 07:33
Here's what you will see with in the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

![image](https://github.com/valinet/ExplorerPatcher/assets/106135298/d3c203ad-ca85-4f50-9161-dd903cff8ea6)

**Comment by pyrates999** [comment] 2023-08-08 07:40
How to stop all updates from being installed automatically: https://pureinfotech.com/disable-automatic-updates-windows-11/

**Comment by Rainman67** [comment] 2023-08-08 07:48
I am quite familiar with the switch you mentioned (and the effect). But why is the update in your system is marked as "Preview", while this word is missing in my system?

The problem is, if I don't install this update, it will keep offering me to the end of days and that can't be the point. Especially since there is a great danger that if several updates are offered together, clicking on "Update all" will also install this update again. I stand by it - this update has now been classified as a regular update by Microsoft.

**Comment by pyrates999** [comment] 2023-08-08 07:57
Yes, it will keep offering it.  But it will never automatically install it.

**Comment by Rainman67** [comment] 2023-08-08 08:10
Okay, i give up! ;-)

**Comment by fuste76** [comment] 2023-08-09 19:47
Volume slider and brightness slider not displaying using fn+<key> after todays install of regular windows update KB5029263 on Windows 11 22H2. Windows version is now 22621.2134

**Comment by gchorbov** [comment] 2023-08-10 08:49
Same problem here -> the volume slider (and other on-screen sliders or values) are missing.

EP version: 22621.1992.56.1
Win 11 version: 22H2; 22621.2134

I've tried to uninstall windows update KB5028254, but it is not listed as available for uninstall. I dont know why...

How can I uninstall the update? 
What is the solution if I cannot uninstall this fu****ng update?

<img width="801" alt="2023-08-10 11_44_11-Settings" src="https://github.com/valinet/ExplorerPatcher/assets/44842191/f5ad5cc2-7cec-4e74-b8e4-18943fdb614f">

<img width="822" alt="2023-08-10 11_44_24-Settings" src="https://github.com/valinet/ExplorerPatcher/assets/44842191/351ebf07-355b-46ce-bac1-989042a29e5f">

**Comment by pyrates999** [comment] 2023-08-10 12:47
Here's how: https://www.windowslatest.com/2021/04/23/how-to-uninstall-windows-10-updates-manually/

**Comment by vdn20** [comment] 2023-08-10 18:01
I'm running Windows 11 22H2 Build 22621.2134, ExplorerPatcher version 22621.1192.56.1, and I don't see the volume slider either.  It looks like KB5029263 broke it.  If I uninstall it, the volume slider is back, but Windows will install it again after I reboot, and it broke it.

**Comment by Jaxel** [comment] 2023-08-10 20:46
Reporting the same issue with yesterday's KB5029263.

**Comment by pezkoreaddict** [comment] 2023-08-11 01:06
Same issue for me with KB5029263.

**Comment by pyrates999** [comment] 2023-08-11 10:49
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1692

Please close this one.

**Comment by panyann** [comment] 2023-08-13 10:11
After uninstalling the KB5029263 the problem disappeared.
From now on I will delay all updates for a month, hopefully this will suffice...

**Comment by OsakaWebbie** [comment] 2023-08-15 04:42
I concur with several other voices here, that KB5029263 caused the volume bar to disappear. I uninstalled that update and the bar reappeared. I don't know whether Windows Update will pester me to install it again at some point - this is my first experience uninstalling an update. FYI, no "preview" updates were ever installed on my machine - this happened only with the official release.

**Comment by Vipin2003** [comment] 2023-08-15 08:46
This is a bug with Win10 Taskbar in EP.... Switch to Win11 Taskbar till it get a fix. Or mention valinet for these bugs

**Comment by OsakaWebbie** [comment] 2023-08-15 09:48
Win10 taskbar (specifically, the ability to put it on the side instead of the bottom of the screen) is non-negotiable for me - that's the reason I installed EP. I'd rather have that than the volume bar if I have to choose between them.

Yup, as I expected, Windows now is trying to install KB5029263 again - it threatens to do it the next time I'm away from my computer during "non-active hours". I'm pausing updates for a week, but that's all I can do with Win11 Home.

Mention valinet? This is his github repo, so I'd think he would see all the open issues anyway. But okay - @valinet : Plus fix this, so we can see the volume indicator while using Win10 taskbar, even after installing KB5029263. It would be a wonderful extra bonus if EP could bring back the style of volume indicator that existed before 22H2 (top left, and with a more visible marker where the volume setting is) - the thin, low-contrast bar in the bottom center might be stylish, but it's not as usable.

**Comment by bubbismith** [comment] 2023-08-15 19:39
@OsakaWebbie Great post, everything I was thinking. Has there been a post from @valinet, something saying we're looking into it? The Win11 taskbar is one of the main problems EP fixes. I too have suspended updates. And yes, please bring back to prior volume bar if possible, the new one is so hard to see. The old one was just fine. It's another case for MS changing things for the sake of changing thigs. (What was wrong with the Task Manager having it's tab buttons across the top. Now we have to remember not to click the Pancake menu when switching views, even though the pancake menu is exactly where you would expect them to be. I did look at 'ModernFlyouts' on my test machine, it looks much better than the new MS one, and it has a popup for CapsLock, Scrolllock, etc... used once a week or never, but it does adds another process to what should actually be in Windows itself.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:41
Duplicate of #1692

**Closed by Poopooracoocoo** 2023-08-22 10:41 UTC
