### ISSUE TITLE
Start Button Won't Open in All Files

### ISSUE THREAD

**Issue by mmschmieg** [valinet/ExplorerPatcher#2592] opened 2023-12-16 04:30 UTC
I am running EP on three machines, all of which are running 23H2 Windows 11. The one in question is running Build 22631.2861 and was installed with a clean install last week. Everything seems to be working fine except that I cannot get the Start Button to open in All Files, even though the EP settings say it should. I am running EP 22631.2861.1 which is currently the latest. My other two machines are working flawlessly. I'm wondering if anyone has any suggestions as to how  to resolve this. Thanks.

**Comment by pyrates999** [comment] 2023-12-17 04:10
Please post explorer patcher version.  EP version 22631.2861.1 does not exist.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

Please update to the latest release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.2861.62.1_9444eee

**Comment by mmschmieg** [comment] 2023-12-17 04:54
Sorry, it is now showing 22621-2861.62.1 for EP. However, tonight, it again downloaded symbols and it is now working. Nothing else changed.

**Comment by pyrates999** [comment] 2023-12-17 10:27
So it is now working?

**Comment by mmschmieg** [comment] 2023-12-17 16:39
It started working about midnight last night.

**Comment by mmschmieg** [comment] 2023-12-18 02:23
> So it is now working that you updated it?
I didn't update it. It downloaded the symbols a second time after the update. It didn't work after the first symbols download and it took a day or so to download the second time.

**Comment by pyrates999** [comment] 2023-12-18 04:58
So this was caused by symbols not being downloaded yet.  Open up the EP properties application and go to advanced, and make sure **Enable symbols download** has a tick beside it.

Always check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  If the symbols haven't been downloaded yet, it will attempt to download them.

**Comment by mmschmieg** [comment] 2023-12-18 05:04
Apparently, Windows gave me a report that the symbols were downloaded when they were not or not completely. I’m still in the process of getting all my settings redone after a clean installation of 23H2 and then reinstalling all of my software on two of my three machines.

**Comment by pyrates999** [comment] 2023-12-18 05:15
Symbols need to be downloaded for every new update that Microsoft releases for windows because they change to match the new version: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by Vipin2003** [comment] 2024-02-08 03:27
Close the Issue if Resolved to minimize the Opened Issue with real one.

**Closed** 2024-02-08 03:34 UTC
