### ISSUE TITLE
Win11 File Explorer issue

### ISSUE THREAD

**Issue by SAIMMINHAS** [valinet/ExplorerPatcher#1632] opened 2023-07-13 14:33 UTC
I was wondering if you can help me out with this issue.
 
One of our users who has Win11 on her machine, has an issue. The same issue has been reported by another user and that user is referring this issue as a bug in Windows itself. The issue is that Windows File Explorer keeps on randomly appear when working in other applications for no apparent reason and is becoming annoying for the user. Below are two snapshots of that issue where the File Explorer is appearing in front of Outlook and another Application. I have already applied the below 2 fixes on her machine along with all the Windows Updates but no luck: 
 
1.	** Restarted Windows Explorer Press Ctrl + Shift + Esc to open Task Manager. 
        Select the Processes tab. Scroll down and select Windows Explorer, Right click then select Restart. 
 
2. Also, run the DISM to check for any system errors and corrupted files. It mentioned that the system needs a restart which was done. 

It seems like some sort of windows settings might need to be changed on this user's machine as i have never experienced this on my machine neither any other user in our company has reported it.

![image](https://github.com/valinet/ExplorerPatcher/assets/30388154/2e1b2c49-9439-452a-b921-b2f9d72897b8)

![image](https://github.com/valinet/ExplorerPatcher/assets/30388154/5a3ea622-5def-4ca4-9373-bb50abad020b)

Please note that the user is using Win11 with all the updates fully updated.

Waiting for a reply,

**Comment by pyrates999** [comment] 2023-07-13 23:59
Please post windows version and build.
Please post explorer patcher version.

**Comment by SAIMMINHAS** [comment] 2023-07-14 08:14
Hi,

It's Windows 11 64-bit (Release 22H2 Build 22621.1992) and i can't seem to locate the Win11 Explorer Patcher Version. Kindly advise the steps.

Waiting for your reply,

Thanks

**Comment by pyrates999** [comment] 2023-07-14 10:58
Open up the explorer patcher properties application and go to about on the left side.

**Comment by SAIMMINHAS** [comment] 2023-07-14 11:50
When i type in 'explorer patcher properties', it just opens up File Explorer. Do i need to first install this App?

**Comment by pyrates999** [comment] 2023-07-14 13:02
It's called: Properties (ExplorerPatcher)

**Comment by SAIMMINHAS** [comment] 2023-07-14 14:27
ok.. I managed to go in the Applicaiton and at 'About'. Below is the snapshot of it.
I also received another message something about 'Symbols for OS build xxxxxxxxx'. Not sure if i need to exeute that as well.

![image](https://github.com/valinet/ExplorerPatcher/assets/30388154/ff10aff8-bb5a-4264-b4d2-67ff680d840b)

![image](https://github.com/valinet/ExplorerPatcher/assets/30388154/b1bf69cb-fa36-481c-b7d7-354aa1097a05)

**Comment by SAIMMINHAS** [comment] 2023-07-14 14:28
By the way, the version is for my own laptop not the end user. I would need to execute it on that machine as well. Do you know how i can revert it back to original Win11 menu? as at the moment, it's like in Win10.

**Comment by SAIMMINHAS** [comment] 2023-07-20 10:46
Hi,
Sorry for the delay. 

Windows 11 64-bit
(Release 22H2 Build 22621.1992)

Also, please see below explorer patcher version:

![image](https://github.com/valinet/ExplorerPatcher/assets/30388154/ab0b299c-c11c-41fb-a2da-bba02efea833)

**Comment by pyrates999** [comment] 2023-07-20 13:53
Ok, now try uninstalling explorer patcher and then reboot.

Does this still occur?

**Comment by SanderGit** [comment] 2023-07-27 06:51
See also #1277

**Comment by pyrates999** [comment] 2023-07-27 10:19
Update to the current release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.1_53ff541

**Comment by SAIMMINHAS** [comment] 2023-07-28 09:57
> Update to the current release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.1_53ff541

@pyrates999 that is for Win10 not Win11.

**Comment by SAIMMINHAS** [comment] 2023-07-28 10:05
> See also #1277

Sure.. will try it once i manage to get some time with the user.

**Comment by pyrates999** [comment] 2023-07-28 16:40
> > Update to the current release: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.1_53ff541
> 
> @pyrates999 that is for Win10 not Win11.

It is for windows 10 and windows 11.

**Comment by SAIMMINHAS** [comment] 2023-07-31 10:10
@pyrates999, the un-install didn't solved the issue so i then instaled the latest udapted version of it. Need to now wait and see.

**Comment by SAIMMINHAS** [comment] 2023-07-31 10:11
> > See also #1277
> 
> Sure.. will try it once i manage to get some time with the user.

Changed to Win10. Will now wait and see.

**Comment by SAIMMINHAS** [comment] 2023-08-04 16:18
@pyrates999 and @SanderGit
So tried both of your suggestions but unfortunately the issue is still there.

**Comment by SanderGit** [comment] 2023-08-04 17:22
I can reproduce the issue ie. on Windows 11 an Explorer window pops up on random moments. Using latest version of the patcher and prod versions of Windows 11.

**Comment by pyrates999** [comment] 2023-08-04 22:10
Check for any other software you have installed that modifies windows such as Windhawk and 7+taskbar tweaker and try uninstalling them all and explorer patcher and see if this still happens.

**Comment by SanderGit** [comment] 2023-08-05 06:12
> Check for any other software you have installed that modifies windows such as Windhawk and 7+taskbar tweaker and try uninstalling them all and explorer patcher and see if this still happens.

Not applicable

**Comment by pyrates999** [comment] 2023-08-05 08:44
> > Check for any other software you have installed that modifies windows such as Windhawk and 7+taskbar tweaker and try uninstalling them all and explorer patcher and see if this still happens.
> 
> Not applicable

what do you mean not applicable?

**Comment by SanderGit** [comment] 2023-08-05 08:46
> 

No such software installed here.

**Comment by pyrates999** [comment] 2023-08-05 10:12
Uninstall explorer patcher and see if it is still happening.

**Comment by SAIMMINHAS** [comment] 2023-08-05 19:44
> Uninstall explorer patcher and see if it is still happening.

@pyrates999
I've already done it and still the same issue.

**Comment by pyrates999** [comment] 2023-08-06 05:05
Then this is not caused by explorer patcher.  Did you try changing the users keyboard?  The windows or E key might be getting called sometimes on its own.

**Comment by SAIMMINHAS** [comment] 2023-08-09 18:25
> Uninstall explorer patcher and see if it is still happening.

Already tried it and it didn't worked.

**Comment by pyrates999** [comment] 2023-08-09 20:59
Then this is not caused by explorer patcher.  Please close this.

**Comment by SAIMMINHAS** [comment] 2023-08-09 23:07
> Then this is not caused by explorer patcher. Did you try changing the users keyboard? The windows or E key might be getting called sometimes on its own.

Could you please further ellaborate this?

**Comment by pyrates999** [comment] 2023-08-10 12:46
If this is happening still after you uninstall explorer patcher and reboot, this is not a bug in explorer patcher.

You may need to repair your windows install: https://www.computerworld.com/article/3080839/repair-windows-10-and-11-step-by-step-guide.html

**Comment by SAIMMINHAS** [comment] 2023-08-14 16:13
> If this is happening still after you uninstall explorer patcher and reboot, this is not a bug in explorer patcher.
> 
> You may need to repair your windows install: https://www.computerworld.com/article/3080839/repair-windows-10-and-11-step-by-step-guide.html

So the DISM didn't showed any errors but SFC did which were fixed. Now it's a waiting game.

**Comment by SAIMMINHAS** [comment] 2023-08-15 09:09
@pyrates999 so the issue is still there. Looks like maybe i need to comletely rebuild this Dell laptop. Somehting must be intefering with the File Explorer.

**Closed** 2023-08-15 15:47 UTC

**Comment by Daoffimai** [comment] 2024-11-06 14:31
The see more option in windows 11 build 27729 is always on top. 
![173090328849599718408589327575](https://github.com/user-attachments/assets/1451622f-ac10-4611-a60b-1eeb967cd86d)
![1730903304400853748334690909203](https://github.com/user-attachments/assets/0da90749-14fc-43fe-9a3b-c31457155aed)
?
