### ISSUE TITLE
Explorer crashes on startup with Windows 10 taskbar enabled

### ISSUE THREAD

**Issue by Henri-J-Norden** [valinet/ExplorerPatcher#320] opened 2021-11-11 16:15 UTC
* With Windows 10 taskbar disabled, Explorer does start, ~~but then the properties are missing as noted in #319 (although `rundll32 C:\Windows\dxgi.dll,ZZGUI` does work)~~

* With Windows 10 taskbar enabled, Explorer exits immediately after starting - without any visual change. 
Releases 22000.318.36.0, ..35.0 work, but not 22000.318.36.1.

In event viewer, I found the following application error:
```Faulting application name: explorer.exe, version: 10.0.22000.120, time stamp: 0xe846e749
Faulting module name: Taskbar.dll, version: 10.0.22000.132, time stamp: 0x4dfba0cb
Exception code: 0xc000027b
Fault offset: 0x00000000000930b4
Faulting process id: 0x31f8
Faulting application start time: 0x01d7d71611ceaa07
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\Windows\System32\Taskbar.dll
Report Id: 6a87bdae-6b23-4c79-a4ea-ec03ead0bd79
Faulting package full name: 
Faulting package-relative application ID: 
```

This is on Windows 11 21H2 22000.318.

**Comment by valinet** [comment] 2021-11-11 16:26
It's hard for me to believe nothing works with the changes from 36.0 to 36.1. I just tested now on a clean VM and on my development machine without any prior registry settings, it works just fine. The latest commit does not change that much, only guards a few features to work only when the Windows 10 taskbar is enabled so that the program is able to start even when the new taskbar is preferred. That's it.

Properties are not missing, they are simply not added to the Windows 11 `Win`+`X`. The README states pretty clearly how to run the Properties GUI manually: `rundll C:\Windows\dxgi.dll,ZZGUI`.

So yeah, start from a clean slate, clear the registry entries for EP from: `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher` and try again. If it does not work, create `AllocConsole` DWORD in there, set to 1 and watch what the console prints when the program starts up. Again, I can't think of any reason why the changes in the latest version could break it.

Thanks

**Comment by Henri-J-Norden** [comment] 2021-11-11 16:44
Clearing the registry keys did not help; this is the console output I get:
![image](https://user-images.githubusercontent.com/55378880/141334753-d80d0505-0656-4e29-b55f-42e2ee5f8ac6.png)

The console stays frozen at this point for around half a second and then closes automatically.


I actually have a similar problem with Window switchers as well... any window switcher other than Windows 10 results in identical behavior (same console output, Explorer crashes). 
The one difference is that for the NT/11 window switchers to work I have to go back to version 34.1, not 35.0.

I also have Open-Shell and Winaero Tweaker, I will test if uninstalling Open-Shell changes anything.

**Comment by Henri-J-Norden** [comment] 2021-11-11 16:55
Uninstalling Open-Shell fixed both problems, so some changes in 35.0 (NT/W11 window switchers) and 36.1 (W10 taskbar) are incompatible with Open-Shell :(

I was using release 4.4.160 of Open-Shell

**Comment by Henri-J-Norden** [comment] 2021-11-11 17:02
Huh... I reinstalled Open-Shell and everything is working now, even after a restart. (Which makes me think if I actually tried restarting before... I can't remember)

Problem solved, I guess..?

**Comment by valinet** [comment] 2021-11-11 17:06
> Huh... I reinstalled Open-Shell and everything is working now, even after a restart. (Which makes me think if I actually tried restarting before... I can't remember)

Yeah, weird stuff may sometimes happen... idk, programs sometimes conflict. Anyway, I was writing you a reply on how to debug it, fortunately it is not needed anymore but I will still post it so it can be used for future reference by people experiencing problems.

Thanks. Original reply below:

Well, idk, it has to be debugged there, I cannot reproduce it on my system. I repeatedly switched those settings, seemed to work fine for me. When it freezes and then closes, that's when it crashes, it can be debugged at that point, see where it dies there.

Couple of suggestions:
* Builds are automatically generated now. Identify the corresponding commit for a particular version from the release notes, than go to [Actions](https://github.com/valinet/ExplorerPatcher/actions), click on the commit name, and you will find the build artifacts in there. That contains not only the DLLs, but also the symbols. You place both the DLL and the symbol file in `C:\Windows` (probably rename `ExplorerPatcher.amd64.pdb` to `dxgi.pdb` as well, or have the file with 2 names just in case), kill Explorer and start it under some debugger, like WinDbg. Then, you press `g` to get past the first automatic breakpoint and let it run until it crashes, at which point WinDbg will show you the stack trace, with the function where it crashed, and the offending instruction that generated the problem. Or, with a locally compiled version, it will actually show on the source code where the trouble may be. Hopefully that will be enough to figure it out.
* What I described above can also be automated: you can use [these instructions](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) to enable crash dumps (collect full dumps, if possible), have Explorer crash, identify the generated dump and upload it somewhere, I download it an look in WinDbg myself and try to identify the cause of the crash.

**Comment by Henri-J-Norden** [comment] 2021-11-11 17:25
Actually not solved - it's intermittent (the best kind of bug). 

Right now with 36.1, the window switcher setting doesn't seem to cause Explorer to crash, but enable Windows 10 taskbar definitely does. BUT it will start eventually if I press Restart File Explorer (or launch explorer from Run...) up to five times. Maybe some kind of race condition? (Open-Shell and ExplorerPatcher trying to hook the same thing at the same time depending on the settings? But I'm not very familiar with how these mods work to know if something like that could occur/could be a problem)

**Comment by valinet** [comment] 2021-11-11 17:34
Yeah, I cannot guess either. It has to be debugged. EP is mainly designed to work with the "Enable Windows 10 taskbar" setting on. That is the use case tested 99% of the time, and it should definitely work with that. Again, recent changes made some edits regarding the behavior when the Windows 10 taskbar is DISABLED, not when enabled, so I cannot imagine why it may cause trouble to you. Again, running under a debugger can provide much valuable info. 

If you want, I can assist you over TeamViewer...

**Comment by Henri-J-Norden** [comment] 2021-11-11 19:13
I shouldn't have spent so much time trying to get the first option to work - running explorer with a debugger attached made it less likely to crash, so I wasn't even looking at the right thing for quite a while. Anyway, no such problems with the second option using WER.

Loading the dump in Visual Studio it looks like the line that causes the exception is 3126 in dllmain.c: 
`if (bIsExplorerProcess && (*((WORD*)&(lpClassName)+1)) && (!wcscmp(lpClassName, L"TrayClockWClass") || !wcscmp(lpClassName, L"ClockButton")))`
I have also emailed you the file as it's probably going to take me a while to figure out what the dump is really pointing towards, since I'm not very familiar with Windows development in C.

**Comment by valinet** [comment] 2021-11-11 20:54
Thanks. Well, it's much more complicated, it seems. 

First of all, it's not that line, it always shows you the next line where execution will resume after the call is made, not the actual line that advanced into the call stack. You can see this even from the call stack, the error is somewhere on the chain it advances on after the `CreateWindowExW` call is made (my `dxgi!CreateWindowExWFunc` is a pointer to that, basically).

The error is further up on the call stack, in one of the functions after `explorer!GetTaskbarTheme`. It basically fails to obtain the factory for `winrt::WindowsUdk::UI::Themes::ISystemVisualTheme`, whatever that is, probably something that tells it how the taskbar looks. Why it fails that, idk... =)))

When calling `CreateWindowExW`, the `lpClassName` parameter points to a string containing "TrayDummySearchControl". Now, what is that? It seems to be "the Cortana bar". So this all happens when it attempts to create the window for the Cortana bar, it throws that exception basically. The bar is broken in Windows 11, but should not cause this either, anyway. The window should still be created in any case, I have it on my system as well even though I do not visually see it. Do you by any chance have the "Type here to search" bar enabled? It should be impossible to pick up by Explorer anyway, since it is disabled also by some hooks I do in EP, but still, maybe somehow have that enabled? Make sure `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search\SearchboxTaskbarMode` is set to 0 or deleted, just as a test. Idk how else that can get enabled... 

Are you sure you haven't done any changes on the system lately? Idk, tweaks, stuff like that. The only change I made regarding this `WindowsUdk` factories recently is that I worked a bit on the code that positions the Start menu at startup. Since I saw you compiled your own version, can you compile https://github.com/valinet/ExplorerPatcher/commit/e4eff89cf1ca9c98a0a89270bbe51d229d56447b as well and see if it works with that? It is the last version before those changes. And then try https://github.com/valinet/ExplorerPatcher/commit/aa0371e0fb4366ba2e371b844d7267fbe74823f8 which is the version with those changes. If we can isolate it there, maybe I have an idea what to change back and have it working again, idk... Anyway, isolating it between 2 commits makes it easier to look out and test what could have gone wrong...

Anyway, the dump was very useful, as expected. It really offers good, valuable information.

**Comment by h3rm** [comment] 2021-11-12 11:12
hi! i just configured everything as you wrote in the readme but after restarting the explorer with taskkill /f /im explorer.exe the start- and searchbuttons in the taskbar don't work and more.

Edition	Windows 11 Pro
Version	21H2
Installiert am	‎06.‎10.‎2021
Betriebssystembuild	22000.318
Leistung	Windows Feature Experience Pack 1000.22000.318.0

https://i.imgur.com/mmorCpz.png
https://i.imgur.com/Dk4z2qH.png
https://i.imgur.com/0zccc2M.png
https://i.imgur.com/ff7CIIT.png
https://i.imgur.com/HZQNSDn.png
https://i.imgur.com/F4w1V8A.png
https://i.imgur.com/caqQ1fc.png

also the mouse mouse cursor is flickering (round circle/loading symbol) every 1-2 seconds asince about 1.5 hours and sometimes the task bar is gone for a few seconds. After 1 hour of waiting i tried to restart but there is still the same problem..

is it really possible that this such a long time? i never saw any countdown for downloading the symbols, but some are still missing:
https://i.imgur.com/D4GzdTY.png

eventlog:
https://i.imgur.com/2t8uh4P.png
https://i.imgur.com/LT34WMQ.png

i set all to "default", restartet the explorer again and "uninstalled" nearly everything (i had no time to delete the registry things cause of work) and experience weired changes in windows and explorer settings now.. maybe cause i did the win10 -> win 11 update and this also messed something up?

Would be cool if someone can help me get explorerpatcher running :) thx!

**Comment by Henri-J-Norden** [comment] 2021-11-12 13:48
@valinet Did you mean some other registry key? `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search\SearchboxTaskbarMode` seems to control the search button on the W10 taskbar, meaning that also the Show Search button option in Explorer Patcher sets it to either 1 or 0.

I will do some more debugging this weekend if I have time - although the reason I compiled my own version was to make some improvements to sws, so I still want to have some time for that too ^^

Regarding having "tweaks", well... yes, loads. In addition to Open-Shell, I use Winaero Tweaker and have done some manual changes too. But before worrying about those too much I think I should check again whether just removing Open-Shell solved it like it seemed to before, with the new knowledge that the problem is kinda intermittent.

**Comment by valinet** [comment] 2021-11-12 15:01
@Henri-J-Norden The regkey is correct; 0 means disabled, 1 means only the search icon is shown, 2 means the search box is shown. Just remove it and test. EP has some hooks and makes Explorer think a 2 there is similar to 1, so don't bother with that.

Since you reported this bug anyway, it would be good if we fixed it. Also, I wanted to ask before, why not post the info in regard of commit number (sha), not 34.0, 35.0 etc. Like, it takes a while to search in the list, I don't remember anyway what the numbers meant.

So https://github.com/valinet/ExplorerPatcher/commit/aa0371e0fb4366ba2e371b844d7267fbe74823f8 is the first problematic commit (35.0). I mitigated some of the changes, can you test with the attached build, please?

[dxgi.zip](https://github.com/valinet/ExplorerPatcher/files/7528480/dxgi.zip)

Thanks

**Comment by oott123** [comment] 2021-11-13 07:27
Same issue here. After using the build attached on https://github.com/valinet/ExplorerPatcher/issues/320#issuecomment-967182452 , it doesn't crash now.

Can we leave this issue open until it's fix and released? It's useful for users like me who is looking for support.

**Comment by valinet** [comment] 2021-11-13 07:30
Okay, I reopened it. Too bad I forgot what changes I did in https://github.com/valinet/ExplorerPatcher/issues/320#issuecomment-967182452...

**Comment by Utherellus** [comment] 2021-11-13 09:18
I have same problem.  Properties menu does not show up when pressing WIN+X  and when using 
rundll32 C:\Windows\dxgi.dll,ZZGUI    and enabling Windows 10 taskbar, explorer crashes

**Comment by sisericm** [comment] 2021-11-13 14:40
Interesting thread as I had a similar failed start up issue with release 36.1.  I wasn't going to post as it has since been resolved but as this seems to be one of those annoying intermittent issues, I thought I'd share my observations incase there was anything useful to others.
Up until yesterday's spurious failed start, I had been running openshell, win 11 318, EP 36.1 win 10 taskbar, and win 10 switcher without any problems - all completely rock solid (Thank you Valinet!). 

After updating intel DCH graphics to 30.0.101.1069 (2/11/2021) explorer would no longer load at start up. Instead, start up finished on black screen and cursor. Explorer and EP could still be run manually but normal start up was impossible. Event log showed a trail of access denied errors.

On reverting EP to 36.0 & 34 a normal startup wa possible but going back to 36.1 repeated the failed start.

Interestingly, I rolled back the intel driver and the same black screen start continued to happen on 36.1 but 34 was fine.

The resolve:

- Clean install of Intel & Nvidia drivers with EP 34 in place.
- Restart Win /EP & Check all working. (clean out registry entries etc)
- Install intel 30.0.101.1069
- Restart Win & Check all working.
- Install EP 36.0 restart explorer with console. Confirm OK
- Restart Win /EP & Check all working.
- Try EP 36.1 again.  Restart explorer with console. Confirm now OK

After the rollback and reinstall all is working fine and dandy...
I have no idea why, how or if the graphic driver update could trigger the start failure but after rolling back the driver and EP all started fine, and the subsequent reinstall of 36.1 has been working flawlessly on the new intel driver since.


Thanks again for this lifesaver of a project Valinet. It does indeed make W11 productive.

**Comment by valinet** [comment] 2021-11-13 21:53
An update will come soon that will address this. I have some fix that various users reported a s mostly working. I am working on some other stuff to fix as well at the moment, once that’s ready, I will push and a release will be generated in 5 minutes after that.

Thanks

**Comment by valinet** [comment] 2021-11-14 19:22
The latest release includes mitigations for this issue. It should not happen anymore, it seemed not to manifest on my test setups. I will close this issue and the related ones, but we can continue chatting should you still encounter problems with this.

**Closed by valinet** 2021-11-14 19:22 UTC
