### ISSUE TITLE
Explorer Patcher (EP) Not downloading due to "Virus detected by Windows Defender (Microsoft Defender)"

### ISSUE THREAD

**Issue by 0s9df8c0sdfd0** [valinet/ExplorerPatcher#3125] opened 2024-04-11 13:52 UTC
When i was downloading Explorer Patcher again for a YouTube video on how to make Windows 11 look like Windows 10 Google Chrome says that its a virus and I pressed keep dangerous file. Once I did that Microsoft Defender was freaking out so I could not download Explorer Patcher. When I download it again it does the same thing.

**Comment by pyrates999** [comment] 2024-04-11 13:59
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2873

This is a false positive.

Update your windows defender signatures by going to settings -> updates & security -> windows security
Then click on virus & threat protection
Under virus & threat protection updates, click on check for updates
Then click on the button named check for updates

Then if it is still being detected as malicious, submit it as a false positive to Microsoft: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by phoenX80** [comment] 2024-04-11 16:48
I bypassed this via adding folder exclusion
C:\Users\"USERNAMEHERE"\AppData\Roaming\ExplorerPatcher

**Comment by vvirtues** [comment] 2024-04-11 21:29
What windows version? might wanna check this out btw https://www.xda-developers.com/microsoft-wont-update-windows-11-these-apps/

**Comment by Amrsatrio** [comment] 2024-04-13 05:16
https://github.com/valinet/ExplorerPatcher/commit/45bd73585604b644c95767fef6e92a9f1a11a212

This new commit by Valinet that is included into 64.3 prerelease seems to be causing the detections...

**Comment by Amrsatrio** [comment] 2024-04-13 05:18
@pyrates999 I cannot recommend the "submit to MS as false positive" anymore. The humans in their threat response department seem to be clueless about this and would mark this as a malware anyway if it contains certain patterns of system calls.

**Comment by pyrates999** [comment] 2024-04-13 05:39
Ah ok.  I'll stop recommending that.

Will there be a new pre-release with that commit removed?

**Comment by Amrsatrio** [comment] 2024-04-13 05:44
I need to have some talks with Valinet beforehand.

**Comment by phoenX80** [comment] 2024-04-13 05:52
On 10.0.22000.2899 for the love of god wasn't able to run RDPWrapper/SuperRDP anymore. Even after doing exclusions. Whatever MS is doing, it is more than adding recognition to Defender. Gladly explorerpatcher is fine for me (with exclusions). Because of RDP I had to roll back my Windows version anyway.

**Comment by pyrates999** [comment] 2024-04-13 07:36
You must be running windows 11 21h2 enterprise as the pro and home versions were end of life on October 10, 2023.

**Comment by phoenX80** [comment] 2024-04-13 08:53
I wasn't updating further because of  unsupported processor for now.

**Comment by pyrates999** [comment] 2024-04-13 09:07
Ok, well windows 11 21h2 enterprise end of life is Oct 8, 2024: https://learn.microsoft.com/en-us/lifecycle/products/windows-11-enterprise-and-education

So be aware of that.

**Comment by Amrsatrio** [comment] 2024-04-14 04:22
You can do an in place upgrade manually using an ISO of 22/23H2 and some registry tweaks.

**Comment by Siderite** [comment] 2024-04-15 09:16
I've seen a worrisome video that Windows now treats Explorer Patcher and other software like this as blockers to updates. In the sense that they actually check for the filename and specifically do things to stop you from using it. I've delayed all my Windows updates since then. 

Can someone tell me if ExplorerPatcher still works for all versions of Win11?

Thanks!

**Comment by pyrates999** [comment] 2024-04-15 11:02
It is only happening in Canary and Dev builds because Microsoft wants you to test windows without it being modified.  Installing EP on them would invalidate the testing environment that you as a tester would be testing on.

If you don't want to submit bug reports and help test windows, then you shouldn't be installing Canary and Dev builds in the first place.

**Comment by Siderite** [comment] 2024-04-15 12:41
I've run Windows Update with no incident. Thanks!

**Comment by Amrsatrio** [comment] 2024-04-26 13:51
Closing as 64.3 has been superseded and the code that might have caused the antivirus has been commented out. Feel free to reopen if 65.1 is detected.

**Closed by Amrsatrio** 2024-04-26 13:51 UTC
