### ISSUE TITLE
Weird Start Menu search behavior

### ISSUE THREAD

**Issue by tricopol** [valinet/ExplorerPatcher#3816] opened 2024-10-17 04:26 UTC
Running W11 23H2 22631.4317  and Explorer Patcher 22621.3880.66.6

I have my taskbar on the top of the screen when i try to search anything from the start menu search textbox, the results are displayed on the bottom of the screen:
<img width="816" alt="image" src="https://github.com/user-attachments/assets/af684349-8f3a-4d75-9055-2d996333773b">

Type something on the search box and then:
<img width="593" alt="image" src="https://github.com/user-attachments/assets/e04a05a2-dc4e-4db5-bfe4-ead467219eb8">

Is this a bug or there is no other way to do it ?

**Comment by pyrates999** [comment] 2024-10-17 10:36
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

Please close this.

**Closed** 2024-10-17 17:25 UTC
