### ISSUE TITLE
The taskbar is covered

### ISSUE THREAD

**Issue by lucky80** [valinet/ExplorerPatcher#1889] opened 2023-08-22 07:58 UTC
After the latest version upgrade, the taskbar is covered like the capture picture.

![Cap 2023-08-22 16-55-50-026](https://github.com/valinet/ExplorerPatcher/assets/1419119/aa0acc29-33c2-4e76-aa92-29dadbf30e16)

![Cap 2023-08-22 16-55-55-345](https://github.com/valinet/ExplorerPatcher/assets/1419119/cc03a495-30d4-421b-93c7-7201e5372257)

![Cap 2023-08-22 16-56-10-136](https://github.com/valinet/ExplorerPatcher/assets/1419119/bd0c8e17-991a-4fae-a540-b65559452678)

![Cap 2023-08-22 16-56-40-226](https://github.com/valinet/ExplorerPatcher/assets/1419119/3c1db59e-7e11-4384-92d0-997ff20e42f9)

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:03
Closing as duplicate of #1854

**Closed by Poopooracoocoo** 2023-08-22 10:03 UTC
