### ISSUE TITLE
Problem occurs in win1122621.2070

### ISSUE THREAD

**Issue by nuneddin** [valinet/ExplorerPatcher#1710] opened 2023-07-29 09:56 UTC
22621.2070 There is a problem that the right button does not open personalization after the window update and keeps refreshing
If you run it several times to open your personalization, the Explorer patcher crashes and the Explorer patcher appears
There is a problem that stops.

**Comment by Transcan** [comment] 2023-07-29 11:25
Also having problems with 22621.2070:
When the system boots up and enters in the user profile, EP keeps restarting for a while.
After that, a windows informing EP is crashing appears.

I also use OpenShell. Don't know if is the combination that makes my crash different from the first comment one.
But I'm confident is caused because the new Windows release.

**Comment by Transcan** [comment] 2023-07-29 11:33
bumped just to warn the OP.
Here they explains how to temporally fix the issue: https://github.com/valinet/ExplorerPatcher/issues/1707
In short: Uninstall Windows patch KB5028254 and wait until EP is updated to apply the windows patch

**Comment by nas398** [comment] 2023-07-29 14:55
same problem..I uninstalled the ExplorerPatcher. the installed the last version but still the same problem :(

**Comment by luciodaou** [comment] 2023-07-29 23:14
Duplicate of #1707

**Comment by nuneddin** [comment] 2023-07-30 01:14
Yes, I see. It's fixed as I keep working

2023년 7월 30일 (일) 오전 8:14, luciodaou ***@***.***>님이 작성:

**Comment by BraINstinct0** [comment] 2023-07-30 15:16
If the problem is solved, please close the issue as solved.

**Closed** 2023-08-22 12:09 UTC
