### ISSUE TITLE
Task View Button

### ISSUE THREAD

**Issue by phpjunkie420** [valinet/ExplorerPatcher#1809] opened 2023-08-09 23:07 UTC
In the latest update with windows Microsoft has changed how the Task View button works and the Task View Option in ExplorerPatcher doesn't work anymore. The only way I've been able to restore the Task View button is to uninstall the Microsoft update.

Windows 11 Pro Build 22621.in-release.220506-1250

**Comment by phpjunkie420** [comment] 2023-08-09 23:50
The Task View button is now set up so you can mouse over it to change Desktops, and the Windows Key + Tab doesn't work anymore.

**Comment by auwsmit** [comment] 2023-08-10 06:38
Regular window switching with alt+tab isn't working for me either. I'm guessing it's related to this since it happened after the same update.

**Comment by sbormann** [comment] 2023-08-10 07:07
👍 Alt+Tab doesn't work either.

**Comment by sunsetsnow** [comment] 2023-08-10 09:27
From my experience, Alt+Tab works until you try to Win+Tab but then stops working after. You can make it work again by restarting File Explorer... at least until the next time you try to Win+Tab.

I've uninstalled the Microsoft update and paused updates for a while. which is hopefully enough time for valinet to figure out a way around this... I hate to just uninstall updates, but not having Win+Tab completely breaks my workflow.

**Comment by rdeforest** [comment] 2023-08-10 10:18
This is a duplicate of #1801.

**Comment by auwsmit** [comment] 2023-08-10 10:50
You can still switch desktops via the Ctrl+Win+Left or Right and it won't
break anything

**Comment by phpjunkie420** [comment] 2023-08-10 13:01
> From my experience, Alt+Tab works until you try to Win+Tab but then stops working after. You can make it work again by restarting File Explorer... at least until the next time you try to Win+Tab.
> 
> I've uninstalled the Microsoft update and paused updates for a while. which is hopefully enough time for valinet to figure out a way around this... I hate to just uninstall updates, but not having Win+Tab completely breaks my workflow.

There is a deprecated app by Microsoft called "[Show or hide updates](https://download.microsoft.com/download/f/2/2/f22d5fdb-59cd-4275-8c95-1be17bf70b21/wushowhide.diagcab)." You won't find it on there site anymore for the simple reason that it is deprecated, but you will find a link to it on Microsoft's website by doing a web search for it. The troubleshooter has been replaced by **other crap** in Windows that won't allow you to stop updates from being installed. [Show or hide updates](https://download.microsoft.com/download/f/2/2/f22d5fdb-59cd-4275-8c95-1be17bf70b21/wushowhide.diagcab) will.

**Comment by pyrates999** [comment] 2023-08-12 10:23
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

**Comment by spersad** [comment] 2023-08-14 05:22
> In the latest update with windows Microsoft has changed how the Task View button works and the Task View Option in ExplorerPatcher doesn't work anymore. The only way I've been able to restore the Task View button is to uninstall the Microsoft update.
> 
> Windows 11 Pro Build 22621.in-release.220506-1250

I am not able to use win+tab to bring up the task view anymore. The task view actually isn't working at all. Any ideas of my issue is also related to the above release? Also, can you please confirm your steps to remove this version? I am not able to find it in my Win11 version history. Thank you.

**Comment by Leevy27** [comment] 2023-08-14 11:27
Hi all, I do not have the mentioned Microsoft Updates installed but the the task view function does not work either. When I switch to Windows 11 Task Bar then I can click the taks view icon and it works, as well as WIN+TAB and ALT+TAB. As soon as I switch back to Windows 10 task bar all the keys and also the task view button in the task bar are not working anymore.

**Comment by phpjunkie420** [comment] 2023-08-14 23:21
> Hi all, I do not have the mentioned Microsoft Updates installed but the the task view function does not work either. When I switch to Windows 11 Task Bar then I can click the taks view icon and it works, as well as WIN+TAB and ALT+TAB. As soon as I switch back to Windows 10 task bar all the keys and also the task view button in the task bar are not working anymore.

Microsoft has made a change in how the Task View button works. The way it use to be is you had to click on it to bring up the task view page. Now all you have to do is mouse over it. This mouse over is what is breaking it.

From what I know the update that is breaking the Task View button comes from an insider updates. In settings got to Windows Update -> Windows Insider Program . The sad part about this is you have to reinstall windows to remove your PC from the Insider Program.

**Comment by phpjunkie420** [comment] 2023-08-14 23:37
> > In the latest update with windows Microsoft has changed how the Task View button works and the Task View Option in ExplorerPatcher doesn't work anymore. The only way I've been able to restore the Task View button is to uninstall the Microsoft update.
> > Windows 11 Pro Build 22621.in-release.220506-1250
> 
> I am not able to use win+tab to bring up the task view anymore. The task view actually isn't working at all. Any ideas if my issue is also related to the above release? Also, can you please confirm your steps to remove this version? I am not able to find it in my Win11 version history. Thank you.

Go to Settings -> Windows Update -> Update history. Click the little up arrow to shrink the "Quality Updates," and click on, "Uninstall updates." Find the update you want to remove and click uninstall. You should see a little blue bar underneath the update indicating that it is being uninstalled. Once uninstalled restart your computer and run [Show or hide updates](https://download.microsoft.com/download/f/2/2/f22d5fdb-59cd-4275-8c95-1be17bf70b21/wushowhide.diagcab). Once [Show or hide updates](https://download.microsoft.com/download/f/2/2/f22d5fdb-59cd-4275-8c95-1be17bf70b21/wushowhide.diagcab) is loaded, click the "Advanced" link and click next. The next part is self explanatory. After you run the program to hide the update restart your computer again.

**Comment by Leevy27** [comment] 2023-08-15 10:30
> > Hi all, I do not have the mentioned Microsoft Updates installed but the the task view function does not work either. When I switch to Windows 11 Task Bar then I can click the taks view icon and it works, as well as WIN+TAB and ALT+TAB. As soon as I switch back to Windows 10 task bar all the keys and also the task view button in the task bar are not working anymore.
> 
> Microsoft has made a change in how the Task View button works. The way it use to be is you had to click on it to bring up the task view page. Now all you have to do is mouse over it. This mouse over is what is breaking it.
> 
> From what I know the update that is breaking the Task View button comes from insider updates. In settings got to Windows Update -> Windows Insider Program. The sad part about this is you have to reinstall windows to remove your PC from the Insider Program after you've unenrolled.

As I said in my previous post, I do not have the mentioned updates installed (KB5028254) nor I'm on the Windows Insider Program. I though it was relevant to the dev that this issue is appearing also to people which have not those updates installed.

**Comment by phpjunkie420** [comment] 2023-08-16 01:21
> > > Hi all, I do not have the mentioned Microsoft Updates installed but the the task view function does not work either. When I switch to Windows 11 Task Bar then I can click the taks view icon and it works, as well as WIN+TAB and ALT+TAB. As soon as I switch back to Windows 10 task bar all the keys and also the task view button in the task bar are not working anymore.
> > 
> > 
> > Microsoft has made a change in how the Task View button works. The way it use to be is you had to click on it to bring up the task view page. Now all you have to do is mouse over it. This mouse over is what is breaking it.
> > From what I know the update that is breaking the Task View button comes from insider updates. In settings got to Windows Update -> Windows Insider Program. The sad part about this is you have to reinstall windows to remove your PC from the Insider Program after you've unenrolled.
> 
> As I said in my previous post, I do not have the mentioned updates installed (KB5028254) nor I'm on the Windows Insider Program. I though it was relevant to the dev that this issue is appearing also to people which have not those updates installed.

I reinstalled windows and found out that this isn't apart of the insider program. I have no idea what  KB update this would be for you but for me it was KB5029263 and I'm using a Custom Windows 11 Pro that is the Alienware x17 R2 System Restore for my computer. I say this 'cause what I've noticed is that the KB that has the change for the Task View button is dramatically different for everyone and seems dependent on their system.

**Comment by Poopooracoocoo** [comment] 2023-08-22 09:43
Closing as duplicate of #1687 and #1802

**Closed by Poopooracoocoo** 2023-08-22 09:43 UTC
