### ISSUE TITLE
Lost ability to choose which apps appear in notification area, now it's either all or none

### ISSUE THREAD

**Issue by lwerman** [valinet/ExplorerPatcher#3554] opened 2024-08-11 13:49 UTC
Edition	Windows 11 Pro
Version	23H2
Installed on	‎8/‎10/‎2024
OS build	22631.3880
Experience	Windows Feature Experience Pack 1000.22700.1020.0

Did a Windows Recovery using Windows Update feature. It took about 3 hours to complete.
Now I can't choose which apps appear in the notification area. The only way to see any app there is to choose "Always show all icons..."
Uninstalled EP & deleted the reg key folder, then installed EP v65.5. No help. System apps there are OK.

**Comment by pyrates999** [comment] 2024-08-11 14:27
You can drag and drop the icon in the system tray to the popup menu that you don't want shown.

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this.

**Closed** 2024-08-11 15:20 UTC
