### ISSUE TITLE
Right-click on patched Windows 11 taskbar crashes Explorer

### ISSUE THREAD

**Issue by TylerMS887** [valinet/ExplorerPatcher#1241] opened 2023-04-02 10:16 UTC
https://user-images.githubusercontent.com/115214762/229346762-41fe3e4a-a157-4be7-ac52-68b997b460de.mp4

To reproduce, right click on the taskbar with taskbar style set to Windows 11.
Tested on build 25324.1011.

**Comment by gangefors** [comment] 2023-04-04 21:08
Duplicate of #1211 maybe?

**Comment by Imold** [comment] 2023-04-12 15:45
I was able to reproduce this bug. It happens when ("Taskbar style" is set to "Windows 11", and "Skin taskbar and tray pop-up menus" is on), or (when "Taskbar style" is set to "Windows 10", and "Skin taskbar and tray pop-up menus" is off).

To use Windows 11 style Taskbar: Turn off "Skin taskbar and tray pop-up menus"
To use Windows 10 style Taskbar: Turn on "Skin taskbar and tray pop-up menus"

Pretty sure this is a dup of  #1147 as that's where I found out about the connection with "Skin taskbar and tray pop-up menus" I found out you have to do the opposite for the win10 taskbar myself.

**Comment by eymre** [comment] 2023-04-24 18:56
Been having the same issue for the past few versions. Turning on "Skin taskbar and tray pop-up menus" using Windows 10 style Taskbar fixed the crash.

Is it possible for EP to automatically apply the workarounds in the previous comment until this issue is fixed? E.g. turn on "Skin taskbar"  automatically if Windows 10 style Taskbar is selected.

**Comment by thestonefox** [comment] 2023-08-14 14:22
I've found if I disable `Do not change the taskbar context menu` option in `Advanced` properties then it no longer crashes.

**Comment by pyrates999** [comment] 2023-08-15 12:16
Build 25324.1011 is a canary build.  So I don't think this will be fixed anytime soon.

It could be related to this one though: https://github.com/valinet/ExplorerPatcher/issues/1828

**Closed** 2023-09-23 04:51 UTC
