### ISSUE TITLE
Taskbar crashes if i richt click on it

### ISSUE THREAD

**Issue by zERO123331** [valinet/ExplorerPatcher#1993] opened 2023-09-04 14:04 UTC
If i rightclick on my taskbar, it just restarts and opens the window that you get if you install windows 11 but its blank and after a few seconds it disappear

i am using windows 11 pro insider preview Build 23531.1001
i know that this is the dev channel but the issue happend before i joined the Insider Programme

**Comment by SiteSplat** [comment] 2023-09-04 14:16
Do you have the update KB5029263 installed?

**Comment by Poopooracoocoo** [comment] 2023-09-04 15:12
Duplicate of #1952

**Closed by Poopooracoocoo** 2023-09-04 15:12 UTC
