### ISSUE TITLE
HackTool:Win32

### ISSUE THREAD

**Issue by MaybeAnge** [valinet/ExplorerPatcher#3744] opened 2024-09-28 08:47 UTC
Why Windows Defender now detects ExplorerPatcher like this, when it didn't before?

![image](https://github.com/user-attachments/assets/629a853c-c640-4300-b455-a32361ada431)

**Comment by PythonTryHard** [comment] 2024-09-28 14:18
Duplicate of #3228

**Closed** 2024-09-28 14:54 UTC
