### ISSUE TITLE
Incompatibility with OpenShell and Windows 11 24H2

### ISSUE THREAD

**Issue by MCAlexisYT** [valinet/ExplorerPatcher#4069] opened 2024-12-26 15:36 UTC
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [X] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

Version 22621.4317.67.1

### Repro Windows Versions

Windows 11 24H2 x64

### 3rd party tweak software installed

OpenShell

### Describe the bug

When the Windows 10 task bar reimplementation is enabled, the taskbar texture in OpenShell config partially works.

### Expected outcome

The taskbar texture is present across the entire taskbar

### Actual outcome

![image](https://github.com/user-attachments/assets/66151703-1415-4eb9-9751-d54ffb305218)

**Comment by Amrsatrio** [comment] 2024-12-26 21:47
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3456

**Closed by Amrsatrio** 2024-12-26 21:47 UTC
