### ISSUE TITLE
Explorer crashing while opening File Explorer

### ISSUE THREAD

**Issue by henrisata** [valinet/ExplorerPatcher#1849] opened 2023-08-14 13:34 UTC
I've opened the Windows File Explorer several times and it keeps restarting explorer.exe (I put the service so it wouldn't get confusing), I'm on the latest version of Windows 11

Note: I noticed a pattern, every 2 times I open the Windows File Explorer and with a certain time between openings, explorer.exe restarts.

**Comment by Will0120** [comment] 2023-08-14 17:48
Exact same issue for me.  Also the exact same patter as described above, it crashes every second time I open "This PC" via my desktop icon.

**Comment by ValePanzer** [comment] 2023-08-14 17:59
Exact same happens to me too. I also noticed that explorer.exe restarts when i have my Taskbar on Win 11 and right-click on the taskbar. There are quite a few with similar/same issues since the last windows update

**Comment by arikanorh** [comment] 2023-08-15 07:58
I updated my windows and it crashes+restarts then stops with crash information
![image](https://github.com/valinet/ExplorerPatcher/assets/17791032/2ecb3a20-7973-4f1f-9bc3-b673f8e0f816)

**Comment by arikanorh** [comment] 2023-08-15 12:42
Windows 11 Pro
Version: 22H2
OS Build: 22621.2134

ExplorerPatcher
Version 22621.56.1

**Comment by ctitoc** [comment] 2023-08-15 12:43
Same issue here. Taskbar and explorer.exe crashing every time I click taskbar. Same error message as posted by arikanorh.

Windows 11 Home 22H2

ver 22621.2134

ExplorerPatcher 
22621.1992.56.1

**Comment by marcelokrol** [comment] 2023-08-15 12:48
I have the same problem, and the same version of Windows and ExplorerPatcher mentioned by the colleague above

**Comment by pyrates999** [comment] 2023-08-15 12:48
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

**Comment by henrisata** [comment] 2023-08-15 14:10
> duplicate of: #1828
> 
> Please close this one.

I can close this issue once the developer has fixed the problem, with all due respect. Also, more people may be able to identify with this issue or even post a solution, not the developer. I also believe that the developer, seeing more and more issues about this topic, will try to fix it as soon as possible (I believe) and without having to scroll through kilometers of chats.

**Comment by Heliomance** [comment] 2023-08-17 10:53
> > duplicate of: #1828
> > Please close this one.
> 
> I can close this issue once the developer has fixed the problem, with all due respect. Also, more people may be able to identify with this issue or even post a solution, not the developer. I also believe that the developer, seeing more and more issues about this topic, will try to fix it as soon as possible (I believe) and without having to scroll through kilometers of chats.

As a developer, duplicate issues are annoying and don't help anything get fixed faster. One issue, one ticket is the way it should be. This is absolutely a duplicate of #1828 and #1861, also #1842, and probably a few others. All except one thread should be marked as duplicates and closed, leaving one issue open until the developer confirms it fixed.

**Comment by phyco1991** [comment] 2023-08-17 14:43
See https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6690573 for a working fix

**Comment by pyrates999** [comment] 2023-08-18 11:13
explorer crashing with aug 8 update

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Closed** 2023-08-18 12:33 UTC

**Comment by ttellerx** [comment] 2023-08-30 04:44
I have the same problem. Explorer patcher is not installed.

**Comment by pyrates999** [comment] 2023-08-30 05:31
> I have the same problem. Explorer patcher is not installed.

If EP is not installed and you still experience file explorer crashing, that is not a bug with EP.
