### ISSUE TITLE
language change doesnt work sometimes

### ISSUE THREAD

**Issue by rdchariotti** [valinet/ExplorerPatcher#2700] opened 2024-01-15 20:41 UTC
After installing app sometimes(maybe 5-10%) ctrl+shift language change does not work

**Comment by pyrates999** [comment] 2024-01-15 21:18
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by rdchariotti** [comment] 2024-01-15 22:57
OS 22621.3007 and latest patcher 22621.2861.62.2, but it didnt work before too so i dont think its related to version right away, more like mix of ctrl+shift language switch+smth

**Comment by s3n0** [comment] 2024-01-16 09:29
The standard keyboard shortcut is Left ALT + Left SHIFT. So why are you using CTRL button ? Did you change the default setting ?

So this could also be a problem... that you changed the default setting to CTRL + SHIFT and then EP will have some problems with this change. 

I also often use switching keyboards (English / Slovak), sometimes even 20-30 times a day, but I haven't noticed any problems yet. Although it's true that I've only been using EP for 2-3 days so far.

**Comment by 4aiman** [comment] 2024-01-28 12:11
I can confirm that across multiple win10 and win11 versions, switching with anything but win+space can stop working properly.
Sometimes it takes up to 10 times to finally switch over a different layout.

But that is **not** an issue within EP.
EP can actually **solve* the issue*.

It's something that's being reported ever since [2016](https://answers.microsoft.com/en-us/windows/forum/all/switching-keyboard-layout-doesnt-work-anymore/fc116a23-1745-4a35-a5dd-048c58ac363d) with little to no attention from Microsoft.
There are solutions for win 10 to remove language switcher popup for win10, but those require a patched dll from the internetz and fail to work for win 11. More history [here](https://answers.microsoft.com/en-us/windows/forum/all/how-to-turn-off-language-switch-bar/a9ed3821-af73-4a06-a105-f725d6e5fdf0?page=8)

But EP can switch the layout switcher (tongue twister, eh?) to one of the prior states (where it worked).
Once EP is installed everything works as expected.

But *sometimes* something goes wrong in-between windows/EP updates with certain setups and language switching stops working again (or starts affecting a user).

If you're like me and simply cannot cope with the way taskbar is in win11, then here's what helped me in the past:
- a total removal of EP and re-installation.

Be aware that EP doesn't clean it's registry entries upon uninstall.
You have to do in manually. 
Here's a "list" of the leftovers:
![изображение](https://github.com/valinet/ExplorerPatcher/assets/2913210/5ac4dc73-fc35-4b92-8147-7fa0fea7af54)

After uninstalling and cleaning up the registry, reboot. Then install EP anew and see if that solves the issue.
If not - welp, I tried. Can't really help with anything.

**Comment by Amrsatrio** [comment] 2024-01-30 05:40
Agreed with @4aiman -- this isn't an EP issue. Closing this for that.

**Closed by Amrsatrio** 2024-01-30 05:40 UTC

**Comment by ekungurov** [comment] 2024-03-15 10:30
I have the same issue only when ExplorerPatcher is installed. While using Alt+Shift for switching. 

This is very hard to reproduce deliberately, but I run into this issue over and over and it is very annoying. I even though this is Windows 11 itself bug, but now I understand it's not. 

Below I will try to explain the issue as detailed as possible. 

The Alt+Shift usually works but if you press and release it either simultaneously, or with very precise timing - it is been ignored and does not switch layouts. 

Now I have to describe more about how layout widget usually works:
- Given we have Alt+Shift as key combination
- And imagine we press Alt first, then Shift, not releasing both keys.  
- Now imagine that you release Shift first, and you release Alt after some delay (lets say one second delay). In this case you will see on-screen language menu with two languages (or more, if you have more installed in the system), and also the layout will switch as well.  
- Now imagine that you release Alt first, and you release Shift after that. In this case you will have just simple language switch, without showing on-screen menu.
- And now imagine that you release Alt and Shift perfectly simultaneously, at a very specific milliseconds timing (when trying to reproduce deliberately you have to brute force the correct timing). In this case nothing happens! On-screen menu is not displayed, but more importantly the switch has not occured!

The last line reproduces only when ExplorerPatcher is installed. Without ExplorerPatcher, the simultaneous Alt+Shift release always switches layout. 

Windows 11 22H2 (currently 22621.3296)

**Comment by 4aiman** [comment] 2024-03-15 12:03
Annoying? Yes.
Has specific timing? 100%.
EP issue? No, definitely *not* an EP issue.

Ever since the last time I've posted anything here, EP stopped helping with the issue.
So I uninstalled it (removed registry entries as well).
And the alt_shift issue is still there.
With or without EP.
With or without the latest 03/2024 22H2 cumulative patch.
The only thing that EP can contribute towards is the aforementioned layout switch flyout/popup.

**Comment by ekungurov** [comment] 2024-03-15 12:39
Strange. When I uninstall EP I am unable to reproduce the issue. But with EP I can reproduce it consistently. 

From #2968 I've learned that EP has some crash detection feature invoked by holding Ctrl+Alt+Shift. Are you sure nothing could interfere with layout switching?

**Comment by Amrsatrio** [comment] 2024-03-15 13:19
The crash detection hotkey is only valid during explorer.exe startup and should not interfere with any other registered hotkeys. It uses the GetAsyncKeyState function:

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate

**Comment by s3n0** [comment] 2024-03-24 10:17
On the topic of switching keyboards, I have to add that I started to observe an interesting phenomenon.

After starting the LOL game (League of Legends), the Alt+Shift keyboard switch will stop working in my OS.

I use two keyboards to switch in my Windows OS - for my native language and for the English language.

After exiting the game or turning off the EP, the problem is not resolved.

I don't know what this could be related to. Maybe some mistake of the LOL game ?

OS: Windows 11 / 22631.3296 / 23H2
EP: 22621.3296.64.1
EP taskbar style: Windows 10
