### ISSUE TITLE
"Enable missing system tray icons" CPL restarts Explorer when the tray clock updates

### ISSUE THREAD

**Issue by Zoomer1988** [valinet/ExplorerPatcher#236] opened 2021-10-30 21:09 UTC
Hello! First of all, thanks for your work. 

That's probably not the ExplorerPatcher's bug per se, but still. 

1. Have your win10 taskbar display clock in the systray.
2. Open "Enable missing system tray icons" dialogue (which is actually a shell window, not ExplorerPatcher's, I know
3. Don't press anything and wait for the clock to update. When It happens, the dialogue window closes and the explorer silently restarts.
You can also enable the "Show settings in the clock" option to have it restart almost instantaneously.

**Comment by valinet** [comment] 2021-10-31 02:28
Yeah, I know, and it’s been like this for a whole while; I tried various things, but was unable to fix it. It took me ages to actually reproduce it, figure out what exactly on that page made it restart, found the answer just yesterday. Should have waited one more day so you could tell me from the get go :)))

So yeah, I would love to fix this, but unfortunately, I don’t know how. One of the subclass procedures goes crazy, apparently, but not mine, as even if I take out all the code but the one that activates the old taskbar, including any subclassing I do, it still happens… yeah, I don’t know, help needed, it’s a hard one, but fortunately not critical, since how often does one access that page…

**Comment by Zoomer1988** [comment] 2021-10-31 21:59
Aw! Cool :D I spotted it right in the beginning but didn't want to report until, you guessed it, I find out a way to reproduce it, haha. At first, it seemed very random. 

Oh well. Indeed it's not critical now when we know what triggers it :)

**Comment by valinet** [comment] 2021-11-01 01:00
Exactly, like, I knew aboutit for quite a while, and it indeed seemed so random and thought it’s just a thing on my system, since no one reported it. And also, I did not find it, as I still say, a major thing because it only happens on that page *when the clock changes*. That’s so weird of a bug…

Anyway, I really wish I’d find out what causes it. I don’t even know if it’s a bug of ExplorePatcher per se. I mean, as I said, compiling the “dumbest” EP that just enables the old taskbar and nothing else still triggers it. And comparing with StartAllBack is not than conclusive even: I don’t know if it happens with that, but it doesn’t even matter that much, as I don’t know if that maybe contains code to fix it, maybe the author there found this Explorer bug as well and patched it in that case… I don’t know, really.

As I said (I think), I will look into it when I have the time and for sure I will fix it if I discover how. For now, that’s all I can say or do about it. And I am glad that it is a minor inconvenience.

Thanks

**Comment by Anixx** [comment] 2021-12-08 08:29
I cannot reproduce this problem, bur for me, very strangely another settings dialog closes on clock update, this one:
![изображение](https://user-images.githubusercontent.com/1271736/145174730-62c1b1e5-53fd-4059-94de-e76f20f5204b.png)

At the same time, the tray icons dialog stays without a problem.

**Comment by Anixx** [comment] 2021-12-08 08:38
It should be noted, the Explorer is not restarted when this dialog closes, only the System Settings app exits.

**Comment by Anixx** [comment] 2021-12-08 08:40
This dialog stays indefinitely without any crashes:
![изображение](https://user-images.githubusercontent.com/1271736/145176319-daa2d9be-b7cc-4830-b7fb-534e5ff082a3.png)

**Comment by Anixx** [comment] 2021-12-08 08:47
Ok, I tried to reproduce this after Explorer killed, and the dialog exited as well, but the window did not disappear, I got this strange empty window:
![изображение](https://user-images.githubusercontent.com/1271736/145177456-81458ec0-bdc5-4c2e-8837-19e7494e89bd.png)

**Comment by valinet** [comment] 2021-12-08 10:40
Are we sure those 2 are the same “bug”? The window that we are talking about originally here is the system icons CPL, not the one with the 3rd party icons that you showed in your screenshot.

You say the Settings app crashes in some page when the clock updates. Can you reproduce this on a clean VM? Your Windows install is too tainted to be reliable for a bug report. If so, then yeah, it may be this or likely some other issue.

**Comment by Anixx** [comment] 2021-12-08 11:05
This dialog also stays upon clock update, nothing happens:

![изображение](https://user-images.githubusercontent.com/1271736/145197957-c6484072-1105-48e5-b004-e2c697cb264a.png)

**Comment by Anixx** [comment] 2021-12-08 11:07
Does your bug happen when the seconds update? I can test it.

**Comment by Anixx** [comment] 2021-12-08 11:11
Well, seconds update does not affect my bug and the dialog exits are seemingly not synced with the clock. It exits after about 30 sec., always.

**Comment by valinet** [comment] 2021-12-27 12:11
This seems to be fixed in the latest pre-release (40.19).

**Comment by Anixx** [comment] 2021-12-27 13:45
The display settings still crash for me.

**Comment by valinet** [comment] 2021-12-27 14:29
I already mentioned previously, this bug is about the system icons CPL crashing. Display settings work fine on rather clean Windows installs.

**Closed** 2021-12-28 19:26 UTC
Labels: bug, help wanted

**Comment by valinet** [comment] 2022-02-01 15:08
This is not a bug in ExplorerPatcher, apparently. It's happening in Windows Explorer all by itself, it happens even in Windows 10 (confirmed today in Windows 10 2021 LTSC IoT Enterprise 19044.1466).
