### ISSUE TITLE
ep_taskbar crashes Explorer when receiving notifications

### ISSUE THREAD

**Issue by 1kartafal4** [valinet/ExplorerPatcher#3605] opened 2024-08-29 10:46 UTC
Good day to the developers,

thanks a lot for this good program.

I use it together with TranslucentTB (both latest version) and on Windows 11 23H2 it worked fine.
After now installing the latest Release Preview build 26100.15xx (new clean install, no windows-insider program), the program keeps crashing the windows explorer, which then automatically restarts.
As you can see in the screenshot, 3 times in 5 minutes.
I can send a copy of the .evtx file of the windows event viewer if needed, and/or are there log files from ExplorerPatcher itself that can be send?

Can you fix it, or is it Windows specific? I'm using the Windows 10 (ExplorerPatcher) taskbar style.

Greetings
![error1](https://github.com/user-attachments/assets/62a1ad37-14a0-4751-ba73-6d45f6d7dc65)
![error2](https://github.com/user-attachments/assets/f364df82-e45a-464b-83cb-2cfdb59d311b)

**Comment by pyrates999** [comment] 2024-08-29 11:50
What version of EP are you running?
Please put the exact windows version and build number.  You can find out by running winver.

**Comment by Amrsatrio** [comment] 2024-08-29 13:10
Thank you for reporting this. I will check soon.

**Comment by Amrsatrio** [comment] 2024-08-29 13:11
Would be great if you can send your explorer.exe with its file extension renamed to .txt.

**Comment by Amrsatrio** [comment] 2024-08-29 13:13
https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation

We have warned for this issue to happen in the 3rd point in its Warning section.

**Comment by CyanDragonS** [comment] 2024-08-29 16:28
The software hasn't been updated in almost four months. Almost all Windows11 versions higher than 23H2 (22621) are not supported, and the 26100(LTSC Preview) version will directly indicate that the application will not run on this computer. Whether the author can update as soon as possible, there are many bugs, almost can not be used. thank you.

**Comment by pyrates999** [comment] 2024-09-06 21:59
if you enabled the option register as shell extension, disable it by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by Amrsatrio** [comment] 2024-09-07 06:49
Were the crashes happening when you were receiving a flurry of notifications? I know that continuous notifications from Telegram crashes Explorer.

**Comment by Amrsatrio** [comment] 2024-09-07 06:57
Yeah just checked it, the error happened in the handler for notifications. I kept getting these crashes too if I have Telegram open and keep getting messages. Seriously I don't know what went wrong in here... but I could compromise the little app icon sliding animation to prevent this from happening altogether.

![image](https://github.com/user-attachments/assets/ee58f2da-87dc-492a-9972-cb6d2cd23ab4)

**Comment by Amrsatrio** [comment] 2024-09-11 19:31
Investigated further. I noticed that a struct used by the private APIs for notifications grew by 8 bytes in 22621.3296 when compared to 22621.1992. Simply there is no easy way to get around this without making complex code matching patterns.

I may have to axe the app icon sliding thingy from the notification center button for good.

**Comment by Amrsatrio** [comment] 2024-09-16 00:51
No, different issue. Anyways I edited the code on my phone to disable the notification gleams feature. The taskbar DLL is building right now and once it's done I'll share you the link.

**Comment by perezsam150** [comment] 2024-10-09 21:24
@Amrsatrio 

Would it be possible to have that DLL as well? I am facing the same issues with ep_taskbar5.dll crashing. Many thanks.

**Comment by perezsam150** [comment] 2024-10-09 21:31
Good day @Amrsatrio 

Would it be possible to have a copy of that taskbar DLL as well? I am also on the [22621.3880.66.6](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.6_92fce8c) release and ep_taskbar5.dll is crashing as well. I'd like to try it out and report if it alleviates the problem.

Regards

**Comment by pyrates999** [comment] 2024-10-11 11:47
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3605

please close this.

**Comment by Amrsatrio** [comment] 2024-10-11 11:49
No it is not a duplicate. Instead it is a sign that I should hurry up with other bug fixes.

**Comment by pyrates999** [comment] 2024-10-14 18:59
@1kartafal4 lol oh no, sorry :D

**Comment by Amrsatrio** [comment] 2024-10-16 17:04
Fixed in 66.7.

**Closed by Amrsatrio** 2024-10-16 17:04 UTC
Labels: ep_taskbar

**Comment by Amrsatrio** [comment] 2024-10-16 17:37
Really sorry for taking this long. 🙇
