### ISSUE TITLE
Right Click on Taskbar not working/reloading winexplorer

### ISSUE THREAD

**Issue by ThiagoScala** [valinet/ExplorerPatcher#1910] opened 2023-08-23 16:21 UTC
When i right click on the taskbar the explorer freezes for a sec and then reloads. i am unable to use right click.

Sorry if this is a old bug i didn't find it here .

**Comment by benlecook** [comment] 2023-08-23 16:42
HI,
I don't hnow if it is a new update for Windows 11, but I have the same bug since 2 days. I start my computer yesterday and the bug was there. First, my toolbars disappeared. Then I reinstalled it. After I update windows 11. I think that's the problem. KB5029351 is the last update on my computer. The bug appeared after the updat.
I tried to install the latest release of ExplorerPatcher 10 minutes ago and nothing change. Even if I uninstall ep_setup.exe and clear the register before re-installing it.
If this can be useful.

**Comment by Vipin2003** [comment] 2023-08-23 16:54
You can still access the R-click in Win10 Taskbar.. But if you are using win11 taskbar, then you have to enable "Do not change context menu" option. Bcoz currently EP is not completely stable with latest stable version 22621.2134. So, the classic CM won't work for now on Win11 taskbar. Use default win11 CM.

Just wait as valinet is working on fixing all currently running bugs from 1992 version to 2134. Wait patiently as he is doing his work and making EP stable for us.

**Comment by ThiagoScala** [comment] 2023-08-23 17:02
Is it possible to know which version is the best one to use until they fix it?

**Comment by benlecook** [comment] 2023-08-23 18:47
I forgot to say, as soon I right clik, the taskbar dissapear and come back a few second later. The taskbar is the Win11 one. Really can't access anything by right clicking.

**Comment by Poopooracoocoo** [comment] 2023-08-23 20:51
Please state which taskbar you are using, what your OS build is and what version of EP you're running. 
Duplicate of #1805

**Closed by Poopooracoocoo** 2023-08-23 20:51 UTC

**Comment by ThiagoScala** [comment] 2023-08-23 21:47
I am using the default windows taskbar i just installed the ExplorerPatcher to get better options when i right click.
My windows version is: 
Win 11 Pro 22H2  - 22621.2134
EP is the last one i think, i don't know where to look the version i have

**Comment by pyrates999** [comment] 2023-08-23 23:15
> I am using the default windows taskbar i just installed the ExplorerPatcher to get better options when i right click. My windows version is: Win 11 Pro 22H2 - 22621.2134 EP is the last one i think, i don't know where to look the version i have

So you're using windows 11 taskbar then?

**Comment by ThiagoScala** [comment] 2023-08-24 01:52
> > I am using the default windows taskbar i just installed the ExplorerPatcher to get better options when i right click. My windows version is: Win 11 Pro 22H2 - 22621.2134 EP is the last one i think, i don't know where to look the version i have
> 
> So you're using windows 11 taskbar then?

Yes, I thought he was asking if I was using another software to change the taskbar or something.
