### ISSUE TITLE
typing in search changes position of start bar

### ISSUE THREAD

**Issue by eQuara** [valinet/ExplorerPatcher#1413] opened 2023-05-02 22:06 UTC
https://streamable.com/go5iez this is what i mean (5secclip)

**Comment by Ichebykin** [comment] 2023-05-10 21:04
https://github.com/valinet/ExplorerPatcher/issues/1378

**Comment by pyrates999** [comment] 2023-09-05 07:16
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1378

Please close this.

**Closed** 2023-09-23 04:31 UTC
