### ISSUE TITLE
Start Menu Bug: Disabled Recommendations Temporarily Reappear

### ISSUE THREAD

**Issue by JCarlos1903** [valinet/ExplorerPatcher#4072] opened 2024-12-28 13:10 UTC
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [X] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

ExplorerPatcher 22621.4317.67.1

### Repro Windows Versions

Windows 11 24H2 26100.2605 x64

### 3rd party tweak software installed

None

### Describe the bug

1. Install ExplorerPatcher.
2. Enable "Disable Recommendations section in Start Menu" option in ExplorerPatcher settings.
3. Open Start menu and verify recommendations are not shown.
4. Try to unpin any shortcut from Start menu.
5. Observe that recommendations section temporarily reappears while unpinning the shortcut.

### Expected outcome

The recommendations section should always remain hidden, even after unpinning shortcuts from the Start menu.

### Actual outcome

While recommendations are generally hidden as configured, they briefly reappear in the Start menu specifically during the action of unpinning shortcuts. This occurs consistently each time a shortcut is unpinned.

### Additional info

The issue occurs consistently and is reproducible.
The behavior appears specific to the interaction between ExplorerPatcher's recommendation hiding feature and Windows' shortcut unpinning process.
The bug appears temporary and self-corrects upon reopening the Start menu.

### Crash Dumps

No crashes occur related to this issue.

**Comment by pyrates999** [comment] 2024-12-28 23:00
which start menu are you using?  windows 10 start menu or windows 11 start menu?

**Comment by milesprower2293** [comment] 2024-12-31 16:25
Duplicate of #3313

**Closed by milesprower2293** 2024-12-31 16:25 UTC
