### ISSUE TITLE
[bug] Vertical taskbar (left), start button at the top, app search appears bottom-left

### ISSUE THREAD

**Issue by alex-jitbit** [valinet/ExplorerPatcher#2421] opened 2023-11-10 19:57 UTC
Not sure where to post bug reports. The issues page says "Use discussions", Discussions has a "how to report problems" document at the top. The "document"  says it's "outdated, please use issues". So posting an issue.

STR the bug:

* Win10 taskbar style, vertical at the left. 
* Win11 start button style.
* Start button and menu are at top-left (all good)
* However if I start typing - the menu is now at bottom left.

**Comment by pyrates999** [comment] 2023-11-10 22:50
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application that you haven't mentioned yet.

**Comment by Amrsatrio** [comment] 2023-11-11 03:25
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1803

**Closed by Amrsatrio** 2023-11-11 03:25 UTC
