### ISSUE TITLE
[Crash] On explorer start

### ISSUE THREAD

**Issue by CrazyWolf13** [valinet/ExplorerPatcher#2066] opened 2023-09-14 19:15 UTC
Hi
Every second time I try to open explorer.exe, the explorer task crashes completely, all my backgrounds get solid color. screen flashes, background image appears, start explorer.exe now working fine. Close and reopen, crash again.

running latest win11
running latest explorerpatcher
already tried reeinstall via some old github tickets about crashes.
[ExplorerPatcher_22621.1992.56.3.reg.txt](https://github.com/valinet/ExplorerPatcher/files/12612501/ExplorerPatcher_22621.1992.56.3.reg.txt)
Attached .reg file of settings exported via explorerpatcher

**Comment by pyrates999** [comment] 2023-09-14 21:32
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2051

Please close this one.

Possible fixes:

1. In ExplorerPatcher Properties, go to Advanced and tick **Do not change the taskbar context menu**
2. In ExplorerPatcher Properties, go to File Explorer and untick **Disable the windows 11 context menu**
3. In ExplorerPatcher Properties, go to Taskbar and set **Taskbar style** to **Windows 11**

**Comment by Poopooracoocoo** [comment] 2023-09-14 22:46
Define latest Windows 11. Define latest EP version.

**Comment by CrazyWolf13** [comment] 2023-09-15 03:36
@Poopooracoocoo 
Why close?
Not sure if they are related, because on my side explorer.exe is crashing specifically every second time, not randomly or always.

**Comment by CrazyWolf13** [comment] 2023-09-15 03:38
@Poopooracoocoo 
Why close?
Not sure if they are related, because on my side explorer.exe is crashing specifically every second time, not randomly or always.
My issue is persisting since like 2-4months, but I've never felt like reporting a bug because otherwise the next update already fixed those bugs.

**Comment by CrazyWolf13** [comment] 2023-09-15 03:41
Explorerpatcher version: 22621.1992.56.3
Win11 version: will follow today evening CET

**Comment by CrazyWolf13** [comment] 2023-09-15 03:44
> Explorerpatcher version: 22621.1992.56.3
> Win11 version: will follow today evening CET 

@Poopooracoocoo 

Explanation:
 https://github.com/valinet/ExplorerPatcher/issues/2051#issuecomment-1720352061

**Comment by miku1881** [comment] 2023-09-15 23:01
Yesterday, there was a windows update, and I updated it.

The next day I booted up my PC and the explorer patcher crashed like it did with 22621.2134.
I have reinstalled it now, so I don't have that problem, but this may be happening to other users, so please make sure that 22621.2283 doesn't crash too, ASAP.

**Comment by loby66** [comment] 2023-09-16 14:29
> Hi Every second time I try to open explorer.exe, the explorer task crashes completely, all my backgrounds get solid color. screen flashes, background image appears, start explorer.exe now working fine. Close and reopen, crash again.

A workaround is to add "explorer.exe" on your folder shortcuts properties

https://i.imgur.com/wnLvy1D.jpg

**Comment by CrazyWolf13** [comment] 2023-09-17 09:18
> > Hi Every second time I try to open explorer.exe, the explorer task crashes completely, all my backgrounds get solid color. screen flashes, background image appears, start explorer.exe now working fine. Close and reopen, crash again.
> 
> A workaround is to add "explorer.exe" in your folder shortcuts properties
> 
> https://i.imgur.com/wnLvy1D.jpg

I sadly can't speak the language displayed in the screenshot, can you explain a bit further what the workaround involves?

**Comment by Amrsatrio** [comment] 2023-09-23 02:37
Valinet has released a new EP build. There should be no more major issues on 22621 builds up to 22621.2359. Please close the issue if they are gone on your end.

**Comment by CrazyWolf13** [comment] 2023-09-23 13:52
Still not fixed...

Explorer still crashes every second time

> Valinet has released a new EP build. There should be no more major issues on 22621 builds up to 22621.2359. Please close this issue if they are gone on your end.

**Comment by Amrsatrio** [comment] 2023-09-23 13:56
Run `winver` and screenshot. Also, are you using other customization software like TranslucentTB?

**Comment by CrazyWolf13** [comment] 2023-09-23 13:57
> Run `winver` and screenshot. Also, are you using other customization software like TranslucentTB?

![image](https://github.com/valinet/ExplorerPatcher/assets/96661824/1d3c1f1b-51c7-4f86-aa54-2fe2c0099e61)
Yes TaskbarX and Nilesoft Shell

**Comment by Amrsatrio** [comment] 2023-09-23 13:58
Please try disabling those. I do not encounter any major issues with 2283 when my customization software is only EP.

**Comment by CrazyWolf13** [comment] 2023-09-23 14:02
Disabled all, including (Rainmeter(TaskbarX), ModernFlyouts, Nilesoft Shell) 
Reloaded Explorer and problem persists

**Comment by Amrsatrio** [comment] 2023-09-23 14:05
Please open `eventvwr`, find a crash for `explorer.exe`, and show me the text I've selected:
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/097a5d61-f6de-4b75-b6c2-c786a40e6a9f)

**Comment by CrazyWolf13** [comment] 2023-09-23 14:07
> Please open `eventvwr`, find a crash for `explorer.exe`, and show me the text I've selected: ![image](https://user-images.githubusercontent.com/20662640/270113013-097a5d61-f6de-4b75-b6c2-c786a40e6a9f.png)

It's in German, but I hope it's still useful 
![image](https://github.com/valinet/ExplorerPatcher/assets/96661824/541f4979-1e38-481c-928b-14a92dcd8408)

**Comment by Amrsatrio** [comment] 2023-09-23 14:18
Have you tried using the Windows 11 command bar? Maybe send your settings too using this button. Your issue is unique I think.
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/2daa1e21-a3cc-4625-9c7d-4faf8d692b23)

**Comment by CrazyWolf13** [comment] 2023-09-23 14:21
[ExplorerPatcher_22621.2283.57.2.reg.txt](https://github.com/valinet/ExplorerPatcher/files/12706645/ExplorerPatcher_22621.2283.57.2.reg.txt)

Here you go, thanks for looking into this.

Edit: renamed the file to allow uploading.

**Comment by CrazyWolf13** [comment] 2023-09-23 14:21
> [ExplorerPatcher_22621.2283.57.2.reg.txt](https://github.com/valinet/ExplorerPatcher/files/12706645/ExplorerPatcher_22621.2283.57.2.reg.txt)
> 
> Here you go, thanks for looking into this.
> 
> Edit: renamed the file to allow uploading.

What do you mean with windows 11 command bar?

**Comment by CrazyWolf13** [comment] 2023-09-23 14:22
> Have you tried using the Windows 11 command bar? Maybe send your settings too using this button. Your issue is unique I think. ![image](https://user-images.githubusercontent.com/20662640/270113633-2daa1e21-a3cc-4625-9c7d-4faf8d692b23.png)

What do you mean with windows 11 command bar?

**Comment by Amrsatrio** [comment] 2023-09-23 14:24
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/becbfb1c-c1aa-4e54-9e63-195c6b5de5b0)

**Comment by CrazyWolf13** [comment] 2023-09-23 14:54
> ![image](https://user-images.githubusercontent.com/20662640/270113970-becbfb1c-c1aa-4e54-9e63-195c6b5de5b0.png)

Is already set to that.

**Comment by Bucko-m** [comment] 2023-09-23 22:54
> Still not fixed...
> 
> Explorer still crashes every second time
> 
> > Valinet has released a new EP build. There should be no more major issues on 22621 builds up to 22621.2359. Please close this issue if they are gone on your end.

same for me.

**Comment by Amrsatrio** [comment] 2023-09-25 05:13
I've identified and fixed the potential crash sites andreleased a new version. Please check if it still crashes. If not, I'll try installing the German version of your build and reproduce there.

**Comment by CrazyWolf13** [comment] 2023-09-25 05:23
> I've identified and fixed the potential crash sites and released a new version. Please check if it still crashes. If not, I'll try installing the German version of your build and reproduce there.

It seems fixed!!

Wow thank you very much!
Very happy to finally be able to work with MS explorer again lol;)

**Closed** 2023-09-25 05:23 UTC

**Comment by Amrsatrio** [comment] 2023-09-25 05:26
Glad it helped. Anytime :)

**Comment by Amrsatrio** [comment] 2023-09-25 05:40
Also, please send me your `twinui.pcshell.dll` from system32 in here by changing its extension to `.pdf`. I need to analyze if my fallback method to get Win+X and Win10 Alt+Tab working, works with your build.

**Comment by CrazyWolf13** [comment] 2023-09-25 06:20
[twinui.pcshell.dll.pdf](https://github.com/valinet/ExplorerPatcher/files/12711708/twinui.pcshell.dll.pdf)
Here you go!

> Also, please send me your `twinui.pcshell.dll` from system32 in here by changing its extension to `.pdf`. I need to analyze if my fallback method to get Win+X and Win10 Alt+Tab working, works with your build.

**Comment by Amrsatrio** [comment] 2023-09-25 06:22
Weird, it's the same as the English (US) version yet it crashed on your installation. Anyways, the issue has been fixed, so no need to worry :)

**Comment by CrazyWolf13** [comment] 2023-09-25 06:28
> Weird, it's the same as the English (US) version yet it crashed on your installation. Anyways, the issue has been fixed, so no need to worry :)

Windows and weird isn't something new lmao :)
Huge thanks for fixing!
