### ISSUE TITLE
Explorer crashes on right click on Windows 11 22h2 build 22621.2506

### ISSUE THREAD

**Issue by rikka0w0** [valinet/ExplorerPatcher#2380] opened 2023-10-31 16:08 UTC
OS: Windows 11 22h2 build 22621.2506

When the Win11 tab UI is disabled, the Win11-style context menu no longer works, only the classic context menu option works.

It is on a fresh installation of Win11 and ExplorerPatcher.

**Comment by Amrsatrio** [comment] 2023-11-01 04:17
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218

**Closed by Amrsatrio** 2023-11-01 04:17 UTC
