### ISSUE TITLE
Task View gestures not working and no sound or brightness flyout effect

### ISSUE THREAD

**Issue by Zilla428** [valinet/ExplorerPatcher#1774] opened 2023-08-04 06:55 UTC
After the last update the gestures broke for task view and the sound and brightness flyout disappeared. This was present on the newest version on both a preview version of Windows 11 and my desktop running stock Windows 11.

**Comment by pyrates999** [comment] 2023-08-04 21:58
Please post windows version and build.
Please post explorer patcher version.

**Comment by FlameOfArda** [comment] 2023-08-05 01:30
Same here. I just downloaded the most recent windows update and the most recent EP

**Comment by Zilla428** [comment] 2023-08-05 02:02
Same version

**Comment by pyrates999** [comment] 2023-08-05 08:41
Please post windows build.

**Comment by FlameOfArda** [comment] 2023-08-05 11:33
Windows 11 22HR OS Build 22621.2070

**Comment by pyrates999** [comment] 2023-08-05 11:56
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by FlameOfArda** [comment] 2023-08-05 12:39
Thx fam

**Comment by PianoMastR64** [comment] 2023-08-07 15:39
> That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8
> 
> Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.

Thank you! This was the problem for me.

If anyone wants to know how to roll back the update after changing the setting: `Settings > Windows Update > Update History > Uninstall Updates (scroll way down)`. Then find the offending preview build update and click `Uninstall`. It should look something like `Update for Microsoft Windows (KB5028254)`. Compare that to the list of windows updates on the microsoft.com webpage linked above to see which `KB` code corresponds to the preview update

**Comment by pyrates999** [comment] 2023-08-12 10:23
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:40
Duplicate of #1687

**Closed by Poopooracoocoo** 2023-08-22 10:40 UTC
