### ISSUE TITLE
Start Menu fixed in Windows 11 mode -- v22621.3296.64.1

### ISSUE THREAD

**Issue by gaiking-uk** [valinet/ExplorerPatcher#3170] opened 2024-04-24 23:52 UTC
After upgrading to version 22621.3296.64.1 - The start menu is locked into Windows 11 mode (EP is set to show the Windows 10 start menu, however this option no longer seems to be working).

I tried following the steps below, but the start menu always shows in the Windows 11 style...
- Toggled the start menu to Windows 11
- Restarted explorer
- Set the start menu back to Windows 10
- Restarted explorer

```
EP version: 22621.3296.64.1
Windows version: 11 23H2 (Build 22631.3527)
```

**Comment by meuskas** [comment] 2024-04-25 01:51
im also having this issue, lets hope it gets fixed soon :P

**Comment by milesprower2293** [comment] 2024-04-25 02:16
> After upgrading to version 22621.3296.64.1 - The start menu is locked into Windows 11 mode (EP is set to show the Windows 10 start menu, however this option no longer seems to be working).
> 
> I tried following the steps below, but the start menu always shows in the Windows 11 style...
> 
>     * Toggled the start menu to Windows 11
> 
>     * Restarted explorer
> 
>     * Set the start menu back to Windows 10
> 
>     * Restarted explorer
> 
> 
> ```
> EP version: 22621.3296.64.1
> Windows version: 11 23H2 (Build 22631.3527)
> ```

Install the latest pre-release

**Comment by wozaibeijizhuxueya** [comment] 2024-04-25 02:26
+1，I also encountered this, and the latest version still has this problem

**Comment by Tom-McW** [comment] 2024-04-25 06:03
I also have encountered this  problem as of EP version: 22621.3296.64.1
Windows version: 11 23H2 (Build 22631.3527). 

I also did the above steps with no change.

**Comment by ScruffR** [comment] 2024-04-25 06:34
Unstalling KB5036980 "Cumulative Update Preview ..." brought the Win10 style Start Menu back.

While it was installed, trying to set Win10 style and restart Explorer resulted in a gray screen with with a spinner indicating that some registry settings are currently reset. Once the "normal" desktop shows the Win11 style Start Menu was back in place.

I despise being patronized by M$!
If they did a proper job themselves, people would not need tools like this here.

**Comment by pyrates999** [comment] 2024-04-25 12:31
Update to the latest pre-release.

**Comment by pyrates999** [comment] 2024-04-25 12:38
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3162

**Closed** 2024-04-25 12:39 UTC
