### ISSUE TITLE
When setting start menu position on screen to 'At Screen Edge', the taskbar overlaps the start menu (while hide taskbar is enabled).

### ISSUE THREAD

**Issue by Kelerexto** [valinet/ExplorerPatcher#2951] opened 2024-03-07 17:44 UTC
![image](https://github.com/valinet/ExplorerPatcher/assets/157363388/e127191b-9a8d-45a8-afe4-6bddb3791696)

When turning off hide taskbar it doesn't happen. Or either if i change the position from 'At Screen Edge' to 'Centre' then it doesn't happen: 

Postion: 'Centre'
![image](https://github.com/valinet/ExplorerPatcher/assets/157363388/11486870-5cd9-4322-8683-2d674be0cb48)

Hide taskbar disabled with position set to: 'At screen Edge'

![image](https://github.com/valinet/ExplorerPatcher/assets/157363388/05dbfc30-879c-49b9-bddb-ab2db2b0c0db)

I like keeping hide taskbar enabled.

**Comment by Amrsatrio** [comment] 2024-04-29 01:21
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2744

**Closed by Amrsatrio** 2024-04-29 01:21 UTC
