### ISSUE TITLE
windows 10 taskbar flips tablet mode and desktop mode

### ISSUE THREAD

**Issue by jw0785** [valinet/ExplorerPatcher#3545] opened 2024-08-07 13:44 UTC
because the first time when the keyboard is folded back, the taskbar gives no response, and when it's unfolded, the distance between app icons widens, as a result, from here on the tablet mode will have a desktop taskbar, and desktop mode will have a widened tablet taskbar.

I suggest either disabling tablet mode or having it respond to the change the first time.

**Comment by Amrsatrio** [comment] 2024-08-07 13:47
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2684

**Comment by Amrsatrio** [comment] 2024-08-07 13:48
Or you can use the [66.4 prerelease](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.4_3c50ea3) and use Windows 10 (ExplorerPatcher) taskbar. It will always use regular sizing for the buttons regardless if you have the keyboard is detached/folder or not.

Make sure to add the folders into Exclusions.

**Closed by Amrsatrio** 2024-08-07 13:47 UTC
