### ISSUE TITLE
ExplorerPatch restarts WIndows Explorer whenever a Windows folder is opened.

### ISSUE THREAD

**Issue by rustydanny** [valinet/ExplorerPatcher#2093] opened 2023-09-18 16:51 UTC
Open any Windows folder, and Windows Explorer restarts. After it restarts, you can normally open the folder you were trying to open before.

**Comment by pyrates999** [comment] 2023-09-19 11:29
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2051

Please close this one.

Possible fixes:

1. In ExplorerPatcher Properties, go to Advanced and tick **Do not change the taskbar context menu**
2. In ExplorerPatcher Properties, go to File Explorer and untick **Disable the windows 11 context menu**
3. In ExplorerPatcher Properties, go to Taskbar and set **Taskbar style** to **Windows 11**

**Comment by Poopooracoocoo** [comment] 2023-09-23 03:42
You shouldn't see this anymore with the new update. Leave a comment or open a new issue if you still do, but make sure to include your EP version and OS build.

**Closed by Poopooracoocoo** 2023-09-23 03:42 UTC
