### ISSUE TITLE
{Win} + {backtick} is not a valid key combination

### ISSUE THREAD

**Issue by plofhaan** [valinet/ExplorerPatcher#288] opened 2021-11-06 09:50 UTC
`Win` + **``` ` ```** is not a valid key combination on some keyboard layouts, such as AZERTY BE. (The **``` ` ```** symbol is not treated as a separate key with this specific keyboard layout.)

**Comment by valinet** [comment] 2021-11-06 18:26
#283 is basically the same issue.

Also, what key is on that layout instead of ~? And what would be a solution?

**Comment by plofhaan** [comment] 2021-11-06 20:13
´´´³´´´ (ASCII code: 252) instead of ´´´~´´´ and ´´´²´´´ (ASCII code: 253) instead of **´´´ ´ ´´´**
Maybe you could add an option to let the user choose up to a maximum of two different modifier keys and one typed character. So the user can type this character into an editable textbox that can accept only a single character and that maybe also causes the the ASCII number to automatically appear next to this textbox. Next, the user would still have to test the chosen key combination to make sure that it works, to avoid the potential risk of it generating some unexpected result/conflict with some other app.

**Comment by valinet** [comment] 2021-11-06 21:41
Yeah, idk… So now when you press Alt and that key it works? Like, the option is not specifically Alt+~, it’s Alt+“the key above the Tab key”. The reason is so that it is close to the Tab key. It does not have to be ~ specifically, it has to be the key above Tab.

**Comment by valinet** [comment] 2021-11-07 01:42
So yeah, closing this, as basically, I will fix this by registering the hot key "Alt+key above Tab", whatever that key is depending on the current keyboard layout. That's the intended behavior for that functionality. Thanks

**Closed by valinet** 2021-11-07 01:42 UTC
