### ISSUE TITLE
On screen volume & brightness displays not working

### ISSUE THREAD

**Issue by JonahWick** [valinet/ExplorerPatcher#1845] opened 2023-08-13 15:32 UTC
Recently the OSDs have stopped working. Uninstalling EP fixes the issue. This is a shame because EP does some things that are really useful (like allowing for a Desktop toolbar), but I really need the OSD functionality so I have to stop using EP until this bug gets fixed.

**Comment by Vipin2003** [comment] 2023-08-13 16:01
currently, EP is unstable with latest 22621.2134 build. If you want the OSD to work, switch to Win11 taskbar and enable "Do not change taskbar context menu" in Advanced option. And, pls don't spam for OSD and EP crash with latest build as DEV's already know this and they are working hard to resolve them. Till then, use Win11 Taskbar.

**Comment by JonahWick** [comment] 2023-08-13 17:30
Thanks for the info Vipin2003. That fix works to get the OSD back, but the Win11 taskbar won't allow me to add the Desktop toolbar. Hopefully that's another fix the DEVs are working on.

**Comment by khaivngo** [comment] 2023-08-17 19:19
I'm experiencing the same. Workaround suggested by @Vipin2003 is confirmed working, but not optimale since you have to use the Win11 Taskbar.

**Comment by pyrates999** [comment] 2023-08-18 11:21
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1692

Please close this one.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:26
Duplicate of #1692

**Closed by Poopooracoocoo** 2023-08-22 10:26 UTC
