### ISSUE TITLE
Update to the right clicking crash issue on Windows 22621.2134

### ISSUE THREAD

**Issue by Girofox** [valinet/ExplorerPatcher#1843] opened 2023-08-13 08:40 UTC
When I completely uninstall EP and delete the corresponding registry keys after reinstalling EP right clicking works. By default Windows 10 taskbar style is active too. When I then switch to Windows 11 taskbar style right clicking on taskbar causes explorer to crash, even when I then switch back to Windows 10 taskbar style. Maybe this helps fixing this bug.

**Comment by DirkBree** [comment] 2023-08-13 11:10
Nope, in other circumstances the explorer crashs again.

My solution atm is the StartAllBack trial, this tool works with all updates.

**Comment by Girofox** [comment] 2023-08-13 11:37
Does StartAllBack hook into explorer process or is it similar to ExplorerPatcher? What I like about EP is that it doesn't need to hook into dlls at all.

**Comment by Vipin2003** [comment] 2023-08-13 14:01
> Does StartAllBack hook into explorer process or is it similar to ExplorerPatcher? What I like about EP is that it doesn't need to hook into dlls at all.

Ya, it completely hook into explorer process to provide its best experience. But it won't let you to hook into Open/Save dialogs as EP provides.
But, it gets fixes immediately for any bug or crash in any build. (like Canary, Dev, etc)

**Comment by InfinityMyth** [comment] 2023-08-14 12:53
Hello,
The latest window update has killed ExplorerPatcher for me.  None of these comments seemed to fix it so I have had to just uninstall it.

To set the taskbar as 'never combine' and to get labels showing again I have used StartAllBack (https://www.startallback.com/) which has worked a treat.  There is a 100 day free trial and after that it's $4.99 but Windows should have rolled out the 'never combine' fix by then.

I'm also using Open Shell to fix the awful Windows 11 Start Menu.  https://github.com/Open-Shell/Open-Shell-Menu

Hope that helps someone out there.  I wish they'd stop trying to turn Windows into a bloody Mac.

**Comment by Girofox** [comment] 2023-08-14 13:33
Too bad Nilesoft Shell doesn't work for me reliable anymore, especially together with Explorer Patcher. Will try Open Shell soon.

**Comment by garyhuge05** [comment] 2023-08-14 14:19
well, ep completely crashed on my 22621.2134. unable to open start menu or explorer. i've uninstalled startallback or start11

**Comment by pyrates999** [comment] 2023-08-15 12:15
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

**Comment by Poopooracoocoo** [comment] 2023-08-22 11:43
Duplicate of #1826

**Closed by Poopooracoocoo** 2023-08-22 11:43 UTC
