### ISSUE TITLE
Inconsistent taskbar and tray menus appearance when "Skin taskbar and tray popup menus" is disabled

### ISSUE THREAD

**Issue by opzch** [valinet/ExplorerPatcher#2453] opened 2023-11-16 18:30 UTC
On Windows 10 22H2, taskbar and tray menu sometimes starts looking weird or becomes almost unreadable when "Skin taskbar and tray popup menus" is disabled and different color settings are used for Windows mode and App mode:
![image](https://github.com/valinet/ExplorerPatcher/assets/99139463/0065987a-4c61-4fbc-862a-6bd8857450a5)

![image](https://github.com/valinet/ExplorerPatcher/assets/99139463/93941094-e48d-4193-b398-06516004ac53)

I can't always reproduce this, but have observed this behavior several times on different devices.

**Comment by Amrsatrio** [comment] 2023-11-16 19:10
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2391

**Closed by Amrsatrio** 2023-11-16 19:10 UTC
