### ISSUE TITLE
Explorer crash on start button right click

### ISSUE THREAD

**Issue by Tom-McW** [valinet/ExplorerPatcher#2312] opened 2023-10-15 05:39 UTC
Explorer restarts when right clicking start button the first time, then works correctly the second time but still won't give me Admin privileges on powershell. 
Winver: 22H2 (OS Build 22621.2428
EP: 22621.2361.58.4
I have 2 machines exhibiting the same issue. Both machines have the same winver and EP are the same on both machines.

**Comment by pyrates999** [comment] 2023-10-15 08:56
Please include what settings you changed in explorer patcher properties application.

**Comment by Amrsatrio** [comment] 2023-10-15 14:11
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2156

**Closed** 2023-10-15 14:13 UTC
