### ISSUE TITLE
ExplorerPatcher crashes when I open a folder

### ISSUE THREAD

**Issue by igroglaz** [valinet/ExplorerPatcher#2041] opened 2023-09-11 11:57 UTC
funchook create 1
Running on Windows 11, OS Build 10.0.22621.2134.
Loaded symbols
Setup ntdll functions done
Setup user32 functions done
Patched taskbar transparency in newer OS builds
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup explorerframe functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Started "Open Start on current monitor" thread.
Open Start on monitor thread
EP Service Window thread
Initialized taskbar centering module.
[Positioning] Added settings for monitor 0000000000010001 : 0
Progman: 918120
Progman hook: 148767653
Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
0 0
[sws] Wallpaper RECT 0 0 1920 1080
[sws] Refreshing theme: 0
[sws] Refreshing theme: 0
[sws] Refreshing theme: 0
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
[Updates] Starting daemon.
10000 46000000
0 46000000
Error in sub_1800135EC on RoGetActivationFactory.

Previously (before past 2-3 updates of ExplorerPatcher) I didn't had such problem.

**Comment by pyrates999** [comment] 2023-09-11 21:14
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1942

Please close this

work around: In ExplorerPatcher Properties, Go to File Explorer > and set Management Interface to Windows 10 instead of Windows 11.

**Comment by Amrsatrio** [comment] 2023-09-25 13:50
Please download the newest version and see if this issue still persists. If it's gone, please close this issue.

**Closed** 2023-09-26 18:04 UTC
Labels: Crash
