### ISSUE TITLE
[24H2] Switching Window switcher style to SWS bricks window switching functionality until EP is completely uninstalled

### ISSUE THREAD

**Issue by PeterVLee** [valinet/ExplorerPatcher#4028] opened 2024-12-13 03:07 UTC
OS Name: Microsoft Windows 11 Pro
Version: 10.0.26100 Build 26100

As the title says, switching to Simple Window Switcher breaks window switching in 2 ways:

The following screenshots are done with the default Win11 switcher. I just added them for clarification

1. The window selected is the last available window, rather than the next one, as if `alt + shift + tab` was pressed, not `alt + tab`
![image](https://github.com/user-attachments/assets/df9217bb-d6b8-4251-b50c-7cfdfe9e5539)
* I'm pretty sure this is not due to sticky keys because everything else works as normal

2. When switching back from SWS to any other style, the UI pop-up does not show at all. Upon pressing alt-tab, the oldest opened window will immediately become active rather than let you choose between windows by holding the hotkey. In other words, it behaves as if you pressed `alt + shift + tab` and then let go.

I can only speak for myself, but I switch between two windows pretty often, and while the first issue doesn't seem so bad it kinda messed with my workflow pretty badly. I don't think I need to say why the second switcher issue is pretty horrible to deal with.

If it seems like this is unreproducible, it's because it takes a minute for the bug to kick in. Restarting file explorer seems to make it happen somewhat consistently, though I can't find anything that makes this happen 100% of the time.

As for the `until EP is completely uninstalled` part of the title, uninstalling normally via Properties window or Win11 settings seems to retain my settings. It's only until deleting the Roaming/ExplorerPatcher folder when the thing was completely uninstalled (which btw was a hurdle in and of itself because it kept getting locked by unrelated tasks).

**Comment by pyrates999** [comment] 2024-12-13 14:50
this mentions already that simple window switcher is broken: https://github.com/valinet/ExplorerPatcher/issues/3765

please add this to there.

**Comment by Amrsatrio** [comment] 2024-12-13 22:32
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3765

**Closed by Amrsatrio** 2024-12-13 22:32 UTC
