### ISSUE TITLE
Missing system tray icons and notifications on 24H2, Build 26090.112

### ISSUE THREAD

**Issue by MidnightInAurora** [valinet/ExplorerPatcher#3069] opened 2024-03-31 13:46 UTC
We're testing the DEV channel build of 24H2 26090.112 and noticed everything in the system tray is missing, both icons and notifications.

In EP Taskbar settings, _Customize notification area icons_ does nothing and _Customize system icons in the notification area_ does bring up the Turn system icons on of off control, but any changes made there do not persist.

For our use, everthing else from EP 22621.3296.2 seems perfect.

Thanks.

**Comment by pyrates999** [comment] 2024-03-31 14:57
After build 25921 in windows 11, they don't have the system tray

duplicate of: https://github.com/valinet/ExplorerPatcher/discussions/2363

please close this.

**Comment by MidnightInAurora** [comment] 2024-03-31 15:04
> After build 25921 in windows 11, they don't have the system tray
> 
> duplicate of: #2363
> 
> please close this.

Who is "they?"  EP or Microsoft?  System tray works as advertised in 23H2 and 24H2 without EP.

**Closed** 2024-03-31 15:08 UTC
