### ISSUE TITLE
Search box location when using left/vertical taskbar

### ISSUE THREAD

**Issue by daltroaugusto** [valinet/ExplorerPatcher#3530] opened 2024-08-03 01:49 UTC
Windows build: 26100.1150 (IoT Enterprise LTSC 24H2)
ExplorerPatch version: 22621.3880.66.4

Issue: when using left placement taskbar (new implementation) with "At screen edge" start menu placement, the menu box doesn't keep at the corner. Tested with both Windows 11 and Windows 10 start menu options.

![2024-08-02_22-43](https://github.com/user-attachments/assets/0c4540c4-ff1a-4463-95e0-f7260556f225)

![2024-08-02_22-44](https://github.com/user-attachments/assets/11786023-0fd5-46fa-bbd9-c77c1daec270)

**Comment by pyrates999** [comment] 2024-08-03 06:39
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

Please close this.

**Closed** 2024-08-03 09:00 UTC
Labels: wontfix
