### ISSUE TITLE
Broken context menu when right clicking on any App in Taskbar (KB5041587)

### ISSUE THREAD

**Issue by Yasukii** [valinet/ExplorerPatcher#3617] opened 2024-08-31 01:55 UTC
Hello,

After installing KB5041587 when I right click the taskbar icon for my file explorer the context menu broke.

![EoN6hUhnYX](https://github.com/user-attachments/assets/696ee21a-9bb9-4f2b-87ee-8064ca5ca5a5)

I am on the latest pre-release version 66.4.

I hope this somehow can be fixed or am I missing something.

Edit: Actually its not just file explorer all right click menus are kinda out of whack with the new update

**Comment by Amrsatrio** [comment] 2024-08-31 06:41
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3615

**Closed by Amrsatrio** 2024-08-31 06:41 UTC
