### ISSUE TITLE
Windows 11 24H2 ALT+Tab Windows NT Break

### ISSUE THREAD

**Issue by Machou** [valinet/ExplorerPatcher#3761] opened 2024-10-03 05:01 UTC
Hello

Since i have upgrade to Windows 24H2, alt+tab icons are no longer displayed and change window directly.

The only ones that work properly are “Windows 10” and “Windows 11” but that's the one I hate the most ^^ 
and I don't think I'm the only one.

Could you please correct this annoying little bug?

Sincerely

**Comment by pyrates999** [comment] 2024-10-03 12:09
did you uninstall EP before upgrading to windows 11 24h2?

**Comment by Machou** [comment] 2024-10-04 00:04
> did you uninstall EP before upgrading to windows 11 24h2?

No.

I have upgrade 23H2 to 24H2.

When i see ExplorerPatcher ALT+TAB is broken, i have uninstall, reboot and reinstall.

ALT+TAB Windows 10 et 11 work, but not NT

**Comment by milesprower2293** [comment] 2024-10-04 04:11
Microsoft removed the old WIndows NT alt tab switcher from 24H2 and it is not possible (at the moment) to bring it back on 24H2+ builds
Also duplicate of #3720

**Closed by milesprower2293** 2024-10-04 04:11 UTC
