### ISSUE TITLE
Sleep stops working in Windows 11

### ISSUE THREAD

**Issue by chara1ampos** [valinet/ExplorerPatcher#559] opened 2021-12-14 09:31 UTC
Sleep stops working in Windows 11 when the taskbar is set to Windows 10 style. If I click on the Sleep button it does not work. If I close the lid, the laptop does not sleep. If I select the default Windows 11 taskbar style, sleep works again. I can't use ExplorerPatcher because of this.

**Comment by valinet** [comment] 2021-12-14 13:42
I repeatedly said issues are for developers. Have you read #56?

Anyway, what kind of sleep? There are 2 types of “sleep”. Run “powercfg -a” and put the report here. The proper S3 sleep probably works just fine, S0ix has always been a shitty mess and it’s likely it has issues, I wouldn’t be surprised.

It’s not because of ExplorerPatcher, it’s because of Microsoft’s poor development. It’s not my fault they cannot code an OS they have total control of properly, and that stupid management decisions get in the way of every last ounce of common sense and logic.

**Comment by valinet** [comment] 2021-12-14 17:18
Well, also, I cannot really even look into this, let alone find out whether there's anything to fix. 

I have a single portable device, a Dell XPS 15 7590, and for the moment, the single device I have access to anyway. Dell was similarly forced to crap out this laptop and ship it with S0ix (low power network connected standby) instead of S3 in order to get the Microsoft Logo certification I think. Despite being of no use, besides saving 1 second on wake up (no apps seem to be able to send push notifications anyway), owners of this model have to endure the stupid S0ix sleep, which never seemed to work properly for me: the machine would wake on its own, the keyboard backlighting sometimes would not turn off etc. You can enable S3 on this model as well, but it is not fully implemented properly (Bluetooth goes missing after wake, the headphone jack does not detect plugged in headphones anymore). Not as Lenovo, which offer a choice for S3 in their ThinkPad BIOS along S0ix and still bother to implement that, but at least Dell allows disabling the BIOS advertising sleep support to the OS, so since I got this, I used that and have set the computer to use hibernate when closing the lid, when idling for longer times etc. That's anyway better than sleep as it consumes no power and with how fast the SSDs are these days, it is as fast as waking from traditional S3 sleep mostly anyways. So I never bothered with sleep for a long time.

I checked it now and a couple of days ago for some other raised issue, but I cannot seem to be able to reproduce anything meaningful at all. This computer just sucks when going to S0ix sleep, you never know if it did it or not, so what's to test? With both taskbars, it seemed to kind of work for me, in like, with both going to "sleep" made it turn off the screen but left the keyboard illuminated.

With traditional S3 sleep, it works fine in both modes, with the usual caveats that this model has, so again, can't properly test that since S3 sucks on this machine. But S3 is in general more reliable.

Also, I don't want to torture this laptop seemingly "testing" this. I don't even know whether anything's broken or how broken it is. I got used to it, it's yet another part of a computer that Microsoft now owns and they decided to ruin it. My advice would be:

* If you want a workaround for the age we live in, use hibernation instead of sleep.
* If you want something that might be reliable and is officially sanctioned, stick with how the OS is configured by Microsoft
* If you want something that works properly, probably best bet is to get a MacBook or some Linux laptop or a ThinkPad with a BIOS supporting S3, or try seeing if you can use that and whether it works at all; if using S3 already and it fails only with the Windows 10 taskbar, I doubt, it would be weird, but again, idk why that could be and how could I fix it, I don't touch anything power related in `explorer` from EP

My friend's laptop, a Lenovo Yoga Slim 7 with Ryzen 4500U has a similar problem, and I similarly resorted to having it set up to hibernate as well, since S3 was similarly half implemented, S0ix was awful and hibernate was just very reliable and wake times for that are insane as well, very very fast. For me, sleep on PCs is ruined thanks to Microsoft.

If someone else wants to work on this or finds a fix, if any or if actually a problem with EP, surely I can integrate that, but other than this, I am not up to tackling this in any other way. I will close this for now, as I won't work on it, but any subsequent info is welcome here, ofc.

**Closed by valinet** 2021-12-14 17:18 UTC
