### ISSUE TITLE
ExplorerPatcher causes certain system windows to downscale

### ISSUE THREAD

**Issue by UnassumingName** [valinet/ExplorerPatcher#1213] opened 2023-03-29 23:30 UTC
It mostly happens with Properties menus for me and the same ones that have the problem will always be shrunken, while the unaffected is always unaffected. Uninstalling the program does not fix it. Neither resetting the ExplorerPatcher settings.

Can in-place upgrade Windows to fix it, but the moment ExplorerPatcher is installed again, the issue reinstates.

Steps to reproduce:
1. Install ExplorerPatcher
2. Click Properties of something (In my case I used my local disk which is affected, and an external disk which isn't.)

![23-03-30_g7x6KDALHuuAdAdYL5Mcui](https://user-images.githubusercontent.com/61767621/228689697-4c8755db-74fb-4361-bbd1-e67422063b63.png)

I have a second device with ExplorerPatcher installed and it does not contain the same issue.

**Comment by Amrsatrio** [comment] 2023-10-26 03:14
I cannot reproduce this issue. On 20ish of physical PCs and VMs I've never had this issue.

But the only moment related to this was my desktop icons size growing after switching back and forth between my laptop display and my external display, so might be related to DPI scaling changes. Anyways, one can always select one of the default themes and restart the PC to fix.

Since there seem to be no more updates to this issue, I will be closing this.

**Closed by Amrsatrio** 2023-10-26 03:14 UTC
