### ISSUE TITLE
The taskbar stops working when right-clicking on it, using the Windows 11 style.

### ISSUE THREAD

**Issue by HelderRocket** [valinet/ExplorerPatcher#2019] opened 2023-09-07 13:11 UTC
Every time I right click on the taskbar, it stops working and restarts (once when I restarted the computer, the explorer would not start and I had to reinstall Windows). Restarting the computer, this time there were no problems with the explorer starting, but I had to use an application to replace the context menu so that it doesn't stop working.

**Comment by edludke** [comment] 2023-09-07 14:27
Seeing the same behavior. Am able to start explorer from TaskMgr (thus avoiding an entire reinstall) and then have to uninstall EP via Window's add/remove programs app. EP is now entirely broken. If I didn't know better (ha!) I'd swear M$ is purposefully trying to nerf EP. I'm on M$ Win 11 Enterprise Ver 10.0.22621 Build 22621. Don't them M$ win! Thanks for all of the time and effort spent on this great utility!

**Comment by Poopooracoocoo** [comment] 2023-09-07 16:10
Duplicate of #1805

**Closed by Poopooracoocoo** 2023-09-07 16:10 UTC
