### ISSUE TITLE
Virtual Desktop fail

### ISSUE THREAD

**Issue by AdasOsorus** [valinet/ExplorerPatcher#1868] opened 2023-08-18 12:27 UTC
Latest version fail to support Windows 11 Virtual Desktop when Explorer patcher in Windows-10 taskbar style.

Step to reproduce:

0- Ensure at most 2 virtual desktops are created:
___a- Press [WindowsKey] + [TAB] and create some

1- Activate Windows-10 style Taskbar
2- Restart File Explorer
3- Press [WindowsKey] + [TAB]
4- == nothing happen
or
3- Click on the TaskView icon (see below)
4- == nothing happen (button do not working)

Win11: 22H2 (22621.2134)
ExpPatcher: 22621.1992.56.1
-
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/ffc5bddd-4813-4356-8c3b-e8bc34765d0f)
-
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/e06bb691-8b85-4105-b6a6-a9f748a3e3f5)

**Comment by AdasOsorus** [comment] 2023-08-18 12:38
Additional note... may be related to 
https://github.com/valinet/ExplorerPatcher/issues/1687
but this issue is specific for Windows-10 taskbar style. The Windows-11 taskbar style work perfectly.

**Comment by pyrates999** [comment] 2023-08-19 09:26
If you set it to windows 11 taskbar style, and press alt+tab and then try windows+tab, does the windows+tab still work?

**Comment by martwenty** [comment] 2023-08-19 11:26
Some issue here. I am quite sure about the cause. I installed yesterday night two last updates KB5029263, KB502894 and then after the restart the problem came out. 
@pyrates999 coming back to W11 taskbar style alt+tab and MS+tab started to work again. 

But after opening EP few times from the right click + properties on the taskbar, now EP is crashing after every right click on the taskbar. I've just remove and install again EP but it presents same crash issue. win and desktop switching are working.

**Comment by pyrates999** [comment] 2023-08-19 11:56
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

Please comment there.

**Comment by Poopooracoocoo** [comment] 2023-08-22 09:46
Closing as duplicate of #1687 and #1802

**Closed by Poopooracoocoo** 2023-08-22 09:46 UTC
