### ISSUE TITLE
Taskbar transparent

### ISSUE THREAD

**Issue by dodemodexter** [valinet/ExplorerPatcher#2983] opened 2024-03-13 07:09 UTC
Hello.

Since this morning (I don't know whether it's a PC update or ExplorerPatcher), the taskbar is transparent, and when the machine starts up, it remains frozen for a while on a black screen before my desktop appears (and even then, I think I'm forcing it by pressing the WIN key).

Win11 23H2 22631.3296
Latest version of explorerPatcher Version 22621.2861.62.2

<img width="1912" alt="Capture d'écran 2024-03-13 080619" src="https://github.com/valinet/ExplorerPatcher/assets/13978651/aea182a6-5659-40c4-b54a-194c4c31f069">

**Comment by miraged** [comment] 2024-03-13 07:18
me too, uninstaled it and everything seems ok now. but yes this night windows update was installed automatically - Win11 23H2 22631.3296

**Comment by dodemodexter** [comment] 2024-03-13 07:21
Thanks, @miraged. I uninstalled, of course, and everything reverted to the default Windows 11 menu (which I don't like). But when I reinstall explorepatcher, the taskbar becomes transparent again... :-(

**Comment by gboor** [comment] 2024-03-13 07:21
Same here, came to github looking for exactly this. Exact same update.

**Comment by Soulreaver1977** [comment] 2024-03-13 07:24
Same here, on 3 machines after installing Cumulative Update KB5035853

**Comment by dodemodexter** [comment] 2024-03-13 07:24
Then... I think we have to wait for an update... :-)

**Comment by miguelreb** [comment] 2024-03-13 07:28
Me too... i wait a update :)

**Comment by mjtDeCompile** [comment] 2024-03-13 07:30
this has been fixed in a pre-lease version of EP
original thread: https://github.com/valinet/ExplorerPatcher/issues/2975

**Comment by dodemodexter** [comment] 2024-03-13 07:45
Thanks @mjtDeCompile !
Works fine with [Latest Pre-lease](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.1_9e9c016)

**Comment by RRTW** [comment] 2024-03-13 08:52
Same issue here,
WIn11 22631.3296
Explorer Patcher 22621.3007.63.3

**Comment by tomeija** [comment] 2024-03-13 09:19
Same issue since Win-Update this morning
Win 11 Pro 22631.3296
Explorer Patcher 22621.2861.62.2

**Comment by Amrsatrio** [comment] 2024-03-13 10:16
Affected users may install the latest pre-release build to have acrylic back.

By the way, duplicate of https://github.com/valinet/ExplorerPatcher/issues/2975.

**Closed by Amrsatrio** 2024-03-13 10:16 UTC
