### ISSUE TITLE
Power mode (click on battery button) doesn't work until explorer restart

### ISSUE THREAD

**Issue by oldrichsmejkal** [valinet/ExplorerPatcher#1934] opened 2023-08-25 07:14 UTC
When I click battery icon in a tray after computer boot (or exploere.exe restart), power mode widget (e.g. changing between balanced, high performance, power save modes) will show.
When I do it repeatedly (sometimes for second, time, sometimes after few more tries) - nothing will show.
This doesn't change until explorer.exe process restart.

Info:
Windows 11 22H2 (OS Build 22.621.2134)
ExplorerPatcher 22621.1992.56.1
(similar behaviour on another pc, with bit different versions)

**Comment by pyrates999** [comment] 2023-08-25 14:34
There's an update available for EP.  Please update it.

**Comment by oldrichsmejkal** [comment] 2023-08-25 22:31
I updated to 22621.1992.56.3
Behaviour is same.

**Comment by pyrates999** [comment] 2023-08-26 11:28
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1692

Please close this one.

Work around until this gets fixed: install an application from the microsoft store called "modernflyouts".

**Comment by coldimmune** [comment] 2023-11-01 20:35
Also affected (for a few months), latest version. Doesn't show in the system tray regardless of settings, just in the expanded view

As an aside, EP has been working great for several months since the last time MS upended everything, thanks for all your work on this program!

**Comment by EugenNY** [comment] 2023-12-16 00:32
I'm having the same problem with latest EP and Windows 11 Pro (23H2, 22631.2861)

**Comment by Amrsatrio** [comment] 2024-02-15 03:39
Fixed in the latest prerelease.

**Closed by Amrsatrio** 2024-02-15 03:39 UTC
Labels: Taskbar10

**Comment by EugenNY** [comment] 2024-04-05 18:41
thanks so much, it works so far!
