### ISSUE TITLE
Win 11 update  - Defender flags Explorer patcher as Malicious 

### ISSUE THREAD

**Issue by wildbl67** [valinet/ExplorerPatcher#3165] opened 2024-04-24 14:12 UTC
After updating to Version 22631.3527,  windows defender now flags Explorer  pre release as malicious.   I installed the pre - release attempting to fix explorer after the update.    Explorer failed after the update.    Looks like Microsoft doesn't like the patcher.

**Comment by wildbl67** [comment] 2024-04-24 16:33
UPDATE:  After adding the exception it appears to be back to normal.  What concerns me is  Microsoft flagging this as malicious because the pre release doesn't have the proper certificate to be allowed by Micro hell?     Or,  is this Malicious?   Or, is Micro Hell not liking the patch because they think we should all love the dumb new start menu?

**Comment by pyrates999** [comment] 2024-04-25 12:22
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3125

Please close this.

They've identified the issue and are seeing about removing that code that is causing it.

**Comment by Amrsatrio** [comment] 2024-04-25 12:39
duplicate of: #3125

**Closed by Amrsatrio** 2024-04-25 12:39 UTC
