### ISSUE TITLE
Preferences Windows will not pop up

### ISSUE THREAD

**Issue by ruebennase56** [valinet/ExplorerPatcher#3461] opened 2024-07-10 06:02 UTC
Hi to everyone,

With the latest version (22621.3810.66.1) the preferences window won't show, just a white box will pop up for a second.

![ep 22621 3810 66 1](https://github.com/valinet/ExplorerPatcher/assets/88430929/4bbd3c53-4f78-4e0e-8b70-27677ccdd4d1)

My system:
Win11 (22631.3880)
AMD Ryzen 7 3700x

**Comment by Uwe-MrT** [comment] 2024-07-10 10:59
Here the Same
Win 11 Prof - 23H2
core i5
latest EP

**Comment by Uwe-MrT** [comment] 2024-07-10 11:04
> Hi to everyone,
> 
> With the latest version (22621.3810.66.1) the preferences window won't show, just a white box will pop up for a second.
> 
> ![ep 22621 3810 66 1](https://private-user-images.githubusercontent.com/88430929/347274915-4bbd3c53-4f78-4e0e-8b70-27677ccdd4d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDk3MTMsIm5iZiI6MTcyMDYwOTQxMywicGF0aCI6Ii84ODQzMDkyOS8zNDcyNzQ5MTUtNGJiZDNjNTMtNGY3OC00ZTBlLThiNzAtMjc2NzdjY2RkNGQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDExMDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NzdkNmVkZTdjNmQ1NjhiNjM1NWVkMjE5MDAyMDRkMDc4MjFjYmIyMzc1YTFhMjFlZWE1MGI5MDFiZTZmMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.40Xgr0glgqiOoxPGGR0xDBVhIMyvUt_dGhzcCLZJLSo)
> 
> My system: Win11 (22631.3880) AMD Ryzen 7 3700x

Go back to 22621.3527.65.5
This workd for me.

**Comment by pyrates999** [comment] 2024-07-12 12:47
You have your EP set to update to pre-releases.  Set it back to only update to releases in the EP properties application in Updates.

**Comment by Amrsatrio** [comment] 2024-07-12 20:34
@1kartafal4 Don't know but what happens if you rename ep_taskbar.2.dll in C:\Program Files\ExplorerPatcher into another name?

**Comment by Amrsatrio** [comment] 2024-07-12 20:36
@Uwe-MrT @pyrates999 Doesn't help in assisting me to fix this issue. From 66.1 onwards EP's taskbar will be included, which is may be the cause of this bug in the settings GUI.

**Comment by pyrates999** [comment] 2024-07-13 09:03
Just mentioned that in case they had set EP to update to the latest pre-release, and they didn't intend to do that.

**Comment by CloudeLecaw** [comment] 2024-07-14 06:38
may bad i openend a new post because i  didnt saw this one before

https://github.com/valinet/ExplorerPatcher/issues/3477

**Comment by CloudeLecaw** [comment] 2024-07-14 06:44
> @1kartafal4 Don't know but what happens if you rename ep_taskbar.2.dll in C:\Program Files\ExplorerPatcher into another name?

This file does not exist
![14-07-2024_08-43-41](https://github.com/user-attachments/assets/c6d2fc9f-b556-44e5-a67d-7720d9e548f4)

**Comment by milesprower2293** [comment] 2024-07-14 17:56
> > @1kartafal4 Don't know but what happens if you rename ep_taskbar.2.dll in C:\Program Files\ExplorerPatcher into another name?
> 
> i tried this with 22621.3810.66.1 - but ... This file does not exist (see screenshot) ![14-07-2024_08-43-41](https://private-user-images.githubusercontent.com/12080017/348519971-c6d2fc9f-b556-44e5-a67d-7720d9e548f4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Nzk5NDcsIm5iZiI6MTcyMDk3OTY0NywicGF0aCI6Ii8xMjA4MDAxNy8zNDg1MTk5NzEtYzZkMmZjOWYtYjU1Ni00NGU1LWE2N2QtNzcyMGQ5ZTU0OGY0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE3NTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MDBkNWQxZDA3ODY5ODAzN2FmN2JlOGMxMmI5ZDBkODExNjU1NDMwYzQzYmQ2YTczN2FhNmEzYTczYmE3NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MCqocPtaG2MzueVh3LCdTjrM2QMg_8xYtVSR0hv0fhk)
> 
> Well checking back on 22621.3527.65.5 this file also does not exist in C:\Program Files\ExplorerPatcher
> 
> ![14-07-2024_09-18-19](https://private-user-images.githubusercontent.com/12080017/348521404-001cafb4-9787-406f-a5e7-1c37a4b34568.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Nzk5NDcsIm5iZiI6MTcyMDk3OTY0NywicGF0aCI6Ii8xMjA4MDAxNy8zNDg1MjE0MDQtMDAxY2FmYjQtOTc4Ny00MDZmLWE1ZTctMWMzN2E0YjM0NTY4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE3NTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNzBlNTk3YmNlYTZhNDQ4ZGFiNDc1MzdlZWU2Y2ExYmM0NDNhNzJmMDVmMjI1ZjdiNzU2NTczNWNmNjVlZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6123xpmz4picqIYJN1ragMhvu7J4KRbtsOkoceOGzo) might its located in an other folder?

ep_taskbar is not available on 24H2 builds at the moment

**Comment by CloudeLecaw** [comment] 2024-07-14 19:49
Well but it works without any seeable issue with  22621.3527.65.5 on 24H2

**Comment by PC-Shark966** [comment] 2024-07-15 13:08
> Hallo an alle,
> 
> Mit der neuesten Version (22621.3810.66.1) wird das Einstellungsfenster nicht angezeigt, nur ein weißes Kästchen wird für eine Sekunde angezeigt.
> 
> ![ep 22621 3810 66 1](https://private-user-images.githubusercontent.com/88430929/347274915-4bbd3c53-4f78-4e0e-8b70-27677ccdd4d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDg4NjAsIm5iZiI6MTcyMTA0ODU2MCwicGF0aCI6Ii84ODQzMDkyOS8zNDcyNzQ5MTUtNGJiZDNjNTMtNGY3OC00ZTBlLThiNzAtMjc2NzdjY2RkNGQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEzMDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NTI3YzI3OWQ4ODgwNDM1YzAyYzM3YTE4M2RkYmY3ODBjZmFiM2EwZTUxY2RmODE0NTEzZjU4OWY2ZjhhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9w6MKPWvw_rLealpAsiPgZfBJDVZl3k7NOtrCzKWhIc)
> 
> Mein System: Win11 (22631.3880) AMD Ryzen 7 3700x

Das selbe habe ich auch. Nur Weißes kleines Fenster.
Nach dem umbenennen der ep_taskbar.2.dll, welche bei mir Existiert, bleibt das Weiße Fenster etwas länger auf dem Bildschirm
sonst tut sich nichts.
Da aber alles was ich Eingestellt habe noch genauso Funktioniert stört es mich nicht weiter.
Gruß
Frank

**Comment by Amrsatrio** [comment] 2024-07-15 13:11
Thank you for hinting me that this issue happens when German is set as the EP language. Reproduced the issue. Will fix in the next prerelease which will add support for Arm64.

**Comment by ruebennase56** [comment] 2024-07-15 15:38
> Thank you for hinting me that this issue happens when German is set as the EP language. Reproduced the issue. Will fix in the next prerelease which will add support for Arm64.

Many thanks, changing the language to english solves the problem.

**Comment by Amrsatrio** [comment] 2024-07-15 15:44
Nevermind about the Arm64 support, it is not ready yet, currently still deciding how the new ep_setup.exe should be structured.

A new prerelease with the same version number is being built now, make sure to download it if the issue affects you. Don't forget to turn off realtime protection and add ExplorerPatcher folders as well since Defender is more likely to falsely flag this as a virus nowadays.

**Closed by Amrsatrio** 2024-07-15 15:44 UTC
