### ISSUE TITLE
right clicking causes file explorer to crash

### ISSUE THREAD

**Issue by Jadenheart101** [valinet/ExplorerPatcher#2522] opened 2023-11-29 21:41 UTC
happens on both the desktop and file explorer

**Comment by lenoobideal** [comment] 2023-11-30 08:26
Same here

**Comment by BookOfSpring** [comment] 2023-11-30 09:35
same here too, i thought groupy 1 and 2 cause crash on multiple selected files

**Comment by pyrates999** [comment] 2023-11-30 12:58
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

Please close this.

**Comment by Amrsatrio** [comment] 2023-12-02 18:15
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218

**Closed by Amrsatrio** 2023-12-02 18:15 UTC
