### ISSUE TITLE
Latest Update Tries To Download Wrong Version Automatically

### ISSUE THREAD

**Issue by Majoraslayer** [valinet/ExplorerPatcher#3505] opened 2024-07-24 16:58 UTC
I'm running version 22621.3880.66.2 on x86_64 currently.  When using the built-in update feature, I'm showing an available update, but when it downloads, it seems to be grabbing the arm64 version of the installer instead of the x86_64 version.

EDIT: I've attached a screenshot of what it's downloading instead.

![image](https://github.com/user-attachments/assets/ebcce535-1a6e-455b-a602-78c214197e65)

**Comment by Amrsatrio** [comment] 2024-07-24 18:09
This is due to a limitation in the old updater code which doesn't parse the JSON of the releases API response, but instead finds for the first occurrence. The updated code in 66.3 no longer has this issue.

I also don't want to rename ep_setup.exe in the releases section to keep normal non-prerelease updates working. Valinet also suggested me to pack the arm64 setup file in the x64 setup file, but figured that something can get wrong rather easily if I'm going that route. So yeah sorry that I decided to leave it like this......

**Comment by J1GGY37** [comment] 2024-07-25 12:24
How is the one below a duplicate of this one? ... it's 2 completely different errors?

https://github.com/valinet/ExplorerPatcher/issues/3506#event-13644735500

**Comment by pyrates999** [comment] 2024-07-25 12:37
Both download the wrong exe file.  So you gotta manually download the correct one.

**Comment by J1GGY37** [comment] 2024-07-25 12:46
> Both download the wrong exe file. So you gotta manually download the correct one.

3505 is about windows not allowing the install ? ... Something about "you don't have permission to run this program on this PC"

**Comment by pyrates999** [comment] 2024-07-25 12:57
If you look at the popup that EP is showing, it is downloading the arm version of EP instead of the x86-64 version of EP.

**Comment by phoenX80** [comment] 2024-07-25 17:22
I didnt see that you are correct. I wasnt convinced since Windows also then intercepted the new download but I managed to keep defenders fingers off it and it finally installed after manually downloading. is the new version also with this bug?

**Comment by pyrates999** [comment] 2024-07-26 13:44
66.3 I think has fixed the update feature as previous versions only expected one exe to be on github instead of 2.

**Comment by Amrsatrio** [comment] 2024-07-27 07:58
Made a new commit which renames ep_setup.arm64.exe to ep_setup_arm64.exe. This makes the arm64 setup appear after the amd64 setup so that older versions would update properly when prerelease is checked.

Shower thoughts are really that powerful sometimes....

**Closed by Amrsatrio** 2024-07-27 07:58 UTC

**Comment by Majoraslayer** [comment] 2024-07-27 08:48
> Made a new commit which renames ep_setup.arm64.exe to ep_setup_arm64.exe. This makes the arm64 setup appear after the amd64 setup so that older versions would update properly when prerelease is checked.
> 
> Shower thoughts are really that powerful sometimes....

Simple solutions are always my absolute favorite 😂

Thanks for chasing this down and coming up with a fix!
