### ISSUE TITLE
Check for updates link doesn't work

### ISSUE THREAD

**Issue by robtgmann** [valinet/ExplorerPatcher#3117] opened 2024-04-09 20:38 UTC
Me, windows 11 user.  Clicking on the link, "Check for updates" doesn't work in version 64.1.  It's the latest version so doesn't matter.  "update program and restart File Explorer on same page does work.

Super program.  Can't imagine life without it!

**Comment by pyrates999** [comment] 2024-04-09 23:58
Check if you have notifications off.  The update check and other features is all done through notifications.

**Comment by robtgmann** [comment] 2024-04-10 00:37
I don’t know there the switch might be.   The only place I find to look is on the Taskbar page, Customize notification area icons. There are no options there for Explorer patcher.  

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
----------------------------------------------------------------------------------------
Robert Goldmann
Clarity & Performance Coaching
Executives, Professionals, Business owners
 <http://www.clarityandperformance.com/> www.ClarityAndPerformance.com
 <http://www.actfromchoice.com/> www.ActFromChoice.com
510.495.4444
--------------------------------------------------------------------------------------

**Comment by pyrates999** [comment] 2024-04-10 11:24
This is a windows setting you need to change: https://support.microsoft.com/en-us/windows/get-notifications-you-want-feeca47f-0baf-5680-16f0-8801db1a8466

**Comment by robtgmann** [comment] 2024-04-10 20:37
Hi 
 
I followed your direction (many thanks!) as best I could.  Explorer Patcher is not shown in the apps list, but there are two showings  of Explorer.  A checked both.
 
1.	In working on that suggestion I discovered that the Control Panel listing of programs, shows the version number for Explorer Patcher as 22621.3007.63.2.
The Explorer patcher about page in Explorer Patcher shows it is 22621.3296.64.1
I notice that the page at https://github.com/valinet/ExplorerPatcher shows a version 22621.3296.64.3
 
2.	Clicking on Check for updates brings up the following popup in the system tray area
Unable to check for updates
Make sure that you are connected to the internet
and the remote server is online
Explorer Patcher
 
A truncated copy of the popup appears in notification area
 
I am on line. clicking on the following links also on the Update page, take me to the promised page
Read about changes in the latest releases
Learn more
 
Licking on these produce a unexpected result
Releases: github.com/valinet/explorerPatcher/releases/latest … produces a popup but clicking on it doesn’t open a browser page.  Entering the URL in a browser takes me to  a page with 2261.3296.64.1 at the top of the page.
Pre-releases:  api.githum.com/repos ….. Opens a dialog asking for a URL, but no URL is presented
Update program and restart File Explorer…. Opens a dialog box asking for a URL, but not URL is presented
 
3.	Miscellaneous other observations 
 
I happened onto your wiki/Configure update-updates and did check that the toast notifications are already what you recommended – not configured
 
 
 
I’m wondering whether the simplest thing might be to uninstall and reinstall EP.  I’ll only do that if you recommend it (because it is working so well!).  
BUT if you recommend reinstalling, this question --- would the install remember my configuration?  If not, I’m prepared to copy down my configuration….no problem…. Just need to hear from you if that’s required.
 
And do you subset using the uninstall link in the program?
 
Many thanks for your help, I’m grateful, and looking forward to your response! 
 

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
----------------------------------------------------------------------------------------
Robert Goldmann
Clarity & Performance Coaching
Executives, Professionals, Business owners
www.ClarityAndPerformance.com <http://www.clarityandperformance.com/> 
www.ActFromChoice.com <http://www.actfromchoice.com/> 
510.495.4444
------------------------------------------------------------------------------------------
 
 
 

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
----------------------------------------------------------------------------------------
Robert Goldmann
Clarity & Performance Coaching
Executives, Professionals, Business owners
 <http://www.clarityandperformance.com/> www.ClarityAndPerformance.com
 <http://www.actfromchoice.com/> www.ActFromChoice.com
510.495.4444
--------------------------------------------------------------------------------------

**Comment by pyrates999** [comment] 2024-04-11 13:33
Don't reply via email.  Your comment has your phone number in it right now.  Please edit your comment.

**Comment by pyrates999** [comment] 2024-04-11 13:34
If you're on your work computer, they may be blocking access to the internet to places like github.

**Comment by gondwanasoft** [comment] 2024-04-12 06:41
I've got the same issue. Explorer Patcher isn't listed in the Settings/Notifications list. I get notifications from other apps. Explorer Patcher used to notify on update checks, but hasn't for a while.

**Comment by pyrates999** [comment] 2024-04-12 12:33
Check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

Then copy and paste the results to here.

**Comment by robtgmann** [comment] 2024-04-12 19:06
CONSOLE DUMP IN A DIFFERENT EMAIL.
 
I’m on my own computer have no difficulty accessing any thing, including GitHub..

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
----------------------------------------------------------------------------------------
Robert Goldmann
Clarity & Performance Coaching
Executives, Professionals, Business owners
www.ClarityAndPerformance.com <http://www.clarityandperformance.com/> 
www.ActFromChoice.com <http://www.actfromchoice.com/> 
------------------------------------------------------------------------------------

**Comment by robtgmann** [comment] 2024-04-12 19:08
Console dump is below.
 

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
----------------------------------------------------------------------------------------

**Comment by gondwanasoft** [comment] 2024-04-13 02:04
I hope this is what you wanted. Mu current installation is up-to-date, but I still expected a notification (or some sort of feedback) in response to 'Check for updates'.

```Running on Windows 11, OS Build 10.0.22000.2538.
Loaded symbols
Setup user32 functions done
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 4F374
ITrayUIHost = 373A68
explorer.exe!TrayUI_CreateInstance() = 15AB78
Setup explorer functions done
Setup uxtheme functions done
[SMA] match1 = 10037C
[SMA] match2 = 1003BB
[SMA] match3 = 255CC
[SMA] CStartExperienceManager::GetMonitorInformation() = 7398C
[SMA] CExperienceManagerAnimationHelper::Begin() = 5F3274
[SMA] CExperienceManagerAnimationHelper::End() = 5F33F0
[SMA] match7a in CStartExperienceManager::Hide() = C9B5
[SMA] match7b in CStartExperienceManager::Hide() = CA07
[SMA] CStartExperienceManager::OnViewCloaking() = 38620
[SMA] match9 in CStartExperienceManager::OnViewHidden() = 255CC
[SMA] CStartExperienceManager::OnViewUncloaked() = 399B0
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup sndvolsso functions done
Setup shell32 functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
Progman: 393702
Progman hook: 1967857099
[Positioning] Added settings for monitor 0000000000010001 : 0
[Positioning] Added settings for monitor 0000000000010003 : 0
[Positioning] Added settings for monitor 0000000000010005 : 0
0 0
>>> Signal shell ready.
Ended "Signal shell ready" thread.
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Checking against hash "22622.3296.64.1.15361a1b13c6f570"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.3296.64.1.15361a1b13c6f570" (valid).
[Updates] Local version obtained from hash is 22622.3296.64.1.
[Updates] No updates are available.
```

**Comment by pyrates999** [comment] 2024-04-13 05:37
**I'll repeat again, you need to edit your previous comment because when you replied via email, you included your contact info that has your phone number.**

That message would seem to indicate something is blocking EP's connection to the internet when it is trying to check for updates.

But EP console indicates there are no updates available.

And 64.3 is a pre-release version, that is why EP shows there are no updates available.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by robtgmann** [comment] 2024-04-14 00:11
My answers follow the order of your statements below.
 
I didn’t realize you wanted me to edit past emails.  I’ve now done so. 
 
I’ll paste screen shots after I’ve done the textual responses.
 
I haven’t knowingly installed any software that modifies the UI of windows.  My computer is an LG laptop, and it has what it has.  EP worked well for a long time, and I am not aware of anything they’ve done that would change Explorer.  That doesn’t mean they haven’t, only that I haven’t been involved and don’t know of such.
 
I did very recently turn on bitdefenders full-time VPN.  It was causing problems – blocking my access to the internet, slowing access to websites when it was not blocking me, so I uninstalled it.  I believe my EP console dump was done before I did the console thing.  If you want me to repeat it, please let me know.  (I could also do a more thorough uninstall of the VPN using Revo, rather than bitdefenders uninstall package
 
The screen shots
 
 

	
		


	
		


	
		


	
		

 

	
		

 
 

	
		


	
		


	
		


	
		

 

	
		

Sorry I wasn’t more consistent with the screen shots. I hope you can see what you wanted to see.
 
And thanks for hanging in there with me.
 

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
 
----------------------------------------------------------------------------------------

**Comment by gondwanasoft** [comment] 2024-04-14 01:45
Maybe a firewall rule is blocking the outbound connection. Even so, I think you should still receive a notification.

**Comment by pyrates999** [comment] 2024-04-14 02:42
You can't reply via email when you want to attach screen shots or upload other files.  Please log into github.com directly and then you can post your screen shots here.

Ok, I tried disabling my internet connection and when I checked for updates, I got a notification it was unable to check and to check my internet connection:

![image](https://github.com/valinet/ExplorerPatcher/assets/106135298/404b0c71-652f-4451-ad7e-4f09c73a8bfa)

**Comment by robtgmann** [comment] 2024-04-14 18:17
![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/fafcc2a7-dc13-4fdd-a15d-073b6a1e2a0d)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/d2158cdd-0541-4a52-a10c-1dd0c18ec1c8)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/938dfbc9-7ae3-4c4c-a2be-d95ff6f6f2e0)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/33b4c480-58fc-4452-ae55-59981e0816f3)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/52b896e5-be60-4e5f-9ab1-be5901bd2b41)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/95aabf7e-a122-4d1d-bd88-e37909755089)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/52378caf-63fc-4bf3-b683-9163b9d88f70)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/9afa45c2-bfb6-47fb-a49f-c377e918488e)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/93f962a5-d991-4e1f-9d1d-d2f25b2e40b7)

**Comment by robtgmann** [comment] 2024-04-14 18:30
Yes. That’s the popup I get, but I have access to the internet, all my browsers are working, still I get that response.
 
I’ve pasted the screen shots at GitHub, and they seem to be displaying 
 
Sorry. I screwed up – thinking close referred to closing my comment.  But have reopened it the issue and checked, and my screen shots are displaying.  
 
Your post about Bitdefender never was received here.  I happened to see it on GitHub.  I’ve uninstalled Bitdefender using their online uninstaller you gave me a link to.  There’s no change in the problem.  Clicking on check for updates produces the popup you got when disconnecting the internet.  My internet is connected, alive and prospering.
 
 
 

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
----------------------------------------------------------------------------------------
Robert Goldmann
Clarity & Performance Coaching
Executives, Professionals, Business owners
 <http://www.clarityandperformance.com/> www.ClarityAndPerformance.com
 <http://www.actfromchoice.com/> www.ActFromChoice.com
510.495.4444
--------------------------------------------------------------------------------------

**Comment by pyrates999** [comment] 2024-04-15 10:48
Every time you respond via email, your phone number gets posted.  Please edit your existing comments to remove that.

Your screen shots have the sides of them cut off, and others are resized weirdly.  Please use snipping tool to take captures of each area of the settings for EP properties application.

Now since you say you have fully uninstalled bitdefender using their uninstall tool.  Try disabling the windows firewall on your network connection and checking if you can check for updates now in the EP properties application.  Make sure you are behind a nat router when doing this.

Here's how to disable windows firewall temporarily: https://support.microsoft.com/en-us/windows/turn-microsoft-defender-firewall-on-or-off-ec0844f7-aebd-0583-67fe-601ecf5d774f

If the windows firewall was already disabled and windows shows a third party firewall is there.  That may be blocking the update attempt silently.

When done, re-enable windows firewall.

**Comment by robtgmann** [comment] 2024-04-15 22:18
![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/57cc39d0-cdf6-46fd-a911-d3caeaa5cc01)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/6fb0a969-ca3f-4f28-a609-f47f149e344f)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/da1edfa3-fe23-4976-a6c6-f51190ca42ef)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/52ab5c97-f1c5-489e-b898-1cac2aecf36c)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/aa2672e4-526f-4217-b8dc-bbcf117401b8)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/1e4f417d-4531-4d01-a38c-9a3f53fb6e65)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/90c50ecc-aab9-4747-8593-037d7ccaefe6)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/1489d648-fd7e-4a14-953b-1c144297987f)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/501dd58d-e251-4a4e-bd09-80f20d289fe0)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/5d1dfbd3-7caf-4fc1-aef9-1e37cd5c0ee4)

![image](https://github.com/valinet/ExplorerPatcher/assets/88255837/5f32e4a8-c47e-4a2c-97fa-08d2f8236e4e)

I hope you now have a satsifactory set of screen shots.

**Comment by robtgmann** [comment] 2024-04-15 23:02
I’ve sent you new screen shots.
 
As lo the firewall changes you wanted.  I had already reinstalled Bitdefender, and wasn’t feeling up to taking it out again.  I did try some other things.  Bitdefender is the active firewall. Windows firewall is inactive.   I added a rule allowing Explorer.exe through the Bitdefender firewall, and, even though Windows firewall is inactive, added a rule for Explorer.exe there too.  There was no change
 
I spent some time looking for what might be the appropriate app to explicitly allow explorerpatcher through but couldn’t find an  EP exe to reference.  Give me one or more app names and locations and I’ll give that a try, if you’d like.
 
As to the weirdly shaped screen shots, I was under the impression that all customizations were indicated by what was in the left column, I was under the impression that I could paste screen shots in the uploaded email, and wanted them to take up as little space as possible.  Chalk that up to ignorance borne of inexperience. 
 
That final remark introduces this personal comment.  I’ll erase this part of the email after you respond to the preceding part of this email.  There’s no need for you to respond to what comes.
 
I am actually smart.  Have a degree from one of the top US engineering schools and from another top post graduate (non-technical) institution.  I first programmed a computer a little over 60 years ago.  Nothing special:  Fortran (before it was Fortran 4) on an IBM 7090 with a 1401 front end.  It was a production program which ran for another 6 years without problems.  I used Dell computers for 20 years.  Finally gave up because their service people were only able to solve only one problem of the 20 or more I had on their computers in those years.  The numerous times they failed, I was left to figure it out and did, learning new things each time.. 
 
But I’m only a user, and not an advanced one at that.  I am not a developer (obvious, right), and my experience with you and GitHub is the first such  experience  I’ve had with this kind of communication regimen. 


So I’m ignorant, not dumb.
 
I am extremely grateful for you work on this problem, your diligence and expertise, and I realize that your constant reminders about my telephone number experience is something you do for my benefit, not yours, but they make me look bad, and maybe stupid.
 
So inexperienced, and also sloppy appearing because I often I forget to do things that I should do.
 
So the point in all this is to say that you don’t ever have to repeat “Every time you respond via email, your phone number gets posted. Please edit your existing comments to remove that.”  I’ve gotten the message.  There’s no need to repeat it each time I forget.  
 
Instead, to save you key strokes and giving people the idea that I am dumb not ignorant, just type, “You did it again.”  If you’d like, you could end it with an emoji that is either smiling 😊, or maybe looks sympathetically sorry for me. 🤨
 
And with or without the emoji, when I see that abbreviated emoji I’ll go back in and erase it.
 
As I said above, I’ll erase this personal business after you’ve had an opportunity to read it.  There’s no need for you to respond or to change the way you communicate with me.  Keep up the good work!
 
Regards.
 
--------------------------------------------------------------------------------------

**Comment by pyrates999** [comment] 2024-04-17 09:29
In EP properties application, please untick register as shell extension and click on restart file explorer.

As for why it is failing to not show a notification when checking for updates, please try what I suggested again.

You can also remove explorer.exe from the firewall rules.  That is not EP.  That is a system file that is part of windows that is the file explorer application.

And I'm just making sure your contact info isn't exposed on the internet by being direct about it.  That's all.

**Comment by robtgmann** [comment] 2024-04-19 00:38
I give up.  I don’t want to spend any more time on this.
 
Un ticking the shell extension thing resulted in these changes.  First: both Check for updates and Update and restart explorer no longer respond in any way to be clicked … no movement, no sign they’ve been clicked, and no popup about there being no connection to the internet.  
 
Second, when shell extension is unclicked, as you suggested, the icons in the quick launch tool bar arbitrarily change in size.  Normally I have them in large.  After changing the shell option the nearly icons double in size.  Sometime later, for no apparent reason the change to normal size.  
 
In addition, my display settings are messed up.  I normally am set up with three displays: two external plus the native lap-top display.  Usually the laptop display is closed.  Whether closed or opened, the display setting is for the display to be ‘extended;’ that is, all 3 display are separate.  When the shell extension in unchecked and the lid is closed, the two external monitors show the same display.  Opening the lid returns it to all three independent.
 
In addition, after unchecking, the ribbon on my outlook (office 365 running entirely on my desktop) was altered.  The individual items were moved around, and one set of functions was erased from the ribbon.  
 
That’s just too much.  This is a fairly new, lightly loaded computer, and I don’t want to tolerate this mess.  So, I’m going to live with my installation as it is.  I can always go to GitHub and see if there’s a change (if I haven’t received an update notification.
 
Again, thank you for your help,  I really am grateful for your effort.  And but for the minor bug, or whatever it is, EP is superb.  I could never live with windows 11 without it. 
 
 

Author: ACT FROM CHOICE 
Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here
Find it on Amazon and other booksellers      
Please follow me on Twitter: @actfromchoice
And join me on LinkedIn
----------------------------------------------------------------------------------------
Robert Goldmann
Clarity & Performance Coaching
Executives, Professionals, Business owners
 <http://www.clarityandperformance.com/> www.ClarityAndPerformance.com
 <http://www.actfromchoice.com/> www.ActFromChoice.com
 
--------------------------------------------------------------------------------------

**Comment by pyrates999** [comment] 2024-04-19 11:09
here's why you should never enable **register as shell extension** by the way: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

As for needing the quick launch tool bar, I find it's easier to just pin an application to the taskbar instead.

For the display setting issue, is it using display port by chance? If so, it's probably related to this: https://github.com/valinet/ExplorerPatcher/issues/1605

Which is caused by display port deep sleep, not by EP, as when tested by one of the developers here with hdmi, wasn't happening.

EP uses notifications, not popups by the way.  I still think it's caused by that bitdefender firewall silently dropping the network connection made when EP was checking for updates.

One last thing you can try is in the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

Then reapply all your settings again for EP.

**Comment by TkMatt** [comment] 2024-06-20 07:50
Just to clarify this with common words: 
ExplorerPatcher takes the place of "Explore resources" (the builtin windows app).
It doesn't show as a different app in w11, for me, but i guess most have the same case. 
So, check that out if you cannot find the exact name of this app.

**Comment by Amrsatrio** [comment] 2024-11-05 17:14
Check your notification settings for Explorer. After some time after installing EP, WIndows will suggest you to turn off notifications for Explorer because "you haven't been interacting with it for a while," and I assume you agreed on the suggestion so Windows turns it off.

Updates are working normally in 66.6 and 66.7 at least.

Closing.

**Closed by Amrsatrio** 2024-11-05 17:14 UTC

**Comment by robtgmann** [comment] 2024-11-05 22:06
Great work. Woth waiting for!

 



Author: ACT FROM CHOICE 

Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here

Find it on Amazon and other booksellers      

Please follow me on Twitter: @actfromchoice

And join me on LinkedIn

----------------------------------------------------------------------------------------

Robert Goldmann

Clarity & Performance Coaching

Executives, Professionals, Business owners

www.ClarityAndPerformance.com <http://www.clarityandperformance.com/> 

www.ActFromChoice.com <http://www.actfromchoice.com/> 

510.495.4444

------------------------------------------------------------------------------------------

**Comment by pyrates999** [comment] 2024-11-06 12:27
I would edit your last comment as it includes some personal info about you that you may not want to let out.

**Comment by Amrsatrio** [comment] 2024-11-06 12:28
@pyrates999 Edited.

**Comment by robtgmann** [comment] 2024-11-06 18:30
Thank you for your concern, and I appreciate it.

 

You’ve reminded me before, but, alas, my business requires it, and for some reason, no one has abused the telephone number.

 



Author: ACT FROM CHOICE 

Read the Kirkus and other reviews   <http://www.actfromchoice.com/sample-reviews-and-press> here

Find it on Amazon and other booksellers      

Please follow me on Twitter: @actfromchoice

And join me on LinkedIn

----------------------------------------------------------------------------------------

Robert Goldmann

Clarity & Performance Coaching

Executives, Professionals, Business owners

www.ClarityAndPerformance.com <http://www.clarityandperformance.com/> 

www.ActFromChoice.com <http://www.actfromchoice.com/> 

510.495.4444

------------------------------------------------------------------------------------------

**Comment by pyrates999** [comment] 2024-11-06 22:42
@robtgmann stop respond via email because that is showing your personal information
