### ISSUE TITLE
Unable to Uninstall Application Due to Compatibility Issues on Win11 Insider Preview Build 262244

### ISSUE THREAD

**Issue by TurthXR** [valinet/ExplorerPatcher#3508] opened 2024-07-26 04:01 UTC
Subject: Unable to Uninstall Application Due to Compatibility Issues on Win11 Insider Preview Build 262244

**Description:**

I am currently using Windows 11 Insider Preview Build 262244 (Home edition) and have encountered an issue where I cannot uninstall your application through the Control Panel due to compatibility issues. Here are the details:

- **Application Name:** [Your Application Name]
- **Windows Version:** Windows 11 Insider Preview Build 262244 (Home edition)
- **Issue Description:**
  - Installation of the application was successful without any compatibility issues.
  - However, after experiencing frequent crashes in system folders, I attempted to uninstall the application via the Control Panel.
  - Upon attempting to uninstall, a compatibility error message appears, preventing the application from being removed.

**Steps to Reproduce:**
1. Install the application as usual.
2. Encounter system folder crashes (not related to the application).
3. Go to Control Panel > Programs > Programs and Features.
4. Select the application and click Uninstall.
5. Observe the compatibility error message preventing the uninstallation process.

**Expected Behavior:**
The application should be uninstalled successfully without any compatibility issues.

**Actual Behavior:**
A compatibility error message appears, and the application remains installed.

**Additional Information:**
- I have tried running the uninstaller with administrator privileges and adjusting compatibility settings but to no avail.
- I have also checked for any specific compatibility rules set in Group Policy that might be affecting the uninstallation process.

**Environment:**
- OS: Windows 11 Insider Preview Build 262244 (Home edition)
- Hardware: [Specify if relevant, e.g., Intel i5-10400, 16GB RAM, etc.]

**Suggested Solutions:**
- Please provide a fix for the compatibility issues when uninstalling the application.
- Alternatively, provide detailed instructions on how to manually remove the application files and registry entries.

Thank you for your attention to this matter. I look forward to your response and assistance in resolving this issue.
<img width="357" alt="1721966456990" src="https://github.com/user-attachments/assets/2a9731ba-36ab-4271-94c2-57220be93f7c">

**Comment by pyrates999** [comment] 2024-07-26 13:50
this is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3229#issuecomment-2096773457

please close this.

**Closed** 2024-07-27 07:58 UTC
