### ISSUE TITLE
Can't use EP with the "Task Kill" option in Settings

### ISSUE THREAD

**Issue by genericexists** [valinet/ExplorerPatcher#3284] opened 2024-05-16 22:38 UTC
Title explains it mostly, the "Task Kill" option in Settings > System > For developers doesn't work at all when you use the Windows 10-style taskbar in ExplorerPatcher. Right-clicking a program from the taskbar and clicking "End Task" doesn't do anything at all.

Screenshot:
![image](https://github.com/valinet/ExplorerPatcher/assets/168141409/e8fb0261-9ad8-49e5-94d1-4dafc58ffe24)

**Comment by pyrates999** [comment] 2024-05-16 22:48
the feature is called end task, not task kill.

this is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2812

please close this.

**Closed** 2024-05-17 00:41 UTC
