### ISSUE TITLE
Finish device setup screen crashes with explorerpatcher installed

### ISSUE THREAD

**Issue by TheBlunius** [valinet/ExplorerPatcher#2624] opened 2023-12-26 16:01 UTC
Finish device setup screen crashes with explorerpatcher installed, and after explorer shows up the search doesnt work as icon, shortcut etc.

**Comment by pyrates999** [comment] 2023-12-27 00:20
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2523

Please close this.

**Closed** 2023-12-27 00:34 UTC
