### ISSUE TITLE
Terminal software on Start Menu right context menu result in error on Microsoft Windows 11 LTSC OSs

### ISSUE THREAD

**Issue by Broswons** [valinet/ExplorerPatcher#3849] opened 2024-10-27 22:58 UTC
Hi, 

I am a quite novice user of the great **Valinet ExplorerPatcher**, because just till recently I did not have **Microsoft Windows 11 OS** installed at all.
To be completely honest, I was afraid and I was terrified in advance, what a next **Microsoft corp.** mumbo-jumbo "visionary" nightmare I will see about its **Start Menu** in particular, and since the Windows **Start Menu** is a super important question, well at least for me.

So, after I almost, sorry to say, puke when I saw the original, ascetic and fully limited Windows 11 **Start Menu** and also the Windows 11 **Taskbar** (including their additional and fully options in the Windows **Settings** applet...), and when I even further explode, especially when I click the **Network** icon on the **Taskbar** and realize its totally idiotic design (when even to see a straightforward and simple Wi-Fi connection are you (still) Online or Offline, is fully hidden and actually need a 2-3 mouse click steps just to see even that vitally important status and that need to be seen instantly to all of us all the time...), I strongly decided that the only, only way I can really live and co-exist with **Microsoft Windows 11** OS environment is to change its **Start Menu** and its **Taskbar** as mandatory here. Period.

With that said, I honestly do not know why for God's sake **Microsoft Corp.** finally do not integrate in the **Windows OS** directly, a 2-3 different direct options how we as a users, like that the **Start Menu** and **Taskbar** looks like. 
I mean, this option truly exist in the one older **Windows OS**! I am not 100% sure was that **Windows Vista** OS very this moment, but I am totally sure that in one **Windows OS** in the distant past, we all have ability to pick up which of two **Start Menu** design we want to use: the present **Windows OS** **Start Menu** design, or one from the first previous **Windows OS** **Start menu** design.

And finally, since this is my very first post here about **Valinet ExplorerPatcher**, if I post this bugs report on the wrong place/thread, please accept my apologize in advance.

------

OK, so, I just tested newest available **Microsoft Windows 11 IoT Enterprise LTSC 2024 OS build 26100.1742 [v24H2] x64 EN US OS** which is also then updated via **Windows Update** service to the **OS build 26100.2033** and with the present **Windows Feature Experience Pack: 1000.26100.2.3.0**...

I then install on this **Windows OS** the **Valinet ExplorerPatcher v22621.3880.66.6** (released on **12 September 2024**), and when I engage its **Taskbar style** to **Windows 10 (ExplorerPatcher)** option, I notice that when I click the **Start Menu right context menu** and then click to **Terminal** or **Terminal (Admin)**, the **wt.exe** error message appear:

_**Windows cannot find 'wt.exe'. Make sure you typed the name correctly, and then try again.**_

After pressing the **OK** button on the above message, sometimes the explorer.exe and/or Taskbar restarts.

I try further to manually search the **wt.exe** file on this Windows OS, but truly does not exist, because on this particular **LTSC OS** I do not have a **Terminal** as a installed software at all, I have only a **PowerShell** and a **Command Prompt** (**CMD**) here.

The **Microsoft Windows 11 IoT Enterprise LTSC 2024 OS build 26100.1742 [v24H2] x64 EN US OS** version (and/or most probably even on **Microsoft Windows 11 Enterprise LTSC 2024 OS** version also), probably won't get **Terminal** at all directly, or it will be introduced and installed via **Windows Update** service much later, so I have two options here:
Install the **Terminal** software by myself (this very moment I still do not know how to done it properly, but I will try + if someone have an idea here, please share with me...), and/or ask from **Valinet ExplorerPatcher** an option that in its **Taskbar style** we get an options: do we want to have on **Start Menu right context menu** the **Terminal** option, or **Command Prompt** option, or the **PowerShell** option, or finally all them 3 together. :)

And finally, maybe it is too much to ask, but since we all waiting a one whole huge decade already that almighty **Microsoft Corp.** finally, finally integrate the Windows **Settings** and the **Control Panel** all together in one merged app. (... but, instead of that quite logically necessity, they just launching a more newer and newer versions of the **Windows** OS itself all the time...), maybe it is not so an-logically here to ask, that we have in **Valinet ExplorerPatcher**, in its **Taskbar style**, also the ability to put on **Start Menu right context menu** the **Control Panel** option also, as we have the Windows **Settings** option, so that they are both here in the same time.  :)

Well, thank you for reading and for all the help and advice's in advance!

Best regards!

**Comment by pyrates999** [comment] 2024-10-27 23:07
Please condense your response.  That's just a word salad that most will skip and not read.

**Comment by Amrsatrio** [comment] 2024-10-28 07:53
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2156

**Closed by Amrsatrio** 2024-10-28 07:53 UTC
