### ISSUE TITLE
Win update broke Taskbar color

### ISSUE THREAD

**Issue by coyote3** [valinet/ExplorerPatcher#2996] opened 2024-03-13 20:16 UTC
My Taskbar ("Accent") color is broken (shows black) after a pair of updates to Windows 11 Pro 64-bit 23H2 (see screenshot).

ExplorerPatcher v22621.2861.62.2
![Win11updatesBrokeTaskbarColor](https://github.com/valinet/ExplorerPatcher/assets/30500973/89acad45-b32c-4cf2-8cfe-80a4d55b4fec)
I'd've tried uninstalling ExplorerPatcher but none of the instructions work as mentioned when I posted a previous issue.

**Comment by JamieOnyx** [comment] 2024-03-13 21:04
Same Issue here too

**Comment by KCFlyer** [comment] 2024-03-13 21:21
The Taskbar seems to be mostly transparent. Doesn't work at all with dark background. Lightened up the background and it works a little better.
![image](https://github.com/valinet/ExplorerPatcher/assets/124475011/2a98ce20-baea-49f9-99b9-c34fe2888cd1)

**Comment by Amrsatrio** [comment] 2024-03-13 22:09
I really should make the [latest prerelease version](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.1_9e9c016) a release so you guys would notice that we have fixed it already 🤦🤦🤦🤦🤦

Duplicate of #2975.

**Comment by Zzyzx-Wolfe** [comment] 2024-03-13 22:09
Same issue here on 22631.3296.

**Closed by Amrsatrio** 2024-03-13 22:09 UTC

**Comment by Zzyzx-Wolfe** [comment] 2024-03-13 22:11
> I really should make the [latest prerelease version](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.1_9e9c016) a release so you guys would notice that we have fixed it already 🤦🤦🤦🤦🤦
> 
> Duplicate of #2975.

Thanks so much. Confirmed this is working for me.
