### ISSUE TITLE
Some apps are missing from all apps. Cannot pin a file (.exe) to the start menu. 

### ISSUE THREAD

**Issue by birchmoonlight** [valinet/ExplorerPatcher#1358] opened 2023-04-22 16:37 UTC
Some apps are missing from all apps. Cannot pin a file (.exe) to the start menu. In addition, the "pin to start menu" in the right-click menu of the resource manager does not work. I don’t know if it’s because the win10 start menu generated by ep is not the start menu of the system, but simulated by ep

**Comment by ARestrepo228** [comment] 2023-04-24 05:11
To Fix The deleted shortcuts issue you have to go to: C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy and delete dxgi.dll then restart explorer and the issue will be fixed

But a problem is that if you right click con an icon on the windows 10 start menu it will crash the menu

**Comment by ARestrepo228** [comment] 2023-04-25 03:06
![bug](https://user-images.githubusercontent.com/131640765/234164554-f7d81202-2c8a-4b84-aa65-19707f8e79e4.png)

**Comment by Armo00** [comment] 2023-04-27 03:37
I find that I cannot pin UWP app to the windows10 start menu. Might be the same problem you are having.

**Comment by ma-er233** [comment] 2023-05-02 06:56
Same problem
- Missing all UWP app from the start menu (Manually put shortcuts in the start menu folder still didn't work)
- Can't pin any shortcut or executable to start from explorer. Right click→"Pin to start" only works in start menu
App version 22621.1555.55.1  Windows 11 Professional 22H2 22621.1635

**Comment by ThaFog** [comment] 2023-05-10 12:12
> I find that I cannot pin UWP app to the windows10 start menu. Might be the same problem you are having.

- In run dialog type `shell:AppsFolder`
- Find your app
- Create shortcut on desktop
- Move created shortcut to `C:\ProgramData\Microsoft\Windows\Start Menu\Programs`

This is how I've figured it if start menu does not have shortcut to some applications (mostly UWP actually). The problem is sometimes there's icon missing

**Comment by Armo00** [comment] 2023-07-06 07:09
I tried this and it indeed solve to problem of missing icon in the start menu. However, the icon in task bar is still missing. Do you have any idea of how to solve that?

**Comment by pyrates999** [comment] 2023-07-06 07:11
Is the icon missing in the system tray?

**Comment by CapoFantasma97** [comment] 2023-07-09 23:24
Same here, UWP apps missing from the start menu altogether. But they're still there.

It's not even always been like that, it was sudden. I had some tiles with them and now they're empty spots. The app list doesn't list them, even system ones like the Store.

**Comment by pyrates999** [comment] 2023-07-10 09:52
> Same here, UWP apps missing from the start menu altogether. But they're still there.
> 
> It's not even always been like that, it was sudden. I had some tiles with them and now they're empty spots. The app list doesn't list them, even system ones like the Store.

Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:15
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:15 UTC
