### ISSUE TITLE
Win11 Search Button not working

### ISSUE THREAD

**Issue by coyote3** [valinet/ExplorerPatcher#2939] opened 2024-03-04 18:54 UTC
I think ExplorerPatcher v22621.2861.62.2 might be breaking the taskbar Search Button on my Windows 11 Pro 64-bit.

The first thing I tried (which worked for a couple of days) was updating to 23H2.

But then this morning  pthe Search Button stopped working again (that is nothing happens when I click it) .  I tried to Uninstall (via the steps at on Github) and no steps seemed to work (for example, running ep_setup.exe /uninstall didn't do anything, and I couldn't find an uninstaller in C:\Program Files\ExplorerPatcher), but something must've worked since ExplorerPatcher then seemed to stop working, and after a reboot the Search Button resumed working, even after I then re-installed ExplorerPatcher.

But I figure this issue will return and I can't live without the Search Button (and I'm not even sure how to uninstall!), so I'm hoping for some help please.  My sincere apologies if this is not considered properly placed here in "Issues".

**Comment by pyrates999** [comment] 2024-03-04 23:38
try this to rebuild the search index: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/windows-search-performance-issues

might be related to this: https://github.com/valinet/ExplorerPatcher/issues/1975

**Comment by coyote3** [comment] 2024-03-05 00:43
Thank you very much for your reply, [pyrates999](https://github.com/pyrates999)!

I just rebuild the Search Index as you recommended; perhaps that will keep the issue from recurring.'

I'd seen that suggestion when googling 'Search Button not working', but guessed it wasn't relevant since the Search Box doesn't even appear (NOTHING happens) when I click the magnifying glass.  Here's what I mean by the Search Box that doesn't appear when the issue occurs:
![ExplorerPatcherSearchWindow](https://github.com/valinet/ExplorerPatcher/assets/30500973/51fc7ab1-d576-4548-9160-f638f75a2b8c)

**Comment by pyrates999** [comment] 2024-03-05 11:10
You can also try killing the process named explorer.exe and then running explorer.exe from windows task manager.

**Comment by pyrates999** [comment] 2024-03-06 09:07
Yes, you should do that if the issue comes back.

EP does binary patching of window's explorer.exe and other windows dll's in order to do what it does.

**Comment by Amrsatrio** [comment] 2024-03-09 12:29
Can confirm that ~3% of the time Search refuses to open. Even when using the new taskbar. This is mostly a Windows issue so sorry to say that there's little we can do.

**Comment by Amrsatrio** [comment] 2024-03-13 00:49
Fixed in the latest prerelease. Nevermind about my previous statement, this was apparently caused by Explorer repeatedly crashing during Second Chance OOBE (SCOOBE) which I've fixed and tested to be fixed.

**Closed by Amrsatrio** 2024-03-13 00:49 UTC
