### ISSUE TITLE
Microsoft Store installed apps disappeared from Windows 10 when running Windows 11.

### ISSUE THREAD

**Issue by gtdurham** [valinet/ExplorerPatcher#1187] opened 2023-03-23 23:29 UTC
I installed EP. When I set the Start Menu to Windows 10 format, all the Microsoft Store installed apps disappear. They don't show up in the app list and therefore don't show up in the start menu. If I do a search, I can launch the apps, all though there's an option to pin to Start, it doesn't work. They all work if I set it to Windows 11 format.

**Comment by SepticFuddy** [comment] 2023-03-25 02:54
Same issue here. The unfortunate part is it was largely the few MS Store apps I use that I was pinning to Start in W10

**Comment by nogenem** [comment] 2023-03-25 18:05
Same problem here, its impossible (!?) to pin the apps that are installed by the Microsoft Store on the Win 10 Start Menu version 😭

I even tried to uninstall and reinstall some of them, in the hopes that they would show up on the "Recently Added" part of the Start Menu, but that didn't help 😅

I found out that the apps should be located on the folder: `C:\Program Files\WindowsApps`, but i couldn't find most of the .exe, and a couple that i found couldn't be executed 🥲

**Comment by djcholapin** [comment] 2023-03-26 21:32
Exactly the same issue for me for the past days, I did an update of Win 11, and EP as well, I don't know which one triggered it but I had all my apps nicely put in the windows menu (netflix, spotify, mail...), and now after that I no longer have all the windows store apps (including the native ones) in the start menu, so impossible to pin them as tiles (and the tiles were removed as well!).

Not sure what to do here. The menu was perfect, similar to Win 10 but after that I only have the manually installed softwared pinned and no longer any Win11 / live tiles apps!

Very much looking for a solution here. I posted in the win 11 forum as well to see if there is a way to bring those back to the win menu.

**Comment by Git-happiness** [comment] 2023-03-26 22:03
Same. New install of EP on Windows 11. They do not appear on the programs list nor can I pin them.

**Comment by djcholapin** [comment] 2023-03-30 16:50
Tried this command on powershell : Get-AppxPackage -allusers | foreach {Add-AppxPackage -register "$($_.InstallLocation)\appxmanifest.xml" -DisableDevelopmentMode}

Same

Tried the SFC Scannow

Same

Tried the DSIM Repair

Same

So I suppose there is something in the Explorer Patcher update that prevent those from popping up. Has anyone tried to downgrade Explorer Patcher ?

Or does anyone know how to add those live tile apps manually until they solve the issue ?

**Comment by Git-happiness** [comment] 2023-03-31 06:17
> Has anyone tried to downgrade Explorer Patcher ?

I haven't tried that because I did a new install. I will though. Which older version seemed to work ?

**Comment by djcholapin** [comment] 2023-04-03 00:47
I have the 22621.1413.54, so I suppose the version right below 22621.1344.53, but can't confirm it as I might have jumped a few versions before upgrading. If someone can confirm...

**Comment by djcholapin** [comment] 2023-04-03 00:58
BTW not sure how to downgrade to previous versions to try them, I would if I knew how. Also I found that the issue has been mentionned several times, there is a post here which is 2 weeks old : #1108 . It's been pinned as under investigation, so hopefully we'll have some news soon.

**Comment by valinet** [comment] 2023-04-05 02:24
> Tried this command on powershell : Get-AppxPackage -allusers | foreach {Add-AppxPackage -register "$($_.InstallLocation)\appxmanifest.xml" -DisableDevelopmentMode}
> 
> Same
> 
> Tried the SFC Scannow
> 
> Same
> 
> Tried the DSIM Repair
> 
> Same
> 
> So I suppose there is something in the Explorer Patcher update that prevent those from popping up. Has anyone tried to downgrade Explorer Patcher ?
> 
> Or does anyone know how to add those live tile apps manually until they solve the issue ?
> 
> Also : If you switch back to Win 11 Star Menu, then all the apps are there again in the list of all apps, you can also pin them as favourite. But when switching back to Win 10, then for some reason all the windows store apps and native windows (only) aer not there. Only the Shortcuts from the "Start Menu" folder are there. So it's definitely an EP issue.

It’s nothing in the latest ExplorerPatcher update. The Windows 10 Start menu, as mentioned multiple times, is the original one that still ships as part of the system. ExplorerPatcher just activates it by patching things here and there. Now, to make it work properly, I redirected it to an older version of the library that handles the Start menu tiles (StartTileData.dll). In the latest OS builds, Microsoft seems to have changed *something* in the backend, and the old StartTileData does not connect to the proper place where tiles are stored anymore. If I patch EP’s code and have the menu load the current OS shipped StartTileData, all tiles come back, including UWP app tiles. The problem then is, the menu itself is not aware of the new data store, and so when right clicking pinned stuff, it registers them as unpinned and offers to pin again, thus there being no way to unpin stuff. I started exploring the situation some time ago, but unfortunately did not have time to finish the investigation and come up with a workaround. But that’s the research so far, if anyone’s interested in investigating it in the mean time…

**Comment by yuan21c** [comment] 2023-04-06 04:18
A way to manually pin apps:

+ Press `WIN + R` and run `shell:AppsFolder`, it will open a `Applications` folder in explorer.
+ Open folder `C:\Users\<your name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`.
+ Just drag a app to `Programs` folder.
+ It will create a shortcut in `Programs` folder, and the app(shortcut) is shown at app list now.
+ The icon is not shown properly, you need to manually change the shortcut icon.
+ Pin to start menu.

To change shortcut icon, you need locate the app's real location. Task Manager will help. 

Run the app -> find it in task manager -> right-click and select open file location

A problem is you will see two same apps in win11 style app list.

**Comment by djcholapin** [comment] 2023-04-06 12:13
> > Tried this command on powershell : Get-AppxPackage -allusers | foreach {Add-AppxPackage -register "$($_.InstallLocation)\appxmanifest.xml" -DisableDevelopmentMode}
> > Same
> > Tried the SFC Scannow
> > Same
> > Tried the DSIM Repair
> > Same
> > So I suppose there is something in the Explorer Patcher update that prevent those from popping up. Has anyone tried to downgrade Explorer Patcher ?
> > Or does anyone know how to add those live tile apps manually until they solve the issue ?
> > Also : If you switch back to Win 11 Star Menu, then all the apps are there again in the list of all apps, you can also pin them as favourite. But when switching back to Win 10, then for some reason all the windows store apps and native windows (only) aer not there. Only the Shortcuts from the "Start Menu" folder are there. So it's definitely an EP issue.
> 
> It’s nothing in the latest ExplorerPatcher update. The Windows 10 Start menu, as mentioned multiple times, is the original one that still ships as part of the system. ExplorerPatcher just activates it by patching things here and there. Now, to make it work properly, I redirected it to an older version of the library that handles the Start menu tiles (StartTileData.dll). In the latest OS builds, Microsoft seems to have changed _something_ in the backend, and the old StartTileData does not connect to the proper place where tiles are stored anymore. If I patch EP’s code and have the menu load the current OS shipped StartTileData, all tiles come back, including UWP app tiles. The problem then is, the menu itself is not aware of the new data store, and so when right clicking pinned stuff, it registers them as unpinned and offers to pin again, thus there being no way to unpin stuff. I started exploring the situation some time ago, but unfortunately did not have time to finish the investigation and come up with a workaround. But that’s the research so far, if anyone’s interested in investigating it in the mean time…

Thanks for the insight. I'm not tech saavy at all but I do hope this helps someone figuring it out. It makes sense, I had made a Windows update at the same time as an EP update, this is when I noticed the change so I didn't know which one, this makes sense.

To be honest if I had to chose, I'd rather that option and not beeing able to unpin stuff, as this is something I would usually not do once my menu is set. But I understand this is a rather bigger issue for some.

I hope someone will come up with a workaroud, or even a manual one in the meatime.

> A way to manually pin apps:
> 
> * Press `WIN + R` and run `shell:AppsFolder`, it will open a `Applications` folder in explorer.
> * Open folder `C:\Users\<your name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`.
> * Just drag a app to `Programs` folder.
> * It will create a shortcut in `Programs` folder, and the app(shortcut) is shown at app list now.
> * The icon is not shown properly, you need to manually change the shortcut icon.
> * Pin to start menu.
> 
> To change shortcut icon, you need locate the app's real location. Task Manager will help.
> 
> Run the app -> find it in task manager -> right-click and select open file location
> 
> A problem is you will see two same apps in win11 style app list.

Yes I am doing this will all software installed manually that did not have a WIN shortcut. But this defies the purpose a bit as there are no live tiles, and you only get the ugly icons. Which by the way, would be nice to be able to replace with a manually created jpg/png tile, that was missing a lot in the Win10 Menu, I found that apps such as Live Tiles Anywhere did not work.

**Comment by pyrates999** [comment] 2023-05-16 09:12
This looks to be the same as https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by justin13601** [comment] 2023-05-25 16:38
> A way to manually pin apps:
> 
> * Press `WIN + R` and run `shell:AppsFolder`, it will open a `Applications` folder in explorer.
> * Open folder `C:\Users\<your name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`.
> * Just drag a app to `Programs` folder.
> * It will create a shortcut in `Programs` folder, and the app(shortcut) is shown at app list now.
> * The icon is not shown properly, you need to manually change the shortcut icon.
> * Pin to start menu.
> 
> To change shortcut icon, you need locate the app's real location. Task Manager will help.
> 
> Run the app -> find it in task manager -> right-click and select open file location
> 
> A problem is you will see two same apps in win11 style app list.

Could you expand on changing the icon for UWP apps? I can't seem to be able to do it even though I know where the file location is. Other than that pinning to start menu works perfectly so thank you!

**Comment by djcholapin** [comment] 2023-05-30 09:12
> > A way to manually pin apps:
> > 
> > * Press `WIN + R` and run `shell:AppsFolder`, it will open a `Applications` folder in explorer.
> > * Open folder `C:\Users\<your name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`.
> > * Just drag a app to `Programs` folder.
> > * It will create a shortcut in `Programs` folder, and the app(shortcut) is shown at app list now.
> > * The icon is not shown properly, you need to manually change the shortcut icon.
> > * Pin to start menu.
> > 
> > To change shortcut icon, you need locate the app's real location. Task Manager will help.
> > Run the app -> find it in task manager -> right-click and select open file location
> > A problem is you will see two same apps in win11 style app list.
> 
> Could you expand on changing the icon for UWP apps? I can't seem to be able to do it even though I know where the file location is. Other than that pinning to start menu works perfectly so thank you!

It's off topic but :

1. Right Clic on the app / open location. Then again right clic on the shortcut, open location. You must find the .exe file
2. Create xxx.VisualElementsManifest.xml (ex EXCEL.VisualElementsManifest.xml), where xxx is the exact name of your exe file.
3. Fill it uo with that :

<?xml version="1.0" encoding="utf-8"?>
<Application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <VisualElements ForegroundText="light" BackgroundColor="#404040" ShowNameOnSquare150x150Logo="off" Square150x150Logo="LogoImages\aExcel.png" Square70x70Logo="LogoImages\aExcels.png"></VisualElements>
</Application>

You will understand that you have 2 picture files, with their path, you can customize the pictures by creating / downloading new tiles, and update their path. The others, shownameon square and background color are pretty much self explanatory. ALthough I noticed that, BackgrouncColor does not work properly. I would usually have one small and one medium picture for each tile.

3. Clear Cache with CMD

Open CMD as an admin. Then go to the path of the start menu shortcuts (you will have it by completing the first step) (cd C:/Users/....)

Then write : for %f in (*.*) do copy /b “%f” +,,

Done

**Comment by Poopooracoocoo** [comment] 2023-09-27 09:38
Duplicate of #1108

**Closed by Poopooracoocoo** 2023-09-27 09:38 UTC
