### ISSUE TITLE
Theat Quarantined, new update change?

### ISSUE THREAD

**Issue by SyPhase** [valinet/ExplorerPatcher#3666] opened 2024-09-10 19:28 UTC
With the latest automatic update today my Windows Defender auto-quarantined the patch:

> Detected: HackTool:Win32/Patcher!MTB
> Status: Quarantined
> Quarantined files are in a restricted area where they can't harm your device.  They will be removed automatically.
> 
> Date: 09/10/2024 1:22 PM
> Details: This program had potentially unwanted behavior.
> 
> Affected items:
> file: C:\Users\pierc\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from
> https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

Not sure what caused this, just thought I'd report it in case it was relevant.  As a side note, I see someone else had this issue in May 2024, however, I have been using this since August 2023 and never had this issue until now (September 2024).

**Comment by advillabotomite** [comment] 2024-09-10 19:38
I got this issue as well. I've also had the program for a while and have never had this issue until now.

**Comment by b3nw** [comment] 2024-09-10 19:59
Also had this during the update:

	Name: Backdoor:Win32/Bladabindi!ml
 	ID: 2147748148
 	Severity: Severe
 	Category: Backdoor
 	Path: file:_C:\Users\user\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: Real-Time Protection
 	User: DESKTOP-#####\user
 	Process Name: C:\Windows\explorer.exe
 	Security intelligence Version: AV: 1.417.624.0, AS: 1.417.624.0, NIS: 1.417.624.0
 	Engine Version: AM: 1.1.24070.3, NIS: 1.1.24070.3

**Comment by Witaminer** [comment] 2024-09-10 20:02
The same here, updater quarantained by Windows Deffender.
HackTool:Win32/Patcher!MTB
Trojan:Win32/Fauppod!ml

**Comment by nshannon123** [comment] 2024-09-10 20:52
Looks to be covered in the Warning on the latest release:

https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.5_5094108

**Comment by hippoduck** [comment] 2024-09-10 21:18
I had this issue, I allowed the threat and updated / restarted but I can no longer open my drives. Icons have changed to white, and explorer hangs when clicking on them. Worked earlier in the day. 

![image](https://github.com/user-attachments/assets/40f0854e-a55d-4b1d-8e8b-490b4d3bca23)

**Comment by pyrates999** [comment] 2024-09-10 22:48
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

You can also set windows defender to exclude the following:

1. %ProgramFiles%\ExplorerPatcher
2. %APPDATA%\ExplorerPatcher
3. Directory that you downloaded ep_setup.exe to

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

**Comment by TheChrisGlass** [comment] 2024-09-10 23:40
Adding the exclusion directories fixed it.
You can find the steps here:
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

But it does feel unfair to flag it as such.

**Comment by Amrsatrio** [comment] 2024-09-11 02:55
Discuss in here. https://github.com/valinet/ExplorerPatcher/issues/3228

They have been doing this since February.

@TheChrisGlass Agree. This way StartAllBack and Windhawk should be flagged as well.

**Closed by Amrsatrio** 2024-09-11 02:55 UTC
