### ISSUE TITLE
White line boarder box

### ISSUE THREAD

**Issue by Vader-Elite** [valinet/ExplorerPatcher#2791] opened 2024-02-06 23:33 UTC
Every time I install EP on any win11 device it causes a white box around the sound volume bar and other areas, I have tried everything and I cannot make it disappear.

I even tried this old fix 
Control Panel\All Control Panel Items\Ease of Access Centre\Make the keyboard easier to use.

but it was already unchecked and didnt make any difference.

Many thanks for this EP btw, I really appreciate it.

![Screenshot (1)](https://github.com/valinet/ExplorerPatcher/assets/159202565/40ebf50a-db52-43c5-910e-a896fb886049)
![Screenshot (2)](https://github.com/valinet/ExplorerPatcher/assets/159202565/9ef833c5-0adc-44c3-bf27-886000ba8887)

**Comment by Vipin2003** [comment] 2024-02-07 03:37
Repeated Issue #2323 and EP is not made for fixing OOBE bugs

**Comment by pyrates999** [comment] 2024-02-07 09:54
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2323

Please close this

**Comment by Vader-Elite** [comment] 2024-02-07 10:07
> Repeated Issue #2323 and EP is not made for fixing OOBE bugs

Hey

So this is a win11 bug not EP so won't be fixed ?

Why does it only happen when EP is used ?

**Comment by Vipin2003** [comment] 2024-02-07 10:09
If you use SAB too, then also it will happen. Check installing StartAllBack. There alao it happens

**Comment by pyrates999** [comment] 2024-02-07 10:25
It's not a bug for EP to fix.

**Comment by Vader-Elite** [comment] 2024-02-07 10:54
> It's not a bug for EP to fix.

Sure ok, but why does it only happen after installation of EP ?

**Comment by pyrates999** [comment] 2024-02-07 11:02
See here for why: https://github.com/valinet/ExplorerPatcher/issues/2323

**Comment by Vader-Elite** [comment] 2024-02-07 11:04
2323 Doesn't explain why it happens

**Comment by Amrsatrio** [comment] 2024-02-08 03:26
Duplicate of #1448 #2323

**Closed by Amrsatrio** 2024-02-08 03:26 UTC
