### ISSUE TITLE
Lost left click menu button

### ISSUE THREAD

**Issue by ARW353** [valinet/ExplorerPatcher#3853] opened 2024-10-28 12:20 UTC
I have the oposite problem. I have a 9 machine network all using EP 22621.3880.67.7 with Win11 latest version 22631.4391 after installing Win update KB5044380. 
Prior to installing the update all machines worked correctly but after installing the update 4 machines were still OK but 5 machines lost the ability to left click on the Start button to reveal the start menu. Nothing happens when the Start Menu icon, bottom left, is left clicked. The right click is unaffected.
I have done some testing and the results are that in every case the function is restored if Explorer Patcher is uninstalled. Reinstalling Explorer Patcher  causes the problem to reoccur.
I really do like Explorer Patcher particularly for the ability to remove the Recommended section as it is just a waste of space.

**Comment by Solithe** [comment] 2024-10-28 15:39
Left click is not the same as right klick =)

Lost Left click too afer hotfixed my win 11 with a small patch

**Comment by Amrsatrio** [comment] 2024-10-29 14:47
Please do not rely on the Windows 10 Start menu anymore. Microsoft has nuked it, and my fixes don't seem to work on all users. I know it is sad but it is the reality. Switch to Windows 11 start menu for now, or uninstall EP.

Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3667

**Closed by Amrsatrio** 2024-10-29 14:47 UTC

**Comment by ARW353** [comment] 2024-10-29 15:41
I was using Win 11 as I said in my original post.
