### ISSUE TITLE
Windows 11 update fails

### ISSUE THREAD

**Issue by mnesto-trex** [valinet/ExplorerPatcher#3893] opened 2024-11-05 23:41 UTC
Getting an error when Windows 11 attempts to install a new update. The error calls out ExplorerPatcher. Can't find a solution for this

![Screenshot 2024-11-05 154001](https://github.com/user-attachments/assets/61c525a5-7c2b-4c0c-8886-bdb69e57ecd1)

**Comment by explor202** [comment] 2024-11-05 23:51
@mnesto-trex  it's noted elsewhere here to uninstall EP, update W11, then reinstall EP.

**Comment by milesprower2293** [comment] 2024-11-06 05:14
Duplicate of #3830

**Closed by milesprower2293** 2024-11-06 05:14 UTC
