### ISSUE TITLE
22621.3007.63.2_fb28688 was detected as virus

### ISSUE THREAD

**Issue by yracnet** [valinet/ExplorerPatcher#2876] opened 2024-02-20 23:59 UTC
The release https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3007.63.2_fb28688 was detected as virus in windows 11,   is it ok?

**Comment by tehkurt** [comment] 2024-02-21 01:25
Seconding the issue. Windows Defender IDs this download as containing HackTool:Win64/Patcher!MSR
![2024-02-20 20_23_50-Windows Security](https://github.com/valinet/ExplorerPatcher/assets/15126901/7135a195-5655-4a49-91f2-5c7a1bf299ea)

**Comment by Amrsatrio** [comment] 2024-02-21 02:42
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2873

**Closed by Amrsatrio** 2024-02-21 02:42 UTC
