### ISSUE TITLE
Crashing on right click @ desktop & file explorer

### ISSUE THREAD

**Issue by blue20-20** [valinet/ExplorerPatcher#2540] opened 2023-12-03 00:50 UTC
Crashing on right-click on the desktop and in file explorer. No other conflicting software, on the latest W11 update.

**Comment by pyrates999** [comment] 2023-12-03 10:34
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

Please close this.

**Closed as completed** 2023-12-03 15:20 UTC
