### ISSUE TITLE
Numerous entries missing from Windows 10 start menu on Win11 host

### ISSUE THREAD

**Issue by origintopleft** [valinet/ExplorerPatcher#1517] opened 2023-06-03 09:14 UTC
I have an assortment of shortcuts to third party applications within `%APPDATA%\Microsoft\Windows\Start Menu\Programs`, like so (exact applications probably aren't of importance to this issue):

![image](https://github.com/valinet/ExplorerPatcher/assets/4407155/4d2bd42d-2609-4723-8711-4bf849c694b0)

Standard Windows behavior is to place them in the start menu alongside the folders. Functions like "Pin to Start" seem to also expect this behavior, because this is where those shortcuts are automatically placed. However, of these shortcuts, only File Explorer and OneDrive appear in the Start menu, and I believe this is only due to them being baked into the OS.

In addition, any application that even sneezes in the general direction of UWP or the Microsoft Store is also missing. This includes baked in UWP applications, such as Phone Link, Windows Terminal, and the Microsoft Store itself. I'm aware that much of the Windows customization scene is horribly allergic to UWP and the MS Store, however I don't believe near-total obliteration of the whole subsystem from my program launcher is intended behavior in this case.

In all of the above cases, invoking the search function using any of the usual methods (Win+Q, typing into start, etc) and searching for the missing application brings intended results, as below:

![image](https://github.com/valinet/ExplorerPatcher/assets/4407155/523f1d0a-0725-4a36-9c78-8e6040fdddbe)

Windows 11 build number: 22621.1702 (22H2)
ExplorerPatcher version: 22621.1555.55.1

**Comment by pyrates999** [comment] 2023-06-03 09:17
Duplicate of this https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Vipin2003** [comment] 2023-06-03 10:01
> 

Try to add these shortcuts here:
"C:\ProgramData\Microsoft\Windows\Start Menu\Programs"

This is another place where Start Menu apps resides.

**Comment by SuchyYT** [comment] 2023-06-06 15:42
But it's still missing some apps, Vipin2003

**Comment by Vipin2003** [comment] 2023-06-06 15:47
Apps like what??

**Comment by origintopleft** [comment] 2023-06-08 00:15
Apps like "anything built with UWP". And in order for your proposed solution to be a viable long term workaround, I would have to move all existing shortcuts from my per-user directory over, delete that per-user directory, and then create a symbolic link, the last step being very complex to achieve without a third party helper program. Not a fix.

I'm not 100% sure it's a total duplicate of #1108, either. Sure, the effects from #1108 are present, but #1108 specifically refers to UWP items, whereas I'm missing some Win32 applications as well. The good news is, #1108 was put up by valinet himself, so at least we know he's aware of the situation.

**Comment by pyrates999** [comment] 2023-06-08 08:43
It is a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1108.
You need to wait for a fix.

**Comment by origintopleft** [comment] 2023-07-26 17:06
The new update has fixed the effects of #1108, but I'm still missing *all* of the Win32 programs with shortcuts in the root of the Start Menu directory. See? I knew it was a different bug.

**Comment by SuchyYT** [comment] 2023-07-26 21:29
It's just apps installed from MS Store don't show up. Other apps are showing up.

MS store = **M**icro**s**oft Store

**Comment by Vipin2003** [comment] 2023-07-26 22:55
Uninstall Eap and install latest EP 1992 from github.  Fixed on latest build of EP

**Comment by SuchyYT** [comment] 2023-07-26 23:04
> Uninstall Eap and install latest EP 1992 from github. Fixed on latest build of EP

What's Eap and EP?

**Comment by Vipin2003** [comment] 2023-07-26 23:51
> > Uninstall Eap and install latest EP 1992 from github. Fixed on latest build of EP
> 
> What's Eap and EP?

EP means ExplorerPatcher... Uninstall it completely

**Comment by Amrsatrio** [comment] 2023-10-06 00:15
Fixed in the latest prerelease. Note that the first time an object in explorer is pinned, this may happen:
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/8bd959c2-f303-4993-b01a-76259f57500c)

In this case you can unpin it and pin again which will always work. I try to find a fix for this.

**Closed by Amrsatrio** 2023-10-06 00:15 UTC
