### ISSUE TITLE
explorer.exe loop after KB5029335 update Windows 11 21H2

### ISSUE THREAD

**Issue by patryn32** [valinet/ExplorerPatcher#2024] opened 2023-09-08 09:24 UTC
After the last windows update  explorer.exe  goes into a restarting loop

Windows version
Windows 11 21H2 compilation 22000.2176

After  uninstalling the update KB5029335 the problem is solved

**Comment by pyrates999** [comment] 2023-09-08 10:32
That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029332-os-build-22000-2360-preview-8f8aec64-77b4-4225-9a0f-f0153204ae28

Don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.

**Comment by aldeniangman** [comment] 2023-09-08 23:52
i am on canary build
But i also have a problem

**Comment by greatpotoo** [comment] 2023-09-09 08:33
I'm on:
Edition	Windows 11 Home
Version	22H2
Installed on	‎31/‎10/‎2022
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

with "Get the latest updates as asson as they're available" on OFF and have the same issue - explorer patcher restarting loop

I have 2023-08 Cumulative Update Preview... (KB5029351) is available for download and install message but did not update to that version

**Comment by pyrates999** [comment] 2023-09-09 09:33
> I have 2023-08 Cumulative Update Preview... (KB5029351) is available for download and install message but did not update to that version

Very good.

If the crash is happening when you right click on the taskbar, it is already reported here: https://github.com/valinet/ExplorerPatcher/issues/1828

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

If opening a new File Explorer window crashes explorer.exe, it is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1942

work around: In ExplorerPatcher Properties, Go to File Explorer > and set Management Interface to Windows 10 instead of Windows 11.

Please close this if either one is the answer.

**Comment by iamstevedavis** [comment] 2023-09-11 04:25
@pyrates999 

> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

This fixed for me. It has been crashing when I right click the task bar for weeks. TY

**Comment by d-s-blade** [comment] 2023-09-13 13:26
> > I have 2023-08 Cumulative Update Preview... (KB5029351) is available for download and install message but did not update to that version
> 
> Very good.
> 
> If the crash is happening when you right click on the taskbar, it is already reported here: #1828
> 
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"
> 
> If opening a new File Explorer window crashes explorer.exe, it is a duplicate of: #1942
> 
> work around: In ExplorerPatcher Properties, Go to File Explorer > and set Management Interface to Windows 10 instead of Windows 11.
> 
> Please close this if either one is the answer.

One question：how can i open ExplorerPatcher Properties while every right click on the taskbar takes a crash？
I truly hope to fix this.
and i install the ExplorerPatcher as shell extension，I even cannot find it in taskmgr.
The right click crash changed my operation habits and makes me crazy！

**Comment by iamstevedavis** [comment] 2023-09-13 15:19
> > > I have 2023-08 Cumulative Update Preview... (KB5029351) is available for download and install message but did not update to that version
> > 
> > Very good.
> > 
> > If the crash is happening when you right click on the taskbar, it is already reported here: #1828
> > 
> > Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"
> > 
> > If opening a new File Explorer window crashes explorer.exe, it is a duplicate of: #1942
> > 
> > work around: In ExplorerPatcher Properties, Go to File Explorer > and set Management Interface to Windows 10 instead of Windows 11.
> > 
> > Please close this if either one is the answer.
> 
> One question：how can i open ExplorerPatcher Properties while every right click on the taskbar takes a crash？
> I truly hope to fix this.
> and i install the ExplorerPatcher as shell extension，I even cannot find it in taskmgr.
> The right click crash changed my operation habits and makes me crazy！

Start > type explorer > explore patcher properties will appear. Open this and make changes.

**Comment by pyrates999** [comment] 2023-09-13 21:56
> > > I have 2023-08 Cumulative Update Preview... (KB5029351) is available for download and install message but did not update to that version
> > 
> > 
> > Very good.
> > If the crash is happening when you right click on the taskbar, it is already reported here: #1828
> > Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"
> > If opening a new File Explorer window crashes explorer.exe, it is a duplicate of: #1942
> > work around: In ExplorerPatcher Properties, Go to File Explorer > and set Management Interface to Windows 10 instead of Windows 11.
> > Please close this if either one is the answer.
> 
> One question：how can i open ExplorerPatcher Properties while every right click on the taskbar takes a crash？ I truly hope to fix this. and i install the ExplorerPatcher as shell extension，I even cannot find it in taskmgr. The right click crash changed my operation habits and makes me crazy！

to run the explorer patcher properties application, run this from the run menu:
C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI

Then go to advanced and make sure the option **Do not change the taskbar context menu (e.g. do not display the "Properties"** is not enabled. Then you can right click on the taskbar and you should see the **Properties** option.

**Comment by tallman69** [comment] 2023-09-14 17:08
> to run the explorer patcher properties application, run this from the run menu:
C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI

You can also start typing `properties (explorerpatcher)` into the start menu search box and click on `Properties (ExplorerPatcher)` in the search results to run the EP properties application.

**Comment by Poopooracoocoo** [comment] 2023-09-23 03:46
Leave a comment or open a new issue if you still see this with the new EP version. Include your EP version and OS build.

**Closed by Poopooracoocoo** 2023-09-23 03:46 UTC
