### ISSUE TITLE
Windows 11 context menu broken

### ISSUE THREAD

**Issue by BlackAnt1968601851** [valinet/ExplorerPatcher#2292] opened 2023-10-12 08:31 UTC
I am using ExplorerPather Version 22621.2361.58.4 and windows 11 build 22621.2361
and the normal context menu for explorer and desktop crashes explorer completely but if I use the old context menu it works fine only crashes on the newer context menu.
This is easy to replicate install explorer patcher and disable the option called "Disable the Windows 11 context menu"
and try to right click desktop or anywhere in file explorer.
has a 100% rate of replication.

**Comment by Amrsatrio** [comment] 2023-10-12 09:06
Please enable the new command bar if you want to use the new context menu. We have no plans yet making the new context menu work with the old command bar.

**Comment by pyrates999** [comment] 2023-10-12 12:14
If it causes a crash, then upon installing EP, it should disable that option.  And if you try to enable that option, it should prevent you from enabling it.

**Comment by Amrsatrio** [comment] 2023-10-17 07:02
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218. I'll close this to clean the list up.

**Closed by Amrsatrio** 2023-10-17 07:02 UTC
Labels: Crash

**Comment by Gandalf58** [comment] 2023-10-17 09:38
> Please enable the new command bar if you want to use the new context menu. We have no plans yet making the new context menu work with the old command bar.


You mean we have to use the Win 11 taskbar?
