### ISSUE TITLE
Windows Explorer restarts when I right click the Windows 10 taskbar on Windows 11

### ISSUE THREAD

**Issue by ghaaribapu** [valinet/ExplorerPatcher#1952] opened 2023-08-28 00:39 UTC
Hi. This issue has been existing since couple previous builds where I right click on the taskbar and instead of bringing up the menu, it refreshes the Windows Explorer. Can you please look into it and fix it.

**Comment by yhl10000** [comment] 2023-08-28 01:42
The description is vague, no details.
After Microsoft August update, the Ep will crash if you right-click on task bar, now **this** issue was fixed, if you haven't install the latest one, please try it.

**Comment by Poopooracoocoo** [comment] 2023-08-28 01:56
>After Microsoft August update, the Ep will crash if you right-click on task bar, now this issue was fixed, if you haven't install the latest one, please try it.

What commit says that? :/

But yes, could you please state your EP version and OS build?

Likely duplicate of #1805 (crash only happens when you right click with the Windows 11 taskbar)

**Comment by yhl10000** [comment] 2023-08-28 02:20
![image](https://github.com/valinet/ExplorerPatcher/assets/574037/9bb0cbeb-4a32-4bc9-9342-76d83c18b317)

**Comment by Poopooracoocoo** [comment] 2023-08-28 03:21
Are you using the Windows 10 or Windows 11 taskbar?

**Comment by yhl10000** [comment] 2023-08-28 05:15
> Are you using the Windows 10 or Windows 11 taskbar?
Be curous about that does anyone install EP on Windws 10? My OS is win 11, I hate the taskbar on Win 11, that's why I use EP.
![image](https://github.com/valinet/ExplorerPatcher/assets/574037/bd22e34a-6c6f-415a-8e64-2ea3afeee808)

By the way, what does 'What commit says that? :/' ? which commit of the EP which fixed the right-click-crush?

**Comment by Roobyx** [comment] 2023-08-28 06:17
> The description is vague, no details. After Microsoft August update, the Ep will crash if you right-click on task bar, now **this** issue was fixed, if you haven't install the latest one, please try it.

Its vague, but this issue has been mentioned a ton of times the past month and it still persists. There's a lot of explanation going around in the other issues. Mark it as a duplicate.

**Comment by Poopooracoocoo** [comment] 2023-08-28 09:02
I'm not sure if there's an issue tracking right-clicking on the Windows 10 taskbar crashing Explorer on Windows 11.

**Comment by pyrates999** [comment] 2023-08-28 10:43
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by Drixer** [comment] 2023-08-31 15:30
This is different than [1828](https://github.com/valinet/ExplorerPatcher/issues/1828) since it only happens when the taskbar style is set to Windows 10 so it should be reopened.

I've include the settings and version information in the attached screenshots to indicate that it still happens with the  "Do not change the taskbar context menu". ticked.

![Screenshot 2023-08-31 084754](https://github.com/valinet/ExplorerPatcher/assets/20618154/ee24919e-9767-46c0-9e28-07f20451e4e2)
![Screenshot 2023-08-31 084845](https://github.com/valinet/ExplorerPatcher/assets/20618154/5fc67581-6b36-4ebe-a8e1-e2c629792af5)
![Screenshot 2023-08-31 084920](https://github.com/valinet/ExplorerPatcher/assets/20618154/1bf6fb7e-d6ea-4f75-9ac7-b5f11c5053e0)

**Comment by pyrates999** [comment] 2023-09-01 07:43
You don't have symbols set to download.  Enable them and wait for the notification that symbols have been downloaded.

**Comment by Drixer** [comment] 2023-09-02 14:10
> You don't have symbols set to download. Enable them and wait for the notification that symbols have been downloaded.

Yeah this fixed it. Maybe a little icon or something next to the options that require symbols would be helpful.

**Comment by TheTimmaeh** [comment] 2023-09-03 11:15
> You don't have symbols set to download. Enable them and wait for the notification that symbols have been downloaded.

This didn't work for me. I reinstalled the latest version as mentioned [here](https://github.com/valinet/ExplorerPatcher/issues/1828#issuecomment-1675937607), waited for the notification that symbols have been downloaded. Everything seems to work fine until I change settings like Taskbar style.

**Comment by pyrates999** [comment] 2023-09-03 23:01
> > You don't have symbols set to download. Enable them and wait for the notification that symbols have been downloaded.
> 
> Yeah this fixed it. Maybe a little icon or something next to the options that require symbols would be helpful.

It would be redundant since everything EP does requires the symbols to be downloaded to work.

**Comment by pyrates999** [comment] 2023-09-03 23:03
> > You don't have symbols set to download. Enable them and wait for the notification that symbols have been downloaded.
> 
> This didn't work for me. I reinstalled the latest version as mentioned [here](https://github.com/valinet/ExplorerPatcher/issues/1828#issuecomment-1675937607), waited for the notification that symbols have been downloaded. Everything seems to work fine until I change settings like Taskbar style.

Make sure it is the latest release you're installing: https://github.com/valinet/ExplorerPatcher/releases

**Closed** 2023-09-23 05:21 UTC
