### ISSUE TITLE
Windows 11 Command Bar (classic Address bar) doesn't work

### ISSUE THREAD

**Issue by Lambholl** [valinet/ExplorerPatcher#3160] opened 2024-04-23 09:42 UTC
As the title said, it doesn't work.
Windows 11 23H2 22631.3155
EP version 22621.3296.64.1
![image](https://github.com/valinet/ExplorerPatcher/assets/55140169/dd92c1f1-beaf-45ac-82bc-49ea18ce458c)

**Comment by Lambholl** [comment] 2024-04-23 09:58
I've uninstalled an update to return to 22H2 22621.3155, but it still doesn't work.

**Comment by pyrates999** [comment] 2024-04-23 12:28
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2701

Please close this.

**Closed** 2024-04-23 13:02 UTC
