### ISSUE TITLE
laptop screen indicators for Volume and Brightness missing since Win11 update of aug. 2023 

### ISSUE THREAD

**Issue by SouthernHeftruck** [valinet/ExplorerPatcher#1838] opened 2023-08-12 19:10 UTC
Windows 11 update KB5029263 : the screen indicators for Volume and  Brightness control on laptops do not appear anymore when the appropriate key combination  (Fn+a Function key)  is used. The same problem as 4 or 5 month ago. Uninstalling the update is the solution for now. Or uninstalling Explorer Patcher....

**Comment by mattos123** [comment] 2023-08-13 00:25
yes, something about the overlay seems to always change...

**Comment by pyrates999** [comment] 2023-08-13 00:56
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1692

Please close this one.

**Comment by fireclod833** [comment] 2023-08-13 06:39
> duplicate of: #1692
> 
> Please close this one.

No, @pyrates999. Issue #1692 is for KB5028185, which was in July. The reported issue here is for KB5029263, which is August. Also, the issue you referenced was disputed in the comments as being a "preview" whereas the one here is a mandatory standard update.

**Comment by FoldZero** [comment] 2023-08-13 10:40
i uninstalled KB5029263 - still no volume sliders
"This security update includes improvements that were a part of update [KB5028254](https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8) (released July 26, 2023)."
So I uninstalled KB5028254  - restarting will find out in a minute

**Comment by pyrates999** [comment] 2023-08-13 22:15
> > duplicate of: #1692
> > Please close this one.
> 
> No, @pyrates999. Issue #1692 is for KB5028185, which was in July. The reported issue here is for KB5029263, which is August. Also, the issue you referenced was disputed in the comments as being a "preview" whereas the one here is a mandatory standard update.
> 
> Edit1: I should mention that I now have the issue described here after updating to KB5029263 yesterday. The main two differences between what was reported above is that I'm on a desktop, and my keyboard does not have a 'Fn' key; instead it has dedicated keys for volume and such.
> 
> ![image](https://user-images.githubusercontent.com/116980373/260285337-8a296c5d-750b-4b93-90a3-78a412f62d91.png)
> 
> Edit2: I can confirm that uninstalling KB5029263 as mentioned in the opening post does indeed restore the volume popup:
> 
> ![image](https://user-images.githubusercontent.com/116980373/260286417-540caa49-439c-4bd3-98b4-d49793f96522.png)

Same result was happening, so I go back to the first issue that it was filed under.  Please close this.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:39
Closing in favour of #1692

**Closed by Poopooracoocoo** 2023-08-22 10:39 UTC
