### ISSUE TITLE
Task View not Working with the lastest update.

### ISSUE THREAD

**Issue by brx6995** [valinet/ExplorerPatcher#1851] opened 2023-08-14 14:06 UTC
The Task View is no longer functioning with the latest update. I have tried reverting to an old version where it did work and it would no longer function in those versions either. When I switch to Windows 11 Task Bar then I can click the Task view icon and it works. As soon as I switch back to Windows 10 taskbar task view stops working.

**Comment by mikeazurek** [comment] 2023-08-14 14:20
I'm having same issue

**Comment by bathindahelper** [comment] 2023-08-14 14:22
me too. On Winver 22621.1992 and EP can be of any version now released in last 3-4 months. Result is same. Right clicking taskbar crashes explorer. TaskView and Volume Up Down by mouse wheel doesn't work. Sometimes Alt+tab also gives problems. 

All this started happening when I updated windows with windows KB5029263 update (and also perhaps KB5028948). Now even after uninstalling these updates isn't helping solve these problems.

**Comment by casio88** [comment] 2023-08-15 01:11
![image](https://github.com/valinet/ExplorerPatcher/assets/35287729/b9fb9e80-e11d-47ab-8e24-7acc177d42eb)
face the same problem, after update the latest window patch file.

anyone got idea how to solve it? thanks

**Comment by schieco** [comment] 2023-08-15 07:40
I also have the same issue.

**Comment by mnasru** [comment] 2023-08-15 10:50
I also have the same issue... waiting for an update with a fix

**Comment by JCSillero** [comment] 2023-08-15 11:07
Same issue.

**Comment by arikanorh** [comment] 2023-08-15 12:45
Windows 11 Pro
Version: 22H2
OS Build: 22621.2134

ExplorerPatcher
Version 22621.56.1

**Comment by pyrates999** [comment] 2023-08-15 12:52
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

**Comment by AllenSeitz** [comment] 2023-08-15 13:42
My Task View button also no longer works as of the latest update. Neither does alt-tab.

**Comment by AllenSeitz** [comment] 2023-08-15 13:45
> duplicate of: #1828
> 
> Please close this one.

No this is not a duplicate. User casio88 seems to be posting about #1828 in this thread, which is the wrong place. But the original post is about a very different issue.

**Comment by konrad79** [comment] 2023-08-15 18:56
Same problem. Alt+Tab not working.
Win 11
22621.2134

**Comment by pyrates999** [comment] 2023-08-15 22:39
> > duplicate of: #1828
> > Please close this one.
> 
> No this is not a duplicate. User casio88 seems to be posting about #1828 in this thread, which is the wrong place. But the original post is about a very different issue.

You're right.  It is actually a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

**Comment by Alice8Flandre** [comment] 2023-08-20 07:37
Same problem.
My PC Environment: Windows 11
Explorer Patcher Version: 22621.1992.56.1
This problem occurs with the following settings.
Taskbar>Taskbar Style* : Windows 10

**Comment by PersimmonApricot** [comment] 2023-08-20 18:34
FYI, it appears that alt-tab works until you click on the Task View.  A reboot seems to reset alt-tab to working again.
Also, thank you for creating Explorer Patcher. It is too bad MS can't give us options like they used to.  They are becoming Apple.
Now get this fixed! :-)

**Comment by pyrates999** [comment] 2023-08-20 22:06
Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

**Comment by sinnoaria** [comment] 2023-08-21 04:29
Tried the workaround, but now I get the file explorer crash whenever I right click the task bar and it wants me to uninstall explorer patcher.

**Comment by pyrates999** [comment] 2023-08-21 04:39
Possible fix for the crash: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by Alice8Flandre** [comment] 2023-08-21 07:53
I tried those methods but none of them could remedy this problem.
Alt+Tab: Not Effect. (In the first place, it is not a keyboard shortcut for calling the task view.)
Windows 11 Style: Confirmed that this issue does not occur. However, this setting does not allow the taskbar to be placed on the left.
"Do not change the taskbar context menu": Not Effect.

**Comment by pyrates999** [comment] 2023-08-21 10:43
Until this is fixed, the work around is to set to use windows 11 taskbar instead of windows 10 taskbar.

**Comment by Poopooracoocoo** [comment] 2023-08-22 09:45
Closing as duplicate of #1687 and #1802

**Closed by Poopooracoocoo** 2023-08-22 09:45 UTC
