### ISSUE TITLE
bitdefender discovers a trojan in latest explorerpatcher

### ISSUE THREAD

**Issue by MrEDIAS** [valinet/ExplorerPatcher#3698] opened 2024-09-14 07:58 UTC
bitdefender finds trojan in latest (22621.3880.66.5) explorerpatcher while trying to download EP_setup.exe pc download.
Please see attached .jpeg file showing the discovery of the infected file.
r/ Mr. EDIAS
Where; Everyday Is A Saturday... 

![2024-09-11 Ep-setup problem](https://github.com/user-attachments/assets/0aa0b7ee-f2d1-4a82-97b2-385b91c18d12)

**Comment by pyrates999** [comment] 2024-09-14 08:48
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges.

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active.

**Closed** 2024-09-14 12:04 UTC
