### ISSUE TITLE
KB5034204 breaks "classic Address Bar" option

### ISSUE THREAD

**Issue by LesFerch** [valinet/ExplorerPatcher#2749] opened 2024-01-26 05:43 UTC
After KB5034204 (OS Builds 22621.3085 and 22631.3085) is installed, the "Windows 11 Command Bar (classic Address Bar)" option no longer works.

**Comment by Amrsatrio** [comment] 2024-01-26 06:39
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2701

**Closed** 2024-01-26 06:39 UTC
