### ISSUE TITLE
Search bar not working in full screen mode.

### ISSUE THREAD

**Issue by CrossyAtom46** [valinet/ExplorerPatcher#1804] opened 2023-08-09 15:11 UTC
Hi, thanks for this good app. I love live titles and full screen start menu since Windows 8.1. when i type something on start menu it's not showing the search bar / screen but when i press to enter it can use (like searching on web or app).

**Comment by pyrates999** [comment] 2023-08-09 20:53
Is it this? https://github.com/valinet/ExplorerPatcher/issues/1781

**Comment by CrossyAtom46** [comment] 2023-08-10 03:05
> Is it this? https://github.com/valinet/ExplorerPatcher/issues/1781

Nope
Search bar working but not showing.
Example when i press random keys then enter it's searchs on web. Or typing google chrome opens chrome, but not showing the search bar just shows the Fullscreen start menu

**Comment by pyrates999** [comment] 2023-08-10 12:39
Try uninstalling explorer patcher, reboot, and then see if it is still happening.

**Comment by CrossyAtom46** [comment] 2023-08-12 17:08
> Try uninstalling explorer patcher, reboot, and then see if it is still happening.

not worked and sorry for late respond

**Comment by pyrates999** [comment] 2023-08-13 00:44
Not a bug in explorer patcher then.  Try these steps and close this: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/fix-problems-in-windows-search

**Comment by CrossyAtom46** [comment] 2023-08-13 14:38
> Not a bug in explorer patcher then as you said it occurs when explorer patcher is not installed. Try these steps and close this: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/fix-problems-in-windows-search
i did all of these steps but still search box not showing on full screen windows 10 start menu. But i can still show it with Windows + S key or with normal w10 start menu

**Comment by pyrates999** [comment] 2023-08-13 22:23
Please close this as it is not a bug in explorer patcher and continue troubleshooting on your own for how to fix search.

**Comment by CrossyAtom46** [comment] 2023-08-14 04:32
> Please close this as it is not a bug in explorer patcher and continue troubleshooting on your own for how to fix search.

Off you are not understand me. But idc any more

**Closed** 2023-08-14 04:32 UTC
