### ISSUE TITLE
Unable to download after closing McAfee and MS Defender

### ISSUE THREAD

**Issue by CinnamorollDing** [valinet/ExplorerPatcher#3794] opened 2024-10-13 04:05 UTC
Um, like I tried all of you guys' methods but I STILL CAN'T DOWNLOAD IT!!!!!! I SHUT OFF McAfee and MS Defender, but I STILL CAN'T DOWNLOAD IT. 
### Couldn't Download- Virus Detected
It was still the same... after I shut the whole antivirus down.
EVEN POWERSHELL DID NOT WORK.
![Screenshot 2024-10-13 120522](https://github.com/user-attachments/assets/fdacf786-07ee-4720-9831-9f175bfe76fb)

**Comment by CinnamorollDing** [comment] 2024-10-13 04:06
Help. HELP. HELLLLLLLLLLLLLP!

**Comment by milesprower2293** [comment] 2024-10-13 07:07
Duplicate of #3228

**Also please read the warning before downloading ExplorerPatcher**

**Closed by milesprower2293** 2024-10-13 07:07 UTC
