### ISSUE TITLE
Norton flags Heur.AdvML.CFull

### ISSUE THREAD

**Issue by TimTechToo** [valinet/ExplorerPatcher#3678] opened 2024-09-11 18:46 UTC
Filename: Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe
Threat name: Heur.AdvML.CFull
Path: C:\Users\twarn\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

On computers as of 
9/11/2024 at 2:35:02 PM

Last Used 
9/11/2024 at 2:37:18 PM

Startup Item 
No
Launched 
No
Threat type: Heuristic Virus. Detection of a threat based on malware heuristics.

Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exeThreat name: Heur.AdvML.C
Locate

Few Users
Hundreds of users in the Norton Community have used this file.

New
This file was released 8 days  ago.

High
This file risk is high.

____________________________

Source: External Media

Source File: 
Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

Infected file: C:\Users\twarn\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exeRemoved

File Thumbprint - SHA:
1c4e1847c722db18d58216c43aa40ad87c8a38aa6196e69d55c0687b8506bf94
File Thumbprint - MD5:
0b77feef8ea361e3bc287e61fd2555a3

**Comment by devxzero** [comment] 2024-09-11 18:52
https://www.virustotal.com/gui/file/1c4e1847c722db18d58216c43aa40ad87c8a38aa6196e69d55c0687b8506bf94
34/73 security vendors flagged this file as malicious, including major companies: Microsoft, BitDefender, Avast, Google, McAfee, AVG.

**Comment by devxzero** [comment] 2024-09-11 18:55
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3670

**Closed** 2024-09-11 19:27 UTC
