### ISSUE TITLE
Any option in System tray doesnt do anything

### ISSUE THREAD

**Issue by xFr0z3n** [valinet/ExplorerPatcher#3439] opened 2024-06-29 20:22 UTC
So basically changing something in the System Tray settings doesnt do anything also nothing happens if i restart windows. 
(for example wanted to remove control center button but nothing changes)  Windows 11 Pro and newest ExplorerPatcher version.

**Comment by pyrates999** [comment] 2024-06-29 21:11
You can drag and drop the icon in the system tray to the popup menu that you don't want shown.

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this.

**Closed** 2024-06-30 09:52 UTC
