### ISSUE TITLE
Weather widget randomly getting replaced by contacts

### ISSUE THREAD

**Issue by Flinticarft** [valinet/ExplorerPatcher#3226] opened 2024-05-03 23:37 UTC
This is how the problem looks like:
![image](https://github.com/valinet/ExplorerPatcher/assets/129693141/c0329273-4f96-46ae-afc5-c9d75e27d200)
![image](https://github.com/valinet/ExplorerPatcher/assets/129693141/2c465a93-acd1-4126-8a43-812435513b49)

I'm running W11 23H2 Build 22631.3527.
![image](https://github.com/valinet/ExplorerPatcher/assets/129693141/167cba5c-6f6d-44e6-a646-84934a63870b)

These are my EP settings (ver 22621.3527.65.2):
![image](https://github.com/valinet/ExplorerPatcher/assets/129693141/62a6516b-229e-49ce-9e8d-b2686e1a27ff)
![image](https://github.com/valinet/ExplorerPatcher/assets/129693141/b53f05cf-77eb-4e43-8d6b-a375be12c4ab)
![image](https://github.com/valinet/ExplorerPatcher/assets/129693141/a9fc226b-963a-4e15-b0fe-6d70fed9ddd6)
![image](https://github.com/valinet/ExplorerPatcher/assets/129693141/1ff109f8-c62b-40ae-913f-7fb7e7547d5e)
![image](https://github.com/valinet/ExplorerPatcher/assets/129693141/63418ea1-f610-441b-86f1-ee906b3f8adc)

I do not have any other software modding the UI

**Comment by pyrates999** [comment] 2024-05-04 07:36
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2010

please close this.

**Closed** 2024-05-04 21:21 UTC
