### ISSUE TITLE
Using Windows 10 alt-tab style crashes under certain conditions

### ISSUE THREAD

**Issue by trollcop** [valinet/ExplorerPatcher#491] opened 2021-12-01 23:29 UTC
Using latest (as of today) version.
Open a couple windows.
Alt-tab to get a list, press tab once/twice to advance, then press shift-tab to go backwards. When the selector passes through the last item in the list, explorer crashes.

This may or may not have something to do with "include desktop" (its enabled) in the alt-tab list settings.
![image](https://user-images.githubusercontent.com/4640472/144330697-4054a52b-80ca-416b-8c9e-0aea07e0fec6.png)

**Comment by valinet** [comment] 2021-12-01 23:34
Too generic of a description, as everything else here lately.

> Alt-tab to get a list, press tab once/twice to advance, then press shift-tab to go backwards. When the selector passes through the last item in the list, explorer crashes.
It does not happen on my side. Define a specific use case, confirm that and tell me how to reproduce it.

**Comment by trollcop** [comment] 2021-12-02 01:54
Hm, it definitely occurs for me. I'm on multi-monitor, if that makes any difference.
Exact steps to reproduce:
1) Alt-tab
2) Keep holding alt
3) press and hold shift, press tab to go "backwards" in the window list.
4) When it goes over the last item, all previews become blank and explorer crashes.

**Comment by valinet** [comment] 2021-12-02 02:00
Use these instructions: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps to enable full crash dumps, collect one, upload it somewhere and post a link here please, so I can take a look and see what it does, maybe I figure it out... Also, tell me the exact version of EP that you are using. Other than that, you could also try attaching with a debugger (WinDbg for example) and see where it crashes.

**Comment by valinet** [comment] 2021-12-05 02:15
Latest commits have drastically rearchitected this window switcher, for the better. Maybe the problem is solved now. Please test that, hopefully it's better, and I will close this for now. Thanks.

**Closed by valinet** 2021-12-05 02:15 UTC

**Comment by trollcop** [comment] 2021-12-12 11:57
I didn't realize there were pre-releases of this stuff and was waiting for a release for like a week, then I clicked /releases page and saw there was recent stuff posted.

I can confirm this bug no longer appears, both with "show desktop" enabled in alt-tab switcher and with it off.

Thanks!

**Comment by valinet** [comment] 2021-12-12 12:28
Thanks for the report, that’s good to hear. Once a pre-release stabilizes and seems to have most, if not all of its quirks solved, it will be promoted to a release and rolled out to all the users. This  is a way to do a bit of testing before pushing an update to all users, since the program has grown pretty large now, so there are a lot of things that may break with each update if not polished carefully.
