### ISSUE TITLE
The right-click taskbar has incomplete translation

### ISSUE THREAD

**Issue by Dreamry2C** [valinet/ExplorerPatcher#3907] opened 2024-11-09 20:13 UTC
![image](https://github.com/user-attachments/assets/0d21810f-2d48-435e-be7b-5eef0f4fb32a)
![image](https://github.com/user-attachments/assets/3d055313-e37f-4161-99a3-adc4499e20d8)

**Chinese has been set
But you can see that there is only one option which is Chinese**
Can I restore to the original style of win11?

**Comment by pyrates999** [comment] 2024-11-10 03:01
probably related to this: https://github.com/valinet/ExplorerPatcher/issues/3667

**Comment by Dreamry2C** [comment] 2024-11-10 16:23
https://github.com/valinet/ExplorerPatcher/issues/3667#issuecomment-2452702447
Is this it?
But I am using the original win11 style, not the win10 style
![image](https://github.com/user-attachments/assets/4b6d0bbd-e374-4934-b8d3-7b09c6794b26)

**Comment by pyrates999** [comment] 2024-11-11 01:11
ah ok, and in the EP properties application, in taskbar, and you set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**?

**Comment by Amrsatrio** [comment] 2024-11-11 16:04
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3519

**Comment by Amrsatrio** [comment] 2024-11-11 16:05
@pyrates999 Bruh. If you are not sure then just stay silent.

@Dreamry2C We'll include Chinese localization for the taskbar in the next EP release.

**Closed by Amrsatrio** 2024-11-11 16:04 UTC

**Comment by pyrates999** [comment] 2024-11-11 17:45
@Amrsatrio sorry.
