### ISSUE TITLE
How should I remove the underline？

### ISSUE THREAD

**Issue by yzq542397** [valinet/ExplorerPatcher#3416] opened 2024-06-23 13:32 UTC

**Comment by yzq542397** [comment] 2024-06-23 13:33
![54eeff55-a2bb-4751-9cc3-8af74ad36ce9](https://github.com/valinet/ExplorerPatcher/assets/173614254/45b193ab-c668-4c45-843b-9221673cb432)

**Comment by yzq542397** [comment] 2024-06-23 13:39
When I click the volume button, the progress bar has a white border

**Comment by Amrsatrio** [comment] 2024-06-23 14:49
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1448

**Closed by Amrsatrio** 2024-06-23 14:49 UTC
