### ISSUE TITLE
Explorer Patcher crashing my computer during installation

### ISSUE THREAD

**Issue by mjw72652** [valinet/ExplorerPatcher#1195] opened 2023-03-24 16:14 UTC
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1194

<div type='discussions-op-text'>

<sup>Originally posted by **mjw72652** March 24, 2023</sup>
I have been using Explorer Patcher on two computers for a long time- A Dell XPS-8940 Desktop and an MSI GS76 Stealth Laptop. Both have Intel i( 11th Gen CPUs and Run the latest version of Windows 11 Pro with all updates installed. The only difference between them is the amount of RAM- 64 GB vs. 32 GB. I have found the program to restore a lot of functionality that Windows 11 removed.

Because of a problem that could not be solved any other way I had to reset the MSI back to its original factory state with Windows 10 home, then upgrade to Windows 11 Home and then Windows 11 Pro.

In the process of reinstalling all my software (with plenty of restore points created along the way) when I came to Explorer Patcher the install routine suddenly crashed and set my screen to blanking on and off. The only thing I could do was enter the recovery environment- where I found all my restore points were gone. I had to start my whole reset all over again. As soon as I had Windows 11 Pro booting OK, I created a restore point, then tried to install Explorer Patcher again. The same thing happened- blanking screen, no boot. This time I was able to use the restore point to recover.

Has anyone else encountered this, and if so, how did you fix it?</div>

**Comment by redtides99** [comment] 2023-03-26 17:35
same happened to me, no restore point available.
the only way i could find to get rid of the issue, was uninstalling using command prompt (available under the taskmanager --> cmd)
i lost 2 hours to fix this... :/

**Comment by mjw72652** [comment] 2023-03-26 19:00
What gets me is that before I was forced to reinstall Windows, Explorer
Patcher was working perfectly on this computer, and it works perfectly on a
virtually identical computer (same processor, edition of windows, etc.).

**Comment by pyrates999** [comment] 2023-04-13 23:03
this appears to be a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1307

**Closed** 2023-09-23 04:57 UTC
