### ISSUE TITLE
Search bar broken

### ISSUE THREAD

**Issue by portex7000** [valinet/ExplorerPatcher#3107] opened 2024-04-08 12:12 UTC
When i use search as search bar, it is broken. I click on it, it dissapears and opens search menu with search bar on top (acts like search bar is search button) and it dissapears with start menu open as well

**Comment by pyrates999** [comment] 2024-04-08 12:56
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

Please close this.

**Comment by portex7000** [comment] 2024-04-08 14:26
That is not the issue i have. The search bar acts like search button, there is nothing with wrong position.

**Comment by pyrates999** [comment] 2024-04-08 22:03
Please show a screen shot of what you mean.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Closed** 2024-04-11 13:38 UTC

**Comment by ItsKade** [comment] 2024-05-31 06:19
hey why wont they fix this
I saw something about windows deleting the windows 10 taskbar but will I still be able to use the windows 10 taskbar with EP and start menu in the future after this and will this fix be applied if you recreate a windows 10 taskbar also if EP creates their own version of the windows 10 taskbar for ep will we still have all the features that the current ep windows 10 taskbar 

 also commented the same thing on a different thread with the same issue
