### ISSUE TITLE
Select which icons appear on the taskbar not working

### ISSUE THREAD

**Issue by udah1** [valinet/ExplorerPatcher#2706] opened 2024-01-16 19:53 UTC
When in windows 10 style and doing "Customize notification area icons", I am unable to change any icon to always be visible.
I change it and nothing happens. when I close and open it, my settings aren't saved.

![image](https://github.com/valinet/ExplorerPatcher/assets/3235731/4a4d82a3-5710-4fa5-bd72-cde786ddb8db)

**Comment by Amrsatrio** [comment] 2024-01-17 00:18
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1454

**Closed by Amrsatrio** 2024-01-17 00:18 UTC
