### ISSUE TITLE
Task View Failing - Windows 11

### ISSUE THREAD

**Issue by gittimmys** [valinet/ExplorerPatcher#1924] opened 2023-08-24 12:10 UTC
Task View icon appears on taskbar, but fails to function. Removed ExplorerPatcher and Task View functions properly. Re-install ExplorerPatcher and Task View fails.

Windows 11, OS build 10.0.22623.1325
ExplorerPatcher  Version 22621.1992.56.3

**Comment by Poopooracoocoo** [comment] 2023-08-24 12:57
Duplicate of #1687

**Closed by Poopooracoocoo** 2023-08-24 12:57 UTC
