### ISSUE TITLE
systray icon visibility settings are ignored

### ISSUE THREAD

**Issue by vladtepesch** [valinet/ExplorerPatcher#3953] opened 2024-11-21 21:36 UTC
Allthough some Icons are set to forced visibility, this is ignored and the icons are hidden behind the overhang menu:

![grafik](https://github.com/user-attachments/assets/ad723ca1-94a6-443b-b8b1-8dfb25cf1779)

**Comment by milesprower2293** [comment] 2024-11-21 22:01
Duplicate of #1454

**Closed by milesprower2293** 2024-11-21 22:01 UTC
