### ISSUE TITLE
Windows 10 taskbar no longer shows after the update to 23H2

### ISSUE THREAD

**Issue by Exthreal3** [valinet/ExplorerPatcher#2111] opened 2023-09-21 04:02 UTC
Just had windows update + the latest update for explorerpatcher, and now:
1. There's no 'properties' context menu for the taskbar to access the settings
2. Transparancy effects are missing
3. All of my user settings are nullified, back to win 11 taskbar
4. any re-configuration of the settings through manual launching of explorerpatcher properties doesn't change anything.
I've tried restarting, re-installing, and i'm out of ideas :(

**Comment by Poopooracoocoo** [comment] 2023-09-21 04:25
OS Build and EP version? What is "the update"?

As a workaround, you can access EP Properties from the Start Menu and Windows Search.

**Comment by Exthreal3** [comment] 2023-09-21 04:33
Operating System: Windows 11 Home 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)

I tried downgrading to the last version of ExplorerPatcher which I was using last night but yielded the same result, downgrading windows isn't really a possibility for me currently.

The EP Properties in Start Menu is what I was referring to in point '4', the only settings that make any kind of difference are those that manage the window-switcher.

**Comment by Amrsatrio** [comment] 2023-09-21 04:38
Please show your specific Windows build number from Win+R, type `winver`, and then enter.

**Comment by lapo-luchini** [comment] 2023-09-21 04:56
Samere here on `Version 22H2 (OS Build 22621.2359)`.
Will recover standard Explorer by opening task manager and running `C:\Users\lapo\Downloads\ep_setup.exe /uninstall` from there.
Hope to get my beloved bar on the left side as soon as possible. ❤️

**Comment by Amrsatrio** [comment] 2023-09-21 05:24
Is that a new update that has been gradually rolling out to everyone?

**Comment by Exthreal3** [comment] 2023-09-21 06:14
> Please show your specific Windows build number from Win+R, type `winver`, and then enter.

So the winver build is different to dxdiag :s
Version 23H2 (OS Build 22631.2338)

**Comment by Poopooracoocoo** [comment] 2023-09-21 06:49
> Is that a new _non-preview_ update that has been gradually rolling out to everyone?

According to ChangeWindows, OS builds [22631.2338](https://blogs.windows.com/windows-insider/2023/09/12/announcing-windows-11-insider-preview-build-22621-2338-and-22631-2338-beta-channel/) and [22621.2359](https://blogs.windows.com/windows-insider/2023/09/14/releasing-windows-11-build-22621-2359-to-the-release-preview-channel/) are insider preview builds. 22621.2283 is still the latest general availability channel OS build.

**Comment by granterogers** [comment] 2023-09-21 07:33
I can also confirm not working at all on 22621.2283

**Comment by Amrsatrio** [comment] 2023-09-21 07:35
@granterogers For 2283, please wait until Valinet pushes a stable update with my PR inside, or compile [my fork](https://github.com/Amrsatrio/ExplorerPatcher/) yourself (but I won't be responsible for any issues caused).

**Comment by anatoliy-savchak** [comment] 2023-09-21 09:14
Please hurry up, it's getting problematic. And thanks @Amrsatrio !

**Comment by Tarvey** [comment] 2023-09-21 11:29
Can confirm.
For anyone who cannot see anything:
- Open ctrlaltdel and task manager
- file > run
- explorer
- file > run
- control
- after some time the control panel will open
- uninstall explorerpatcher
- (you can also do safemode with command prompt)

**Comment by anatoliy-savchak** [comment] 2023-09-21 12:42
Version 22H2 (OS Build 22621.2283)
When you bring up EP via mouse or win button the EP will bring up but Search Text control cannot be focused into to search an App, not typing anything will find an app.

And please do not mark it as the spam.

**Comment by pyrates999** [comment] 2023-09-21 13:30
> Version 22H2 (OS Build 22621.2283) When you bring up EP via mouse or win button the EP will bring up but Search Text control cannot be focused into to search an App, not typing anything will find an app.
> 
> And please do not mark it as the spam.

Please file what you found as a separate issue.

**Comment by stalmage** [comment] 2023-09-21 16:47
Just to add a symptom to this thread, whenever I start a program by any means (one that brings up a window), ExplorerPatcher will crash one or more times.  Eventually (after starting just a few programs), ExplorerPatcher crashes three times in a row fast enough that it disables itself.

**Comment by Amrsatrio** [comment] 2023-09-21 17:46
@lapo-luchini If you are still on 22621.2359 and haven't updated, it would be very appreciated if you could send me `twinui.pcshell.dll` and `Windows.Internal.HardwareConfirmator.dll` so that I can make my patches better.

**Comment by stalmage** [comment] 2023-09-21 19:06
Update:  my system just downloaded new Windows symbols and ExplorerPatcher is no longer crashing.

**Comment by Daisyfan1995** [comment] 2023-09-21 19:54
Insider Previews are not supported. after build 22631,2129

**Comment by pyrates999** [comment] 2023-09-21 20:40
> Update: my system just downloaded new Windows symbols and ExplorerPatcher is no longer crashing.

EP needs to do this every time after you install a new update.

**Comment by gh-log** [comment] 2023-09-21 22:09
2283 is not Insider Preview.

"EP needs to do this every time after you install a new update."
how to do this?

**Comment by gh-log** [comment] 2023-09-22 00:19
volume popup still not working.

**Comment by Poopooracoocoo** [comment] 2023-09-22 02:46
Please don't use this issue as a catch all. Issues may only be present on certain builds.

**Comment by sinabahram** [comment] 2023-09-22 07:20
I believe I may be experiencing the same issue over here.

Output from running winver:
Version 22H2 (OS Build 22621.2283)

Additional observations, Windows+b, a keystroke I press probably hundreds of times a day is totally broken. Just plays  system bell and doesn't move focus to the system tray. None of my icons are showing up either e.g. Slack, Dropbox, etc.

After symbols downloaded, I can invoke the context menu on the task view button and get to properties, so that part works, but the system tray icons of apps I know are running, no longer show up once EP has been installed, first letter navigation is still broken even if I tab to system tray, etc.

Thanks for any advice and happy to provide any additional info.

**Comment by pyrates999** [comment] 2023-09-22 12:10
> I believe I may be experiencing the same issue over here.
> 
> Output from running winver: Version 22H2 (OS Build 22621.2283)
> 
> Additional observations, Windows+b, a keystroke I press probably hundreds of times a day is totally broken. Just plays system bell and doesn't move focus to the system tray. None of my icons are showing up either e.g. Slack, Dropbox, etc.
> 
> After symbols downloaded, I can invoke the context menu on the task view button and get to properties, so that part works, but the system tray icons of apps I know are running, no longer show up once EP has been installed, first letter navigation is still broken even if I tab to system tray, etc.
> 
> Thanks for any advice and happy to provide any additional info.

It sounds like you got a stuck key on the keyboard.  Try rebooting.

**Comment by lucen-ms** [comment] 2023-09-22 13:14
I can confirm on build 22H2 22621.2361

**Comment by Poopooracoocoo** [comment] 2023-09-22 13:31
even microsoft employees use software to fix windows 11?!

**Comment by lapo-luchini** [comment] 2023-09-22 14:58
> @lapo-luchini If you are still on 22621.2359 and haven't updated, it would be very appreciated if you could send me `twinui.pcshell.dll` and `Windows.Internal.HardwareConfirmator.dll` from System32 so that I can make my patches better.

Yes, I still have that (as reported by "winver").

```
% ll twinui.pcshell.dll Windows.Internal.HardwareConfirmator.dll
-r-xr--r-- 2 lapo lapo 10285056 set 18 21:18 twinui.pcshell.dll
-r-xr--r-- 2 lapo lapo   507904 set 18 21:18 Windows.Internal.HardwareConfirmator.dll
```

(I send them to your commit e-mail)

> I've built a release of my fork with the fixes.

Works for me, thanks!

**Comment by Amrsatrio** [comment] 2023-09-22 15:00
Thanks, and that's great to hear!

**Comment by gh-log** [comment] 2023-09-22 15:52
> 2283 is not Insider Preview.
> 
> "EP needs to do this every time after you install a new update." how to do this?
> 
> just reinstalled EP and seems to be working with 2283. cant right click taskbar properties to access EP properties, menu option not there. so it is a setting now, Advanced, Do not change the taskbar context menu.

why was my comment marked as off topic?

**Comment by gh-log** [comment] 2023-09-22 15:53
> Version 22H2 (OS Build 22621.2283) When you bring up EP via mouse or win button the EP will bring up but Search Text control cannot be focused into to search an App, not typing anything will find an app.
> 
> And please do not mark it as the spam.

why was this message marked as off topic?

**Comment by gh-log** [comment] 2023-09-22 15:55
> volume popup still not working.

why was this marked as off topic? volume popup doesnt work in 2283 even after downloading new symbols .

**Comment by Poopooracoocoo** [comment] 2023-09-22 16:38
> > volume popup still not working.
> 
> why was this marked as off topic? volume popup doesnt work in 2283 even after downloading new symbols .

It's already being tracked in a different issue. The author of this issue is on preview build 22631.2338 and is seeing specific issues.

**Comment by isaacfinnegan** [comment] 2023-09-22 17:03
I have tried the patched fork, and the main release.  Patch seems to have fixed my virtual desktop issues (Thanks @Amrsatrio !!). 
But I set to Windows 11 style to debug another issue, and now I cannot bring up the dialog at all (right clicking on taskbar crashes file explorer) to change it to Windows 10 style (I like ungrouped).

Uninstalling resolves all stability issues, but installing either current build from this repo or @Amrsatrio 's build result in inability to bring up properties at all since file explorer just crashes.

**Comment by Amrsatrio** [comment] 2023-09-22 17:25
@isaacfinnegan You're welcome! I haven't fixed the crashing roght click on Windows 11 taskbar yet since I don't know where did Valinet get the code for managing cascade windows/undo menu items from, but I'll do that next week. For now you can turn on "Do not modify the context menu" or something in the advanced section of EP properties. You can open it through the start menu or `rundll32 C:\Windows\System32\dxgi.dll,ZZGUI`. Apologies for this.

**Comment by isaacfinnegan** [comment] 2023-09-22 17:28
Thanks for the tip @Amrsatrio , but I get 'Missing entry ZZGUI' when I do that.

**Comment by Amrsatrio** [comment] 2023-09-22 17:43
I am sorry, I meant `rundll32 C:\Windows\dxgi.dll,ZZGUI`

**Comment by Amrsatrio** [comment] 2023-09-23 02:21
Although Valinet has pushed a new release to fix task view and stuff on newer builds of 22621, the issues OP mentioned still persists on 22631 and I will keep this open until the taskbar (and potentially other important issues) are fixed.
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/1b431a2a-b1c1-4e6b-b96b-e2a60cba4c88)

**Comment by Daisyfan1995** [comment] 2023-09-23 05:11
> Although Valinet has pushed a new release to fix task view and stuff on newer builds of 22621, the issues OP mentioned still persists on 22631 and the newly released 22621.2361 Release Preview. I will keep this open until the taskbar (and potentially other important issues) are fixed. ![image](https://user-images.githubusercontent.com/20662640/270081727-1b431a2a-b1c1-4e6b-b96b-e2a60cba4c88.png)

EP are not compatible in Windows 11 insider Build (Beta) 22631.2338.
Except in 22621.2283.57.1 or 2 still no working.

**Comment by Amrsatrio** [comment] 2023-09-23 05:13
That is the point, and I am planning to fix the taskbar and other stuff before it hits the masses.

**Comment by Daisyfan1995** [comment] 2023-09-23 05:15
But How it only me work in Build 22631.2115 before in Build 22631.2129 & 22631.2338

**Comment by Amrsatrio** [comment] 2023-09-23 05:16
Because Microsoft pushed features stated here into 22631.2338 and 22621.2361, where the old taskbar doesn't work. https://blogs.windows.com/windows-insider/2023/09/22/rolling-out-new-features-for-windows-11-22h2-to-the-release-preview-channel/

**Comment by pyrates999** [comment] 2023-09-23 12:40
EP is not supported in Insider builds and in Preview updates.

**Comment by Amrsatrio** [comment] 2023-09-23 22:20
Taskbar, done. You can install the latest prerelease to get the old taskbar back. I'll let Valinet make a release version for this one since I'm not sure yet about the versioning.

Though, the Win11 taskbar context is still crashing even after Valinet's commit that fixed it on Moment 3.
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/88721806-eba1-44f9-b484-9c0c82cb3fe0)

**Comment by Daisyfan1995** [comment] 2023-09-23 22:57
> Taskbar, done. You can install the latest prerelease to get the old taskbar back. I'll let Valinet make a release version for this one since I'm not sure yet about the versioning.
> 
> Though, the Win11 taskbar context is still crashing even after Valinet's commit that fixed it on Moment 3. I'll keep this open until it's fixed because OP mentioned about "Properties context menu for the taskbar". ![image](https://user-images.githubusercontent.com/20662640/270135549-88721806-eba1-44f9-b484-9c0c82cb3fe0.png)


Yup, its working. Now.

**Comment by Amrsatrio** [comment] 2023-09-24 22:00
The latest prerelease should fix all the issues mentioned by OP. Closing.

**Closed by Amrsatrio** 2023-09-24 22:00 UTC

**Comment by Amrsatrio** [comment] 2023-09-25 18:26
Should **major** aka **breaking** issues like this happen again, or just want to vibe together, here's a new Discord where you can report them on and expect an instant response (I hope): https://discord.gg/gsPcfqHTD2 ♥️
