### ISSUE TITLE
Volume/Brightness sliders not visible (KB5029263 Build 22621.2134)

### ISSUE THREAD

**Issue by ss6271** [valinet/ExplorerPatcher#1692] opened 2023-07-27 05:37 UTC
When I press the buttons for inc/dec sound and brightness, the pop-up slider does not appear after KB5029263.

Using Windows 10 taskbar
Windows 11 22H2
OS Build 22621.2134

**Edit: 
Workarounds:**
- Option 1: Use [ModernFlyouts](https://modernflyouts-community.github.io/)

- Option 2: Use the Windows 11 taskbar. To show labels on taskbar items, you can use Windhawk, Start11 or StartAllBack (you can disable the custom Start Menus that the latter two have)
   - To fix right clicking on the taskbar crashing Explorer, you can enable "Do not change the taskbar context menu (e.g. do not display the "Properties" item)" in the advanced section of the ExplorerPatcher Properties.

**Comment by pyrates999** [comment] 2023-07-27 10:17
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by bitroniq** [comment] 2023-07-27 11:07
Latest Win11 Pro + Latest Exploer Patcher

Same issues

1. Task View doesn't work
2. sliders (volume etc) doesn't work
3. Alt+TAB doesn't work (after trying Task View)

**Comment by morrow95** [comment] 2023-07-27 15:19
@bitroniq  Win 11 was updated early this morning for me and experiencing exactly the same as you.

Version	10.0.22621 Build 22621

**Comment by TheChrisGlass** [comment] 2023-07-27 15:32
Yup. Same issue. On 22621.19992.56.1

**Comment by pyrates999** [comment] 2023-07-27 20:45
Don't install preview updates if you want explorer patcher to work.

**Comment by bitroniq** [comment] 2023-07-27 20:48
> Don't install preview updates if you want explorer patcher to work.

It's not a preview update!

I only install stable updates

![image](https://github.com/valinet/ExplorerPatcher/assets/1032724/641b99c6-6cc1-4161-b575-3782181d5fdd)

**Comment by pyrates999** [comment] 2023-07-27 20:52
Microsoft says it is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

**Comment by bitroniq** [comment] 2023-07-27 20:53
Well, somehow in Europe they pushed this to a stable channel. As you can see I don't allow installing/upgrading anything considered as preview/insider/etc.

**Comment by gjf** [comment] 2023-07-28 10:47
> Don't install preview updates if you want explorer patcher to work.

![image](https://github.com/valinet/ExplorerPatcher/assets/322186/e2d0347c-1dd6-416a-95e0-d1cceeb2d619)
Where it says it is a preview? Just a latest release.

**Comment by gjf** [comment] 2023-07-28 10:48
> Well, somehow in Europe they pushed this to a stable channel. As you can see I don't allow installing/upgrading anything considered as preview/insider/etc.

Same here. Never install preview updates - however I experience the same problem.

**Comment by pyrates999** [comment] 2023-07-28 16:42
Did the update prompt you to download and install or did it automatically install?

It will also include the word preview in the name of the update.

**Comment by Girofox** [comment] 2023-07-31 08:00
![image](https://github.com/valinet/ExplorerPatcher/assets/43116061/47b7d9b3-c9f7-4b06-9b26-63c3648e87e4)
As you can see in Germany the cumulative update has no word preview in it, but there was a prompt to install though. As far as i can tell all cumulative updates prompt you and never auto install. The only preview upate was for .NET framework.

**Comment by gjf** [comment] 2023-07-31 10:17
Also I have to report this "preview" is very unstable with ExplorerPatcher making Explorer process crash regularly.
So sliders are not the only issue.

**Comment by pyrates999** [comment] 2023-08-01 10:05
Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by Ingo00086** [comment] 2023-08-05 10:08
Hello.

Ich habe das gleiche Problem, war bereits schonmal am 15.03.2023 mit der Version 22621.1344.53.1 der Fall.
Wenn ich die Option "Taskbar Style" von Windows 10 auf 11 umstelle, geht es wieder.

Was ist jetzt der Workaround?
![image](https://github.com/valinet/ExplorerPatcher/assets/99134245/22ec7606-29cf-4485-999a-1fd26c0e846d)
Ich habe keine Vorschau Updates installiert.

Liebe Grüße

**Comment by Ingo00086** [comment] 2023-08-05 10:10
Hallo.

Was ist jetzt der Workaround? Ich habe keine Vorschau Updates installiert.
Welche KB müsste ich jetzt Deinstallieren?

![image](https://github.com/valinet/ExplorerPatcher/assets/99134245/72b3be3d-ca08-4e49-9d0a-84220b9d3026)

Mir ist der Fehler auch mal bereits am 15.03.2023 mit der Version 22621.1344.53.1 aufgefallen, aber darauf hatte ich keine Rückmeldung bekommen, hatte das glaube ich auch mal gemeldet.

Liebe Grüße
Fabian

**Comment by pyrates999** [comment] 2023-08-05 10:21
Please run winver and show us a screen shot of that.  It will show your windows build number.

It should match this: https://support.microsoft.com/en-au/topic/july-11-2023-kb5028185-os-build-22621-1992-605fa18f-bd49-41d8-80b1-245080e26c3d

**Comment by Ingo00086** [comment] 2023-08-05 10:25
Thank. But i have the newster Build, i wait to off the 08.08.2023 Updates:
![image](https://github.com/valinet/ExplorerPatcher/assets/99134245/55717931-46c1-466d-902d-fdfaddb54c89)
See my Edit Answer.

**Comment by pyrates999** [comment] 2023-08-05 10:29
I would look into how to uninstall that preview update then as it is causing this.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

**Comment by pyrates999** [comment] 2023-08-05 10:30
> When I press the buttons for inc/dec sound and brightness, the pop up slider does not appear after the latest window release.

Your KB is wrong in the title.  It is KB5028254.

**Comment by Ingo00086** [comment] 2023-08-05 10:40
Ich habe den Beitrag Link angepasst. Ja das KB5028254 ist schuld. Die Update Einstellung habe ich angepasst, vielen Dank. Da ich bisher nur keine Anzeige bekomme, wenn ich die Lautstärke verändere, warte ich auf ein Update. Mir ist die Anzeige in der Startleiste wichtiger, da dies unter Windows 11 nicht mehr geht :) Danke für deinen Zeit.

![image](https://github.com/valinet/ExplorerPatcher/assets/99134245/08c14240-f002-4fe6-af8c-4141c3ea5aa7)
Beispiel: alle Icons im Systemtray und einen Ordner anhefte mit Menü :)

**Comment by pyrates999** [comment] 2023-08-05 11:55
You're welcome.

**Comment by impeeza** [comment] 2023-08-19 01:44
I have two computers both with the same Windows 11 version and the sliders are missing:
![image](https://github.com/valinet/ExplorerPatcher/assets/41979604/cc290af3-d04c-4681-bf18-ce24107557a4)

Uninstalling the Explorer Patcher the slider come back

![image](https://github.com/valinet/ExplorerPatcher/assets/41979604/5182892b-fcc1-4bf3-8368-21b5554ef17b)

I really don't know if I should put this comment on issue #1838 or both issues should be merged.

**Comment by pickonedev** [comment] 2023-08-22 10:35
I have installed a NON-preview update for windows and volume osd has gone....

https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8

I have installed and customized this app, then I got the flyouts back. It is not a perfect app, but for a temporary workaround...

https://apps.microsoft.com/store/detail/modernflyouts-preview/9MT60QV066RP?hl=en-us&gl=us

**Comment by regs01** [comment] 2023-08-22 16:59
> I have installed and customized this app, then I got the flyouts back. It is not a perfect app, but for a temporary workaround...
> 
> https://apps.microsoft.com/store/detail/modernflyouts-preview/9MT60QV066RP?hl=en-us&gl=us

Thanks for pointing. It's much better than stock one. It's in the edge and it's visible, as original is too small.

Here is GitHub link.
https://github.com/ModernFlyouts-Community/ModernFlyouts

**Comment by impeeza** [comment] 2023-08-23 01:17
you are completely right, on Windows 11 Taskbar style:

![image](https://github.com/valinet/ExplorerPatcher/assets/41979604/e0d8c8dd-0cf5-4577-8308-9f36e9f6bf67)

but once you enable Windows 10 style taskbar, no slider is shown even if your brightness and volume is modified:

![image](https://github.com/valinet/ExplorerPatcher/assets/41979604/31c00468-466d-40f4-888f-9a6604dad82a)

**Comment by pyrates999** [comment] 2023-08-23 12:37
> I HATE 3 things about Windows 11 Taskbar Style:
> 
> 1 - When you have a browser (firefox for example) with many tabs opened, if you click the app from taskbar, it won't switch to the app, instead it will show you the windows of the app, like hovering with the mouse... then you must click the window of the tab you want to see... This is STUPID as hell ![image](https://user-images.githubusercontent.com/34201387/262595111-b820b08e-33a3-4e7c-b82c-b5fce92297d0.png) Edit: A solution for this, maybe someone else needs this, I found a way to solve the first thing, just add a registry [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced] "LastActiveClick"=dword:00000001
> 
> 2. I like the taskbar to show the full size app when it is opened, not only the icon...
>    ![image](https://user-images.githubusercontent.com/34201387/262595789-ba8917a0-8471-4251-bbfe-830cedac5b98.png)
> 3. The fact that you cannot resize start menu or remove completely the recommendation message...
>    ![image](https://user-images.githubusercontent.com/34201387/262618989-c1f947ba-b0da-4195-8ae7-a94be7c5646e.png)
> 
> And about ExplorerPatcher, when I was switching from tasbark 10 to 11 and back, I got this error...
> 
> ![image](https://user-images.githubusercontent.com/34201387/262595664-c5f721e1-3c85-43a2-8793-d1536714c890.png)

The crash was reported here already: https://github.com/valinet/ExplorerPatcher/issues/1828

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by gh-log** [comment] 2023-08-23 17:33
![Screenshot 2023-08-23 183220](https://github.com/valinet/ExplorerPatcher/assets/16019542/3233a1b4-34f6-48b9-a0c9-91d0660e70d5)

no luck with new version. cant see volume OSD.

**Comment by pickonedev** [comment] 2023-08-23 19:25
I have uninstalled ExplorerPatcher and I try to adapt to windows 11 completely....

**Comment by pyrates999** [comment] 2023-08-23 23:07
Work around until this gets fixed: install an application from the microsoft store called "modernflyouts".

**Comment by InteXX** [comment] 2023-08-24 20:26
I can confirm the reports by @cgequi and @gh-log.

In my case, the problem manifested after installing v22621.1992.56.3.

**Comment by ahmet-umut** [comment] 2023-08-25 15:07
Modernflyouts won't work for me. I installed it from microsoft store but when I click the program it does not do anything and the "flyouts" did not change. Any other workaround?

**Comment by aLanaMaunz** [comment] 2023-08-25 17:36
modern flyouts (preview) from MS store fixed everything for me:
![image](https://github.com/valinet/ExplorerPatcher/assets/87087955/3c64ee38-873b-40fa-8506-e131a11ad5ea)

**Comment by pyrates999** [comment] 2023-08-26 11:24
> Modernflyouts won't work for me. I installed it from microsoft store but when I click the program it does not do anything and the "flyouts" did not change. Any other workaround?

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

**Comment by Gedili** [comment] 2023-08-26 13:51
> > Modernflyouts won't work for me. I installed it from microsoft store but when I click the program it does not do anything and the "flyouts" did not change. Any other workaround?
> 
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.

Same problem here. Using the latest release of EP (ZP 22621.1992.56.3) on my laptop and desktop, both on the same Win 11 version (Win 11 Pro - Version 22H2 - Build 22621.2134 ). The standard Windows sound/brightness flyout show up if I set "Taskbar Style" to Win 11 in EP, but not with Win 10 style. 

I was able to use ModernFlyout on the desktop, but not on my laptop, despite being the same build. I tried installing it from Microsoft Store, and from the installer on github, none worked. Also tried uninstalling both ModernFlyout and EP, and reinstalling, didn't work neither (ModernFlyout gets installed, but it won't show the customs flyout, nor open ModernFlyout settings page)?

**Comment by pyrates999** [comment] 2023-08-26 14:56
Then you gotta wait until this gets fixed.

**Comment by pickonedev** [comment] 2023-08-26 17:38
I won't be fixed too soon, or if it will, still... the best solution in this moment, is to use Windows 11 natively and adapt to the standard usability. Think about when we update to xp, then 7, 8, 10, now 11. 

I am using windows without ExplorerPatcher for about 3 days and everything is ok.
I found ways to avoid the most annoying things from windows 11 and I still search for some, but things whih are not so annoying...

This issue has been opened one month ago... this made me optimistik in trying to adapt

**Comment by impeeza** [comment] 2023-08-27 05:07
Setting the taskbar style to Windows 11 allows the slider to show, but the right click on the taskbar crashes the explorer proces ;(

think is related to:
https://github.com/valinet/ExplorerPatcher/issues/1798

**Comment by pyrates999** [comment] 2023-08-28 10:27
> Setting the taskbar style to Windows 11 allows the slider to show, but the right click on the taskbar crashes the explorer proces ;(
> 
> think is related to: #1798

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by alandsidel** [comment] 2023-08-28 15:00
> > Setting the taskbar style to Windows 11 allows the slider to show, but the right click on the taskbar crashes the explorer proces ;(
> > think is related to: #1798
> 
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

Unlikely workaround.  I've always had this ticked.

**Comment by pyrates999** [comment] 2023-08-30 05:15
> > > Setting the taskbar style to Windows 11 allows the slider to show, but the right click on the taskbar crashes the explorer proces ;(
> > > think is related to: #1798
> > 
> > 
> > Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"
> 
> Unlikely workaround. I've always had this ticked.

The possible fix is for the crash you are experiencing.

**Comment by RolandYip** [comment] 2023-09-01 09:38
> When I press the buttons for inc/dec sound and brightness, the pop up slider does not appear after the latest window release.
> 
> **Edit: Workarounds:**
> 
> * Option 1: Use [ModernFlyouts](https://modernflyouts-community.github.io/)
> * Option 2: Use the Windows 11 taskbar. To show labels on taskbar items, you can use Windhawk, Start11 or StartAllBack (you can disable the custom Start Menus with the latter two)
>   
>   * To fix right clicking on the taskbar crashing Explorer, you can enable "Do not change the taskbar context menu (e.g. do not display the "Properties" item)" in the advanced section of the ExplorerPatcher Properties.

Tks worked!!

**Comment by saulob** [comment] 2023-09-03 19:34
Still this bug for me in the last version

**Comment by Amrsatrio** [comment] 2023-09-23 01:25
Fixed in 22621.2283.57.1.

**Closed by Amrsatrio** 2023-09-23 01:25 UTC

**Comment by regs01** [comment] 2023-09-23 10:27
With ModernFlayouts I can use both now

**Comment by Ingo00086** [comment] 2023-09-24 00:26
Hallo. 

Ich wollte ein Feedback geben, dass es nun wieder geht.
Nach Update ExplorerPatcher 22621.2283.57.2 mit Windows 11 22H2 Build 22621.2283 wurde der Bug mit Helligkeit/Lautstärke HUD-Anzeige behoben!

Dankeschön :)

**Comment by regs01** [comment] 2023-09-27 20:28
> With ModernFlayouts I can use both now

I can see* When using ModernFlayouts system popup is also visible.

**Comment by pyrates999** [comment] 2023-09-28 00:59
> > With ModernFlayouts I can use both now
> 
> I can see* When using ModernFlayouts system popup is also visible.

Since it's been fixed, you no longer need ModernFlayouts installed.

**Comment by regs01** [comment] 2023-09-29 03:14
> Since it's been fixed, you no longer need ModernFlayouts installed.
But it's much better

**Comment by pyrates999** [comment] 2023-09-29 12:32
Then you need to google how to disable those flyouts so you can use modern flyouts.
