### ISSUE TITLE
Control Panel crashes in notification area customization

### ISSUE THREAD

**Issue by Balint817** [valinet/ExplorerPatcher#3058] opened 2024-03-26 19:57 UTC
To preface, In "Other" settings I prevented "Customize notification icons" from being redirected to Settings app.
in the "Taskbar" settings I first attempted to open "Customize system icons in the notification area", which consistently crashed explorer immediately upon clicking it, with 1 exception out of a lot of tries
I honestly don't know why it didn't crash that time, but at least that 1 exception let me change what I wanted.
But I wasn't so lucky with "Customize notification area icons", which crashed immediately when I attempted to change one of the settings, click "Cancel", "Ok", or interact with basically anything.
When ExplorerPatcher disabled itself due to crashing too much, attempting to open it the same way yielded a completely blank settings page.
Ask away if you need any more info.

![image](https://github.com/valinet/ExplorerPatcher/assets/66092782/0731cdb2-4567-4ba4-87c1-d1601cb7226e)
 
![image](https://github.com/valinet/ExplorerPatcher/assets/66092782/69a85564-351f-4612-9ded-3d2b6e45a002)
![image](https://github.com/valinet/ExplorerPatcher/assets/66092782/57c55d57-fff4-4543-a33f-aad84582e593)

**Comment by Balint817** [comment] 2024-03-26 20:00
Update: I found the issue.
Changing "Taskbar icon size" from Small to Large fixed the crashes

**Comment by pyrates999** [comment] 2024-03-26 20:24
You can drag and drop the icon in the system tray to the popup menu that you don't want shown.

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.

**Comment by Amrsatrio** [comment] 2024-03-27 03:19
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1454

**Closed by Amrsatrio** 2024-03-27 03:19 UTC
