### ISSUE TITLE
The search function does not appear in fullscreen start menu 

### ISSUE THREAD

**Issue by jaylay99** [valinet/ExplorerPatcher#2083] opened 2023-09-17 08:05 UTC
Using Windows 11 version 22h2 OS build: 22621.1702

I enabled the Windows 10 start menu in fullscreen, but there's one issue. When pressing the Window key or simply clicking on the "start" button, after typing something to search, the search does work but it does not appear so I can't see what I'm typing or see the results. 

This only happened after installing ExplorerPatcher, it works with the Windows 11 start menu. The issue seems to be that when the Windows 10 Start menu is active, the search menu is under and not over the start menu.

**Comment by Poopooracoocoo** [comment] 2023-09-17 08:14
Duplicate of #1975

**Closed by Poopooracoocoo** 2023-09-17 08:14 UTC
