### ISSUE TITLE
Explorer Patcher crashes on right click to open context menu

### ISSUE THREAD

**Issue by psybersenpai** [valinet/ExplorerPatcher#2656] opened 2024-01-05 04:35 UTC
I just installed EP, and on the desktop, if I right-click to open the context menu, it crashes everything. Not only the desktop, but if I select a file and right-click to open the context menu, it crashes again. I have tried restarting my PC, reinstalling EP but no luck. Had to uninstall the program.

**Comment by psybersenpai** [comment] 2024-01-05 04:45
Upon further troubleshooting, it seems that the error is occurring when the File Explorer Control Interface is set to "Windows 10 Ribbon". Switching it back to "Windows 11 Command Bar (classic Address Bar)" has resolved the issue. However, this means that we cannot change the File Explorer interface to anything other than Windows 11 style.

**Comment by pyrates999** [comment] 2024-01-05 12:16
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

please close this

**Closed** 2024-01-05 15:21 UTC
