### ISSUE TITLE
M$ Cancelled your amazing program

### ISSUE THREAD

**Issue by HyperSane** [valinet/ExplorerPatcher#3870] opened 2024-11-02 02:45 UTC
![image](https://github.com/user-attachments/assets/ecabd994-4c1a-4c2b-a818-036cc6cab103)

The entire update section doesn't work at all now.

Leave it to MicroPeni to ruin everything.

Getting ****** sick of MS, just fascism at this point.

Nothing works with the app at all since trying to update windows.

and now there's this 

![image](https://github.com/user-attachments/assets/2e142f22-386b-4a01-b87b-1281980d3595)

Clicking the recieve pre-release button works, but others don't, when I clicked it I got this message.

Literally everything's been fine for months until trying to install this new update.

# Edit

The windowskey+X now no longer works either, completely broken.

I'm afraid if I uninstall and update windows, I won't be able to reinstall explorer patcher.

**Comment by deeseem** [comment] 2024-11-02 09:39
Yeah, I was going to just skip Windows Updates from now, then I checked and there's a new build of EP that is apparently compatible, so I created a restore point and uninstalled EP.

New Windows update currently installing, then will try the new version of patcher, but if MS think I'm going back to their forced oversized taskbar abomination, that is a no, just no.

Soon as I rebooted from uninstalling EP, there it was, as I suspected, more than twice the size I actually want, or need, or have every allowed my taskbar to be, can't fit half my icons on it, and very deliberately made near impossible to make the size the buyer (in my case) of Windows actually wants it to be.

I even went over to try out Linux again for a bit till I found EP, and apart from the gaming side have to say Cinnamon variation builds are pretty good, and very similar to Windows in functionality overall.

The hubris of forcing customers to use a massive oversized taskbar, with no simple way to change it outside of resorting to third party software, is... frankly bizarre, and far from user friendly.

Since Win XP, MS have delivered and developed an OS that (typically) has been fairly good at covering most of the needs of their massive userbase by offering customisability, and the option to disable and change all the garbage, so people that actually use computers as tools, not to consume assorted trash newsfeeds and product upgrade offers, have a great user experience.

About half downloaded 24H2 now, which had no features at all I have interest in or use (I don't allow NoPilot to run etc), so interested to see what the manage to break, force into operation again despite my best efforts, and if I will be able to get EP installed again properly and resize that horrible taskbar.

Starting out by mimicking Apple in design is a bad sign to me, as next they will come for more of our third party software, and try to lockdown everything and the kitchen sink into the MS ecosystem under the guise of saving us from whatever they need to use as an excuse to force hardware upgrades that should be OPTIONAL, and at users risk to use non-TPM supported for example, if there even is any risk in real terms.

**Comment by Panzimy** [comment] 2024-11-02 10:40
If I'm looking good are using Windows 10. You need to unistall the EP, install Windows 11 and re-install EP. Because the EP can have problems. And yeah you need to exclude these folders:
```Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy"```
If you are using Microsoft Defender.
Or you need to add these folders to exclusion:
```C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy
C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy

**Comment by pyrates999** [comment] 2024-11-02 11:03
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

**Comment by Amrsatrio** [comment] 2024-11-02 11:47
Nothing we can do to counter those. It's outside of our control. How we pack files in the setup file resemble actual PUPs out there in the wild.

**Closed by Amrsatrio** 2024-11-02 11:47 UTC
