### ISSUE TITLE
Right clicking the taskbar crashes the explorer

### ISSUE THREAD

**Issue by xSqrtn** [valinet/ExplorerPatcher#1880] opened 2023-08-21 04:05 UTC
Hello, since the last time i updated my system, the entire taskbar crashes just from right clicking it
earlier a simple fix was to just turn off 'Skin taskbar and tray popup menus', now it also doesnt work.
now, i dont need to right click the taskbar a lot of time, but once i accidently right clicked when copying files which reverted the whole process and i need to undo that.
i really love explorer patcher and dont want to install it, hence i request y'all to find a fix for this issue, as in the summary list also it shows right click and go to properties to access the settings.

**Comment by pyrates999** [comment] 2023-08-21 04:27
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by lethanh1440** [comment] 2023-08-21 09:44
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu

Work like a charm!

**Comment by pyrates999** [comment] 2023-08-21 10:45
Now please close this one.  There's no reason to have duplicate issues open.

**Comment by SukiCZ** [comment] 2023-08-21 17:29
How to open Properties without right click?

**Comment by stephanlamoureux** [comment] 2023-08-22 00:42
this just saved me

**Comment by Poopooracoocoo** [comment] 2023-08-22 11:45
Duplicate of #1826

**Closed by Poopooracoocoo** 2023-08-22 11:45 UTC

**Comment by xSqrtn** [comment] 2023-08-23 10:13
> duplicate of: #1828
> 
> Please close this one.
> 
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

how is it a copy of #1828, both the issues are different.
in #1828, the guy was stating that explorer was constantly crashing, here i am raising the issue because explorer is crashing only on a right click of the taskbar
