### ISSUE TITLE
taskbar issues

### ISSUE THREAD

**Issue by TehEbil** [valinet/ExplorerPatcher#4035] opened 2024-12-14 12:54 UTC
Hello, I do have two errors.

I am using a samsung g9, so I have a resolution of 5120 x 1440. I put my taskbar to the right. I am on ExplorerPatcher Version 22621.4317.67.1 and Windows 11, BS-Build 22631.4602.

But I am experiencing two issues:

1) If I press WIN, the taskbar expands, so I can search. It is aligned on the right side of the monitor, but vertically centered instead of top right, is that correct? If I do start a search now (e.g. by entering "Calc"), the taskbar expansion suddenly is moved to the middle (horizontal centered) of the screen, bottom aligned.

2) I only have 11 possible icons in my taskbar (the area between windows icon and explorer icon is completely empty). Can I increase the numbers? But the problem is, if I have 12 icons, I cannot see the 12th one. It looks like if I have more than 18, a horizontal scrollbar for the taskbar appears, which you can see in the screenshot.

![image](https://github.com/user-attachments/assets/1c3de447-736e-4033-8f79-6130f717ca37)

Thank you for your help

**Comment by pyrates999** [comment] 2024-12-14 13:34
For item 1, that is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

For item 2, right click on the taskbar and untick **Lock the taskbar**.  Then the separators are shown and you can move them up and down to make more room for more icons.  Then right click on the taskbar and tick **Lock the taskbar**.

**Closed** 2024-12-14 13:54 UTC

**Comment by pyrates999** [comment] 2024-12-14 15:31
you're welcome
