### ISSUE TITLE
EP Explorer.exe crash after KB5034204

### ISSUE THREAD

**Issue by Justtaway** [valinet/ExplorerPatcher#2750] opened 2024-01-26 12:29 UTC
Win11x64 23H2 22631.3085, EP 22621.2861.62.2
After installing KB5034204, Explorer now crashes every time I try to start it.
Scheluder logs:
```
 AppName explorer.exe 
  AppVersion 10.0.22621.3085 
  AppTimeStamp a58eee1c 
  ModuleName ExplorerFrame.dll 
  ModuleVersion 10.0.22621.3085 
  ModuleTimeStamp 0b45ea8a 
  ExceptionCode c0000005 
  FaultingOffset 000000000000862b 
  ProcessId 0xe24 
  ProcessCreationTime 0x1da504e5740ed46 
  AppPath C:\Windows\explorer.exe 
  ModulePath C:\Windows\SYSTEM32\ExplorerFrame.dll 
  IntegratorReportId 2be3db4a-e262-4cf0-9712-74ba0d63641f 
  PackageFullName  
  PackageRelativeAppId  
```

I tried various combinations of those settiings: ![image](https://github.com/valinet/ExplorerPatcher/assets/9951646/fa33cad7-940e-47b9-982d-14b8af1e776b)
Still get crashes. If some additional info is needed, I'll gladly provide it.

**Comment by pyrates999** [comment] 2024-01-26 12:33
Never enable register as shell extension.  Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

your crash is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

please close this

**Comment by Justtaway** [comment] 2024-01-26 12:48
> Never enable register as shell extension.
As I said, i tried it on and off.

> your crash is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

Except that workaround is not working for me, and I don't even right click, Explorer crashes before I see window.

**Comment by pyrates999** [comment] 2024-01-26 12:57
That's why it's still open.  It's on going.  Please close this and comment there.

**Closed** 2024-01-26 13:01 UTC
