### ISSUE TITLE
Windows search menu stuck as windows 11

### ISSUE THREAD

**Issue by SmugyGaming** [valinet/ExplorerPatcher#3035] opened 2024-03-20 21:05 UTC
When having ExplorerPatcher set my taskbar to windows 10, the search menu still shows up as windows 11 and therefor does not open on the "right" side where my taskbar is set to.

I use ExplorerPatcher specifically to move my taskbar to the right side of my screen as i used to have it. 
![image](https://github.com/valinet/ExplorerPatcher/assets/142067120/e93de80e-0c2d-4c9d-9670-b0dfa109e1f4)

**Comment by Amrsatrio** [comment] 2024-03-20 21:19
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1803

**Closed by Amrsatrio** 2024-03-20 21:19 UTC
