### ISSUE TITLE
KB5028254 Crash 

### ISSUE THREAD

**Issue by PhenixShade** [valinet/ExplorerPatcher#1715] opened 2023-07-29 15:18 UTC
Since the latest Windows 11 update, Explorer Patcher no longer works properly and crashes every time the application is relaunched.

**Comment by pasomnica** [comment] 2023-07-29 16:54
Just updated and can confirm, Explorer crashes as soon as I boot my laptop

**Comment by Loner3362** [comment] 2023-07-29 18:20
Same here.

**Comment by luciodaou** [comment] 2023-07-29 23:15
Duplicate of #1707

**Comment by PhenixShade** [comment] 2023-07-30 01:08
Sorry for duplicate post 
For the moment, the only solution to avoid a crash is to uninstall the latest Windows update KB5028254.

**Comment by victormuscles** [comment] 2023-07-30 02:06
apologies - i am reasonably tech savvy, i have the same issue and had to uninstall explorer patcher.  when i looked on the MS website on instructions to uninistall KB5028254 for windows 11 - it mentions the SSU and LCU and having to run the DISM command to remove it - "sort of clueless on that process".

This is where i saw the comment..
https://www.elevenforum.com/t/kb5028254-windows-11-cumulative-update-preview-build-22621-2070-22h2.16658/

**Comment by Girofox** [comment] 2023-07-30 07:49
In my case it only crashed when right-clicking on taskbar. Setting taskbar style to "**Windows 10**" fixed that temporarily for me, even right-clicking works.

**Comment by Morphorxz** [comment] 2023-07-31 05:21
Same. And setting taskbar style to win10 would be fine.

**Comment by victormuscles** [comment] 2023-07-31 06:15
my setting is set to windows 10 style and the crash still occurs.

**Comment by Morphorxz** [comment] 2023-07-31 06:24
> apologies - i am reasonably tech savvy, i have the same issue and had to uninstall explorer patcher. when i looked on the MS website on instructions to uninistall KB5028254 for windows 11 - it mentions the SSU and LCU and having to run the DISM command to remove it - "sort of clueless on that process".
> 
> This is where i saw the comment.. https://www.elevenforum.com/t/kb5028254-windows-11-cumulative-update-preview-build-22621-2070-22h2.16658/

Seemingly you can uninstall it as [here](https://github.com/valinet/ExplorerPatcher/issues/1707#issuecomment-1656768672). I have tried it yet and now it works well.

**Comment by victormuscles** [comment] 2023-07-31 07:05
many thanks  - i have uninstalled the update as suggested above and the issue is resolved.  "never combine" being unavailable is painful.

**Comment by pyrates999** [comment] 2023-08-01 09:55
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by BenjaminWKI** [comment] 2023-08-02 18:58
Follow [these instructions](https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6580555) to fix the issue ... and you don't need to uninstall the Windows 11 update.

**Comment by Poopooracoocoo** [comment] 2023-08-22 11:17
KB5028254 and 22621.2070 was a preview update

**Closed by Poopooracoocoo** 2023-08-22 11:17 UTC
