### ISSUE TITLE
Explorer "crashing" on right-click (Duplicate?)

### ISSUE THREAD

**Issue by nzkfc** [valinet/ExplorerPatcher#2000] opened 2023-09-05 03:43 UTC
Been having this issue: https://youtu.be/YdPLBk0tnac

I've looked through github to find a few similar issues, but the option of turning off the "properties" option on context and a restart of the system didn't fix anything.
https://i.imgur.com/HtIa9wp.png

I've also uninstalled and reinstalled latest from releases and restarted, same issue.

https://i.imgur.com/OdNDJbZ.png

**Comment by PrivateRoDee** [comment] 2023-09-05 04:27
I have the same issue

**Comment by PrivateRoDee** [comment] 2023-09-05 04:45
I have a similar issue when I try to access the properties for explorer patcher by right clicking on the task bar - explorer crashes. 
winver - `22H2 (OS Build Version 22621.2215)`
Explorer patcher Version - `22621.1992.56.3`

**Comment by Loping151** [comment] 2023-09-05 06:12
Guess you are looking for: #1952 #1938 #1805 (solved) #1802 .
Another problem you might come across is #1920 #1687 . 
Check out.

**Comment by nzkfc** [comment] 2023-09-05 07:26
> Guess you are looking for: #1952 #1938 #1805 (recommend this) #1802 . Another problem you might come across is #1920 #1687 . Check out.

Yeah those all sound like the same issue, each one keeps telling people to set that setting and restart, but problem persists.

**Comment by pyrates999** [comment] 2023-09-05 07:28
> I have a similar issue when I try to access the properties for explorer patcher by right clicking on the task bar - explorer crashes. winver - `22H2 (OS Build Version 22621.2215)` Explorer patcher Version - `22621.1992.56.3`

That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.

**Comment by Poopooracoocoo** [comment] 2023-09-05 07:48
No fix yet, sorry. Closing as a dupe of the above

**Closed by Poopooracoocoo** 2023-09-05 07:48 UTC

**Comment by Loping151** [comment] 2023-09-05 10:44
> 

I guess for now it is a choice between the latest version of Windows and ExplorerPatcher.

After all, it's Microsoft's fault not to provide such options...
