### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by Master-ZizO** [valinet/ExplorerPatcher#499] opened 2021-12-03 11:56 UTC
BUG : Can't drag any file to any application in taskbar

**Comment by BraINstinct0** [comment] 2021-12-03 12:32
Hmm? Seems like it works for me. Though, that does the 'pin this item', not 'open with...'.
That is sort of an expected behavior IIRC, but my memory of Win10 is already being hazy so correct anything I might've gotten wrong.

**Comment by valinet** [comment] 2021-12-03 14:09
It works in the 10 one; no one mentions which ‘taskbar’ despite clearly being huge differences between the 10 and 11 ones. This program mostly affects the 10 one, the 11 one is untouched mainly, as it ships from Microsoft.

As I said at some point, I am closing incomplete reports. Thanks

**Closed by valinet** 2021-12-03 14:09 UTC
