### ISSUE TITLE
windows 10 start menu not working after KB5036980 update

### ISSUE THREAD

**Issue by Shubham-860** [valinet/ExplorerPatcher#3163] opened 2024-04-24 10:06 UTC
windows 10 start menu not working after 2024-04 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5036980) update

**Comment by zake2002v2** [comment] 2024-04-24 10:22
@Shubham-860 this is a repost of https://github.com/valinet/ExplorerPatcher/issues/3162, please check that issue

**Comment by 1robertsway** [comment] 2024-04-24 18:16
I don't know what update it was., but Windows 10 start. doesn't exist anymore.. Properties. Are set for Windows 10? But it stuck on windows 11. Yes, would appreciate someone checking into it.

**Comment by trusampler** [comment] 2024-04-25 06:20
Same issues happenieng here, after latest win11 update. Explorer Patcher reverts back to Windows 11 start menu, with no ability to make changes to Win10 start menu. Question, will we lose the history of how we had it previously set up ?

**Comment by zake2002v2** [comment] 2024-04-25 10:39
> Question, will we lose the history of how we had it previously set up ?
@trusampler no, it seems that after updating to a preview build that patches it to work again(while having to allow it in Windows Defender as well), the computer remembers the tile placement in the start menu, so you don’t have to worry about rearranging the tiles all over again

**Comment by Amrsatrio** [comment] 2024-04-25 12:39
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3066

**Closed by Amrsatrio** 2024-04-25 12:39 UTC
