### ISSUE TITLE
Alt + Tab not working anymore

### ISSUE THREAD

**Issue by ArnoldCorns** [valinet/ExplorerPatcher#1094] opened 2023-03-17 07:14 UTC
Hi ExplorerPatcher Team

Explorer Patcher V 22621.1344.53.1
OS: Windows 11 V22H2 Build 22621.1413

Since latest update of ExplorerPatcher Alt + Tab Shortcut as well as Win + Tab as well as Desktop Switching Widget do not work anymore.

Otherwise a great solution, keep going!

Best
Peter

**Comment by Booser** [comment] 2023-03-17 07:35
Hi there,
I am having the same problem. In Windows 11 Pro 22H2 Build 22621.1265

ExplorerPatcher is on the newest update.

I had issues after installing the newest windows version. After login explorer died every second after it started itself again.
When i patched the ExplorerPatcher that went away. But i could not use Alt+Tab, explorer.exe died every time i pressed the keys. I tried to fix it by using DISM and sfc [like shown here](https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-365e0031-36b1-6031-f804-8fd86e0ef4ca), it showed some defective files that where replaced but it did not help with the problem.

I changed the Alt+Tab behaviour around in the Patcher settings and after coming back to the standard setting it worked for a few hours. But then the problem started coming back again until I finally had to uninstall ExplorerPatcher and all prooblems went away... and my "normal" Taskbar with it :(

**Comment by slybud** [comment] 2023-03-17 08:25
Hi there and thank you for this very useful program.
I'm having the same issue here since  last windows update

**Comment by ArnoldCorns** [comment] 2023-03-17 10:33
might be that [this](https://github.com/valinet/ExplorerPatcher/issues/1095) is what happened...

**Comment by CthRio** [comment] 2023-03-17 10:39
> might be that [this](https://github.com/valinet/ExplorerPatcher/issues/1095) is what happened...

For a more detailed explanation, you can look at these:
1.[Why did it happen](https://github.com/valinet/ExplorerPatcher/discussions/1087#discussioncomment-5343845)
2.[How to alleviate it?](https://github.com/valinet/ExplorerPatcher/discussions/1087#discussioncomment-5344021)

**Comment by pl77** [comment] 2023-03-17 14:27
For anyone else who doesn't realize that the above post actually solves the Alt-Tab problem, please follow the second link in that post, install ViveToolGUI, and disable 26008830. Thanks so much for finding the solution for us, @CthRio!

**Comment by jibnew** [comment] 2023-03-17 19:11
With me, it works but only if I press Tab after keeping Alt pressed for about a second. Weird

**Comment by asaf400** [comment] 2023-03-17 22:40
See the solution here:

https://github.com/valinet/ExplorerPatcher/discussions/1087#discussioncomment-5346671
also this is a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1098

**Comment by valinet** [comment] 2023-03-18 14:10
Latest version [22621.1413.54.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1413.54.1_8b5443d) addresses this issue.

**Closed by valinet** 2023-03-18 14:10 UTC
