### ISSUE TITLE
After I downloaded and reinstalled explorerpatcher in windows 24H2 (26100.2605), when I opened the start interface (full screen tile of win10), the desktop icons still existed instead of the clean background.

### ISSUE THREAD

**Issue by null287** [valinet/ExplorerPatcher#4036] opened 2024-12-14 15:11 UTC
After I downloaded and reinstalled explorerpatcher in windows 24H2 (26100.2605), when I opened the start interface (full screen tile of win10), the desktop icons still existed instead of the clean background.
![微信图片_2024-12-14_231032_900](https://github.com/user-attachments/assets/2fd5ebe1-7e94-423d-a355-475cad8a8150)

**Comment by Amrsatrio** [comment] 2024-12-15 10:06
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3565

This is a new change in 24H2, this also applies to the task view. We have no plans on fixing this. Sorry.

**Closed by Amrsatrio** 2024-12-15 10:06 UTC
