### ISSUE TITLE
Win11 style start button and task view do not work.

### ISSUE THREAD

**Issue by r-rikka** [valinet/ExplorerPatcher#1967] opened 2023-08-31 02:07 UTC
When using 22621.1992.56.3 on Win11 Pro 22H2 22621.2215
Win11 style start button does not work. Win10 style works.
Also, click the task view button or flick the three fingers with a mouse pad, will not be able to use a task view.
After starting the PC , click the task view button or flick the three fingers with a mouse pad , will not be able to use all the three finger gestures of the mouse pad.
(This English sentence is a machine translation, so it may be difficult to understand. sorry.)

**Comment by Poopooracoocoo** [comment] 2023-08-31 04:54
Duplicate of #1687

**Closed by Poopooracoocoo** 2023-08-31 04:54 UTC
