### ISSUE TITLE
Right click on task bar to open Task manager

### ISSUE THREAD

**Issue by Azertixe** [valinet/ExplorerPatcher#1985] opened 2023-09-03 16:05 UTC
Hello. This option disapeared with Windows 11 ?
Any solution possible with ExplorerPatcher ?

Thanks !

**Comment by sultan99** [comment] 2023-09-03 16:36
The same issue on my side:
![image](https://github.com/valinet/ExplorerPatcher/assets/2598056/8cdd4a60-91be-4c8e-b8b1-41bc949f0711)

**Comment by Azertixe** [comment] 2023-09-03 16:49
> The same issue on my side: ![image](https://user-images.githubusercontent.com/2598056/265277076-8cdd4a60-91be-4c8e-b8b1-41bc949f0711.png)

Hi. I noticed that explorer don't crash with Win10 taskbar style (the only way i found to not combine openned programs). 
I experienced crashes with Win11 tb style only.

Also, it's possible to open task manager right clicking directly on the menu button, but not to an empty zone of the taskbar. 

Last point : taskbar properties shortcut on right click seems to have disapeared with Win 11 :(
I hope ExplorerPatcher can offer us a solution...

**Comment by Poopooracoocoo** [comment] 2023-09-03 18:12
> Hello. This option disapeared with Windows 11 ? Any solution possible with ExplorerPatcher ?
> 
> Thanks !

This is the first time I've heard of your issue. What OS build and ExplorerPatcher version do you have?

**Comment by Azertixe** [comment] 2023-09-03 19:35
> > Hello. This option disapeared with Windows 11 ? Any solution possible with ExplorerPatcher ?
> > Thanks !
> 
> This is the first time I've heard of your issue. What OS build and ExplorerPatcher version do you have?

Hello. I have Win11 22H2. My ExplorerPatcher is up to date.

**Comment by Syth-1** [comment] 2023-09-03 21:09
> > Hello. This option disapeared with Windows 11 ? Any solution possible with ExplorerPatcher ?
> > Thanks !
> 
> This is the first time I've heard of your issue. What OS build and ExplorerPatcher version do you have?

same issue, on version: 
using OS:
Edition: Windows 11 Pro
Version: 22H2
OS Build: 22621.2134

i have tried updating to the following OS version: 
> 22621.2215
still same issue. 

Also how to access property menu? is there an alternate method, ive tried looking into win+x menu, unfortunately no luck. figured there was a short cut, but cant find anything about that in the wiki.

**Comment by AphLute** [comment] 2023-09-03 23:05
This worked for me, from [docs](https://github.com/valinet/ExplorerPatcher/wiki/About-advanced-settings#hide-the-program-settings-item-properties-from-the-taskbar-context-menu).

> If you are facing such a situation, click the Start button, type "run" (or press [Win]+[R]) and enter the following command: rundll32 C:\Windows\dxgi.dll,ZZGUI to open the configuration window manually.

**Comment by pyrates999** [comment] 2023-09-03 23:12
> > > Hello. This option disapeared with Windows 11 ? Any solution possible with ExplorerPatcher ?
> > > Thanks !
> > 
> > 
> > This is the first time I've heard of your issue. What OS build and ExplorerPatcher version do you have?
> 
> Hello. I have Win11 22H2. My ExplorerPatcher is up to date.

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.  Do not say latest because that doesn't mean anything.

**Comment by TiddlyQwert** [comment] 2023-09-03 23:48
To chime in here. For me, the issue was I had one of the features enabled that requires you to register EP as a shell extension. One I enabled the top option here the issue mentioned in this thread went away. 
![image](https://github.com/valinet/ExplorerPatcher/assets/18452101/3629db2d-b46c-46d7-990e-bfb36f92789a)

**Comment by PlUmPaSsChIcKeN** [comment] 2023-09-05 03:21
Having the same issue. Running Windows 11 Pro Version 22H2 OS Build 22621.2134 and ExplorerPatcher Version 22621.1992.56.3

Tried TiddlyQwert's fix but did not work for me

**Comment by pyrates999** [comment] 2023-09-05 07:23
Here's what register as a shell extension does and is not recommended you enable it: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by Azertixe** [comment] 2023-09-05 18:43
> > > > Hello. This option disapeared with Windows 11 ? Any solution possible with ExplorerPatcher ?
> > > > Thanks !
> > > 
> > > 
> > > This is the first time I've heard of your issue. What OS build and ExplorerPatcher version do you have?
> > 
> > 
> > Hello. I have Win11 22H2. My ExplorerPatcher is up to date.
> 
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version. Do not say latest because that doesn't mean anything.

Win11 22H2 22621.2134
EP 22621.1992.56.3

**Comment by pyrates999** [comment] 2023-09-05 20:55
> > > > > Hello. This option disapeared with Windows 11 ? Any solution possible with ExplorerPatcher ?
> > > > > Thanks !
> > > > 
> > > > 
> > > > This is the first time I've heard of your issue. What OS build and ExplorerPatcher version do you have?
> > > 
> > > 
> > > Hello. I have Win11 22H2. My ExplorerPatcher is up to date.
> > 
> > 
> > Please post windows version and build. You can find this by running winver. Please post explorer patcher version. Do not say latest because that doesn't mean anything.
> 
> Hello there ! Win11 22H2 22621.2134 EP 22621.1992.56.3
> 
> Thanks :)

Please show a screen shot of what you see when you right click on the taskbar.

**Comment by PlUmPaSsChIcKeN** [comment] 2023-09-05 21:00
> Please show a screen shot of what you see when you right click on the taskbar.

What happens on my end is that right clicking does not open the menu but rather crashes file explorer and then it restarts itself. After doing it a few times you'll get the crash error posted above

**Comment by pyrates999** [comment] 2023-09-05 21:01
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by Azertixe** [comment] 2023-09-06 06:50
> that was reported here: #1828
> 
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

Hello. This fixes explorer crashing but not opening context menu.

**Comment by pyrates999** [comment] 2023-09-07 10:41
answer was posted here: https://github.com/valinet/ExplorerPatcher/issues/1948

**Comment by Poopooracoocoo** [comment] 2023-09-23 03:48
Should be resolved now. Leave a comment if you still see issues. Include your EP version and OS build.

**Closed by Poopooracoocoo** 2023-09-23 03:48 UTC

**Comment by Azertixe** [comment] 2023-09-24 07:31
Hello. Now taskview button is working but i still haven't right click on task bar. 
Any option to activate in EP menu ?

EP 22621.2283.57.2
Build 22621.2134
