### ISSUE TITLE
windows taskbar turned transparent

### ISSUE THREAD

**Issue by Dzire2Dzine** [valinet/ExplorerPatcher#2982] opened 2024-03-13 06:42 UTC
After update last night (IST), taskbar turned transparent, now I am having dificulty reading labels. Unable to find any option also to change it back. Seems something went wong.

https://twitter.com/TheBobPony/status/1767780649358762402

![image](https://github.com/valinet/ExplorerPatcher/assets/5224576/1c78c741-7532-4b79-a600-d1cfb5a5dc50)

**Comment by zme-ul** [comment] 2024-03-13 06:44
this has been fixed in a pre-lease version of EP
original thread: https://github.com/valinet/ExplorerPatcher/issues/2975

**Comment by Amrsatrio** [comment] 2024-03-13 10:16
Affected users may install the latest pre-release build to have acrylic back.

By the way, duplicate of https://github.com/valinet/ExplorerPatcher/issues/2975.

**Closed by Amrsatrio** 2024-03-13 10:16 UTC
