### ISSUE TITLE
Windows Defender is now flagging ExplorerPatcher as high risk malware, FYI

### ISSUE THREAD

**Issue by MartijnDekkers-EI** [valinet/ExplorerPatcher#3260] opened 2024-05-10 15:17 UTC

**Comment by MartijnDekkers-EI** [comment] 2024-05-10 15:19
<img width="424" alt="Screenshot 2024-05-10 171811" src="https://github.com/valinet/ExplorerPatcher/assets/122533599/771e0525-f995-446c-95fe-cd230b588318">

**Comment by pyrates999** [comment] 2024-05-10 19:17
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

please close this.

**Closed** 2024-05-11 04:10 UTC
