### ISSUE TITLE
Explorer crashes when right clicking on a file

### ISSUE THREAD

**Issue by ckgurr** [valinet/ExplorerPatcher#2475] opened 2023-11-20 18:13 UTC
I have have issues with older version giving an unusable flashing screen immediately after signing in; this has happened since about March 2023 after windows update. I solved this but rolling back updates. 
I finally figured out that is was a clash with ExplorerPatcher. 
Today a removed the old version and installed the latest version (22621.2506.60.1), after rebooting whenever I right click on ANY file, Windows Explorer will crash.

I really like being able to customize my task bar on multiple screens, thanks for your work.

System Summary:
Windows 11 pro
10.0.22621 build 22621
CTHINKPAD
LENOVO
20QWS08W00
x64-based PC

**Comment by Amrsatrio** [comment] 2023-11-20 18:31
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218

**Closed by Amrsatrio** 2023-11-20 18:31 UTC
