### ISSUE TITLE
ExplorerPatcher make explorer.exe continuosly crashing

### ISSUE THREAD

**Issue by pedro80bg** [valinet/ExplorerPatcher#1191] opened 2023-03-24 08:40 UTC
ExplorerPatcher make explorer.exe continuosly crashing

**Comment by topia** [comment] 2023-03-24 08:43
Please add information on what version you are using for Windows and ExplorerPatcher, including the build number.

**Comment by kpietraszko** [comment] 2023-03-24 09:45
Had the same issue this morning. You need to enter Windows recovery mode (hold power while windows is starting, repeat a few times for windows to think it's broken). Uninstall latest update there, restart pc, and update ExplorerPatcher.

**Comment by pedro80bg** [comment] 2023-03-24 10:56
Mi sai dire quale aggiornamento windows?

Grazie
________________________________
Da: Krzysztof Pietraszko ***@***.***>
Inviato: venerdì 24 marzo 2023 10:46
A: valinet/ExplorerPatcher ***@***.***>
Cc: pedro80bg ***@***.***>; Author ***@***.***>
Oggetto: Re: [valinet/ExplorerPatcher] ExplorerPatcher make explorer.exe continuosly crashing (Issue #1191)


Had the same issue this morning. You need to enter Windows recovery mode (hold power while windows is starting, repeat a few times for windows to think it's broken). Uninstall latest update there, restart pc, and update ExplorerPatcher.

**Comment by pedro80bg** [comment] 2023-03-24 13:42
> Please add information on what version you are using for Windows and ExplorerPatcher, including the build number.

Windows 11 Pro 2H2 Build s22621.1413
Windows Feature Experience Pack 1000.22639.1000.0

ExplorerPatcher Version: 22621.1413.54.5

**Comment by monkeeboy3** [comment] 2023-03-24 22:13
I am also having this problem. I tried deleting `dxgi.dll` as in #1148, but that makes ExplorerPatcher stop working entirely

**Comment by pyrates999** [comment] 2023-03-24 22:41
> I am also having this problem. I tried deleting `dxgi.dll` as in #1148, but that makes ExplorerPatcher stop working entirely

Well that makes sense because explorer patcher needs that to function.

Did you try uninstalling explorer patcher and then downloading and installing the latest release?

**Comment by monkeeboy3** [comment] 2023-03-25 01:02
> > I am also having this problem. I tried deleting `dxgi.dll` as in #1148, but that makes ExplorerPatcher stop working entirely
> 
> Well that makes sense because explorer patcher needs that to function. At the same time that is causing explorer.exe to crash due to the explorer patcher version you have installed.
> 
> Did you try uninstalling explorer patcher and then downloading it and installing the latest release?

Literally the first thing I tried, yes.

**Comment by Tridy** [comment] 2023-03-25 14:47
I had this problem on 2 computers. It could be so (not sure), that this problem happens when, after a Windows update, on startup, Windows is trying to display a couple of additional dialogs with more options or settings, before actually getting to the Desktop.

So, the behavior is that explorer.exe is constantly crashing.
I am still able to Alt+Ctrk+Del and

1. Start the Task manager.
2. With some _luck and good timing_ I was able to kill explorer.exe myself before it crashed.
3. From the task manager, I started appwiz.cpl and uninstalled Explorer patcher.
4. From the task manager opened a browser, downloaded the latest version of explorer patcher, and installed it.
5. From the Task Manager started explorer.exe. Seems to work ok now.
6. After that, restarted the computer, went through the extra options and settings mentioned earlier, and now it looks ok.

**Comment by RLB42** [comment] 2023-03-27 13:54
I have the same issue, but I cannot get explorer.exe to stop crashing. The computer is a brand new Dell Vostro (two hours old) and I'm using the latest ExplorerPatcher release. Which has not run correctly at all because the problem happened immediately after installing.

**Comment by pyrates999** [comment] 2023-04-13 23:03
this appears to be a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1307

**Closed** 2023-09-23 04:56 UTC
