### ISSUE TITLE
[226x1.4112] The context menu is not visible when the taskbar is on top.

### ISSUE THREAD

**Issue by Schecher1** [valinet/ExplorerPatcher#3615] opened 2024-08-30 16:53 UTC
I have installed Windows 11 (unfortunately) and am very happy that I can turn my win 11 into win 10, but unfortunately the context menu is no longer ‘accessible’ when I left-click on an icon.

My guess is that the menu glitches upwards and not downwards.

The Menu (only accessible when the taskbar is bottom):
![image](https://github.com/user-attachments/assets/226f6239-2fd2-4aa0-8c1e-ac2fdb44c049)

**Comment by pyrates999** [comment] 2024-08-30 21:44
Install the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment] 2024-08-31 06:42
Hi, reproduced your issue. I will make a fix soon but to prepare for future updates I suggest you to add ExplorerPatcher's folders into exclusions. Details here: https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment] 2024-09-01 10:42
Fixed in 66.5.

**Closed by Amrsatrio** 2024-09-01 10:42 UTC
Labels: investigating

**Comment by qquq** [comment] 2024-09-16 19:56
@Amrsatrio hello, appreciate you manage to fix it, but sadly i cant upgrade to 66.5 due to false virus flag that is not present in 65.4. Would it be possible to share changes made so i can fix it myself? Or fix it in this older version?

**Comment by pyrates999** [comment] 2024-09-16 20:39
Source code is available on github repo here, except for the reimplemented windows 10 taskbar.  So you can check it yourself.  You can even fork it and do your own builds if you like.

**Comment by qquq** [comment] 2024-09-16 21:37
Thats not option for me since i dont know how to code this, but thanks for the suggestion nevertheless
