### ISSUE TITLE
KB5045935 appears to disable Start Button right click menu for Windows 10 or Windows 10 (ExplorerPatcher) Taskbar styles

### ISSUE THREAD

**Issue by cpresco** [valinet/ExplorerPatcher#3844] opened 2024-10-24 20:27 UTC
"Get the latest updates as soon as they're available" was unknowingly enabled in Settings app>Windows Update on a Windows 11 23H2 system. 

This allowed for KB5045935 - Cumulative Update Preview for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 and Windows 11, version 23H2 to be automatically installed. 

After the install completed the right click menu of the Start Button was disabled (nothing would happen on a right click) when ExplorerPatcher>Taskbar>Taskbar style was set to either Windows 10 or Windows 10 (ExplorerPatcher).

Setting ExplorerPatcher>Taskbar>Taskbar style to Windows 11 (default) would re-enable the right click menu of the Start Button to display.

Rolling back the Windows 11 system to the previous System Restore Point removed KB5045935 and restored the right click menu of the Start Button when ExplorerPatcher>Taskbar>Taskbar style was set to either Windows 10 or Windows 10 (ExplorerPatcher).

This appears to be another attempt by Microsoft to sabotage ExplorerPatcher.

**Comment by pyrates999** [comment] 2024-10-24 22:30
do you have the latest pre-release installed? https://github.com/valinet/ExplorerPatcher/releases

**Comment by randomidiot2887** [comment] 2024-10-25 02:48
i realised the menu also doesnt work for me

**Comment by cpresco** [comment] 2024-10-25 10:59
> do you have the latest pre-release installed? https://github.com/valinet/ExplorerPatcher/releases

I'm on release 22621.3380.66.6 which I believe is the current release.

I mainly wanted to report this in case someone else installed KB5045935 and also ran in to the same issue. I typically don't have "Get the latest updates as soon as they're available" enabled to reduce problems like this and haven't had problems with release 22621.3380.66.6 on other Windows 11 systems.

I'll try enabling "Get the latest updates as soon as they're available", letting KB5045935 install then installing the latest ExplorerPatcher release.

**Comment by pyrates999** [comment] 2024-10-25 11:50
> > do you have the latest pre-release installed? https://github.com/valinet/ExplorerPatcher/releases
> 
> I'm on release 22621.3380.66.6 which I believe is the current release.
> 

If you went to the link, you'd see there was a pre-release there that is newer.

**Comment by pyrates999** [comment] 2024-10-25 12:44
If the windows 10 start menu option shows windows 11 start menu instead, and your windows 11 version language is in Chinese, this is a known issue: https://github.com/valinet/ExplorerPatcher/issues/3667

**Comment by cpresco** [comment] 2024-10-25 12:59
> > > do you have the latest pre-release installed? https://github.com/valinet/ExplorerPatcher/releases
> > 
> > 
> > I'm on release 22621.3380.66.6 which I believe is the current release.
> 
> If you went to the link, you'd see there was a pre-release there that is newer.

I meant "letting KB5045935 install then installing the latest ExplorerPatcher pre-release" instead of " letting KB5045935 install then installing the latest ExplorerPatcher release".

**Comment by pyrates999** [comment] 2024-10-25 14:01
don't install https://support.microsoft.com/en-us/topic/october-22-2024-kb5045935-cumulative-update-preview-for-net-framework-3-5-and-4-8-1-for-windows-11-version-22h2-and-windows-11-version-23h2-ab94d368-5074-466c-aab1-3aee2965285a until EP has been updated to fix this.

**Comment by cpresco** [comment] 2024-10-25 18:21
> don't install https://support.microsoft.com/en-us/topic/october-22-2024-kb5045935-cumulative-update-preview-for-net-framework-3-5-and-4-8-1-for-windows-11-version-22h2-and-windows-11-version-23h2-ab94d368-5074-466c-aab1-3aee2965285a until EP has been updated to fix this.

Understood.

**Comment by milesprower2293** [comment] 2024-10-26 00:31
Duplicate of #3837

**Closed by milesprower2293** 2024-10-26 00:31 UTC
