### ISSUE TITLE
Start menu search bar not working #2

### ISSUE THREAD

**Issue by RobAus** [valinet/ExplorerPatcher#2774] opened 2024-02-01 21:48 UTC
Having a repeat of a previous issue #1513, link below.

https://github.com/valinet/ExplorerPatcher/issues/1513

Unable to type any search text in the application menu when either clicking on start or pressing the window key.  Additionally, unable to manually select the search bar to get the cursor active.

Pressing a key will select an app in the Pinned apps, ie pressing w jumps to Word but I am unable to select the search bar and type.

Using EP version 22621.2861.62.2

Thanks in advance!

**Comment by pyrates999** [comment] 2024-02-02 01:41
Please post windows version and build.  You can find this by running winver.

**Comment by pyrates999** [comment] 2024-02-06 09:46
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2523

Please close this.

**Closed** 2024-02-10 10:31 UTC
