### ISSUE TITLE
crash explorer patcher

### ISSUE THREAD

**Issue by miku1881** [valinet/ExplorerPatcher#1828] opened 2023-08-12 00:36 UTC
Yesterday, there was a windows update, and I applied the update.
The next day explorer patcher didn't start and I installed it.
After installing it, explorer restarted several times.
explorer patcher crashed.
Please fix!

**Comment by MerriestWly** [comment] 2023-08-12 00:59
I have same issues on win11

**Comment by miku1881** [comment] 2023-08-12 01:14
windows 11 os build 22621.2134

**Comment by PCL86** [comment] 2023-08-12 01:23
In my case, I deleted the registry after uninstalling Explorer patcher, and then installed Explorer patcher after rebooting. Explorer patcher crashes when trying to open a folder icon.

**Comment by ibcurly** [comment] 2023-08-12 01:26
damn windows updates..
same issue, win 11 build 22621.2134

**Comment by miku1881** [comment] 2023-08-12 02:42
The solution is to uninstall the explorer patcher and then install it, and I have confirmed that it works as usual.

**Comment by johnwasme** [comment] 2023-08-12 02:57
That only works for some people,i have tried installing and reinstalling and deleting registry shortcuts but still get crashes.

**Comment by SMxSoMuch** [comment] 2023-08-12 07:51
same in 22621.2134
only given this message
![image](https://github.com/valinet/ExplorerPatcher/assets/132253241/66c7426f-3cb2-49de-a97c-f4bf9435bf2c)

**Comment by eMuonTau** [comment] 2023-08-12 08:52
What is your ExplorerPatcher version? Can you try latest version?
Update notification setting was off in my settings so i was using an old version. I don't know it may happen again, i am still testing but it is stable for now.

**Comment by 4everImmortality** [comment] 2023-08-12 10:05
There is a same issue on win11 OS Bulid 22621.2070
Update too quickly is not a good choice.

**Comment by mr-asa** [comment] 2023-08-12 10:52
Same problem! The latest update (KB5029263) breaks explorerpatcher (22621.1992.56.1 build)
Release: Windows 11
Version: 22H2
OS build: 22621.2134

When uninstalling that update everything works as it should, but I can't skip that update and it automatically updates even when I chose to pause updates for a week

**Comment by SMxSoMuch** [comment] 2023-08-12 10:56
> 

it is the last verson I think

here is the about page
![image](https://github.com/valinet/ExplorerPatcher/assets/132253241/6dbd54b3-eb19-4355-986c-9d2c85867b6c)

**Comment by Vipin2003** [comment] 2023-08-12 11:09
already mentioned in PR #1834

**Comment by ValentinBrclz** [comment] 2023-08-12 13:55
@Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.

**Comment by Vipin2003** [comment] 2023-08-12 14:20
You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.

To fix this issue

**Comment by assuena** [comment] 2023-08-12 18:23
> > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> 
> You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> 
> To fix this issue, follow these steps now:
> 
> 1. Uninstall EP completely and make a restart.
> 2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> 3. make another restart.
> 4. Install EP again
> 5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> 6. After symbols notification, make one last restart.
> 
> After this, everything will work fine.

This solved my issue!

**Comment by johnwasme** [comment] 2023-08-12 19:27
I tried that method and waited 15 minutes but no symbols were downloaded.

**Comment by pyrates999** [comment] 2023-08-13 00:47
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by johnwasme** [comment] 2023-08-13 03:13
I clicked on the console and it displayed that the symbols were downloaded and installed but explorer still crashes at times.

**Comment by pyrates999** [comment] 2023-08-13 06:11
Please wait for a new release that fixes it.  It is being worked on by @Vipin2003.

**Comment by sephdoto** [comment] 2023-08-13 16:39
> > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> 
> You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> 
> To fix this issue, follow these steps now:
> 
> 1. Uninstall EP completely and make a restart.
> 2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> 3. make another restart.
> 4. Install EP again
> 5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> 6. After symbols notification, make one last restart.
> 
> After this, everything will work fine.

Seems to have fixed mine as well.

**Comment by m7d2** [comment] 2023-08-13 22:43
> > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> 
> You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> 
> To fix this issue, follow these steps now:
> 
> 1. Uninstall EP completely and make a restart.
> 2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> 3. make another restart.
> 4. Install EP again
> 5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> 6. After symbols notification, make one last restart.
> 
> After this, everything will work fine.

Doesn't work

**Comment by pyrates999** [comment] 2023-08-13 22:47
> > > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> > 
> > 
> > You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> > To fix this issue, follow these steps now:
> > 
> > 1. Uninstall EP completely and make a restart.
> > 2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> > 3. make another restart.
> > 4. Install EP again
> > 5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> > 6. After symbols notification, make one last restart.
> > 
> > After this, everything will work fine.
> 
> Doesn't work

Can you post your windows version, build, and explorer patcher version that you installed?

**Comment by m7d2** [comment] 2023-08-13 22:51
> > > > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> > > 
> > > 
> > > You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> > > To fix this issue, follow these steps now:
> > > 
> > > 1. Uninstall EP completely and make a restart.
> > > 2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> > > 3. make another restart.
> > > 4. Install EP again
> > > 5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> > > 6. After symbols notification, make one last restart.
> > > 
> > > After this, everything will work fine.
> > 
> > 
> > Doesn't work
> 
> Can you post your windows version, build, and explorer patcher version that you installed?

Windows 11 v22H2 Build 22621.2134, EP v22621.1992.56.1

**Comment by Revan7even** [comment] 2023-08-14 00:17
Edition	Windows 11 Pro
Version	22H2
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

Restarted PC after applying KB5029263 and Explorer Patcher crashed on startup. Restarted again and same thing.
Uninstalled KB5029263 (I can keep it uninstalled since I have GPEdit set to check but let me install), restarted and Explorer Patcher works fine.

**Comment by pyrates999** [comment] 2023-08-14 00:18
Please do the following:

1. wait for explorer to crash 3 times and let it show that error message about how it will stop reloading now
2. open up windows event viewer or computer management
3. go to Event Viewer and go to Windows Logs -> Application
4. check the logs here for explorer.exe and paste them here

**Comment by Revan7even** [comment] 2023-08-14 01:04
> Please do the following:
> 
>     1. wait for explorer to crash 3 times and let it show that error message about how it will stop reloading now
>     2. open up windows event viewer or computer management
>     3. go to Event Viewer and go to Windows Logs -> Application
>     4. check the logs here for explorer.exe and paste them here

Well, now I can't recreate it after reinstalling KB5029263. Restarted two more times to try and get it to happen. However, this time I received a notification "Successfully downloaded symbols for OS build 10.0.22621.2134". This did not occur before because it crashed 3 times.

**Comment by pyrates999** [comment] 2023-08-14 03:06
I suspect it was because the symbols had now downloaded yet combined with a setting you had that was causing it to crash.

**Comment by mr-asa** [comment] 2023-08-14 09:29
I don't know if it's a fluke or not, but I stopped having exlorerpatcher crash after a BIOS update on my laptop. After rebooting the computer, everything loaded in exlorerpatcher and now it works stably. (in case this information will help someone somehow)

**Comment by emeyedeejay** [comment] 2023-08-14 10:57
`Faulting application name: explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c
Faulting module name: twinui.pcshell.dll, version: 10.0.22621.2070, time stamp: 0x0eca457b
Exception code: 0xc0000409
Fault offset: 0x00000000001ab0cd
Faulting process ID: 0x0x6774
Faulting application start time: 0x0x1D9CE9D006DA569
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\twinui.pcshell.dll
Report ID: 603fb096-6edb-4abb-80cc-23f3d1bd8741
Faulting package full name: 
Faulting package-relative application ID: `

`Faulting application name: explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c
Faulting module name: ntdll.dll, version: 10.0.22621.2134, time stamp: 0xeee69ec7
Exception code: 0xc0000374
Fault offset: 0x000000000010c239
Faulting process ID: 0x0x6DF4
Faulting application start time: 0x0x1D9CE9D08E98F31
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 096cf25f-264e-40a4-b54a-335abd6fc6e7
Faulting package full name: 
Faulting package-relative application ID: `



> Please do the following:
> 
> 1. wait for explorer to crash 3 times and let it show that error message about how it will stop reloading now
> 2. open up windows event viewer or computer management
> 3. go to Event Viewer and go to Windows Logs -> Application
> 4. check the logs here for explorer.exe and paste them here

`Faulting application name: explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c
Faulting module name: twinui.pcshell.dll, version: 10.0.22621.2070, time stamp: 0x0eca457b
Exception code: 0xc0000409
Fault offset: 0x00000000001ab0cd
Faulting process ID: 0x0x6774
Faulting application start time: 0x0x1D9CE9D006DA569
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\twinui.pcshell.dll
Report ID: 603fb096-6edb-4abb-80cc-23f3d1bd8741
Faulting package full name: 
Faulting package-relative application ID: `

`Faulting application name: explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c
Faulting module name: ntdll.dll, version: 10.0.22621.2134, time stamp: 0xeee69ec7
Exception code: 0xc0000374
Fault offset: 0x000000000010c239
Faulting process ID: 0x0x6DF4
Faulting application start time: 0x0x1D9CE9D08E98F31
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 096cf25f-264e-40a4-b54a-335abd6fc6e7
Faulting package full name: 
Faulting package-relative application ID: `

2 from a couple of minutes ago. They seem to be in pairs like this.

**Comment by miku1881** [comment] 2023-08-15 01:59
ログの名前:         Application
ソース:           Application Error
日付:            2023/08/12 9:28:00
イベント ID:       1000
タスクのカテゴリ:      アプリケーション クラッシュ イベント
レベル:           エラー
キーワード:         
ユーザー:          DESKTOP-TVKFUGQ\miku1
コンピューター:       DESKTOP-TVKFUGQ
説明:
障害が発生しているアプリケーション名: explorer.exe、バージョン: 10.0.22621.2070、タイム スタンプ: 0x2bd7252c
障害が発生しているモジュール名: twinui.pcshell.dll、バージョン: 10.0.22621.2070、タイム スタンプ: 0x0eca457b
例外コード: 0xc0000409
障害オフセット: 0x00000000001ab0cd
障害が発生しているプロセス ID: 0x0x4E94
障害が発生しているアプリケーションの開始時刻: 0x0x1D9CCB3D3045406
障害が発生しているアプリケーション パス: C:\WINDOWS\explorer.exe
障害が発生しているモジュール パス: C:\WINDOWS\SYSTEM32\twinui.pcshell.dll
レポート ID: 951f52eb-2b41-4e8f-bc32-20692052014e
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID: 
イベント XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-12T00:28:00.7730662Z" />
    <EventRecordID>119076</EventRecordID>
    <Correlation />
    <Execution ProcessID="21144" ThreadID="21148" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-TVKFUGQ</Computer>
    <Security UserID="S-1-5-21-2936407668-1429154489-3045782074-1001" />
  </System>
  <EventData>
    <Data Name="AppName">explorer.exe</Data>
    <Data Name="AppVersion">10.0.22621.2070</Data>
    <Data Name="AppTimeStamp">2bd7252c</Data>
    <Data Name="ModuleName">twinui.pcshell.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.2070</Data>
    <Data Name="ModuleTimeStamp">0eca457b</Data>
    <Data Name="ExceptionCode">c0000409</Data>
    <Data Name="FaultingOffset">00000000001ab0cd</Data>
    <Data Name="ProcessId">0x4e94</Data>
    <Data Name="ProcessCreationTime">0x1d9ccb3d3045406</Data>
    <Data Name="AppPath">C:\WINDOWS\explorer.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\SYSTEM32\twinui.pcshell.dll</Data>
    <Data Name="IntegratorReportId">951f52eb-2b41-4e8f-bc32-20692052014e</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by kuriandungu** [comment] 2023-08-15 08:33
> > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> 
> You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> 
> To fix this issue, follow these steps now:
> 
> 1. Uninstall EP completely and make a restart.
> 2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> 3. make another restart.
> 4. Install EP again
> 5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> 6. After symbols notification, make one last restart.
> 
> After this, everything will work fine.

This works!

**Comment by ctitoc** [comment] 2023-08-15 12:58
> > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> 
> You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> 
> To fix this issue, follow these steps now:
> 
> 1. Uninstall EP completely and make a restart.
> 2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> 3. make another restart.
> 4. Install EP again
> 5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> 6. After symbols notification, make one last restart.
> 
> After this, everything will work fine.

Tried this, but it's still crashing like hell

Windows 11 Home 22H2

ver 22621.2134

ExplorerPatcher
22621.1992.56.1

The issue started after windows 11 last automatic update.

**Comment by InfiniteImp** [comment] 2023-08-16 02:30
Might as well add my experience.   I've also been getting explorer.exe crash/restarts every second time I open explorer.  This started after a recent Windows update.

ExplorerPatcher v22621.1992.56.1
Win11 22H2 build 22621.2134.

I followed the steps from @Vipin2003 including waiting for symbols to update and doing all the reboots but it didn't solve the problem.

Windows will not let me uninstall KB5029263 so can't try that as a possible fix.

Looking in event viewer, this is the error each time explorer crashes:

Faulting application name: explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.2070, time stamp: 0xa1d6b8fe
Exception code: 0xc000027b
Fault offset: 0x00000000008720c0
Faulting process id: 0x0xFE8
Faulting application start time: 0x0x1D9CFE8A87651F5
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 580987d8-c9f9-418f-8391-ca2f77c8e7a6
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Vipin2003** [comment] 2023-08-16 03:06
> Might as well add my experience. I've also been getting explorer.exe crash/restarts every second time I open explorer. This started after a recent Windows update.
> 
> ExplorerPatcher v22621.1992.56.1 Win11 22H2 build 22621.2134.
> 
> I followed the steps from @Vipin2003 including waiting for symbols to update and doing all the reboots but it didn't solve the problem.
> 
> Windows will not let me uninstall KB5029263 so can't try that as a possible fix.
> 
> Looking in event viewer, this is the error each time explorer crashes:
> 
> Faulting application name: explorer.exe, version: 10.0.22621.2070, time stamp: 0x2bd7252c Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.2070, time stamp: 0xa1d6b8fe Exception code: 0xc000027b Fault offset: 0x00000000008720c0 Faulting process id: 0x0xFE8 Faulting application start time: 0x0x1D9CFE8A87651F5 Faulting application path: C:\Windows\explorer.exe Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll Report Id: 580987d8-c9f9-418f-8391-ca2f77c8e7a6 Faulting package full name: Faulting package-relative application ID:

What can I fo bro... I also tried to point out this problem with a PR, but valinet close that PR by marking it as a spam. You can directly make a comment in that PR by mentioning valinet. So, that he can do something for that. I'm not mentioning him for a reason. If you guys make comment in that PR, maybe valinet release a fix for that.

**Comment by plakic** [comment] 2023-08-16 04:59
> > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> 
> You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> 
> To fix this issue, follow these steps now:
> 
>     1. Uninstall EP completely and make a restart.
> 
>     2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> 
>     3. make another restart.
> 
>     4. Install EP again
> 
>     5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> 
>     6. After symbols notification, make one last restart.
> 
> 
> After this, everything will work fine.

This worked for me.

**Comment by johnwasme** [comment] 2023-08-16 05:33
This method only works for some computers,not all,my system still crashes no matters what i do.

**Comment by himynameisubik** [comment] 2023-08-16 08:07
> > @Vipin2003 : #1834 mentions a few bugs but no systematic crash like this issue.
> 
> You tried to access explorer or R-clicked on taskbar after immediate update.. And you haven't wait for symbols to download. That's why, this happens.
> 
> To fix this issue, follow these steps now:
> 
> 1. Uninstall EP completely and make a restart.
> 2. After restart, delete all EP reg. keys : `HKEY_CURRENT_USER\Software\ExplorerPatcher` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher`
> 3. make another restart.
> 4. Install EP again
> 5. wait for Symbols to be downloaded. Don't even touch taskbar. It will take around 5-6 min
> 6. After symbols notification, make one last restart.
> 
> After this, everything will work fine.

This only worked for me if I use Windows 10 task bar style. As soon as I change to the Windows 11 (default) unfortunately it crashes on right-click.

So, for win 10 task bar style it works, win 11 not.

22H2 Build: 22621.2134

**Comment by pyrates999** [comment] 2023-08-16 11:09
> already mentioned in PR #1834

I checked your code changes.  How does changing the version number fix the bugs that were found?

**Comment by Vipin2003** [comment] 2023-08-16 11:12
> > already mentioned in PR #1834
> 
> I checked your code changes. How does changing the version number fix the bugs that were found?

I'm trying to fix the bug with code changes... I've to do something at that time to push my commit. So, I only just make a commit there, without any code.

**Comment by InfiniteImp** [comment] 2023-08-16 13:23
> This only worked for me if I use Windows 10 task bar style. As soon as I change to the Windows 11 (default) unfortunately it crashes on right-click.
> 
> So, for win 10 task bar style it works, win 11 not.
> 
> 22H2 Build: 22621.2134

I'm running the Win10 task bar style and it's still crashing.  So, there's more to it than that.

Now this is interesting!  I just switched to the Win11 task bar style and it only crashed once in 10 attempts to open file explorer.  With the Win10 style it would consistently crash every 2 opens.  Thanks @himynameisubik .  I'll take any improvement I can get!

**Comment by InfiniteImp** [comment] 2023-08-16 13:37
> I was using Windows 10 style taskbar as well when I uninstalled and reinstalled KB5029263 when it downloaded icons and started working again.

Is there anything special you had to do to uninstall that update?  Windows doesn't list it as one that I can uninstall.

**Comment by Revan7even** [comment] 2023-08-16 13:39
> > I was using Windows 10 style taskbar as well when I uninstalled and reinstalled KB5029263 when it downloaded icons and started working again.
> 
> Is there anything special you had to do to uninstall that update? Windows doesn't list it as one that I can uninstall.

I'm using Pro, it's a security update which might not be an option to uninstall on Home.

**Comment by m7d2** [comment] 2023-08-16 13:43
> > > I was using Windows 10 style taskbar as well when I uninstalled and reinstalled KB5029263 when it downloaded icons and started working again.
> > 
> > Is there anything special you had to do to uninstall that update? Windows doesn't list it as one that I can uninstall.
> 
> I'm using Pro, it's a security update which might not be an option to uninstall on Home.

Don't Uninstall system updates for the sake of this broken software. The problem is the program itself not being compatible with recent updates and we should wait the creator to push new version because there's no work around it. Until then just uninstall EP

**Comment by himynameisubik** [comment] 2023-08-16 13:59
> > This only worked for me if I use Windows 10 task bar style. As soon as I change to the Windows 11 (default) unfortunately it crashes on right-click.
> > So, for win 10 task bar style it works, win 11 not.
> > 22H2 Build: 22621.2134
> 
> I'm running the Win10 task bar style and it's still crashing. So, there's more to it than that.
> 
> Now this is interesting! I just switched to the Win11 task bar style and it only crashed once in 10 attempts to open file explorer. With the Win10 style it would consistently crash every 2 opens. Thanks @himynameisubik . I'll take any improvement I can get!
> 
> EDIT: Actually, never mind. With the Win11 style I can't right-click on the taskbar without crashing. Back to Win10 style. Really hoping this gets fixed soon.

Yup exactly. Win 11 style crashes right-click. With Win 10 right-click works. But I've uninstalled it for now and live with the Start Menu "Recommendations" as this was the only thing that really bothered me on Win 11.

**Comment by HughKallen** [comment] 2023-08-16 15:25
**### FYI, two days ago my wife's Win 11 laptop would not even finish starting up. As explorer was loading (taskbar partly loaded) it would crash, give a gray screen, then crash again. Eventually it would stop with just a gray screen. Nothing on the screen. Task manager would open via ctrl-leftshift-esc but that was it. There was no way around it. Safe mode did the same thing. Eventually I had to do a clean install of windows keeping data. It was a huge sh*tshow and a big headache with a day of productivity lost.**

**Comment by Vipin2003** [comment] 2023-08-16 15:42
> **### FYI, two days ago my wife's Win 11 laptop would not even finish starting up. As explorer was loading (taskbar partly loaded) it would crash, give a gray screen, then crash again. Eventually it would stop with just a gray screen. Nothing on the screen. Task manager would open via ctrl-leftshift-esc but that was it. There was no way around it. Safe mode did the same thing. Eventually I had to do a clean install of windows keeping data. It was a huge sh*tshow and a big headache with a day of productivity lost.**

Try opening taskmgr using that method... after that, go to "new task" and type explorer and hit enter. 
It will start the explorer. Let it crash for 3-4 times in 10 sec. After which, win10 taskbar will be disabled. Open EP settings and change taskbar to win11 and enable "do not change context menu" option from Advanced in EP settings and make a restart. It will be fixed.
There is currently no way to fix win10 taskbar. So, use win11 taskbar till it gets a fix.

**Comment by HughKallen** [comment] 2023-08-16 18:06
> Try opening taskmgr using that method... after that, go to "new task" and type explorer and hit enter.
It will start the explorer. Let it crash for 3-4 times in 10 sec. After which, win10 taskbar will be disabled. Open EP settings and change taskbar to win11 and enable "do not change context menu" option from Advanced in EP settings and make a restart. It will be fixed.

Hopefully this will be helpful to someone, too late for us now.

**Comment by pyrates999** [comment] 2023-08-17 13:18
> > > already mentioned in PR #1834
> > 
> > 
> > I checked your code changes. How does changing the version number fix the bugs that were found?
> 
> I'm trying to fix the bug with code changes... I've to do something at that time to push my commit. So, I only just make a commit there, without any code.

You shouldn't do a commit if nothing is fixed in your commit.

**Comment by trun4o** [comment] 2023-08-18 11:29
`reg.exe add "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve 
reg.exe add "HKCU\Software\Classes\CLSID{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}\InprocServer32" /f /ve`

That fixed every second folder open crash (at least for me).

**Comment by PCL86** [comment] 2023-08-18 12:40
> `reg.exe add "HKCU\Software\Classes\CLSID{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" /f /ve
> 
> reg.exe add "HKCU\Software\Classes\CLSID{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}\InprocServer32" /f /ve `
> 
> That fixed every second folder open crash (at least for me).

I tried adding the registry key, it didn't work in my environment.
By the way
'reg.exe add "HKCU\Software\Classes\CLSID{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}\InprocServer32" /f /ve'
teeth
'reg.exe add "HKCU\Software\Classes\CLSID\{d93ed569-3b3e-4bff-8355-3c44f6a52bb5}\InprocServer32" /f /ve'
Isn't it?

The backslash after CLSID was missing.

**Comment by InfiniteImp** [comment] 2023-08-18 13:26
Ya I just tried the above reg adds (with the added backslashes) as well and no change for me.  Still crashing every second open.

**Comment by InfiniteImp** [comment] 2023-08-18 13:59
Ok, I found a solution that worked for me.  I did the following:

1. I am running OpenShell so I made to update to the latest ver (191) as noted in another ticket here on github.
2. Uninstall ExplorerPatcher.  It asked for a reboot so I did that.
3. Went into Regedit and searched for ExplorerPatcher.  Removed anything that looked like leftover settings.  I left stuff like MRU and Applet settings
4. Restarted.
5. Reinstalled ExplorerPatcher.  Waited for it to download symbols.  It did that in a minute and asked me to restart file explorer.
6. Right-clicked the taskbar, selected Properties and clicked Restart File Explorer* at the bottom.
7. It then repeated the 'downloaded symbols, restart file explorer' notification a few times but it was just notifying me of the same OS version each time so after restarting explorer 3 times I stopped.
8. Opened file explorer 4 times, no crashes.  Just tried it now and it still opens without crashing
9. I noticed that file explorer now shows the full ribbon at the top (Properties, Media Access, Map network drive, etc).  It's possible I had that turned off via an EP setting before.

Hope this helps someone.

**Comment by Daisyfan1995** [comment] 2023-08-18 14:14
More Problems Crash when uninstall windows 11 versions when windows updates with updates history > Unistall updates for regression to windows 11 older.

**Comment by gcc-compiled** [comment] 2023-08-19 05:30
After some troubleshooting on a brand new user profile on my machine I have determined for my particular case that ticking "Do not change the staskbar context"menu has fixed my right clicking issue. After some new issues within the repo it seems other people have done this aswell.

I have tried the previous mentioned regexes and they did not work. Potentially issue is from the taskbar settings menu, worth looking into that area but everything else is working fine with that option ticked.

**Comment by PCL86** [comment] 2023-08-19 12:13
> Ok, I found a solution that worked for me. I did the following:
> 
>     1. I am running OpenShell so I updated to the latest ver (191) as noted in another ticket here on github.
> 
>     2. Uninstall ExplorerPatcher.  It asked for a reboot so I did that.
> 
>     3. Went into Regedit and searched for ExplorerPatcher.  Removed anything that looked like leftover settings (there were quite a few).  I left stuff like MRU and Applet settings
> 
>     4. Restarted.
> 
>     5. Reinstalled ExplorerPatcher.  Waited for it to download symbols.  It did that in a minute and asked me to restart file explorer.
> 
>     6. Right-clicked the taskbar, selected Properties and clicked Restart File Explorer* at the bottom.
> 
>     7. It then repeated the 'downloaded symbols, restart file explorer' notification a few times but it was just notifying me of the same OS version each time so after restarting explorer 3 times I stopped.
> 
>     8. Opened file explorer 4 times, no crashes.  Just tried it now and it still opens without crashing
> 
>     9. I noticed that file explorer now shows the full ribbon at the top (Properties, Media Access, Map network drive, etc).  It's possible I had that turned off via an EP setting before.
> 
> 
> Hope this helps someone.

thank you.
This measure also worked in my environment, and Explorer crashes no longer occur.

**Comment by InfiniteImp** [comment] 2023-08-20 19:10
I just noticed that even though file explorer does not crash any more, it also doesn't have tabs.  It's as if I was running the old file explorer (before Win11 22H2).   Tried various things to bring the new file explorer back but with no luck.  Sfc /scannow reported corrupted files and repaired them but no change.  Obviously I'll take no tabs over explorer crashing every 2 opens but I'm curious how this happened.

**Comment by pyrates999** [comment] 2023-08-20 22:18
> I just noticed that even though file explorer does not crash any more, it also doesn't have tabs. It's as if I was running the old file explorer (before Win11 22H2). Tried various things to bring the new file explorer back but with no luck. Sfc /scannow reported corrupted files and repaired them but no change. Obviously I'll take no tabs over explorer crashing every 2 opens but I'm curious how this happened.

No tabs in file explorer is a known issue.

**Comment by M0lyk** [comment] 2023-08-21 06:19
I have also followed the above solution to the letter. I had a silent installation and indeed after 3 minutes I received a notification telling me that the symbols had been installed. Then I rebooted and everything works fine, as before, but I still get a crash with a right-click on the taskbar.

I've gone back to another tip suggested elsewhere to avoid this: In ExplorerPatcher's properties > Advanced > uncheck `Do not change the taskabr context menu (e.g. do not display the "Properties" ite…`

**Comment by ctitoc** [comment] 2023-08-22 00:01
I don't exactly know what happened, but I tried to clean up all regedit and it didn't solve the issue. So I uninstalled Explorerpatcher and used W11 as default.

After getting 2 work days being kicked in the *** with the combined W11 taskbar (I've never learned how to be productive with combined taskbar since W8), I tried to install ExplorerPatcher again.

So I downloaded the installer (from https://github.com/valinet/ExplorerPatcher/releases) and installed it. It began with W11 taskbar as default, and everything worked as it should while in W11 taskbar, EXCEPT for the W10 taskbar. It began to crash multiple times and didn't work

Then fileexplorer told me I had an update available (22621.1992.56.1) and I read the "about" section of the filexplorer and it wans't my version. I used the "restart and update" feature from properties and it installed successfully. Right on the moment I tried W10 taskbar and IT WORKED as it always had.

Restarted multiple times and continues to work. I really don't know what happened, but at least I hope I help somebody with this story.

**Comment by Poopooracoocoo** [comment] 2023-08-22 11:40
Duplicate of #1798

**Closed by Poopooracoocoo** 2023-08-22 11:40 UTC

**Comment by sultan99** [comment] 2023-09-06 16:08
@ctitoc does "tasks veiw" (win + tab) work for you?

**Comment by ctitoc** [comment] 2023-09-06 17:32
No it doesn’t, unfortunately, but alt+tab works just fine!

Em qua., 6 de set. de 2023 às 13:09, Sultan ***@***.***>
escreveu:

**Comment by NifTTY** [comment] 2023-09-13 23:25
Can confirm that uninstalling and blocking KB5029263 seems to resolve and prevent the issue.

**Comment by v0idp** [comment] 2023-09-18 19:03
> I have also followed the above solution to the letter. I had a silent installation and indeed after 3 minutes I received a notification telling me that the symbols had been installed. Then I rebooted and everything works fine, as before, but I still get a crash with a right-click on the taskbar.
> 
> I've gone back to another tip suggested elsewhere to avoid this: In ExplorerPatcher's properties > Advanced > uncheck `Do not change the taskabr context menu (e.g. do not display the "Properties" ite…`

THIS actually fixed my issue with right-click crashing it.

**Comment by Amrsatrio** [comment] 2023-09-23 03:09
Please install the newly released EP build. The new version should never do irrecoverable crashes like these anymore. There should be no more major issues on 22621 builds up to 22621.2359.

新しいEPのビルドをインストールしてください。新しいバージョンは、このような回復不可能なクラッシュをしないはずです。22621.2359までの22621ビルドでは、もう大きな問題はないはずです。

**Comment by InfiniteImp** [comment] 2023-09-26 20:56
Version 58.1 (just released) fixed this for me!   
My thanks to @valinet and anyone else involved.

**Comment by valinet** [comment] 2023-09-26 21:54
> Version 58.1 (just released) fixed this for me!
> My thanks to @valinet and anyone else involved.

Thank @Amrsatrio, he worked on almost all of the fixes. I thank him. 🙏

**Comment by InfiniteImp** [comment] 2023-09-26 21:57
Well then, thanks @Amrsatrio !  Appreciate all your time.

**Comment by v0idp** [comment] 2023-10-07 11:06
finally fixed and I can use the contextmenu again!
