### ISSUE TITLE
Fn keys won't display volume anymore

### ISSUE THREAD

**Issue by LAPIII** [valinet/ExplorerPatcher#1791] opened 2023-08-07 11:02 UTC
I don't know if that is because of this software, can you tell me if it is? My OS is Windows 11 Pro 10.0.22621 and I have the latest ExplorerPatcher Version 22621.1992.56.1.

**Comment by Vipin2003** [comment] 2023-08-07 13:02
It is bcoz u r using preview build... It is a bug in that

**Comment by SoftWyer** [comment] 2023-08-07 15:45
I have the same with version 22621.1992.56.1.  This is the **release** build.

**Comment by pyrates999** [comment] 2023-08-07 22:46
You most likely are running a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by saulob** [comment] 2023-08-08 03:18
I got the same problem , and I'm using no preview version

I'm using taskbar style Windows 10, If I use Windowss 11 the volume OSD appears. It's not working with the Windows 10 style

![image](https://github.com/valinet/ExplorerPatcher/assets/3660977/71e928ad-7285-435b-8a12-555d93980110)

**Comment by pyrates999** [comment] 2023-08-08 04:56
Run winver and show what it shows here.

**Comment by Rainman67** [comment] 2023-08-08 05:41
I have the same problem. Since installing the update kb5028254, this problem occurred. First this was a preview update and I uninstalled it and changed the switch to "no preview updates". This solved the problem for about one week or so. And then the same update came as an regular update again. And with this update came the bug back again :-(

 Winver shows 22H2 Build 22621.2070

After uninstalling explorer patcher all is working fine. When I use other Tools (like Start is back or Start11 for example), all is fine too. 

It would be nice, if you can fix this bug, because i prefer your tool instead the others. Sorry for my bad english!

**Comment by pyrates999** [comment] 2023-08-08 06:22
> I have the same problem. Since installing the update kb5028254, this problem occurred. First this was a preview update and I uninstalled it and changed the switch to "no preview updates". This solved the problem for about one week or so. And then the same update came again as a regular update. And with this update came the bug back again :-(
> 
> "Winver" shows 22H2 Build 22621.2070
> 
> After uninstalling explorer patcher all is working fine. When I use other Tools (like Start is back or Start11 for example), all is fine too.
> 
> It would be nice if you can fix this bug, because i prefer your tool instead the others. Sorry for my bad English!

That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by Rainman67** [comment] 2023-08-08 06:31
As i wrote before, this update first was installed as an "preview". After getting the problems i uninstalled this update, unticked "Get the latest updates as soon as available" and for one week or so all was fine. But after a few days the same update was offered me again (the option was unticked), and after installing it, the bug was back again. I think, that microsoft changed this update from "preview" to "regular".

**Comment by pyrates999** [comment] 2023-08-08 06:33
Nope.  If it was not automatically installed, and only prompting you to install it, the setting is doing what it says.  You chose to install it.  So uninstall it and don't install it again.

**Comment by bubbismith** [comment] 2023-08-08 20:32
I'm having a similar problem again today with the updates it auto-installed. As @saulob said, it goes away if you enable the Win11 taskbar (oh... please, save me from that.... 👍 :-)) Here's my WinVer and also the update done today

![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/44269c3f-adbb-4cf4-acce-bf4376bb9907)

![image](https://github.com/valinet/ExplorerPatcher/assets/30091315/11a07018-b1d5-48b8-81a3-57012cb4ec1a)

**Comment by okplayer-net** [comment] 2023-08-08 20:37
I have the same problem with the missing sliders-overlay. 
Will this be patched by the DEVs of EP? 
The thing with uninstalling of KB 50028254 is no longer possible. due to the new updates of today. 

The recomended tweak by @saulob does not fix it. On my rig at least. 

I´m on the same version as @bubbismith.

**Comment by pyrates999** [comment] 2023-08-08 21:10
Considering this is a regular update, then yes it should be fixed by the dev's of explorer patcher.

**Comment by Menno5** [comment] 2023-08-09 08:00
ExplorerPatcher 22621.1992.56.1.
Windows 11 Pro 22H2 / build 22621.2134

I can confirm cause the same problem here now: yesterday KB5029263 and KB5028948 were installed during the normal Windows update and the onscreen volume slider is gone now.

**Comment by FaustKnight** [comment] 2023-08-09 13:50
Can confirm I installed KB5028948 and KB5029263 and my OSD no longer appears. 

22H2 22621.2134

**Comment by Paft** [comment] 2023-08-09 19:44
( I normally have updates paused, but was lazy and just decided to let it update without investigating each one [stupid that we have to do this] )

So which update actually broke the OSD? KB5028948, KB5028254  or KB5029263 . Or is it a mixture?

I assumed it was **KB5028254** since that's technically a Preview even though it doesn't show that in Windows, and people were reporting that a week or so ago. https://github.com/valinet/ExplorerPatcher/issues?q=is%3Aissue+is%3Aopen+volume

But when I uninstalled **KB5029263** (which is supposed to be a final update?) the OSD was back.

I went from 22621.2134 back to 22621.1992. By uninstalling KB5029263. I don't think I can easily uninstall KB5028254 as it isn't showing in 'uninstall updates'.  I do however have images I could potentially revert to.

**Comment by fuste76** [comment] 2023-08-09 19:58
Guess, it must be KB5028948 or KB5029263. I have the same issue, but never seen KB5028254  on my system.

**Comment by alandsidel** [comment] 2023-08-09 20:46
Same issue here.  OSD stopped working after installing KB5029263 and KB5028948 for Win11 Pro yesterday.  Preview updates never enabled or installed.    Winver reports 22H2 (OS Build 22621.2134).  The OSD does work if I uninstall ExplorerPatcher, stops working as soon as I reinstall.

Not on a laptop, no Fn keys to worry about here, just normal media keyboard with volume controls.  The volume controls do work fine still, just no OSD.

**Comment by Paft** [comment] 2023-08-09 22:38
> Same issue here. OSD stopped working after installing KB5029263 and KB5028948 for Win11 Pro yesterday. Preview updates never enabled or installed. Winver reports 22H2 (OS Build 22621.2134). The OSD does work if I uninstall ExplorerPatcher, stops working as soon as I reinstall.
> 
> Not on a laptop, no Fn keys to worry about here, just normal media keyboard with volume controls. The volume controls do work fine still, just no OSD.

Yeah, I wasn't clear. FN keys are irrelevant as those are just keys, and it's Explorer Patcher that technically causes the OSD not to show with some specific update.

**Comment by alandsidel** [comment] 2023-08-10 01:59
> Yeah, I wasn't clear. FN keys are irrelevant as those are just keys, and it's Explorer Patcher that technically causes the OSD not to show with some specific update.

Sure, but they're in the report title from the OP as well, just wanted to make sure @valinet knows it's unrelated and has something to do with one of these updates; probably the OS rollup, seems unlikely that it was the .net update.

**Comment by gchorbov** [comment] 2023-08-10 09:14
+1, same problem here

EP version: 22621.1992.56.1
Win 11 version: 22H2; 22621.2134

I've tried to uninstall windows update KB5028254, but it is not listed as available for uninstall. I dont know why...

How can I uninstall the update?
What is the solution if I cannot uninstall this fu****ng update?

**Comment by pyrates999** [comment] 2023-08-10 12:48
https://www.windowslatest.com/2021/04/23/how-to-uninstall-windows-10-updates-manually/

**Comment by pyrates999** [comment] 2023-08-11 10:50
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1692

Please close this one.

**Comment by okplayer-net** [comment] 2023-08-20 10:29
As a temporary fix to get some overlay information on the screen I got the small app called "modernflyouts" from the Microsoft store. I wish this wasn´t nesesary but better then nothing to hold over ´till patcher gets fixed.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:29
Duplicate of #1692

**Closed by Poopooracoocoo** 2023-08-22 10:29 UTC
