### ISSUE TITLE
win 11 Properties missing

### ISSUE THREAD

**Issue by Dan-Essin** [valinet/ExplorerPatcher#3947] opened 2024-11-19 20:41 UTC
I removed and reinstalled EP because, suddenly, mt taskbar rt-click was missing the "Properties". It installed and working with my old prefs bu the Properties are still not accessible because the item is missing from the menu
![2024-11-19_12h40_59](https://github.com/user-attachments/assets/23b9c191-c05a-4a63-9e14-e61eb297d163)

**Comment by Amrsatrio** [comment] 2024-11-19 22:07
Duplicate of #3944

**Closed by Amrsatrio** 2024-11-19 22:07 UTC
