### ISSUE TITLE
Windows 11 classic Address Bar in File Explorer has stopped working 

### ISSUE THREAD

**Issue by davuses** [valinet/ExplorerPatcher#2771] opened 2024-02-01 09:13 UTC
I noticed that the *Windows 11 classic Address Bar* option in *File Explorer* hasn't stopped working since a few days ago. See the screenshot below:

<img width="974" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/54793121/dc24ad60-dcc8-4e88-bc4f-fb9dd3b7bd94">

As shown in the image, the address bar is of the new style.

Some debug information:

ExplorerPatcher Version `22621.2861.62.2`
Running on `Windows 11, OS Build 22631.3007.`

Also there's no other applications installed on my computer that modifies the File Explorer UI.

A couple screenshots of settings that might be helpful:

<img width="595" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/54793121/450a77ca-a96f-4ddb-85f7-b52237de824f">

<img width="595" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/54793121/77cfa9ac-20ad-4b95-8f92-2c83d0fe0e1c">
<img width="599" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/54793121/32dbef79-5004-46a2-80c2-6b777cfd6cd5">

**Comment by pyrates999** [comment] 2024-02-01 11:03
disable the option register as shell extension by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

Here's why: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by davuses** [comment] 2024-02-01 11:13
> disable the option register as shell extension by opening up the EP properties application, go to **File Explorer**, and untick **Register as shell extension**.

This doesn't seem to solve the issue. the address bar remains new style after I disable the option and restart File Explorer. See the screenshots:

<img width="588" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/54793121/c74aaba2-e574-4979-a1ef-c07e0776c970">

<img width="955" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/54793121/eb335beb-dadc-4533-a99d-ab8c424370e2">

**Comment by pyrates999** [comment] 2024-02-01 12:39
Try disabling dark mode.

**Comment by pyrates999** [comment] 2024-02-01 14:47
Did you run the vive tool?

**Comment by Amrsatrio** [comment] 2024-02-02 03:48
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2701

@pyrates999 Running ViVeTool to disable the feature flag will cause crashes starting from an update from January, therefore that's why I've made that feature no longer work on such versions.

**Closed by Amrsatrio** 2024-02-02 03:48 UTC

**Comment by jedikalimero** [comment] 2024-02-17 19:02
Same issue here. Dark mode is disabled and EP is not registered as shell extension but when I select "Windows 11 Command Bar (classic Address Bar)", there is no difference with "Windows 11 Command Bar (default)" option.

As a consequence I can not drop a file into the address bar breadcrumbs to move it to a parent folder. This only works with "Windows 10 Ribbon" or "Windows 7 Command Bar", but then you lose explorer tabs.

I noticed this happening after latest Windows 11 update and it didn't fix with the current ExplorerPatcher update.

**Comment by rcrh** [comment] 2024-03-31 14:43
Has there been a resolution to this?  I'm in the same position.

**Comment by jedikalimero** [comment] 2024-04-02 01:29
> Has there been a resolution to this? I'm in the same position.

I "fixed" the issue by using another hack tool called **Windhawk**. This program can apply several hacks to the system that you download and install from the program itself and one of the hacks is called "Classic Explorer Navigation Bar".

You can download it at https://windhawk.net/

It is not the ideal solution needing to install yet another hack tool in the system but since the people at ExplorerPatcher don't fix this problem and it looks like it is not a priority for them to fix it in the near future despite the option is still selectable in the program, I had to use this hack tool.

Apart from **ExplorerPatcher** and **Windhawk/Classic Explorer Navigation Bar**, I am also using **Open Shell/Classic Explorer** to restore the functionality of the Start menu and some other things in the File Explorer and **OldNewExplorer** to move the details pane to the bottom as it was before so you can have details and preview panes open at once.

Yes, it seems the voyage of Microsoft Windows to stupidity needs a growing number of fixes every time to keep it functional for experienced users like us.

**Comment by rcrh** [comment] 2024-04-02 14:44
> > Has there been a resolution to this? I'm in the same position.
> 
> I "fixed" the issue by using another hack tool called **_Windhawk_**. This... 

Thanks!  This seems to be working.  But I fear Microsoft will break it... I mean "enhance" it again soon.

**Comment by jedikalimero** [comment] 2024-04-02 18:43
> > > Has there been a resolution to this? I'm in the same position.
> > 
> > 
> > I "fixed" the issue by using another hack tool called **_Windhawk_**. This...
> 
> Thanks [jedikalimero](https://github.com/jedikalimero)! This seems to be working. But I fear Microsoft will break it... I mean "enhance" it again soon.

They will. Microsoft always will f*ck what is perfectly working. That's a fundamental law of Computer Science 😅🤦

**Comment by davuses** [comment] 2024-04-16 12:26
@jedikalimero Thanks for introducing *Windhawk*! This works great, at least for now !
