### ISSUE TITLE
Windows search "flyout" position

### ISSUE THREAD

**Issue by glenviewjeff** [valinet/ExplorerPatcher#1443] opened 2023-05-12 12:37 UTC
I am not sure if this is a Windows bug or is related to ExplorerPatcher, but either way it would be great if we could fix it with ExplorerPatcher. My primary (and only) taskbar is on the right side of my screen. However, when I use the taskbar search feature by typing while the Start Menu is showing, the search flyout opens at the bottom left of my large monitor, as if my taskbar were on the bottom of the screen. This is new behavior that coincides with my Windows 11 upgrade and simultaneous installation of ExplorerPatcher. Previously, the flyout would correctly open adjacent to the start menu icon on the top-right corner of the screen.

![image](https://github.com/valinet/ExplorerPatcher/assets/334914/c417853b-379e-4d06-b7e3-5200683b95a3)

**Comment by glenviewjeff** [comment] 2023-05-12 12:49
The source of the bug doesn't really matter to me either way; it would be great if ExplorerPatcher could correct it.

**Comment by zuldero** [comment] 2023-05-23 09:20
i have the same problem. i think it is pointless to test it deinstalled. because than the taskbar would be at the buttom and than it would be obviously right. this did not happend. when i was istalling ExplorerPatcher something like a half year ago. i additionally observed that when i set the taskmenu to be centerd it is also center at the buttom of the screen (bassicly the same bug).

**Comment by pyrates999** [comment] 2023-05-23 10:28
Here's how you can try setting the taskbar to the side without having to install explorer patcher: https://pureinfotech.com/move-taskbar-top-side-windows-11/

It does say to install explorer patcher as a second way of doing this, but I would first try it without needing explorer patcher installed to prove if it's a bug with explorer patcher or not.

**Comment by zuldero** [comment] 2023-05-23 10:38
i tried it in the sandbox envoierment. the binary change did not affect anything. after explorer restart it was set back to 03. so i could not test it. and in my productive setup i will not edit the binary by myself. i evan dont like to edit the registry, casue of updates that will set it back.

**Comment by pyrates999** [comment] 2023-05-23 10:47
Windows sandbox most likely ignores what you set in the registry, therefore you should test it without it.

Just be prepared to start windows in safe mode just in case.

**Comment by frederick99** [comment] 2023-05-24 07:15
+1, this broke with the last windows 11 update for me too. would be great if explorer patcher can fix it.

**Comment by pyrates999** [comment] 2023-09-05 07:16
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1378

Please close this.

**Comment by Poopooracoocoo** [comment] 2023-09-25 16:17
Duplicate of #1378

**Closed by Poopooracoocoo** 2023-09-25 16:17 UTC
