### ISSUE TITLE
Taskbar too wide on right-hand side of screen.

### ISSUE THREAD

**Issue by apmReaper** [valinet/ExplorerPatcher#3091] opened 2024-04-04 17:15 UTC
I have dual monitors and my taskbars are set up on the left-hand side of the left screen, and the right-hand side of the right screen, which was never a problem, until recently where as shown in the image attached, the taskbar for some reason on the right screen has become really wide and there's no way for me to change it.

Left Screen: 4k resolution, scale 200%
Right Screen: 1440p resolution, scale 125%
(tried adjusting scales, that didn't work)

I've re-installed explorerpatcher but that didn't help.

Is there anything that can be done to fix this?

![Wide Taskbar](https://github.com/valinet/ExplorerPatcher/assets/166050428/d56efaff-054e-4851-be9e-cf5a2d6e97ef)

**Comment by pyrates999** [comment] 2024-04-05 00:37
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2964

please close this.

**Closed** 2024-04-05 07:03 UTC
