### ISSUE TITLE
The Properties button is missing

### ISSUE THREAD

**Issue by Lisyachiy-y** [valinet/ExplorerPatcher#3493] opened 2024-07-20 16:58 UTC
The Properties button disappeared when right-clicking on the taskbar. There is an application and I can access it through the start button, but not through the taskbar. How to return Properties?

**Comment by pyrates999** [comment] 2024-07-20 20:10
to run the explorer patcher properties application, run this from the run menu:
`C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`

Then go to advanced and make sure the option **Do not change the taskbar context menu (e.g. do not display the "Properties"** is not enabled. Then you can right click on the taskbar and you should see the **Properties** option.

If it doesn't show up now, or doesn't work, click on restart file explorer in the bottom left in the EP properties application.

You can also try to open up task manager and kill explorer.exe and then run task manager again and run explorer.exe.

Also try restarting your computer.

**Comment by Lisyachiy-y** [comment] 2024-07-21 08:51
I did everything you said, but the properties did not appear.

This originally happened after resetting explorerpatcher to default.

**Comment by Lisyachiy-y** [comment] 2024-07-21 08:52
> to run the explorer patcher properties application, run this from the run menu: `C:\Windows\System32\rundll32.exe "C:\Program Files\ExplorerPatcher\ExplorerPatcher.amd64.dll",ZZGUI`
> 
> Then go to advanced and make sure the option **Do not change the taskbar context menu (e.g. do not display the "Properties"** is not enabled. Then you can right click on the taskbar and you should see the **Properties** option.
> 
> If it doesn't show up now, or doesn't work, click on restart file explorer in the bottom left in the EP properties application.
> 
> You can also try to open up task manager and kill explorer.exe and then run task manager again and run explorer.exe.
> 
> Also try restarting your computer.

What else is fashionable to do?

**Comment by Lisyachiy-y** [comment] 2024-07-21 09:14
Reinstalling the program didn't work.

**Comment by Lisyachiy-y** [comment] 2024-07-21 09:20
Reinstalling the program didn't work.
@pyrates999

**Comment by pyrates999** [comment] 2024-07-21 10:26
In the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

**Comment by pyrates999** [comment] 2024-07-21 10:27
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment] 2024-07-21 11:23
@Lisyachiy-y

1. Are you using Windows 10 (ExplorerPatcher) taskbar?
2. If you are using any other taskbar than that, make sure this is off
<img width="607" alt="image" src="https://github.com/user-attachments/assets/f15ce662-3819-4ede-89dd-5593a4fef7ea">

**Comment by CloudeLecaw** [comment] 2024-07-21 22:34
![22-07-2024_00-33-45](https://github.com/user-attachments/assets/04132f87-7012-459a-9af2-089475b3ffef)

well i can agree its not there since i updated the windows version
![22-07-2024_00-34-39](https://github.com/user-attachments/assets/75608a09-0ad2-448d-96f7-9df8c3b0ed27)

**Comment by pyrates999** [comment] 2024-07-21 23:50
You're running a windows inside preview build: https://blogs.windows.com/windows-insider/2024/07/15/announcing-windows-11-insider-preview-build-26120-1252-dev-channel/

Please wait for this to get fixed.

**Comment by CloudeLecaw** [comment] 2024-07-22 04:16
> You're running a windows inside preview build: https://blogs.windows.com/windows-insider/2024/07/15/announcing-windows-11-insider-preview-build-26120-1252-dev-channel/
> 
> Please wait for this to get fixed.
correct im using that. :D
at least dont rush with it to hard.
insiders are made for testing and may see issues that could appear.

i would not mind if a fix waits until its released :-)

So i be patient.

it was more to inform about and because it was fitting here to the post of the other user (that might also use the preview version? he never told us..)

**Comment by pyrates999** [comment] 2024-07-22 06:36
Not including that you're running an insider preview build wasted a lot of time.  Next time always include that and the EP version you're running.

**Comment by pyrates999** [comment] 2024-07-22 10:25
The windows version and build and EP version should be posted when you first create a new issue and discussion.

**Comment by Amrsatrio** [comment] 2024-07-22 11:20
26100.1252 has nuked the classic 10 taskbar code altogether so expect some things being broken such as that right click menu.

**Comment by Lisyachiy-y** [comment] 2024-07-22 16:36
@pyrates999 

1. I already clicked on "Restore default settings". And then rebooted Windows.
2. ![image](https://github.com/user-attachments/assets/67f324e1-4b0d-434a-8385-7d3eca767980)
![image](https://github.com/user-attachments/assets/de889a0c-8786-421d-997c-26f2947458cb)
3. No other software.

**Comment by Lisyachiy-y** [comment] 2024-07-22 16:39
@Amrsatrio 

1. ![image](https://github.com/user-attachments/assets/b34571ea-56e4-4f7f-941b-07644e25fbb1)
2. No other software is installed.

**Comment by Lisyachiy-y** [comment] 2024-07-23 01:16
Properties disappeared after clicking on "Restore default settings"

**Comment by Amrsatrio** [comment] 2024-07-23 01:20
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1371

**Closed by Amrsatrio** 2024-07-23 01:20 UTC
