### ISSUE TITLE
Windows update reverts and prevents changes from being applied (issue with file explorer ribbon bar and UWP apps in Start)

### ISSUE THREAD

**Issue by andyman1222** [valinet/ExplorerPatcher#1590] opened 2023-06-25 23:40 UTC
In an attempt to update my laptop's graphics drivers I was made to update the rest of the system, which has a tendency to undo these unofficial changes like from ExplorerPatcher. I forgot about this until opening to the win11 start menu and file explorer. I updated ExplorerPatcher and got the win10 start menu back, however all UWP apps (I just love UWP, works every time) are not visible in the start menu. I noticed this issue came up in the past here before, so I suspect the change to fix this was reverted in the update and ExplorerPatcher didn't redo the modification when I updated the program.

On the same note, file explorer is ignoring the setting for the control interface, forcing the atrocious win11 ribbon instead of what I set- restarting file explorer and updating the patcher does not fix this (I have Start 11 which can also change this option, that could be interfering in some way)

Unrelated, the graphics driver software I was trying to originally update now won't open (AMD saying the graphics drivers changed) so I figured I'll just revert the windows update anyways.

**Comment by pyrates999** [comment] 2023-06-26 04:02
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:11
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:11 UTC
