### ISSUE TITLE
Volume Indicator missing after installing Windows Cumulative Update preview 22H2(KB5028254)

### ISSUE THREAD

**Issue by ahamling27** [valinet/ExplorerPatcher#1706] opened 2023-07-28 23:05 UTC
The volume indicator seems to be missing for me in the latest windows update preview(KB5028254). W11pro v10.0.22621

Edit: and by “volume indicator” I mean the notification that pops up automatically when you change the volume, not the sound icon/button on the taskbar. 

Uninstalled windows update (KB5028254) and it came right back.

_2023-07 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5028254)_

**Comment by Asad-13** [comment] 2023-07-29 05:18
Before this latest version was out, I did experience that issue (didn't experience on this latest version of ep). I was busy for a bit and then noticed that my volume button was gone. I tried disabling and enabling the button in the taskbar a few times, and somehow it came back.

Not a good fix, I know, but a temporary one at least.

**Comment by makidrone** [comment] 2023-07-29 16:01
It also went missing for me after the 2023-07 update

**Comment by Aroniel** [comment] 2023-07-29 17:38
Uninstalled Windows update (KB5028254)
It helped, thanks for the tip

**Comment by Kel-Leonym** [comment] 2023-07-30 10:19
I'm also seeing this issue with KB5028254 installed and the newest EP.

**Comment by z0000l** [comment] 2023-07-30 13:11
Also missing, but dont wanna unin the update:(

**Comment by pyrates999** [comment] 2023-08-01 09:47
You shouldn't be installing preview updates because they're not fully tested by Microsoft.

**Comment by makidrone** [comment] 2023-08-01 10:05
It updated automatically for me

**Comment by pyrates999** [comment] 2023-08-01 10:23
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

**Comment by pyrates999** [comment] 2023-08-01 21:40
It is still a preview update and you have something set to automatically install them.

**Comment by ahamling27** [comment] 2023-08-01 22:10
> It is still a preview update and you have something set to automatically install them.

Except I turned off the previews and it still downloaded and installed it anyway today. I'm not sure what else to tell you, but if you saw what I did in windows update, you'd be as surprised as I was this afternoon. Anyway, I've uninstalled it yet again and paused all updates for now.

**Comment by pyrates999** [comment] 2023-08-02 10:25
In the settings app, make sure that "Get the latest updates as soon as available" is unticked.

**Comment by ahamling27** [comment] 2023-08-02 13:20
> In the settings app, make sure that "Get the latest updates as soon as available" is unticked.

That’s what I said I did. I turned previews off and it still installed it. The installed update has no mention of “preview” in the title. I think MS pushed it out as a release update, maybe by accident. But I’ve paused all updates now, so I’m okay for now.

**Comment by pyrates999** [comment] 2023-08-11 10:48
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1692

Please close this one.

**Closed** 2023-08-11 14:34 UTC
