### ISSUE TITLE
Apps can't be pinned to Windows 10 styled start menu.

### ISSUE THREAD

**Issue by FedericoD3** [valinet/ExplorerPatcher#1572] opened 2023-06-20 16:13 UTC
As stated in the title:

Common procedure: 
Click on Start > type "someapp.exe" >  when the app is found click on "Pin to Start Menu" > the app **does not** get pinned.
Alternate procedure:
Explore to C:\Users\username\some\folder\with\an\app\App.exe" > right-click on the exe > click on "Pin to Start Menu" > the app **does not** get pinned.

Switch Start Menu to Windows 11 style, and apps get pinned with either procedure, but they don't appear pinned when switching back to Windows 10 style.

Pinning shortcuts does not work either
Pinning to Windows 10 styled **taskbar** works.

**Comment by pyrates999** [comment] 2023-06-21 09:23
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Vipin2003** [comment] 2023-06-22 15:46
Full Solution 👍 
https://github.com/valinet/ExplorerPatcher/issues/1534#issuecomment-1601017536

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:14
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:14 UTC
