### ISSUE TITLE
Calendar has circular numbers

### ISSUE THREAD

**Issue by HAYDENCRAFT2008** [valinet/ExplorerPatcher#2857] opened 2024-02-18 20:14 UTC
![image](https://github.com/valinet/ExplorerPatcher/assets/141458603/9516be31-6aee-4998-839e-3b93d2f1be97)

Happens on Windows 11 (not sure if this issue has already been addressed before or not) would it be possible to fix this?

the only way to fix it is to restart file explorer

**Comment by pyrates999** [comment] 2024-02-18 21:39
This is not caused by EP. See: https://github.com/valinet/ExplorerPatcher/issues/2323

Please close this.

**Comment by HAYDENCRAFT2008** [comment] 2024-02-18 21:45
> This is not caused by EP. See: #2323
> 
> Please close this.

Huh, strange

**Comment by milesprower2293** [comment] 2024-02-19 04:03
> ![image](https://private-user-images.githubusercontent.com/141458603/305743720-9516be31-6aee-4998-839e-3b93d2f1be97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTU2MzcsIm5iZiI6MTcwODMxNTMzNywicGF0aCI6Ii8xNDE0NTg2MDMvMzA1NzQzNzIwLTk1MTZiZTMxLTZhZWUtNDk5OC04MzllLTNiOTNkMmYxYmU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwNDAyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGQ1YzQ3MzJiY2MyZGI2ZTMyZWYxOGViYTEwZmI5NWZiYWJmMGQ1OTk2NWMwYTI1NjhkY2MzODMyMzc2YTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kVBASjSgEEbbKlLom14iT0PZoktdNw0JrrmfybnimEM)
> 
> Happens on Windows 11 (not sure if this issue has already been addressed before or not) would it be possible to fix this?
> 
> the only way to fix it is to restart file explorer

that happens because you opened the notification center before clock

**Closed** 2024-02-19 07:04 UTC
