### ISSUE TITLE
Showing Taskbar Icons

### ISSUE THREAD

**Issue by LookingForWayOut** [valinet/ExplorerPatcher#2990] opened 2024-03-13 12:39 UTC
Hello. My current laptop had to be reloaded, and W11 (meh) was forced on. When I installed the latest version of ExplorerPatcher, it hid all the icons but the forced ones (speaker, network, as I rather hide those). Before, I was able to show the few I wanted.

But now, icons showing:
![image](https://github.com/valinet/ExplorerPatcher/assets/11941595/2c0710c2-ec83-469a-802a-20198e0950ea)

Icons hidden:
![image](https://github.com/valinet/ExplorerPatcher/assets/11941595/83e0f410-dba9-4ccc-ac5b-a0621d302fd1)

I want to show icons I want to see and hide others. However, under Window$ (W10 version of) Settings > Personalization > Taskbar, showing icons instead of hiding them still do not show up.

![image](https://github.com/valinet/ExplorerPatcher/assets/11941595/819ece93-50a2-41c4-9d09-08ce71bc49e8)
![image](https://github.com/valinet/ExplorerPatcher/assets/11941595/3b5b53ec-4c5b-44f1-bb29-ee6c77ab82c1)

I tried to figure which setting in ExplorerPatcher could be blocking this, but I can not so wanted to come asking. Am I missing a function to click, or a combo of them?

I thought I read somewhere, but could not find it again, that between W11 and EP, it is either...
1 - have all icons (but the forced ones) hidden from view, as they are now, or
2 - show all icons from (Classic) Settings > Notifications:

![image](https://github.com/valinet/ExplorerPatcher/assets/11941595/e6674472-dd32-4831-b867-8aec24d506b6)

Any thoughts?

Thank you.

**Comment by pyrates999** [comment] 2024-03-13 13:30
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.

**Comment by Amrsatrio** [comment] 2024-03-13 14:04
You can drag the icons from the hidden icons popup to the taskbar.

Also, duplicate of #1454

**Closed by Amrsatrio** 2024-03-13 14:04 UTC

**Comment by LookingForWayOut** [comment] 2024-03-13 14:23
Oh wow! Never knew I could do that... ever!
Thanks!
