### ISSUE TITLE
On Win11, 23h2 the Win11-style tray flyouts of Wi-Fi and language switcher do not work on Win10 taskbar

### ISSUE THREAD

**Issue by Anixx** [valinet/ExplorerPatcher#3009] opened 2024-03-15 10:28 UTC
If to select Win11 (default) Wi-Fi and language flyouts, they do not appear when using the Win10 taskbar.

The Win10-style flyouts work well.

This in on Windows build 23h2 (22631). On 21h2 (22000) all works well.
If these flyouts are not available, meybe it is better to remove these options?

EP version: 64.1.

**Comment by Amrsatrio** [comment] 2024-03-15 10:46
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2096

**Comment by Amrsatrio** [comment] 2024-03-15 10:47
Sorry, closed the wrong issue.

**Comment by pyrates999** [comment] 2024-03-15 11:16
Since you set your taskbar to windows 10, perhaps it doesn't have the code to show the windows 11 flyouts, only the flyouts for windows 10.

**Comment by Anixx** [comment] 2024-03-15 11:22
@pyrates999 do you claim the code somehow does not exist in Explorer or what?

**Comment by Amrsatrio** [comment] 2024-03-15 11:27
I think you have "UseLiteLayout" enabled in HKLM\Software\Microsoft\Windows\Control Center.

**Comment by Anixx** [comment] 2024-03-15 11:31
> I think you have "UseLiteLayout" enabled in HKLM\Software\Microsoft\Windows\Control Center. Otherwise I cannot reproduce your issue on 22631.3296.

Hmmm. I do not have HKLM\Software\Microsoft\Windows\Control Center at all...

**Comment by pyrates999** [comment] 2024-03-15 12:15
That location in the registry also doesn't exist for windows 10.

**Comment by Anixx** [comment] 2024-03-15 12:23
Additional info: the flyouts do not open even if Windhawk is disabled, regardless of the theme (in the default theme as well).
On the other hand, they do open if to set the taskbar to be Win11.

**Comment by pyrates999** [comment] 2024-03-15 14:02
Open up the properties application for explorer patcher, go to advanced, and click on enable console.

Try to see if the flyouts work for the windows 10 taskbar.  Copy and paste the results from the EP console here then.

**Comment by Anixx** [comment] 2024-03-16 04:31
Update: after I enabled console, the language Win11 flyout now works!

The Wi-Fi flyout still does not, the console output is:
Started "Check foreground window" thread.
Ended "Check foreground window" thread.

**Comment by pyrates999** [comment] 2024-03-16 09:24
can you paste the complete output from the EP console?

**Comment by Amrsatrio** [comment] 2024-03-16 20:18
@Anixx These lines suggest that your current Windows build is too old. What's your Windows build?

Started "Check foreground window" thread.
Ended "Check foreground window" thread.

**Comment by Anixx** [comment] 2024-03-16 21:04
10.0.22631.3296

**Comment by Amrsatrio** [comment] 2024-03-16 21:09
Yeah, please install EP 62.2 or newer.

**Comment by Anixx** [comment] 2024-03-16 22:24
For some reason it does not get updated from the dialog.

**Comment by Amrsatrio** [comment] 2024-03-16 22:26
Then update from the releases section.

**Comment by Anixx** [comment] 2024-03-16 22:29
I updated but the flyout still does not appear.

It still says

Started "Check foreground window" thread.
Ended "Check foreground window" thread.

**Comment by Anixx** [comment] 2024-03-17 13:26
Since the language flyout now works, the issues with the Wi-Fi flyout may be caused by something else. I will watch the issue and report my findings if any.

**Closed** 2024-04-13 15:18 UTC
