### ISSUE TITLE
Crash after right click

### ISSUE THREAD

**Issue by SusanQuinn** [valinet/ExplorerPatcher#1965] opened 2023-08-30 14:46 UTC
Application doesn't start. Application crashes after right click on windows taskbar.

Edition	Windows 11 Pro
Version	22H2
Build OS	22621.2134
Performance	Windows Feature Experience Pack 1000.22659.1000.0

**Comment by pyrates999** [comment] 2023-08-30 18:00
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by Poopooracoocoo** [comment] 2023-08-31 09:08
Closing in favour of #1952

**Closed by Poopooracoocoo** 2023-08-31 09:08 UTC
