### ISSUE TITLE
Windows 10 Start-Button right-click context menu missing

### ISSUE THREAD

**Issue by ScruffR** [valinet/ExplorerPatcher#3851] opened 2024-10-28 11:46 UTC
I swear I searched but couln't find a previous report about this 🤔
It used to work a while ago but I don't know when this stopped working.

Previously when right-clicking the Start button (Win10 or Win11 style) on a Windows 10 taskbar (legacy or ExplorerPatcher vesion) this context menu popped up 
![image](https://github.com/user-attachments/assets/d3d0dafa-0b91-467b-a182-bcfe5d5f348f)

But now this feature seems to have gone.
When I switch back to Windows 11 taskbar, the context menu is back (this is how I obtained the screenshot).

Can we please have this back, it's a convenient way to quickly get to Device Manager, Admin Terminal, ...

**Comment by milesprower2293** [comment] 2024-10-28 12:17
Duplicate of #3837

**Closed by milesprower2293** 2024-10-28 12:17 UTC
