### ISSUE TITLE
Explorer Patcher Windows 10 Start Menu On Windows 11 Laggy Not Responsive

### ISSUE THREAD

**Issue by ggg1221** [valinet/ExplorerPatcher#2430] opened 2023-11-12 12:44 UTC
I click on start menu and it comes up after a few seconds and when I click somewhere else it dissapears after some seconds

Windows 11 22h2 (22261.2506) NO INSIDER!
**Windows 11 Pro**

**Comment by pyrates999** [comment] 2023-11-12 13:08
If you meant this version: https://support.microsoft.com/en-us/topic/october-31-2023-kb5031455-os-builds-22621-2506-and-22631-2506-preview-6513c5ec-c5a2-4aaf-97f5-44c13d29e0d4

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

But as far as I know, the start menu has always closed itself if you click elsewhere on the screen.

So what is the bug here?

**Comment by Amrsatrio** [comment] 2023-11-12 16:04
I'm fine with 22621.2506. This issue seems to be isolated to your installation. Have you restarted Explorer after changing the start menu style?

Because I fixed the start menu animations which is a more elaborate patch, but for some reason, maybe due to modified system files, the patch failed to apply. To find the exact reason, I need to show the first full screen height page of the console output after restarting Explorer.

**Comment by Amrsatrio** [comment] 2023-11-12 16:13
Also do you have Start11 or other customization software installed? Because if you do, then such scenarios are not supported.

**Comment by sorlag110** [comment] 2023-11-13 09:26
Same problem here as OP, fresh Windows 11 install, no customization software besides Explorer Patcher.

**Comment by sorlag110** [comment] 2023-11-13 16:43
I did the ol' "don't read the comments thoroughly" and complain anyway. Restarting explorer works. /facepalm

**Comment by sorlag110** [comment] 2023-11-13 17:23
I thought it was an encouraging kissy face *:

Jokes aside, perhaps the interface could be a little clearer, like how Winaero Tweaker will make it very clear you need to restart explorer for some changes to work after you've changed them.  I completely missed the asterisk, now that I see it, yeah it makes perfect sense considering the restart explorer button has one too. But you know, assume the average user is half blind and barely even born.

**Comment by Amrsatrio** [comment] 2023-11-13 17:28
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/b7970bbc-2dbc-43b3-b4be-3a4a3b8704d5)

Yeah well, it's just that the current UI code is too messy and stiff to add stuff into. I've been attempting on a new UI lately and I promise you that things are happier here, but it's not fully done yet.

**Comment by sorlag110** [comment] 2023-11-13 17:50
Looks promising, keep up the good work!

**Comment by Amrsatrio** [comment] 2023-11-14 21:12
Probably I will close this because this issue seems to be caused by user error.

**Closed by Amrsatrio** 2023-11-14 21:12 UTC
