### ISSUE TITLE
Windows 11 Classic Address Bar Not Working

### ISSUE THREAD

**Issue by bfloat16** [valinet/ExplorerPatcher#2879] opened 2024-02-21 10:23 UTC
Version:
![image](https://github.com/valinet/ExplorerPatcher/assets/38366253/5ab0a4fe-b656-4b3a-a487-a565f12b0518)
Windows 10 Ribbon and Windows 7 Command Bar are working, but Windows 11 Classic Address Bar broken.
![image](https://github.com/valinet/ExplorerPatcher/assets/38366253/a71c75dc-c755-400a-9777-c1803e2f7c5f)
![image](https://github.com/valinet/ExplorerPatcher/assets/38366253/99a67bfe-358c-4544-8c3b-12dfac8b37e8)
![image](https://github.com/valinet/ExplorerPatcher/assets/38366253/577b2ec9-b913-417e-8436-1240641ffa45)

**Comment by Amrsatrio** [comment] 2024-02-21 10:26
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2701

**Closed by Amrsatrio** 2024-02-21 10:26 UTC
