### ISSUE TITLE
Problem with power button since latest W11 update

### ISSUE THREAD

**Issue by Liudprand** [valinet/ExplorerPatcher#3625] opened 2024-09-01 15:35 UTC
Hi.

Since the last Windows 11 update, just a few days ago, the behaviour of the start menu has changed in an annoying way. Whereas before the power button, with options so sleep/hibernate, etc., appeared directly above the start button when you clicked it. Now, there's an ugly fly-out menu, and to reach the power button you have to move the cursor to more or less the middle of the screen again. I seem to have the most recent version of ExplorerPatcher, so I was just wondering if anyone knows of a fix for this?

Thanks in advance.

**Comment by Liudprand** [comment] 2024-09-01 16:57
Here's what I'm talking about:

![Start error](https://github.com/user-attachments/assets/6bf7fc80-767b-40c8-96c5-5238c05bf59b)

**Comment by pyrates999** [comment] 2024-09-01 22:20
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Try installing the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by 4everImmortality** [comment] 2024-09-02 06:25
I have got a same issue on the latest version
Here is my version
![image](https://github.com/user-attachments/assets/26bfbb29-4c17-4f36-b56e-555cca514761)

**Comment by pyrates999** [comment] 2024-09-02 08:03
Please provide info asked for.

**Comment by Amrsatrio** [comment] 2024-09-02 12:21
Please provide a video explanaion on your issue.

**Comment by Liudprand** [comment] 2024-09-02 15:06
Sorry for the delayed response. This is my windows version.

![Screenshot 2024-09-02 160437](https://github.com/user-attachments/assets/99fe1374-22f0-4c77-9e69-04c8de10907c)

ExplorerPatcher settings to follow in a moment...

**Comment by Liudprand** [comment] 2024-09-02 15:14
I'm not sure how many of the settings I changed - it was a while ago. But they should all be on the following screens.

![EP6](https://github.com/user-attachments/assets/e635543d-e75f-4efa-9b2b-d8ad2bf34a8f)
![EP5](https://github.com/user-attachments/assets/fc2479be-2e86-449a-bdc7-8f0c2c2ee317)
![EP4](https://github.com/user-attachments/assets/ab6f9a1a-4570-4f23-b9e7-43fce3dd4fb2)
![EP3](https://github.com/user-attachments/assets/99127a1c-ebe9-417c-ac51-5a7d0596c48d)
![EP2](https://github.com/user-attachments/assets/d184cfe3-909a-443c-9ac2-ea17a68b6250)
![EP1](https://github.com/user-attachments/assets/c313a5cc-e52f-4fd1-b8fb-bc6ce72f31b9)

**Comment by Liudprand** [comment] 2024-09-02 15:18
As for the pre-release, I'm not sure whether I need the "ep_setup.exe" or "ep_setup_arm64.exe" file?

**Comment by Liudprand** [comment] 2024-09-02 16:44
> Please provide a video explanaion on your issue.

I'm not sure what you mean by this. I could upload a video clip of me clicking on "Start", and what would pop up is precisely what's shown in the screenshot. It wouldn't be a very exciting video.

**Comment by Liudprand** [comment] 2024-09-02 16:52
> Please include any other software you have installed that modifies the UI of windows.

There's nothing else.

**Comment by Amrsatrio** [comment] 2024-09-02 16:56
Alright. You mean the Windows 10 start menu is gone. In this case, please download the latest prerelease. You will need the ep_setup.exe file since I assume your PC is Intel/AMD-based.

**Comment by Amrsatrio** [comment] 2024-09-02 16:56
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3603

**Closed by Amrsatrio** 2024-09-02 16:56 UTC

**Comment by pyrates999** [comment] 2024-09-02 20:11
Read the release notes of the pre-release of what folders you need to exclude before installing.

**Comment by Liudprand** [comment] 2024-09-02 21:52
That did the trick. Thanks.
