### ISSUE TITLE
Unable to pin Snipping Tool to Start Menu

### ISSUE THREAD

**Issue by rustyjarz** [valinet/ExplorerPatcher#1649] opened 2023-07-18 23:10 UTC
Hi

Trying to pin the Snipping Tool to the Start Menu is failing, I'm receiving the successful message but when I check to see if it's on the Start Menu the Snipping Tool isn't there.

**Comment by pyrates999** [comment] 2023-07-19 00:01
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Vipin2003** [comment] 2023-07-19 02:08
fix #1591

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:10
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:10 UTC
