### ISSUE TITLE
"View tasks" button and Alt+Tab not working on Win11 22H2

### ISSUE THREAD

**Issue by Azertixe** [valinet/ExplorerPatcher#1984] opened 2023-09-03 16:03 UTC
Hello. My "View tasks" button is not working :( I use it in order to have multiple desktops.
Also i can't use Alt+Tab shortcut.
I use Windows 10 taskbar and Win11 Start menu style aligned to left. This same button works on Windows 11 tb style and Alt+Tab too.
Any advice ?
Thanks :)

**Comment by Syth-1** [comment] 2023-09-03 18:21
To add to this, same issue but windows + tab not working either. 
it seems i can get alt+tab to work, until i use windows + tab, then nothing works, 

This seems to be exclusive to win10 task bar, when using win11 task bar both are working fine (except now i cant right click task bar to bring up properties -- insta crash. but thats a seperate issue)

using OS: 
Edition: Windows 11 Pro
Version: 22H2
OS Build: 22621.2134

**Comment by pyrates999** [comment] 2023-09-03 23:04
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

**Closed** 2023-09-03 23:58 UTC

**Comment by Azertixe** [comment] 2023-09-05 18:38
> 

Not a solution for me : i only use Win10 skin because i can't work with combined icons on task bar.
Any solution ?

**Comment by Azertixe** [comment] 2023-09-05 18:41
> duplicate of: #1687
> 
> Please close this one.
> 
> Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

Hello. Using Win11 skin is not a solution for me because i can't work with combined icons on task bar.
Any solution ?

**Comment by pyrates999** [comment] 2023-09-05 20:53
No solution yet.
