### ISSUE TITLE
Start Button & Automatic Search

### ISSUE THREAD

**Issue by 1993Nani** [valinet/ExplorerPatcher#3307] opened 2024-05-22 17:14 UTC
After entering full start screen automatic search is not working, Please suggest any setting or create an update, Thanks all....

**Comment by pyrates999** [comment] 2024-05-23 11:34
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment] 2024-05-23 13:24
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1975

**Closed by Amrsatrio** 2024-05-23 13:24 UTC
