### ISSUE TITLE
Clipped weather window

### ISSUE THREAD

**Issue by teslasystemsx** [valinet/ExplorerPatcher#3108] opened 2024-04-08 15:45 UTC
Hello.
When I open a weather window by clicking weather icon on taskbar, its content appears clipped on the top. Screenshot attached.
<img width="507" alt="Weather" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/e3da6778-1fe1-4202-8653-e63d6c2161b7">

OS: Win11 23H2
Windows display scaling: 150%

**Comment by pyrates999** [comment] 2024-04-08 22:02
Try setting windows display scaling to 100%.

**Comment by pyrates999** [comment] 2024-04-08 22:42
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by teslasystemsx** [comment] 2024-04-09 17:24
<details>
<summary>Screenshots</summary>
<img width="599" alt="9" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/422cd3ca-f2d5-443e-aab9-e1851d01a35c">
<img width="599" alt="1" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/ec4abffe-4c47-42a7-9c38-cd6a951d4684">
<img width="599" alt="2" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/dc3a2872-2ea7-4de6-b23d-c44e7dfe56e8">
<img width="599" alt="3" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/69dd924d-2704-404a-99c4-a9fe38ff6fa5">
<img width="599" alt="4" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/3b090bee-aeef-4c82-9080-da144f58d8b5">
<img width="599" alt="5" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/002b0f33-01ae-4062-886c-7680f11dc31c">
<img width="599" alt="6" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/ecfb8f82-bc95-4c8e-b60a-e37bca51916c">
<img width="599" alt="7" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/79024747-9805-4032-b80f-152e45b816d9">
<img width="599" alt="8" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/46165b8f-a736-4e6d-9bc4-5c1017d80b4b">
</details>

I have standard Calculator from Win7 and standard Task Manager, but it's not UI-modifying soft, it only replaces some apps.

**Comment by pyrates999** [comment] 2024-04-09 23:53
You have modified the theme to be purple.  Please undo your UI changes to the theme and see if that fixes it.

**Comment by teslasystemsx** [comment] 2024-04-10 00:01
> You have modified the theme to be purple. Please undo your UI changes to the theme and see if that fixes it.

Are you a developer of this app? Or you just trolling me? How the color is connected to the problems with clipped content? And no, it doesn't changes anything.

**Comment by pyrates999** [comment] 2024-04-10 00:04
No, I just try to help.

I noticed that the part that was being blocked had a purple bar, and your windows also had a purple bar.  So I suggested that as a possible fix.

Can you post a screen shot of it still happening after you reset the theme back to the original?

**Comment by teslasystemsx** [comment] 2024-04-10 00:08
> No, I just try to help.
> 
> I noticed that the part that was being blocked had a purple bar, and your windows also had a purple bar. So I suggested that as a possible fix.
> 
> Can you post a screen shot of it still happening after you reset the theme back to the original?

<img width="507" alt="00" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/9740c4cd-5f6c-4de1-a086-9970529ba4ef">

Changes in color may only affect color, so the window's color just changed to the theme's color.

**Comment by pyrates999** [comment] 2024-04-10 00:13
Understood.  So I ask again:

Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.  Did you use a third party application to modify windows theme to be purple or just the built in options in the settings application?

**Comment by teslasystemsx** [comment] 2024-04-10 00:16
> Understood. So I ask again:
> 
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.
> 
> Please include any other software you have installed that modifies the UI of windows. Did you use a third party application to modify windows theme to be purple or just the built in options in the settings application?

Have you read my previous post? There is everything you asked. I'm changing the color with standard windows settings app without external apps.

**Comment by pyrates999** [comment] 2024-04-10 00:26
Oh sorry.  But you still haven't said the windows 11 build.  You can find that by running winver.

**Comment by teslasystemsx** [comment] 2024-04-10 00:31
> Oh sorry. But you still haven't said the windows 11 build. You can find that by running winver.

An About window of ExplorerPatcher already includes it. 22631.2428

**Comment by pyrates999** [comment] 2024-04-10 14:07
Your windows version is out of date.  Please install the windows updates available for it.

**Comment by teslasystemsx** [comment] 2024-04-10 15:23
> Your windows version is out of date. Please install the windows updates available for it.

Are you hear me? It's not a problem with Windows, it works ok on other machine with the same version.

**Comment by pyrates999** [comment] 2024-04-11 13:27
EP developers don't test on older builds of windows.  Please update and come back to here when you have.

**Comment by teslasystemsx** [comment] 2024-04-11 13:40
> EP developers don't test on older builds of windows. Please update and come back to here when you have.

I don't ask anyone to test it. I asked about specific reasons which may cause such behavior. And please don't tell me what to do on my machine. There is no any sense to continue this discussion.

**Comment by plofhaan** [comment] 2024-05-14 08:19
I can confirm that this issue still happens on Windows 11 build 22631.3527 running EP 22621.3527.65.4 with Widget size : Automatic (fit content (default), Zoom : 100 % (default), and Language : nl. This is with 3840x2160 screen resolution and the Scale set to 150% under Windows Settings | Display. 

![EP weather misaligned](https://github.com/valinet/ExplorerPatcher/assets/93003106/bb037b02-7400-41a3-a924-4f96805adb83)

Here it is on another laptop from another brand, using 1920x1200 screen resolution and 125% Scale.

![EP weather misaligned 2](https://github.com/valinet/ExplorerPatcher/assets/93003106/79bdd0d9-f98f-435c-8048-1258ff9936f5)

**Comment by gtdurham** [comment] 2024-05-14 22:55
I have the same issue. I am using Windows 11 build 22631.3527 and running EP 22621.3527.65.4 with Widget size : Automatic (fit content) (default), Zoom : 100 % (default), and Language : nl.

**Comment by pyrates999** [comment] 2024-05-14 23:06
Since I cannot enable weather on windows 10, this must be limited to windows 11.

Try going through this guide: https://github.com/valinet/ExplorerPatcher/wiki/Weather

**Comment by gtdurham** [comment] 2024-05-14 23:44
It seems like others are having this same issue. There ought to be some kind of resolution.

**Comment by teslasystemsx** [comment] 2024-05-15 03:34
> Try going through this guide: https://github.com/valinet/ExplorerPatcher/wiki/Weather

Well, I have enabled a developer mode and now it looks like this:
<details>
<summary>Screenshot</summary>
<img width="580" alt="DevMode" src="https://github.com/valinet/ExplorerPatcher/assets/140281857/21206ca1-307e-4ce4-9df8-ef43cba0464b">
</details>

Also, it is mentioned, that the weather window contains a cropped content of the webpage. It means, that the cropping is working incorrectly in some cases. Probabaly because the webpage may look differently on different machines.

**Comment by pyrates999** [comment] 2024-05-15 11:49
Try the following:

1. right click on desktop and select personalize
2. in settings that shows up, select Colours/Colors
3. Under **Show the accent colour on the following surfaces**, untick **Title bars and window borders**.

**Comment by teslasystemsx** [comment] 2024-05-15 12:11
> Try the following:
> 
>     1. right click on desktop and select personalize
> 
>     2. in settings that shows up, select Colours/Colors
> 
>     3. Under **Show the accent colour on the following surfaces**, untick **Title bars and window borders**.
> 
>     4. In EP properties application, in weather, disable and enable weather feature.

If you perform action 4, nothing changes, it's clipped as before. But if you change the state of this setting and open a weather window after that, you can see how its content is jumping.

<details>
<summary>Video</summary>
https://github.com/valinet/ExplorerPatcher/assets/140281857/049b857d-fff7-4203-8ae5-a4e313a3da29
</details>

**Comment by plofhaan** [comment] 2024-05-15 12:14
Fixed in EP 22621.3527.65.5 on both computers. 👍

**Comment by plofhaan** [comment] 2024-05-15 12:29
That's weird. Did you restart explorer?

**Comment by gtdurham** [comment] 2024-05-15 15:41
This has been fixed with the latest update.
Thank you

**Comment by gtdurham** [comment] 2024-05-16 16:04
This issue can be closed.

**Closed** 2024-05-16 16:35 UTC
