### ISSUE TITLE
Start Menu Opens Halfway Outside of Screen

### ISSUE THREAD

**Issue by CompuGenius-Programs** [valinet/ExplorerPatcher#3874] opened 2024-11-02 23:14 UTC
On secondary monitors, the Start menu opens halfway below the screen when clicking the Windows key, but fully when clicking the Windows icon in the taskbar.

My primary monitor is 1440p, the two secondaries are 1080p (not sure if that's relevant).

![image](https://github.com/user-attachments/assets/9489e7ea-92e1-4542-9a7e-9131c55f30c1)

**Comment by pyrates999** [comment] 2024-11-03 01:29
Update to the pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by CompuGenius-Programs** [comment] 2024-11-03 01:45
@pyrates999 that did not fix it, unfortunately.

**Comment by pyrates999** [comment] 2024-11-03 01:56
is it this? https://github.com/valinet/ExplorerPatcher/issues/3464

**Comment by CompuGenius-Programs** [comment] 2024-11-03 02:26
I don't seem to have that exact issue, but it may be related.
No, it works perfectly without EP.

**Comment by pyrates999** [comment] 2024-11-03 03:13
ok, please wait for a developer to respond.

**Comment by Amrsatrio** [comment] 2024-11-03 11:15
Duplicate of #1122

**Closed by Amrsatrio** 2024-11-03 11:15 UTC

**Comment by Amrsatrio** [comment] 2024-11-03 11:16
<img width="607" alt="image" src="https://github.com/user-attachments/assets/9eb0b13a-1672-42b7-aa78-c2f882891f28">

Make sure it's like this. I hope it helps.

**Comment by CompuGenius-Programs** [comment] 2024-11-03 12:35
@Amrsatrio but I don't want that lol. I specifically want it to open on the monitor in which the cursor is on.

**Comment by Amrsatrio** [comment] 2024-11-03 12:36
Yeah that means we haven't fixed it. Once we have fixed it we'll notify you and the post I linked.

**Comment by CompuGenius-Programs** [comment] 2024-11-03 12:37
Ohh. I saw you marked as not planned and I was so confused. I just woke up, didn't realize you had linked another issue.
Cool, thanks.
