### ISSUE TITLE
the windows start menu is now windows 11 and i had the old start menu. fix this

### ISSUE THREAD

**Issue by ErikaXGH** [valinet/ExplorerPatcher#3610] opened 2024-08-30 00:11 UTC

**Comment by CHAFAN2** [comment] 2024-08-30 12:03
i got the same thing the shitty win 11 start menu is back somehow

**Comment by CHAFAN2** [comment] 2024-08-30 12:03
is there any fix even

**Comment by pyrates999** [comment] 2024-08-30 12:49
Install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by gex581990** [comment] 2024-08-31 01:52
> Install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

I have the same issue and latest pre-release doesn't fix it

**Comment by Amrsatrio** [comment] 2024-08-31 06:43
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3603

**Closed by Amrsatrio** 2024-08-31 06:43 UTC
