### ISSUE TITLE
22621.2361 - "Hide Reccomendations in Start Menu" doesn't work

### ISSUE THREAD

**Issue by ArbestRiAgain** [valinet/ExplorerPatcher#2235] opened 2023-10-03 03:39 UTC
Title. The option only works half the time, because right-clicking anything in the Start menu shows the Recommended tab again.

**Comment by Amrsatrio** [comment] 2023-10-03 04:29
Dupe of #2212

**Closed by Amrsatrio** 2023-10-03 04:29 UTC

**Comment by idbssoft** [comment] 2023-10-03 06:26
App list Hide/Disable is not working..!
