### ISSUE TITLE
switching between users is hidden in a side taskbar

### ISSUE THREAD

**Issue by Tsurha** [valinet/ExplorerPatcher#3590] opened 2024-08-26 00:39 UTC
In a side taskbar, when a different user is trying to login, the option to select him is hidden. Please see screen capture.
Apologies if this is known and was discussed a million times. I'm new here.

![image](https://github.com/user-attachments/assets/18105584-9882-4042-8339-8b77ce10badb)

**Comment by pyrates999** [comment] 2024-08-26 05:47
Install the latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

It has the fix for the start menu appearing on top of the windows taskbar when it's not at the bottom.

**Comment by Amrsatrio** [comment] 2024-08-31 06:44
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3464

**Comment by Amrsatrio** [comment] 2024-08-31 06:45
@pyrates999 Prerelease does not fix this issue and I have no plans to make it fix the alignments. But maybe some day I want to look into disabling it...

**Closed by Amrsatrio** 2024-08-31 06:44 UTC

**Comment by pyrates999** [comment] 2024-08-31 07:24
Understood :)
