### ISSUE TITLE
File Explorer crashes every second time it is opened

### ISSUE THREAD

**Issue by bsdinis1** [valinet/ExplorerPatcher#2059] opened 2023-09-13 23:57 UTC
I've been having this issue for months now, every time I open microshit's File Explorer the explorer.exe process crashes, then on the second try it opens but sometimes without the Minimize/Maximize/Close buttons on the top right.

And it will keep on happening...;
first time - crashes
second time - opens
third time - crashes
fouth time - opens

Funny thing, right after explorer.exe crashes and I open File Explorer I get the dreaded explorer focus steal bug that microshit refuses to acknowledge it even exists.

The explorer.exe crashing doesn't always happen, sometimes I can open and close the stupid thing and it doesn't crash

**Comment by pyrates999** [comment] 2023-09-14 09:22
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by bsdinis1** [comment] 2023-09-14 09:41
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application.

![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/46ab3929-ef14-4cf6-a9e7-c16cdaaf153d)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/be4b5748-7ac8-418d-afdf-a603a777c573)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/00ac0da4-8fd2-4175-b696-bbf5ec62ac96)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/94212a76-7046-408e-8634-0adc680b0fd7)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/fa37bc74-dd4a-43c5-b29b-c565d21f91ef)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/8394440c-316e-4c31-827b-67ceaedbe974)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/30f209c9-886b-4af4-97a7-c519fad54133)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/46bbe5df-ca2a-4d45-8432-14fa3e7f415f)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/98f19070-cf7c-4ca0-9854-2f3dcd9b4c9b)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/bc6f210c-3ed5-4408-91d1-c55063e7e3ed)
![image](https://github.com/valinet/ExplorerPatcher/assets/98789652/cd47f49e-e7cc-4d22-902b-8abeedbd06df)

**Comment by pyrates999** [comment] 2023-09-14 10:43
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2051

Please close this one.

Possible fixes:

1. In ExplorerPatcher Properties, go to Advanced and tick **Do not change the taskbar context menu**
2. In ExplorerPatcher Properties, go to File Explorer and untick **Disable the windows 11 context menu**
3. In ExplorerPatcher Properties, go to Taskbar and set **Taskbar style** to **Windows 11**

**Closed** 2023-09-14 10:46 UTC

**Comment by bsdinis1** [comment] 2023-09-24 20:43
All I had to do was set the Taskbar style back to Windows 11, but this is fucking awful to say the least, is there a way to make this shit **never combine**?

**Comment by Poopooracoocoo** [comment] 2023-09-25 01:43
@bsdinis1 if you're still seeing this, please create a new issue. Include your ExplorerPatcher version and Windows build number. 

Windows 11 will soon be getting the "23H2" update, OS Build 22631, with taskbar ungrouping and labels. 

I've found that the Windhawk tweak isn't too great, so I was using Start11 for a while.
