### ISSUE TITLE
Choose icons to be always displayed in the system tray

### ISSUE THREAD

**Issue by PhunkyBob** [valinet/ExplorerPatcher#1582] opened 2023-06-22 12:20 UTC
I have 2 applications I always want displayed in the system tray (a screenshot tool and an audio player). 

Since the latest Windows update (Windows 11 22H2 22621.1848), this parameter is not taken in account anymore: all my icons are hidden and I have to click on the arrow to popup all availables icons. 

## Steps to reproduce
- Use https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.1_a95a688
- In the systray, choose to always display "OneDrive" icon. 
- Make sure OneDrive is launched. 

## Expected
- The "OneDrive" icon is displayed next to the battery icon. 

## Actual behavior
- The "OneDrive" icon is not displayed. 
- Only the "⌃" icon is displayed. 
- When I click on the "⌃" icon, a panel appeats with all the icons, OneDrive's included.

**Comment by pyrates999** [comment] 2023-06-23 09:49
Did you change any of the settings in explorer patcher to cause this?

**Comment by PhunkyBob** [comment] 2023-06-23 10:28
No. 
I only had Windows Update installing the latest version of Windows' patch. 

In this MR https://github.com/valinet/ExplorerPatcher/pull/1138 @NyaMisty said that he faced a problem with the tray and the preview version of 23H2. 
Maybe it's linked.

**Comment by pyrates999** [comment] 2023-06-23 11:50
Preview builds and insider builds are not supported due to the symbols not being available to download for them.  That's why that request was never accepted.

https://github.com/valinet/ExplorerPatcher/wiki/Symbols

But if you're not modifying any of the settings that explorer patcher has, why install it?

**Comment by PhunkyBob** [comment] 2023-06-23 12:14
> But if you're not modifying any of the settings that explorer patcher has, why install it?

I don't understand your question. 
I use ExplorerPatcher to have every window in the taskbar (I don't like the "group by" behaviour). 

ExplorerPatcher and my settings worked fine until the new Windows update. 
I didn't changed settings in ExplorerPatcher since a long time. 

The problem is not something I changed in ExplorerPatcher's settings, nor something a new version of ExplorerPatcher changed. The problem comes from the latest Windows update.


> Preview builds and insider builds are not supported

I understand. I don't use preview builds. 
I've just said that the problem someone noticed weeks ago in the preview build is now present in the official build. 
(this seems expected)

**Comment by pyrates999** [comment] 2023-06-23 20:48
Ok, misunderstanding.  I had asked if you changed any settings at all in explorer patcher and you have, just not recently.

Perhaps you can try showing all icons in the system tray for now until this is fixed.

**Comment by PhunkyBob** [comment] 2023-06-24 09:24
> Perhaps you can try showing all icons in the system tray for now until this is fixed.

Yes, it's a workaround. 

> You can also try a pre-release of explorer patcher to see if that fixes it.

I will.

**Comment by PhunkyBob** [comment] 2023-06-26 06:38
I tried [22621.1555.55.2](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.2_6fb998e). 
It doesn't change the behavior.

**Comment by pyrates999** [comment] 2023-06-26 07:16
Thank you for testing.  This appears to be a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

**Comment by PhunkyBob** [comment] 2023-06-26 07:46
Sorry for the duplicate. Yet I had done a search. 
My bad.

**Comment by pyrates999** [comment] 2023-08-13 00:36
Please close this one as it is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

**Closed** 2023-08-13 19:25 UTC
