### ISSUE TITLE
Windows 22621.2134 error reproducible on 5 systems

### ISSUE THREAD

**Issue by wohack** [valinet/ExplorerPatcher#1892] opened 2023-08-22 14:52 UTC
I opened the issue again already closed by Poopooracoocoo because I have overseen that the first time the issue was opened by Krassikn was pointing on a prerelease.
My add on to the ticket showing the same behavior is based on the August update.

ExplorerPatcher crashes on Windows 22621.2134.
None of the supposed fixes works. I used a console to find the error. Here it is if it is of any help fixing the issues.

I uninstall ExplorerPatcher and remove all registry leftovers. Restarted. New install than restart again. The first time I open the file explorer (any folder) the following error appears in the console -
"10000 46000000
0 46000000
Error in sub_1800135EC on RoGetActivationFactory."

After this I close the file explorer and on next reopening the ExplorerPatcher crashes and restarts.

This error appears every time on opening any folder than on second opening ExplorerPatcher crashes and restarts.

I was testing during the last days on my different systems.
As it's now already described I can add some more details from my testing.

Open the first file explorer window the error message appears.
Closing this file explorer window and open a new one the crash happens.

Open the first file explorer window the error message appears.
Keep it open and open additional file explorer windows all is stable.
Keeping one of them open also no crash happens by opening an additional window.
As long as one explorer window is open for each additional one you won't see an error message
Then it looks that way e.g. opening 4 windows.
"10000 46000000
0 46000000
Error in sub_1800135EC on RoGetActivationFactory.
10000 46000000
0 46000000
10000 46000000
0 46000000
10000 46000000
0 46000000"
Closing all of them and open a new one the crash will happen.

I have 5 different systems, 3 physical (intel and amd) and 2 virtual under vmWare player 17 and they show all the same behavior.

I have also 2 systems running windows 11 21H2 with august patch level.
There everything is stable.
Opening there an explorer window you will only see
"10000 46000000
0 46000000"
and no error message.

I don't have an internal view whats going on in windows but my impression is that it has to do with the error message

Hope this helps to identify and fix the problem.

**Comment by pyrates999** [comment] 2023-08-23 12:18
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Closed** 2023-08-30 20:23 UTC
