### ISSUE TITLE
First item highlighted 

### ISSUE THREAD

**Issue by GuillaumeMartinMD** [valinet/ExplorerPatcher#2569] opened 2023-12-08 15:24 UTC
Hi,

When opening new menus (such as Sound, or the Start Menu), the first items are usually already 'selected' and thus highlighted in white. This is quite a minor issue, but esthetically unpleasing (see sound menu for example).

Is it only me ? Is there a fix ? Is a fix planned ? 

Thanks

![image](https://github.com/valinet/ExplorerPatcher/assets/79311638/74c7ebf0-43bd-44b6-9b3a-725ec6859ada)
![image](https://github.com/valinet/ExplorerPatcher/assets/79311638/f499b2c7-82af-40d7-b535-3ed75f2ac950)

**Comment by Amrsatrio** [comment] 2023-12-09 07:35
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1448

**Closed by Amrsatrio** 2023-12-09 07:35 UTC
