### ISSUE TITLE
[bug but feature] transparent taskbar

### ISSUE THREAD

**Issue by MarceloMachadoxD** [valinet/ExplorerPatcher#2986] opened 2024-03-13 10:28 UTC
![image](https://github.com/valinet/ExplorerPatcher/assets/892172/1cc38b60-2b3e-443d-82cc-fe789a25e3fc)
guys today my taskbar wakeup full transparent color
i dont know why but it seems so beautiful to me xD seems like my Zorin OS gnome

suggestion to add an option to make it full transparent

Follow my full setup if it help to find the cause
[settings.zip](https://github.com/valinet/ExplorerPatcher/files/14586195/settings.zip)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/ebeda31a-c35a-4203-96c4-615c4bf6d414)
 
![image](https://github.com/valinet/ExplorerPatcher/assets/892172/fee996fc-2aa3-4312-addc-1147b303a5d4)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/95b6d51a-dded-431a-8105-cf09019d1e06)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/d0867f1e-c5b7-4790-a4e1-2e31041f44aa)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/60ae53fe-a20c-4f43-8310-0ba09b317ac0)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/10251ada-0e98-49b9-b75e-cc3ef58d8a2f)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/4a8fd20b-62cb-4d3e-b608-578083be5e89)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/b5f9e495-6455-49c9-8f6a-a96294f68ac1)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/63ac9bc8-1f46-4bfd-a872-6f3e3dfe7641)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/d9d5b60d-24e8-4ff4-8de2-b9c3bece7a8d)

![image](https://github.com/valinet/ExplorerPatcher/assets/892172/a3fc6cce-d958-4866-b6c1-493b0390b0ca)

**Comment by Amrsatrio** [comment] 2024-03-13 10:31
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2975

**Comment by Amrsatrio** [comment] 2024-03-13 10:31
If you want to keep using the transparent taskbar you can try out https://github.com/TranslucentTB/TranslucentTB.

**Closed by Amrsatrio** 2024-03-13 10:31 UTC

**Comment by MarceloMachadoxD** [comment] 2024-03-13 10:32
> Duplicate of #2975

sorry... i'll try find on the code where i can setup it to do an pull request to add this feature

[not familiar to c and c++ but... lets try]

**Comment by Amrsatrio** [comment] 2024-03-13 10:35
https://github.com/valinet/ExplorerPatcher/blob/5e7bad22cd07a7bd7b4ec99dd15de3b1cd14fa6b/ExplorerPatcher/Taskbar10.cpp#L249

Speaking about transparent taskbar, because there are simply too many options/behaviors that a user may want, we don't have plans to add it to EP in the near future.

**Comment by MarceloMachadoxD** [comment] 2024-03-13 10:38
Thanks so much!!!
