### ISSUE TITLE
Left mousebutton doesnT work

### ISSUE THREAD

**Issue by Chrisah1159** [valinet/ExplorerPatcher#3847] opened 2024-10-27 00:17 UTC
The left mousebutton doesn't work if I click at the windows 11 start button - had uninstalled Explorer Patcher and it works as normal

**Comment by pyrates999** [comment] 2024-10-27 00:43
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3837

please close this.

**Closed** 2024-10-27 01:32 UTC
