### ISSUE TITLE
Taskbar transparent

### ISSUE THREAD

**Issue by ChrisOpperman** [valinet/ExplorerPatcher#2739] opened 2024-01-23 06:34 UTC
Since the last Windows update (Cumulative Update for Windows 11 Insider Preview (10.0.22635.3066) (KB5034209)), my taskbar is transparent. Icons still work and load their associated programs but any text or items behind taskbar is visible trough taskbar.
![Taskbar](https://github.com/valinet/ExplorerPatcher/assets/157452077/75002c0b-9ff1-4164-a0ae-6621d650d180)

**Comment by NicciZar** [comment] 2024-01-23 10:18
The same issue being discussed here https://github.com/valinet/ExplorerPatcher/issues/2722

**Comment by Amrsatrio** [comment] 2024-01-24 01:43
Duplicate of #2722

**Closed by Amrsatrio** 2024-01-24 01:43 UTC
