### ISSUE TITLE
Windows 11 Command Bar (classic Address bar) fix

### ISSUE THREAD

**Issue by IvyAnnette** [valinet/ExplorerPatcher#2989] opened 2024-03-13 12:28 UTC
Did this feature for the file explorer ever get fixed new patches? It worked in an earlier versions, but hasn't worked now for months.

**Comment by pyrates999** [comment] 2024-03-13 13:30
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment] 2024-03-13 13:59
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2701

**Comment by Amrsatrio** [comment] 2024-03-13 14:00
I did not touch explorerframe.dll in this update. If I fixed the classic navigation bar feature, I would've posted it in the release notes.

**Closed by Amrsatrio** 2024-03-13 13:59 UTC
