### ISSUE TITLE
Customizing behavior of notification areas does not work anymore

### ISSUE THREAD

**Issue by capricorn8** [valinet/ExplorerPatcher#2917] opened 2024-02-26 21:46 UTC
Since a few days, the Task Manager icon has disappeared from the notification area. It's part of the system tray now.
It seems that EP is the reason for this. 

In EP properties, Taskbar, Customize notification area icons every entry in the list except Dropbox (which is visible indeed as an icon) is listed as "Only show notifications". When trying to change this to "Show icon and notification" for any entry, nothing happens and checking the list again reveals that the change has not been accepted - "Only show notifications".

Clicking "Always show all icons and notifications on the taskbar" works as expected but it's not possible anymore to specify the behavior of individual apps/icons.

![attachment](https://github.com/valinet/ExplorerPatcher/assets/33000800/98a25b7b-11ee-45bb-bd29-c0d610638312)

**Comment by pyrates999** [comment] 2024-02-26 22:12
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.

**Closed** 2024-02-27 06:23 UTC
