### ISSUE TITLE
Right clicking a task bar icon gives me the windows 11 context menu instead of a windows 10 menu when on the right

### ISSUE THREAD

**Issue by Astrogem2** [valinet/ExplorerPatcher#3550] opened 2024-08-10 03:29 UTC
I updated ExplorerPatcher since there were updates available, but afterwards when I tried to use the context menu for the pinned apps on my taskbar, which is on the right side, it gives me the windows 11 context menu instead of the windows 10 menu it used to give me. I looked into the wiki, but I don't see an option to turn it back on, and I really liked using the windows 10 context menu instead of the windows 11 version, since it was more open with more options to click on.

**Comment by pyrates999** [comment] 2024-08-10 12:10
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Astrogem2** [comment] 2024-08-10 19:04
Version 23H2 (OS Build 22631.2958), x64 based
ExplorerPatcher 22621.3527.65.5
![image](https://github.com/user-attachments/assets/a486dd4c-6910-4fcd-88a8-9950c4be7577)
![image](https://github.com/user-attachments/assets/431ce80c-b7ac-447c-9daf-b5b1851370ba)
![image](https://github.com/user-attachments/assets/0836c699-e23d-4d09-9a60-c06fa92761f4)
![image](https://github.com/user-attachments/assets/3fb4ef5b-3d53-4b49-a7b0-a9c079e45809)
![image](https://github.com/user-attachments/assets/75bd6825-fd52-46a6-856e-deac8e110c34)
![image](https://github.com/user-attachments/assets/db507802-8354-4403-a9dd-ee1be1369da4)
![image](https://github.com/user-attachments/assets/2da7e86b-ad6f-47bf-8452-22a6a837ab93)
![image](https://github.com/user-attachments/assets/3e3e95bd-d622-4aea-ac75-8f619570a31f)
![image](https://github.com/user-attachments/assets/3589c0d2-e90b-4a3e-a2db-9cda524b745a)
Sorry if its a lot of images.
I don't have any other software the modifies the UI of windows.

**Comment by pyrates999** [comment] 2024-08-10 22:11
Did you mean 22631.3958?

Use Windows 10 (ExplorerPatcher) taskbar style. We no longer offer more support on the stock Windows 10 taskbar.

If that doesn't work, try setting the start menu to windows 10.

**Comment by Astrogem2** [comment] 2024-08-11 00:28
Yeah, 22631.3958, windows 11, and I tried the start menu windows 10 style, but right clicking on the apps on the task bar still gives me the windows 11 style of context menu, but it's specifically only does the windows 11 style when I put the taskbar to the right side, on the bottom it gives me the windows 10 style context menu.

**Comment by pyrates999** [comment] 2024-08-11 00:43
Open up EP Properties application, go to taskbar, and set **taskbar style** to **Windows 10 (ExplorerPatcher)**, _not_ **Windows 10**.  We no longer offer more support on the stock Windows 10 taskbar.

**Comment by Astrogem2** [comment] 2024-08-11 01:23
![image](https://github.com/user-attachments/assets/215238f2-7778-4ce2-a9c9-de6cf1b67067)
I don't see an option for windows 10 (ExplorerPatcher)

**Comment by Amrsatrio** [comment] 2024-08-11 04:34
EP does not offer modifications to the jump list menu, if that's what you mean by the menu that appears when right clicking pinned icons. It is not a bug.

@pyrates999 Windows 10 (ExplorerPatcher) taskbar is only available on 66.x+

**Comment by pyrates999** [comment] 2024-08-11 04:50
Oh right, sorry.

**Comment by pyrates999** [comment] 2024-08-11 06:28
can you show a screen shot of you right clicking on the taskbar while it's on the bottom?  And then a screen shot of you right clicking on the taskbar while it's on the right side?

**Comment by Astrogem2** [comment] 2024-08-11 15:18
![image](https://github.com/user-attachments/assets/0245f453-8b64-4301-a73a-ed58dff4b118)
![image](https://github.com/user-attachments/assets/27e5a664-4938-4427-8b34-dae6c75f5fde)
It's like a big version on the bottom, and a mini one on the right, I've just been calling them 10 and 11 respectively cause that's what it feels like, sorry if they're not actually called that. I just want the big version to be available to be on the right again, since it used to be that way.

**Comment by Amrsatrio** [comment] 2024-08-11 15:21
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3515

**Comment by Amrsatrio** [comment] 2024-08-11 15:22
Get the latest prerelease version in here: https://github.com/valinet/ExplorerPatcher/releases

Don't forget to configure exclusions. That version fixes the issue.

**Closed by Amrsatrio** 2024-08-11 15:21 UTC

**Comment by Astrogem2** [comment] 2024-08-11 16:35
Cool, after some messing around I got it to work, thanks!
