### ISSUE TITLE
WebView2: weather - under COM Surrgate becomes CPU hog, up to 18%.

### ISSUE THREAD

**Issue by Beaverhoosen** [valinet/ExplorerPatcher#3007] opened 2024-03-15 08:18 UTC
COM Surrogate (7)
WebView2: weather xxxxx(Place), NSW - Google Search 18.5% 18.4%

I have been hunting down what has been consuming excess CPU resources on my Windows 11 system. I have weather displayed in the taskbar; it's a feature I like in Explorer Patcher.

It often happens when starting the PC where WebView2: weather will take up around 10% of the CPU resources, not it is currently pegging 18+% of the CPU.

It has been doing it for some time, even after upgrading to yesterday's latest patch. 

If I kill WebView2: weather (end task) in the task manager, it will reload and act as expected, with very low to zero resources. However, it will return to consuming 10+% of the CPU resources. Today alone, I have ended it as a task three times.

Feel free to let me know if there is anything I can provide to help narrow down the issue. I can't seem to find what triggers the step-up to being a CPU hog.

![image](https://github.com/valinet/ExplorerPatcher/assets/154385350/2e20772b-2d36-48eb-8903-5d1305bad20d)

![image](https://github.com/valinet/ExplorerPatcher/assets/154385350/c672850b-7e3d-4051-bc22-d10cb69baf56)

**Comment by Amrsatrio** [comment] 2024-03-15 10:47
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2096.

**Closed by Amrsatrio** 2024-03-15 10:47 UTC
