### ISSUE TITLE
need help about a BUG

### ISSUE THREAD

**Issue by 469705068** [valinet/ExplorerPatcher#1907] opened 2023-08-23 13:56 UTC
there is a volume bar when i change the volume using win11 taskbar,and it disappears when i use win10 taskbar.
[https://www.elevenforum.com/data/attachments/48/48873-62e590d2d47ade7082e9b930fa16592d.jpg](url)
in addition, the taskbar disappeared when i right click it under win11 style.
really need help

**Comment by Vipin2003** [comment] 2023-08-23 16:56
It is a known bug from 2048 preview update.
Just wait as valinet is working on fixing all currently running bugs from 1992 version to 2134. Wait patiently as he is doing his work and making EP stable for us.

**Comment by Poopooracoocoo** [comment] 2023-08-23 20:49
You need to state which OS build and EP version you have. 
Duplicate of #1692

**Closed by Poopooracoocoo** 2023-08-23 20:49 UTC
