### ISSUE TITLE
Customize notification area icons not working

### ISSUE THREAD

**Issue by Guerrilla-RadiO** [valinet/ExplorerPatcher#3466] opened 2024-07-10 17:42 UTC

**Comment by pyrates999** [comment] 2024-07-11 01:57
You can drag and drop the icon in the system tray to the popup menu that you don't want shown.

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this.

**Closed** 2024-07-11 18:47 UTC
