### ISSUE TITLE
Updating to version 22621.3007.63.3 makes Windows Defender detect a Trojan

### ISSUE THREAD

**Issue by Pessoa1769** [valinet/ExplorerPatcher#2885] opened 2024-02-21 15:45 UTC
When updating to version 22621.3007.63.3, Windows Defender detects that there is a Trojan and declines updating ExplorerPatcher

When opening Windows Defender, it says:
Trojan:Win32/Wacatac.B!ml

**Comment by miles-prower** [comment] 2024-02-21 15:59
Same, except Defender is detecting «**Backdoor:Win32/Bladabindi!ml**»:

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Backdoor%3AWin32%2FBladabindi!ml&threatid=2147748148

**Comment by pcgames3112** [comment] 2024-02-21 16:01
Also getting the `Backdoor:Win32/Bladabindi!ml` warning on my end.

**Comment by AhmadxAli** [comment] 2024-02-21 16:02
same

**Comment by mmschmieg** [comment] 2024-02-21 16:02
I'm getting HackTool:Win64/Patcher!MSR.

**Comment by KhasanovRustam** [comment] 2024-02-21 16:04
Trojan:Win32/Wacatac.B!ml detected in file: C:\Users\rusta\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https꞉∕∕github.com∕valinet∕ExplorerPatcher∕releases∕latest∕download∕ep_setup.exe

**Comment by astrukme** [comment] 2024-02-21 16:10
Defender detects Backdoor:Win32/Bladabindi!ml

**Comment by shrydvd1** [comment] 2024-02-21 16:15
Detected: Trojan:Win32/Wacatac.B!ml
Status: Removed
Details: This program is dangerous and executes commands from an attacker.

**Comment by dberken** [comment] 2024-02-21 16:16
Same problem here seeing both Trojan:Win32/Wacatac.B!ml and HackTool:Win64/Patcher!MSR.

**Comment by Darth-Postal** [comment] 2024-02-21 16:22
Same.
![image](https://github.com/valinet/ExplorerPatcher/assets/19946716/8bd4bf5b-9ce8-45ee-802b-c87b1fdf064b)

**Comment by mkbel** [comment] 2024-02-21 16:31
When updating to version [22621.3007.63.3](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3007.63.3_1517de0) using taskbar/properties/updates/Update program and restart File Explorer
I got error message:
```
Header:
C:\Users\censored\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https://
Text:
C:\Users\censored\AppData\Roaming\ExplorerPatcher\Update for ExplorerPatcher from https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe

Operation did not complete successfully because the file contans a viros or potentially unwanted software.
Buttons:
OK
```
When I download [22621.3007.63.3](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3007.63.3_1517de0) manually and try to run ep_setup.exe I got blue square message:
```
This app can't run on your PC
To find a version for your PC, check with the software publisher.
Buttons:
Close
```
When this message is displayed, area around that message on that particular display is slightly grayed out - similar to when app is asking for administrator privilege.

**Comment by mkbel** [comment] 2024-02-21 16:44
This is weird, file ep_setup.exe downloaded from [22621.3007.63.3](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3007.63.3_1517de0) using Firefox has 0 bytes on my hard drive.

**Comment by mkbel** [comment] 2024-02-21 16:47
When I check Firefox downloads I see some info message there:
![image](https://github.com/valinet/ExplorerPatcher/assets/35807926/d5dd86bc-c076-4300-a50d-222b97dbc627)
Details:
![image](https://github.com/valinet/ExplorerPatcher/assets/35807926/a7ae2dc8-47c2-4eae-9fb7-d43735f7c322)

**Comment by mkbel** [comment] 2024-02-21 16:50
When I allow download from Firefox, I got some Windows defender security alert:
![image](https://github.com/valinet/ExplorerPatcher/assets/35807926/8021cfe8-ce28-4770-9e17-5c994df41337)

**Comment by twistios** [comment] 2024-02-21 16:51
This is a duplicate of #2873.

**Closed** 2024-02-21 19:18 UTC

**Comment by kilgorezer** [comment] 2024-09-11 20:53
i got an error too
