### ISSUE TITLE
Windows 11 Task Bar Bug.

### ISSUE THREAD

**Issue by xsm99** [valinet/ExplorerPatcher#1904] opened 2023-08-23 12:09 UTC
https://imgur.com/a/zGWEqtY So when i click right click on a taskbar it's just restarting, any fix?

**Comment by pyrates999** [comment] 2023-08-23 12:46
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by GinoMan** [comment] 2023-08-23 13:27
> duplicate of: #1828
> 
> Please close this one.
> 
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

That would be a workaround, not a fix. 

A fix would mean that you don't need to change configuration to ameliorate the bug.

**Comment by e-t-l** [comment] 2023-08-23 13:31
> > duplicate of: #1828
> > Please close this one.
> > Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"
> 
> That would be a workaround, not a fix.
> 
> A fix would mean that you don't need to change configuration to ameliorate the bug.

Exactly. I _like_ being able to access EP Properties via Taskbar. (If this is the only current workaround, I think I'm going to add a shortcut to the Properties executable to the Desktop context menu)

**Closed as not planned** 2023-08-23 13:35 UTC
