### ISSUE TITLE
Doesn't work anymore - latest windows update

### ISSUE THREAD

**Issue by IAADIA** [valinet/ExplorerPatcher#1896] opened 2023-08-22 20:40 UTC
<img width="408" alt="Screenshot 2023-08-22 120447" src="https://github.com/valinet/ExplorerPatcher/assets/122183072/9e65bdff-0dbf-4ab8-ad3d-c45cf7c095c6">

Essentially it runs File Explorer automatically then crashes it as of 8/18. Worked prior to that.

**Comment by michaltalaga** [comment] 2023-08-22 21:13
on my Windows 10.0.22621.2215 it does not crash but I can't open start menu.

**Comment by Poopooracoocoo** [comment] 2023-08-22 21:36
Need more info. Provide EP version and Windows build number. 

Likely a duplicate of #1798

**Comment by kbmarisa** [comment] 2023-08-22 22:21
I didn't crash after this windows update but start menu wents out of commission. With very slow icon loading after first login. 
Current using 22621.1992.56.1 which the latest version, with Windows 11 22H2 22621.2215 .

**Comment by Poopooracoocoo** [comment] 2023-08-22 22:24
@kbmarisa Preview updates are not supported

**Comment by edsonmoretti** [comment] 2023-08-23 12:31
Acabei achando a solução temporária.

work for me:
https://github.com/valinet/ExplorerPatcher/issues/1892#issuecomment-1688453251

1 - uninstall explorerpatcher (https://allthings.how/how-to-use-explorer-patcher-to-bring-back-many-windows-10-styles-on-windows-11/#:~:text=Roll%20Back%20to%20Default%20Windows%2011%20Appearance)
2 - delete user appdata folder (roaming) "explorerpatcher" (win+R -> %appdata% -> enter)
3 - uninstall last win update KB5029263 in powershell admin console: wusa /uninstall /kb:5029263
4 - reboot PC
6 - reinstall explorerpatcher.

**Comment by SiteSplat** [comment] 2023-08-23 15:01
so is this confirmed? 
EP does NOT work under win 11 with the update KB5029263?

I see so many issues about this update KB5029263 (before this was the update preview version)

@valinet this update from 4h ago does not solve the issue with KB5029263 correct? 
Are you planning to support that update seeing as its not a preview release any longer? 

Please advice. Thanks!

**Comment by Vipin2003** [comment] 2023-08-23 16:56
Just wait as valinet is working on fixing all currently running bugs from 1992 version to 2134. Wait patiently as he is doing his work and making EP stable for us.

**Comment by scardigne** [comment] 2023-08-23 23:56
damn man this just completely screws my taskbar now latest updates

**Comment by MightyM8** [comment] 2023-08-24 00:30
![image](https://github.com/valinet/ExplorerPatcher/assets/95981915/0136a8df-f24b-41b5-a284-aba785db9fe4)
I do not even get the "Properties" in the right click on Task Bar menu
![image](https://github.com/valinet/ExplorerPatcher/assets/95981915/80a4424e-1375-46c2-9186-5f4f93126281)

**Closed as not planned** 2023-08-24 08:36 UTC
