### ISSUE TITLE
Issue: Classic Adress Bar option not working (22631.3527)

### ISSUE THREAD

**Issue by WinAurora** [valinet/ExplorerPatcher#3230] opened 2024-05-04 16:35 UTC
When i downloaded Windows 11, the first thing i have installed is ExplorerPatcher, just to enable the classic adress bar since in the new one you can almost have no control on it, like moving files and stuff.

The classic adress bar option did **work** before, but now it just suddenly stopped working after an update.

Proof that i actually have the **Control Interface set to Classic Adress Bar**:
![Screenshot 2024-05-04 193340](https://github.com/valinet/ExplorerPatcher/assets/168923855/bd2a8d14-e543-4799-91a7-8202e7f26506)
yet.. ExplorerPatcher just **refuses to modify the explorer**.
![Screenshot 2024-05-04 193410](https://github.com/valinet/ExplorerPatcher/assets/168923855/eb84180f-51ab-4023-a2d9-cca354e50092)

**Comment by pyrates999** [comment] 2024-05-05 11:41
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2701

Please close this.

**Comment by WinAurora** [comment] 2024-05-05 13:25
> Duplicate of: #2701
> 
> Please close this.

Closed.

**Closed** 2024-05-05 13:26 UTC
