### ISSUE TITLE
Task bar suddenly transparent

### ISSUE THREAD

**Issue by LSchulzCan** [valinet/ExplorerPatcher#2992] opened 2024-03-13 15:41 UTC
Today when I arrived at my computer, the taskbar on Windows 11 is completely transparent.

![2024-03-13 Transparent Taskbar](https://github.com/valinet/ExplorerPatcher/assets/97815601/d4a4e452-081a-4f5b-aba8-ef16fb5ff688)

I haven't changed any settings since this happened and I've Googled and checked Windows and ExplorerPatcher settings but do not see what could be causing this issue.

**Comment by Skipuppy** [comment] 2024-03-13 15:47
I updated Windows yesterday to OS Build 22631.3296 and then my taskbar was transparent upon reboot.  I uninstalled KB5035853 and then my taskbar was no longer transparent.  This morning my machine updated again and again the taskbar was transparent. Seems like we need an update to EP.

**Comment by PhilllChabbb** [comment] 2024-03-13 15:55
Experienced the same thing this morning. Following last night's Windows 11 update, the taskbar turned transparent.
A [number of users on Twitter/X](https://twitter.com/search?q=explorerpatcher&src=typed_query) are reporting similar issues.

**Comment by Skipuppy** [comment] 2024-03-13 15:55
I just downloaded EP V 22621.3296.64.1 Pre-Release and that seems to have fixed the issue.  Thanks!

**Comment by PhilllChabbb** [comment] 2024-03-13 15:59
> I just downloaded EP V 22621.3296.64.1 Pre-Release and that seems to have fixed the issue. Thanks!

Worked for me! Big Thanks! :)

**Comment by chargard** [comment] 2024-03-13 16:18
Hi, this is a major issue and has ruined my day! I'm not a techie, so would someone please explain how I can download and install the pre-relesae patch. It's just not clear. As a footnote, the Uminstall for Explorer Patcher doesn't work either. Many thanks for your help

**Comment by Skipuppy** [comment] 2024-03-13 16:29
Google explorer patcher download and you can find the pre-release version
on Major Geeks.  When you try to install it Windows prevents it but you can
override that warning.

**Comment by LSchulzCan** [comment] 2024-03-13 16:29
> I just downloaded EP V 22621.3296.64.1 Pre-Release and that seems to have fixed the issue. Thanks!

That worked.  Thank you.

**Comment by HotBlack77** [comment] 2024-03-13 16:33
Can confirm pre-release version 22621.3296.64.1  fixes the issue.
You can go to settings (properties when you right click the taskbar) in ExplorerPatcher and then just enable pre-release versions and do an update to get the new version.

**Comment by chargard** [comment] 2024-03-13 16:34
> Google explorer patcher download and you can find the pre-release version on Major Geeks. When you try to install it Windows prevents it but you can override that warning.

Thank you so much!

**Comment by BroncoDJ** [comment] 2024-03-13 16:51
> Hi, this is a major issue and has ruined my day! I'm not a techie, so would someone please explain how I can download and install the pre-release patch. It's just not clear. As a footnote, the Uninstall for Explorer Patcher doesn't work either. Many thanks for your help

![pre](https://github.com/valinet/ExplorerPatcher/assets/103258235/5e34b85e-0b91-4c0f-a709-bb81ff1bf665)

**Comment by wystan234** [comment] 2024-03-13 21:52
Unfortunately this did not work for me - still cannot see time and such....

**Comment by Amrsatrio** [comment] 2024-03-13 22:10
Duplicate of #2975.

**Closed by Amrsatrio** 2024-03-13 22:10 UTC

**Comment by valinet** [comment] 2024-03-13 22:43
> > Can confirm pre-release version 22621.3296.64.1 fixes the issue. You can go to settings (properties when you right click the taskbar) in ExplorerPatcher and then just enable pre-release versions and do an update to get the new version.
> 
> Can also confirm that this fixed the issue for me. Thanks much @valinet for providing the prompt fix!

I will direct and supplement myself the thanks to @Amrsatrio, he's at work on this one and much more.
