### ISSUE TITLE
Explorer pacther refresh click boton right mouse

### ISSUE THREAD

**Issue by martinhodfranco** [valinet/ExplorerPatcher#2632] opened 2023-12-29 14:24 UTC
When I right-click on a file or on the desktop, the explorer reinstalls. I already reinstalled and the problem continues.

**Comment by pyrates999** [comment] 2023-12-29 23:33
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

please close this

**Comment by Amrsatrio** [comment] 2023-12-31 15:58
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

**Closed by Amrsatrio** 2023-12-31 15:58 UTC
