### ISSUE TITLE
The start menu can't be switched to win10

### ISSUE THREAD

**Issue by LNHHandsome** [valinet/ExplorerPatcher#3699] opened 2024-09-14 11:06 UTC
![QQ_1726311807718](https://github.com/user-attachments/assets/9ddf3b5b-f784-42ab-b077-49cb52f713a7)
![A](https://github.com/user-attachments/assets/ec7b3977-c891-447a-972a-65eb51c34c1a)
After the system is updated to this version, it is not possible to change the start menu to win10.
Can I go back to a previous version?

**Comment by pyrates999** [comment] 2024-09-14 11:19
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3667

please close this.

**Comment by Amrsatrio** [comment] 2024-09-14 12:03
The 10 start menu is gone in your build.

**Closed by Amrsatrio** 2024-09-14 12:03 UTC
