### ISSUE TITLE
Start menu search bar not working

### ISSUE THREAD

**Issue by luizgamabh** [valinet/ExplorerPatcher#1513] opened 2023-06-02 17:26 UTC
I am not able to search though start menu items. By default I would go into the start menu and type in some term, the search would start automatically and I could easily find any program. Now the search bar doesn't work, and when you go into the start menu and start typing the name of some app, you just keep jumping between pinned apps, as you type a letter, it will select an app that starts with that letter. It has become almost impossible to open certain apps or settings directly from the start menu.

![image](https://github.com/valinet/ExplorerPatcher/assets/1342678/1f114ee2-cd0c-44db-993d-f9b489c806fd)

**Comment by pyrates999** [comment] 2023-06-02 21:24
Uninstall explorer patcher, reboot, and see if search still behaves like this.

**Comment by stef-barburou** [comment] 2023-06-06 18:03
getting the same issue since last update

**Comment by Luxato** [comment] 2023-06-08 13:17
Same issue, will try @pyrates999 's solution.

**Comment by pyrates999** [comment] 2023-06-08 19:24
The reason I'm asking to do that is to determine if it's a bug in windows or caused by explorer patcher.

**Comment by luizgamabh** [comment] 2023-06-09 21:33
> Uninstall explorer patcher, reboot, and see if search still behaves like this.

No, I have uninstalled it, and the stat menu search is working fine, when I open the start menu and start typing something, automatically it starts to search some app. If Explorer Patcher installed I can't search any app, nor starting to type the app name, nor clicking on the search bar that is totally unusable, you can't select it to type something.

**Comment by pyrates999** [comment] 2023-06-10 07:44
You haven't posted the version of explorer patcher you installed and the windows build version.  You can find that out by running winver.

**Comment by KisImre** [comment] 2023-06-11 09:54
I have the same problem. Uninstalling ExplorerPatcher fixes the issue for me as well.
ExplorerPatcher version: 22621.1555.55.1
Windows build version: 22621.1702

**Comment by pyrates999** [comment] 2023-06-11 10:23
Let's see if it's a setting causing this:

1. uninstall explorer patcher
2. delete the same registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher

Then attempt to search in the start menu.

**Comment by KisImre** [comment] 2023-06-11 10:46
> Let's see if it's a setting causing this:
> 
> 1. uninstall explorer patcher
> 2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
> 3. reboot
> 4. install explorer patcher
> 5. verify you get a notification that symbols have been downloaded
> 6. restart windows explorer using either the task manager or in the properties window of explorer patcher
> 
> Then attempt to search in the start menu.

This solved the issue, the search box works again. Thank you.

**Comment by luizgamabh** [comment] 2023-06-11 17:19
Windows 22H2 Build 22621.1702
ExplorerPatcher 22621.1555.55.1
That solution also worked for me. Thanks.

**Comment by pyrates999** [comment] 2023-06-11 23:33
Please close this then.

**Closed** 2023-06-17 18:28 UTC

**Comment by Sh4d** [comment] 2023-10-03 16:31
@luizgamabh I think this needs to be reopened for some further digging.

I did the above fix last week and it's worked great and then suddenly now it's broken again. Not ideal to have to do a wipe + reinstall regularly.

**Comment by pyrates999** [comment] 2023-10-04 15:10
> @luizgamabh I think this needs to be reopened for some further digging.
> 
> I did the above fix last week and it's worked great and then suddenly now it's broken again. Not ideal to have to do a wipe + reinstall regularly.

try this to rebuild the search index: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/windows-search-performance-issues

**Comment by Sh4d** [comment] 2023-10-04 16:07
> > @luizgamabh I think this needs to be reopened for some further digging.
> > I did the above fix last week and it's worked great and then suddenly now it's broken again. Not ideal to have to do a wipe + reinstall regularly.
> 
> try this to rebuild the search index: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/windows-search-performance-issues

Just tried that but no luck. Just to clarify on behaviour, it's not an issue of not finding things via search.

When I hit the start button and start typing, there's no reaction from the start menu to my keyboard input. If I click on the actual search box in the start menu at the top, no cursor ever appears and I can't type into the field at all.

**Comment by Sh4d** [comment] 2023-10-04 16:37
Did a bit of playing around with this, none of these things help:
 - Updating to reprelease versions
 - Wiping the registry key and restarting the app (no system reboot)
 - Restoring default settings (under About)

**Comment by helixxger** [comment] 2023-10-08 10:17
Have the same issue, reinstalling helps, but not long, it is breaking again from time to time

EP: 22621.2361.58.4

Windows 11 Build 10.0.22621.2361

**Comment by glctcx** [comment] 2023-10-09 21:09
> Let's see if it's a setting causing this:
> 
>     1. uninstall explorer patcher
> 
>     2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
> 
>     3. reboot
> 
>     4. install explorer patcher
> 
>     5. verify you get a notification that symbols have been downloaded
> 
>     6. restart windows explorer using either the task manager or in the properties window of explorer patcher
> 
> 
> Then attempt to search in the start menu.

thank you so much it worked !

**Comment by jincao1** [comment] 2023-10-12 00:36
> Have the same issue, reinstalling helps, but not long, it is breaking again from time to time
> 
> EP: 22621.2361.58.4
> 
> Windows 11 Build 10.0.22621.2361

Also facing the same issues on the same build of ExplorerPatcher. Windows build 10.0.22621.2428

**Comment by CMeCode** [comment] 2023-11-01 15:36
Why closed? Experiencing same issue on 22621.2428.59.1

**Comment by pyrates999** [comment] 2023-11-02 10:41
> Why closed? Experiencing same issue on 22621.2428.59.1

Please post windows version and build.  You can find this by running winver.

**Comment by Lyve1981** [comment] 2023-11-23 15:33
Same issue here
Windows 11 Pro Build 22621.2715
ExplorerPatcher 22621.2506.60.1

Its a keyboard focus problem, not a search index problem, as others have pointed out already. Even when left-clicking into the search box, there is no indicator that the text field gets focused, there is no blinking cursor

**Comment by Lyve1981** [comment] 2023-11-23 15:35
Another interesting observation: The focus seems to be on the part below the search box instead. if I press the E key, the selection rectangle jumps to Edge, if I press M it jumps to Mail, etc. However, it won't let me focus the search text box via clicking

**Comment by pyrates999** [comment] 2023-11-24 01:39
If it's a keyboard focus problem, this is not a bug in EP I think.

**Comment by RobAus** [comment] 2024-01-31 12:55
Happening again on the latest version =( 

Version 22621.2861.62.2

Anyone else having this issue again?

**Comment by pyrates999** [comment] 2024-01-31 13:04
> Happening again on the latest version =(
> 
> Version 22621.2861.62.2
> 
> Anyone else having this issue again?

open up task manager and kill explorer.exe and then run task manager again and run explorer.exe

**Comment by RobAus** [comment] 2024-01-31 13:10
Thanks for the suggestion but no luck...

**Comment by RobAus** [comment] 2024-01-31 13:16
Refuses to activate the search bar. Can click as much as I like, similar to last time.  Previously, I gave up fixing it and after an EP update, it just resolved itself.

**Comment by pyrates999** [comment] 2024-01-31 14:08
Please open up a new discussion then and link it to this one.

**Comment by daalta** [comment] 2024-02-11 21:39
Hmm, I'm confused about why this issue was closed. 🤔
I'd appreciate a fix!

**Comment by pyrates999** [comment] 2024-02-11 23:10
it's a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2523
