### ISSUE TITLE
Opening a new File Explorer window crashes explorer.exe

### ISSUE THREAD

**Issue by NotLoopyy** [valinet/ExplorerPatcher#1942] opened 2023-08-25 21:45 UTC
It doesn't happen every time I open a new window. Maybe 1 in every 20 times it happens. I have attached a video of what happens when it crashes.

Windows Version: Windows 11 Pro 22H2 Build 22621.2134

Explorer Patcher Version 22621.1992.56.3

https://github.com/valinet/ExplorerPatcher/assets/87902962/11808cc7-8b82-455d-ad1f-a9d7bc23a8e9

**Comment by descentfan1975** [comment] 2023-08-25 22:15
I had the same issue. So tried uninstalling it.

Now, it crashes on install, then when I right-click on the taskbar it crashes over and over until I get the message that it crashed 3 times in 10 seconds.

Windows 11 Pro
22H2
Installed on 20 Mar 2023
OS Build 22621.2215

**Comment by Gxtod** [comment] 2023-08-26 07:26
I have the same problem: https://github.com/valinet/ExplorerPatcher/issues/1935

**Comment by SouthernHeftruck** [comment] 2023-08-26 10:17
Same. Uninstalled KB5029263 as only workable solution

**Comment by pyrates999** [comment] 2023-08-26 11:28
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by Girofox** [comment] 2023-08-26 11:31
For explorer crashes randomly, often after unlocking User or when exiting standby.

**Comment by Girofox** [comment] 2023-08-26 12:15
This is my crash message in event viewer, it shows `Windows.UI.Xaml.dll` has something to do with it:

![image](https://github.com/valinet/ExplorerPatcher/assets/43116061/ef8641b3-eeda-475e-bcdf-a91e5a4f7278)

**Comment by saulob** [comment] 2023-09-03 19:32
Same problem here

**Comment by Bagu** [comment] 2023-09-04 11:11
> duplicate of: #1828
> 
> Please close this one.
> 
> Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

Don't work

**Comment by Bagu** [comment] 2023-09-05 07:22
I tried both (with full uninstall, clean, reboot, reinstall between tries), but now it have an X.

**Comment by pyrates999** [comment] 2023-09-05 07:29
Click on it so it has a tick mark beside "Do not change the taskbar context menu".  And then restart file explorer.

**Comment by Bagu** [comment] 2023-09-05 07:32
If you read my sentence, you can see i try with both...

**Comment by pyrates999** [comment] 2023-09-05 09:41
After it showed a tick mark beside "Do not change the taskbar context menu", did you restart file explorer?

What about rebooting after doing the above?

**Comment by Bagu** [comment] 2023-09-05 10:39
Did you really read my first answer ?
In short : yes.

**Comment by pyrates999** [comment] 2023-09-05 20:42
Just being thorough.  Now please wait for this to get fixed.

Somethings you can try.

1. uninstall EP and reboot
2. Then open a command prompt with elevated privileges and run the following: sfc /scannow

**Comment by Bagu** [comment] 2023-09-05 21:20
Ok.
To be clear, i already done these things.
sfc /scannow
dism /online /cleanup-image /startcomponentcleanup
dism /online /cleanup-image /restorehealth
I already try to install ep to a fresh install.

But, on a clean an updated windows 11, ep make a random explorer restart.
Where can i find some usefull log to contribute to find where ep fail please ?

**Comment by pyrates999** [comment] 2023-09-05 21:35
When it happens, do the following:

1. open up windows event viewer or computer management
2. go to Event Viewer and go to Windows Logs -> Application
3. check to see if there's an entry for explorer.exe and paste it here.

**Comment by descentfan1975** [comment] 2023-09-07 04:24
<HTML><HEAD>
<SCRIPT>
  
    function Toggle(node)
    {
      if (!window.fullyLoaded) return;

      var divNode = node.nextElementSibling;

      // nextElementSibling may unexpectedly return null
      if (!divNode) divNode = node.nextSibling;
      if (!divNode || divNode.nodeType != 1) return;

      // Expand the branch?
      if (divNode.style.display == 'none')
      {
        // Change the sign to "-".
        var bNode = node.getElementsByTagName("b")[0];
        bNode.innerText = "-";

        // show the branch
        divNode.style.display = '';
      }
      else // Collapse the branch
      {
        // Change the sign to "+".
        var bNode = node.getElementsByTagName("b")[0];
        bNode.innerText = "+";

        // hide the branch
        divNode.style.display = 'none';
      }
    }

    // Toggle "System" element by default so that its default status is to hide its children
    function ToggleSystemElement()
    {
      var body = document.getElementById("body");
      var anchor = body.getElementsByTagName("table")[0];
      Toggle(anchor);
    }

    // If binary data is present in event XML, show it in friendly form.
    function ProcessBinaryData(binaryString, binaryDataCaption, wordsFormatString, bytesFormatString, normalFont, fixedWidthFont)
    {
      var bodyNode = document.getElementById("body");

      // Add a <hr> at the end of the HTML body.
      bodyNode.appendChild(document.createElement("hr"));      

      // This paragraph (p element) is the "Binary data:" literal string.
      var p = document.createElement("p");
      p.style.fontFamily = normalFont;
      var b = document.createElement("b");
      b.appendChild(document.createTextNode(binaryDataCaption));
      p.appendChild(b);
      p.appendChild(document.createElement("br"));
      bodyNode.appendChild(p);

      //
      // Show binary data in Words format.
      //
      p = document.createElement("p");
      p.style.fontFamily = normalFont;
      p.appendChild(document.createTextNode(wordsFormatString));
      bodyNode.appendChild(p);

      // Must use fixed-width font for binary data.
      p = document.createElement("p");
      p.style.fontFamily = fixedWidthFont;
    
      var i = 0;
      var j = 0;
      var s, tempS;
      var translatedString;
      var charCode;
      var byte1, byte2;

      // Each character in binaryString is a hex (16-based) representation of
      // 4 binary bits. So it takes 2 characters in binaryString to form a
      // complete byte; 4 characters for a word.
      while (i < binaryString.length) {

        s = (i / 2).toString(16);    // To hex representation.
        while (s.length < 4) {
          s = "0" + s;
        }
        s += ": ";

        // DWords representation is simply a rearrangement of the original binaryString
        // For example, from:
        // 
        // 0000000002005600000000000f000540
        //
        // (which is 00 00 00 00 02 00 56 00 00 00 00 00 0f 00 05 40).
        //
        // to:
        //
        // 0000: 00000000 00560002 00000000 4005000f
        // 8 words per line, 4 DWords per line.
        for (j = 0; j < 4; j++) {
          s += binaryString.substring(i + 6, i + 8);
          s += binaryString.substring(i + 4, i + 6);
          s += binaryString.substring(i + 2, i + 4);
          s += binaryString.substring(i, i + 2) + " ";
          i += 8;
        }

        p.appendChild(document.createTextNode(s));
        p.appendChild(document.createElement("br"));
      }

      bodyNode.appendChild(p);

      //
      // Show binary data in bytes format.
      //
      p = document.createElement("p");
      p.style.fontFamily = normalFont;
      p.appendChild(document.createTextNode(bytesFormatString));
      bodyNode.appendChild(p);

      // Must use fixed-width font for binary data.
      p = document.createElement("p");
      p.style.fontFamily = fixedWidthFont;
    
      i = 0;
      j = 0;

      // Each character in binaryString is a hex (16-based) representation of
      // 4 binary bits. So it takes 2 characters in binaryString to form a
      // complete byte.
      while (i < binaryString.length) {
        translatedString = "";
        // 2 characters in binaryString to form a byte
        s = (i / 2).toString(16);   // to hex representation.

        // Prefix with '0' until its length is 4.
        while (s.length < 4) {
          s = "0" + s;
        }
        s += ": ";

        // Show 8 bytes per line
        for (j = 0; j < 8; j++) {
          tempS = binaryString.substring(i, i + 2); // 2 for 1 byte
          i += 2;
          s += tempS + " ";

          // Treat tempS as hex integer
          charCode = parseInt(tempS, 16);
          if (charCode < 32) {
            translatedString += ".";
          } else {
            translatedString += String.fromCharCode(charCode);
          }
        }

        while (s.length < 32) {
          s += " ";
        }
        s += translatedString;
        
        p.appendChild(document.createTextNode(s));
        p.appendChild(document.createElement("br"));
      }

      bodyNode.appendChild(p);
    }
  
  </SCRIPT>
</HEAD>
<BODY id=body 
onload=window.fullyLoaded=true;ToggleSystemElement();><TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>System</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Provider</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>Name</B>] </TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">Application 
Error</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>Guid</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">{a0e9b465-b939-57d7-b27d-95d8e925ff57}</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventID</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">1000</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Version</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Level</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">2</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Task</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">100</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Opcode</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Keywords</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0x8000000000000000</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>TimeCreated</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>SystemTime</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">2023-09-07T04:21:51.2410587Z</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventRecordID</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">55791</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'"><B>Correlation</B></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Execution</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>ProcessID</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">23160</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>ThreadID</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">18088</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Channel</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">Application</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Computer</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">CPS-DESKTOP</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Security</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>UserID</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">S-1-5-21-1433234332-2147125120-3220829628-1001</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE></DIV>
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventData</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>AppName</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">explorer.exe</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>AppVersion</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">10.0.22621.2215</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>AppTimeStamp</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">b9c28810</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>ModuleName</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">Windows.UI.Xaml.dll</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>ModuleVersion</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">10.0.22621.2215</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>ModuleTimeStamp</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">ec54f32d</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>ExceptionCode</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">c000027b</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>FaultingOffset</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0000000000872320</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>ProcessId</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0x318c</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>ProcessCreationTime</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0x1d9e0e7fff42a21</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>AppPath</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">C:\Windows\explorer.exe</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>ModulePath</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">C:\Windows\System32\Windows.UI.Xaml.dll</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>IntegratorReportId</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">83bcc021-8ec9-426c-a7a4-53dafed299d3</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>PackageFullName</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top"></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>PackageRelativeAppId</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top"></TD></TR></TBODY></TABLE></DIV></BODY></HTML>

**Comment by pyrates999** [comment] 2023-09-07 10:59
@descentfan1975 That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

Preview updates are not supported by EP.

**Comment by descentfan1975** [comment] 2023-09-08 18:37
> @descentfan1975 That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692
> 
> Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.
> 
> Preview updates are not supported by EP.

I get that you don't want to support release previews, but this crashing has been happening before this preview was installed and has been happening since I installed EP at the beginning of summer. The management interface thing Balabai mentioned seems to be working, but I lose the ability to have the tabbed interface with explorer which I was just starting to get used to.

Overall, love the program and appreciate the work you're doing to support it.

**Comment by pyrates999** [comment] 2023-09-08 21:52
> > @descentfan1975 That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692
> > Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> > In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> > All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> > Preview updates are also not fully tested by Microsoft and thus could have bugs.
> > Preview updates are not supported by EP.
> 
> I get that you don't want to support release previews, but this crashing has been happening before this preview was installed and has been happening since I installed EP at the beginning of summer. The management interface thing Balabai mentioned seems to be working, but I lose the ability to have the tabbed interface with explorer which I was just starting to get used to.
> 
> Overall, love the program and appreciate the work you're doing to support it.

Then don't install preview updates.

**Comment by Girofox** [comment] 2023-09-09 12:31
Why does Microsoft even release preview updates with Windows insider disabled? And this even happens when "Get get latest updates..." is disabled

**Comment by NifTTY** [comment] 2023-09-15 00:33
@pyrates999 

I still have one Win11 Home 22H2 (22621.2134) system using EP 22621.1992.56.3 where the bug doesn't happen!

In this system (Example C from #2055), the Control Interface is set to Windows 11. I have tabbed file browsing and no crash bug when opening new windows. Not sure what's different about this sample.

**Comment by pyrates999** [comment] 2023-09-15 13:38
> @pyrates999 This does not seem to be the same issue as described in #1828 or #2051
> 
> Can you confirm the context?

See answer: https://github.com/valinet/ExplorerPatcher/issues/2051#issuecomment-1721298149

**Comment by Poopooracoocoo** [comment] 2023-09-23 03:50
Should be resolved now. Leave a comment or create a new issue if you're still seeing issues. Make sure to include your OS build and ExplorerPatcher version.

**Closed by Poopooracoocoo** 2023-09-23 03:50 UTC
