### ISSUE TITLE
File Explorer doesn't save the size and position

### ISSUE THREAD

**Issue by geircito** [valinet/ExplorerPatcher#2321] opened 2023-10-17 20:11 UTC
Winver 22H2 (OS Build 22621.2428) (the latest)
ExplorerPatcher 22621.2361.58.4 (the latest)

File explorer save each folder view settings, but NOT their sizes and their position.
Every time I open a folder they are stacked (a little down and a little to the right from the first folder size and position).

How come?

**Comment by pyrates999** [comment] 2023-10-17 22:36
Please include what settings you changed in explorer patcher properties application.

Please show screen shot of what you mean.

**Comment by geircito** [comment] 2023-10-17 23:36
Hi, I know now the File Explorer windows is cascaded (and NOT stacked as I wrote earlier).
On my Desktop I have some most used folders that I open often, and when I open them, each window open stacked from the first File Explorer window (se picture).
In earlier versions of ExplorerPatcher all the folder windows opened at the last size and position, anywhere on the screen.

<img width="684" alt="File Explorer" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/6ece7b80-d81e-4959-ad92-77e56f089648">


Mine ExplorerPatcher Settings:

<img width="364" alt="1 Taskbar" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/b31a39ed-05b3-49b8-ab3a-a1b0a7fbbdc9">

<img width="364" alt="2 System tray" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/bedd764f-6d74-4024-b40f-3dae8df3ce28">

<img width="364" alt="3 File Explorer" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/8f0b2221-2823-445b-a76e-b0b51774d5ff">

<img width="364" alt="4 Start menu" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/fbabea4d-a0a7-426d-bfbf-27251c74442d">

<img width="364" alt="5 Windows switcher" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/c835df79-fd2c-4675-ad00-589cac3357f6">

<img width="364" alt="6 Weather" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/f96278ae-0dcc-4d47-b7d6-3f2e1fbf1c99">

<img width="364" alt="7 Other" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/f0680620-8955-4b01-8b4d-fd022bbd577e">

<img width="364" alt="8 Updates" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/b252485d-4bb0-4e25-8d33-665321adc506">

<img width="364" alt="9 Advanced" src="https://github.com/valinet/ExplorerPatcher/assets/105722507/71be7248-e7f3-452c-8ed7-b38523c873ce">

**Comment by pyrates999** [comment] 2023-10-18 09:53
Does this happen when EP is not installed?

**Comment by Amrsatrio** [comment] 2023-10-22 10:09
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2243

**Closed by Amrsatrio** 2023-10-22 10:09 UTC
