### ISSUE TITLE
Auto-hide toolbar

### ISSUE THREAD

**Issue by mariusartificially** [valinet/ExplorerPatcher#2860] opened 2024-02-19 04:06 UTC
Toolbar auto hide causes teh following issues:
* the start menu is displayed under the startbar
* the start menu loses focus and closing it requires first to click on it

![pexplorer](https://github.com/valinet/ExplorerPatcher/assets/158453668/3189429f-c92d-4a97-90ca-108644651042)

**Comment by pyrates999** [comment] 2024-02-19 04:39
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment] 2024-02-19 07:10
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2744

**Closed by Amrsatrio** 2024-02-19 07:10 UTC
