### ISSUE TITLE
After New Update Right click corner doesnt work as intended

### ISSUE THREAD

**Issue by TheCelestial2000** [valinet/ExplorerPatcher#3869] opened 2024-11-02 01:50 UTC
After the Recent Update the right click function on the start menu doesn't show up anymore

**Comment by ChasingSol** [comment] 2024-11-02 03:20
Same issue here with latest available version of ExplorerPatcher. Using Windows 11 24H2 Build 26100.2161

**Comment by Panzimy** [comment] 2024-11-02 10:54
If you are reading the changelog it is not recommended to use EP on Windows 11 Build 24H2.
[More in the changelog](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.6_92fce8c/)

**Comment by pyrates999** [comment] 2024-11-02 11:04
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3837

please close this.

**Comment by Amrsatrio** [comment] 2024-11-02 11:46
Duplicate of #3842

Don't worry. This is high priority and I'm working on it right now.

**Closed by Amrsatrio** 2024-11-02 11:46 UTC
