### ISSUE TITLE
Taskbar is double width when placed vertically on the left or right side

### ISSUE THREAD

**Issue by marq08** [valinet/ExplorerPatcher#3760] opened 2024-10-03 02:18 UTC
After the latest update to version 22621.3880.66.6 my taskbar when placed vertically on the left side is double-triple the width of what it was before the patch. Full uninstall and reinstall do not address the issue. Placing it horizontally and restarting explorer, then vertically again and restarting explorer will fix it for a few seconds before it widens again.

**Comment by pyrates999** [comment] 2024-10-03 12:08
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2964

please close this.

**Closed** 2024-10-04 04:12 UTC
