### ISSUE TITLE
WinKey+Tab Issue

### ISSUE THREAD

**Issue by Hadipour** [valinet/ExplorerPatcher#1848] opened 2023-08-14 10:32 UTC
[22621.1992.56.1] still have this issue with WinKey+Tab Issue. 
the first time that you use this shortcut then the ALt+Tab shortcut would also stop working.

**Comment by a-allard** [comment] 2023-08-14 11:07
Same on windows 11 10.0.22621.2134.

To get back the Alt+Tab shortcut after pressing Win+Tab I have to restart explorer.

**Comment by pyrates999** [comment] 2023-08-15 12:05
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:06
Closing as duplicate of #1687

**Closed by Poopooracoocoo** 2023-08-22 10:06 UTC
