### ISSUE TITLE
task view doesnt work

### ISSUE THREAD

**Issue by Epixx512** [valinet/ExplorerPatcher#1887] opened 2023-08-22 03:30 UTC
win + tab doesnt work. the button doesnt work. task view doesnt work.

**Comment by nunsamu** [comment] 2023-08-22 04:54
This is the same issue as #1687, see the contents of 'zwassall-globus'.

**Comment by Poopooracoocoo** [comment] 2023-08-22 09:45
Closing as duplicate of #1687 and #1802

**Closed by Poopooracoocoo** 2023-08-22 09:45 UTC
