### ISSUE TITLE
This app can't run on this device 

### ISSUE THREAD

**Issue by golephish** [valinet/ExplorerPatcher#3088] opened 2024-04-04 16:22 UTC
"this app can't run because it causes performance or system issues"

-disabled program compatibility services and restarted 
- 10.0.26100.1
- canary branch insider preview 

note: I did have to uninstall before the last update
![Screenshot 2024-04-04 122229](https://github.com/valinet/ExplorerPatcher/assets/48928387/c9051002-b95e-47b8-86c2-7addccd6ba2e)

**Comment by helloboy4000** [comment] 2024-04-04 16:53
Try this one, It works fine for me https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3296.64.1_9e9c016

**Comment by golephish** [comment] 2024-04-04 17:20
thank you for the quick reply! same error message. I am dumb for being on canary but I want those xbox sounds back :)

**Comment by mackid1993** [comment] 2024-04-04 23:48
This is affecting StartAllBack as well. Tihiy the dev said to rename the StartAllBack installer to anything else. Perhaps try to rename ep_setup.exe and that may let you install.

**Comment by pyrates999** [comment] 2024-04-05 00:38
Canary builds are not supported because the code is not final and can change with each new release.

**Comment by golephish** [comment] 2024-04-05 06:13
thank you all. I figured as much was just sharing what happened. I will try renaming and see if that works!

**Comment by golephish** [comment] 2024-04-05 06:15
![Screenshot 2024-04-05 021429](https://github.com/valinet/ExplorerPatcher/assets/48928387/272ecdc5-48de-4e8d-8052-85b0b0b84a62)

renamed it to heynow and it actually did install !

**Comment by PandaFiredoge** [comment] 2024-04-05 13:52
这是微软故意添加的限制，StartAllBack也遇到了相同的问题，参看[https://www.ithome.com/0/760/090.htm](https://www.ithome.com/0/760/090.htm)（中文网页）

This is a restriction deliberately added by Microsoft, and StartAllBack has encountered the same problem, see [https://www.ithome.com/0/760/090.htm](https://www.ithome.com/0/760/090.htm) (Chinese web page)

**Comment by pyrates999** [comment] 2024-04-09 11:56
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3085

please close this.

https://fxtwitter.com/StartIsBack/status/1775660727719928173

You're not supposed to use ExplorerPatcher on Dev/Canary at the moment.

**Closed** 2024-04-09 20:38 UTC
