### ISSUE TITLE
Search window not centered!!!

### ISSUE THREAD

**Issue by rawSalmon01101** [valinet/ExplorerPatcher#3296] opened 2024-05-19 12:01 UTC
![Screenshot 2024-05-19 172834](https://github.com/valinet/ExplorerPatcher/assets/154772441/43ea8ed8-ae6e-4bc8-b3dc-e9d3691aea3f)
When the start menu is centered, the search menu isn't.
Windows 10 Pro version 22H2 19045.4170

**Comment by pyrates999** [comment] 2024-05-19 12:05
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

Please close this.

**Comment by rawSalmon01101** [comment] 2024-05-19 12:06
> Duplicate of: #1803
> 
> Please close this.

That is not the same issue.

**Comment by rawSalmon01101** [comment] 2024-05-19 12:08
![image](https://github.com/valinet/ExplorerPatcher/assets/154772441/37bda58d-8592-4df6-a694-c145eac65e3a)
![image](https://github.com/valinet/ExplorerPatcher/assets/154772441/78d80030-b7f2-4255-b110-358fbbb7a0e5)
https://github.com/valinet/ExplorerPatcher/assets/154772441/bf8fa133-15d3-4eeb-ba71-02804bd6a71c

**Comment by Amrsatrio** [comment] 2024-05-19 16:01
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2619

**Closed by Amrsatrio** 2024-05-19 16:01 UTC
