### ISSUE TITLE
Changing Taskbar Style to Windows 11, Causes Explorer to Crash When Right Clicking Taskbar on 22621.2215

### ISSUE THREAD

**Issue by AlphaLMN** [valinet/ExplorerPatcher#2047] opened 2023-09-12 05:31 UTC
Windows Explorer crashes every time you right-click on the taskbar, after changing the setting Taskbar Style to Windows 11. No other changes are necessary to reproduce this bug. I have tried restoring the default settings numerous times, rebooting numerous times, and reinstalling ExplorerPatcher with the latest available version from 3 weeks ago.

**Comment by Poopooracoocoo** [comment] 2023-09-12 07:49
Duplicate of #1805

**Closed by Poopooracoocoo** 2023-09-12 07:49 UTC
