### ISSUE TITLE
Windows 10 Start menu doesnt launch

### ISSUE THREAD

**Issue by adisetiawan22** [valinet/ExplorerPatcher#3183] opened 2024-04-26 06:45 UTC
When i was update my windows at May 25, then I restart my laptop, suddenly the start menu change into windows 11 style. Whereas I have set my start menu at explorer patcher properties into windows 10 style, then I restart file explorer but it doesn't work. The start menu keep applying windows 11 style. Even when I was try to restart my laptop, the windows 11 start menu  style keep applying and doesn't change into windows 10 start menu style.

**Comment by eviltek2099** [comment] 2024-04-26 07:32
I'm having same issue.
Windows 11 Pro version 23H2 OS build 22631.3527 Windows Feature Experience Pack 1000.22700.1003.0

**Comment by zhh9211** [comment] 2024-04-26 07:39
Microsoft had announced that it was going to remove the windows 10 start menu completely in the future, is it that this update removes it？

**Comment by PinkYuDeer** [comment] 2024-04-26 08:37
Same issue

**Comment by yhdsl** [comment] 2024-04-26 09:10
I tried the 22621.3527.65.1 Pre-release version and the problem was fixed

**Comment by SeriousConcept1134** [comment] 2024-04-26 09:18
> I tried the 22621.3527.65.1 Pre-release version and the problem was fixed

Would just like to confirm that this worked for me as well. Thank you.

**Comment by pyrates999** [comment] 2024-04-26 12:55
In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by Amrsatrio** [comment] 2024-04-26 13:46
> Microsoft had announced that it was going to remove the windows 10 start menu completely in the future, is it that this update removes it？

Yes, kinda. It's a part of it but fortunately I was able to get around it. Don't expect the 10 start menu to say for longer.

**Comment by Amrsatrio** [comment] 2024-04-26 13:47
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3066

Install the latest prerelease if you want to have working 10 start menu again.

**Closed by Amrsatrio** 2024-04-26 13:47 UTC
