### ISSUE TITLE
 key combination ALT+tab is not longer working

### ISSUE THREAD

**Issue by Fred-ooo** [valinet/ExplorerPatcher#2052] opened 2023-09-13 13:47 UTC
Hi all, 
Several times a day, key combination ALT+tab is not longer working, I have to restart the file explorer.

Version 22621.1992.56.3

**Comment by Poopooracoocoo** [comment] 2023-09-13 14:39
Duplicate of #1687

**Closed by Poopooracoocoo** 2023-09-13 14:39 UTC
