### ISSUE TITLE
The Windows Search disappears with the text bellow when I click on start button

### ISSUE THREAD

**Issue by poluxserver** [valinet/ExplorerPatcher#3801] opened 2024-10-14 22:47 UTC
/
![Capture d'écran 2024-10-15 004432](https://github.com/user-attachments/assets/cf553e8b-2c4e-4b1b-beb1-f213884777e1

**Comment by pyrates999** [comment] 2024-10-15 00:05
no one click this.

**Comment by milesprower2293** [comment] 2024-10-15 03:00
duplicate of #2827

**Closed by milesprower2293** 2024-10-15 03:00 UTC
