### ISSUE TITLE
Action Center not work

### ISSUE THREAD

**Issue by toshirai** [valinet/ExplorerPatcher#2118] opened 2023-09-22 07:49 UTC
With the latest ExplorerPatcher, Action Center cannot be launched by any means. (Win+A nor push Notification)
In addition, Fn + Volume button (etc.) does not show current volume on the display. (Lenovo X1 YOGA Gen7th)

**Comment by Poopooracoocoo** [comment] 2023-09-22 11:10
Duplicate of #1998

**Closed by Poopooracoocoo** 2023-09-22 11:10 UTC
