### ISSUE TITLE
Touchpad shortcut (showing tasks screen) not working on W11 using W10 taskbar

### ISSUE THREAD

**Issue by kojinmalia** [valinet/ExplorerPatcher#2053] opened 2023-09-13 14:13 UTC
I'm on 22621.2234. When using W10 taskbar style, mentionned touchpad shortcut does NOT work.

**Comment by Poopooracoocoo** [comment] 2023-09-13 14:38
Duplicate of #1687

**Closed by Poopooracoocoo** 2023-09-13 14:38 UTC
