### ISSUE TITLE
Toast Notifications are displaying in the wrong area after a Windows Update.

### ISSUE THREAD

**Issue by Apocalypse612** [valinet/ExplorerPatcher#2089] opened 2023-09-18 14:22 UTC
I'm not quite sure when this happened exactly, but it did occur recently. I will include everything needed to help diagnose this problem. My taskbar location in the settings is "Bottom: (default)"

Further, my taskbar is 3 bars high.

![Wrong Location TOast](https://github.com/valinet/ExplorerPatcher/assets/6374154/41836662-8826-456c-b58a-8e6877e9b119)

My settings export:
https://filebin.net/jongadorwmy5soxa

Microsoft Windows
Version 22H2 (OS Build 22621.2283)
© Microsoft Corporation. All rights reserved.

ExplorerPatcher
Version 22621.1992.56.3

**Comment by Poopooracoocoo** [comment] 2023-09-18 16:19
Duplicate of #1788

**Closed by Poopooracoocoo** 2023-09-18 16:19 UTC
