### ISSUE TITLE
Crash when clicking Pen Menu in Windows 10 taskbar

### ISSUE THREAD

**Issue by smikutsky** [valinet/ExplorerPatcher#1938] opened 2023-08-25 17:03 UTC
If the pen menu is enabled, clicking on it in the Windows 10 taskbar causes Windows Explorer to crash (and not open the menu).

Currently on version 22621.1992.56.3 and Windows 11 Pro build 22621.ni_release.220506-1250

**Comment by pyrates999** [comment] 2023-08-26 11:22
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by smikutsky** [comment] 2023-08-28 00:04
The taskbar works as normal, it only crashes when the Pen Menu is clicked. Explorer then restarts and is fine.

Changing that setting did not affect the error.

For now, turning off the pen menu in Windows settings prevents me from clicking the 'crash' button.

**Comment by gtxaspec** [comment] 2023-09-05 04:57
Confirm this bug, clicking the pen menu crashes explorer.  The fix @pyrates999 mentioned did not work.  Windows 22621.2134

**Comment by pyrates999** [comment] 2023-09-05 07:26
What is the pen menu exactly?

**Comment by smikutsky** [comment] 2023-09-10 20:47
> What is the pen menu exactly?

It is a Windows toolbar that brings up tools that you might use when using a pen:

![Pen Menu](https://github.com/valinet/ExplorerPatcher/assets/23638583/4d6ace3e-5ec4-4877-a43e-b6c21820008a)


It can be toggled in settings:

![Pen Menu in Settings](https://github.com/valinet/ExplorerPatcher/assets/23638583/7abfd1eb-95dc-45a6-9caf-e864ed6c6006)

**Comment by pyrates999** [comment] 2023-09-11 05:16
Ah ok.  Thanks.

**Comment by Amrsatrio** [comment] 2023-09-25 04:14
Fixed in 1977d78.

**Closed by Amrsatrio** 2023-09-25 04:14 UTC
