### ISSUE TITLE
4 errors, the browser crashes every 10 sec. The animations do not match those of Windows 10. I can't pin or unpin Start apps. The search button is outdated.

### ISSUE THREAD

**Issue by Fabri247Gato10X** [valinet/ExplorerPatcher#2033] opened 2023-09-10 01:59 UTC
Hello, I use Windows 11 and i have 4 problems with ExplorerPatcher... The first problem is that the explorer crashes every 10 seconds, the second is that when switching to the W10 start menu in Windows 11 it does not have the same animation that is shown in Windows 10 , the third is that I cannot pin or unpin the start menu tiles using the "Pin to Start" button, and the final problem is that the search button is the same as the old versions of Windows 10, it needs to be updated to the new one, which is similar to that of Windows 11. I would be very grateful if you could fix the error.

**Comment by Poopooracoocoo** [comment] 2023-09-10 04:32
In the future could you please state your OS build and EP version?
1. There's numerous issues that this is a duplicate of. 
2. #1619
3. #1679
4. That's not an issue but a feature request. #260

**Closed by Poopooracoocoo** 2023-09-10 04:32 UTC
