### ISSUE TITLE
Configured icons don't show in system tray

### ISSUE THREAD

**Issue by tbcam88** [valinet/ExplorerPatcher#3465] opened 2024-07-10 12:37 UTC
As above - I can't get my configured icons to display in the system tray. They remain hidden even when set to appear (see attached).

Windows 11
EP v.22621.3527.65.5

![Untitled](https://github.com/valinet/ExplorerPatcher/assets/19891537/42d6c554-2495-4a3c-bdc7-b88cad0b3a1d)

**Comment by pyrates999** [comment] 2024-07-10 12:48
You can drag and drop the icon in the system tray to the popup menu that you don't want shown.

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this.

**Comment by tbcam88** [comment] 2024-07-10 12:56
> You can drag and drop the icon in the system tray to the popup menu that you don't want shown.
> 
> duplicate of: #1454
> 
> Please close this.

Excellent!

Many thanks.

**Comment by tbcam88** [comment] 2024-07-10 12:57
> You can drag and drop the icon in the system tray to the popup menu that you don't want shown.
> 
> duplicate of: #1454
> 
> Please close this.

Excellent!

Many thanks.

**Closed** 2024-07-10 12:56 UTC
