### ISSUE TITLE
Weather not displaying correctly when taskbar is on side

### ISSUE THREAD

**Issue by Johnczek** [valinet/ExplorerPatcher#3636] opened 2024-09-04 11:01 UTC
Hello,

I would like a defect a small defect thats happening when using Weather app widget when taskbar is placed on side (on the right side in my case).

Weather when displaying Icon and temperature alongside does not fit the width
![image](https://github.com/user-attachments/assets/906d6309-9287-4480-b3a9-c10c0c44da5d)

When I choose just icon or temperature, it fits well but in this case (which would be probably the most common scenario) it does not.

Is it possible to change the placement of the Icon and temperature under each other for instance?

**Comment by pyrates999** [comment] 2024-09-04 11:21
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2710

please close this.

**Closed** 2024-09-04 11:32 UTC
