### ISSUE TITLE
weather issue 

### ISSUE THREAD

**Issue by Bart0420** [valinet/ExplorerPatcher#3764] opened 2024-10-04 05:09 UTC
I tired to put up the weather on my taskbar and it just shows people widget. I had the weather widget working for the longest but now i can't make it work. if anyone knows how to fix it please let me know

**Comment by pyrates999** [comment] 2024-10-04 12:38
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2010

please close this.

and weather is not yet supported on the windows 10 (ExplorerPatcher) taskbar: https://github.com/valinet/ExplorerPatcher/issues/3546

**Closed** 2024-10-04 17:07 UTC

**Comment by Jazzzed** [comment] 2024-10-04 17:47
Try this 
https://github.com/valinet/ExplorerPatcher/issues/3674#issuecomment-2344725859
