### ISSUE TITLE
bruhh windows 11 24h2 rounded corners not working

### ISSUE THREAD

**Issue by HaloRage** [valinet/ExplorerPatcher#3949] opened 2024-11-20 07:28 UTC
bruhh windows 11 24h2 rounded corners not working. tried it updated ep still not working

**Comment by pyrates999** [comment] 2024-11-20 12:54
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3555

please close this.

**Comment by milesprower2293** [comment] 2024-11-20 17:46
duplicate of: #3555

**Closed by milesprower2293** 2024-11-20 17:46 UTC
