### ISSUE TITLE
Search menu position unchanged (bottom left), despite taskbar on top. 

### ISSUE THREAD

**Issue by austinjklim** [valinet/ExplorerPatcher#1214] opened 2023-03-30 13:36 UTC
![Screenshot 2023-03-30 212924](https://user-images.githubusercontent.com/16682922/228852538-9bd6a5b5-99c1-419b-8b73-b6cfd82deb5a.png)
![Screenshot 2023-03-30 213407](https://user-images.githubusercontent.com/16682922/228853151-53dfc849-8705-43a9-808f-9571dcec2b3a.png)

Search menu (by clicking on search icon or typing something after pressing the windows button, e.g., search calculator app quickly), is somehow stucked on the bottom left corner (or the original position), instead of the top left corner. 

Previous versions prior to this 22621.1413 did not have this issue, if I installed this windows update, it would go back to normal (being on the top left corner).

On my secondary system, it seems to work fine despite on 22621.1413, but both have different internal specs.

Tried Re-installing EP, but still to no avail.

**Comment by pyrates999** [comment] 2023-09-05 07:19
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1378

Please close this.

**Comment by Poopooracoocoo** [comment] 2023-09-25 16:17
Duplicate of #1378

**Closed as not planned by Poopooracoocoo** 2023-09-25 16:17 UTC
