### ISSUE TITLE
Non-Win32 apps do not show in Windows 10 Start menu on OS builds 22621.1344+

### ISSUE THREAD

**Issue by valinet** [valinet/ExplorerPatcher#1108] opened 2023-03-18 14:30 UTC
Something changed in the Windows 10 Start menu implementation that prevents it from displaying tiles and entries for non-Win32 (UWP) apps.

Discussed:
* https://github.com/valinet/ExplorerPatcher/discussions/1107
* https://www.elevenforum.com/t/new-version-of-explorerpatcher.1991/post-245366 (and it keeps being discussed for a few pages there)

**Comment by valinet** [comment] 2023-03-18 15:06
The fix may be to stop using old versions of `StartTileData.dll` and `AppResolver.dll`, and instead use the OS inbox versions. The problem with this is, as it the long standing case of pining tiles from File Explorer, that pining/unpining to the Windows 10 Start menu doesn't work properly:
* Right click app -> Pin to Start does not work. Alternative: drag tile from app list to the tile area
* Right click tile -> Unpin from Start does not even appear. The menu fails to determine correctly whether the tile is pinned. Alternative: none
* Same actions from File Explorer: not working.

**Comment by CthRio** [comment] 2023-03-18 16:55
> The fix may be to stop using old versions of `StartTileData.dll` and `AppResolver.dll`, and instead use the OS inbox versions. The problem with this is, as it the long standing case of pining tiles from File Explorer, that pining/unpining to the Windows 10 Start menu doesn't work properly:
> 
> * Right click app -> Pin to Start does not work. Alternative: drag tile from app list to the tile area
> * Right click tile -> Unpin from Start does not even appear. The menu fails to determine correctly whether the tile is pinned. Alternative: none
> * Same actions from File Explorer: not working.

I found that StarDock's Start11 static tile (experiment) is still valid, even if I adjust the start menu style, I monitor its API calls (I just took a brief look, but didn't go into detailed research on its assembly, and their software is commercial, which may involve some special disputes). It's also uses a Hook (start10_64.dll) and Function: CreateWindowInBand and GetPackagesByPackageFamily, but it works, and the tiles still work. Developers can try and see how they do it.
------------
P.S.: I have also found that receiving the recreated messages from the taskbar through a transparent window has an effect on preventing constant crashes, as the resource manager will send special messages to all top-level windows during the rebuild process. And there are two undisclosed functions that may be valid: HungWindowFromGhostWindow and GhostWindowFromHungWindow.

**Comment by valinet** [comment] 2023-03-18 17:06
@CthRio Sorry, I don't understand what you have said. As far as I know, Stardock uses their own reimplementation of a menu that looks like the Windows 10 one. Even if it supported live tiles, which as far as I know, doesn't, it still is a custom menu.
ExplorerPatcher just patches the old Windows 10 menu made by Microsoft which is still shipped with Windows to make it work. Right now, it has to be patched further to map to the correct backend when querying whather a tile is pinned to Start, when pinning/unpinning etc. and then it could theoretically work with the `StartTileData.dll` from the current build. In the past, it was using the DLL from build 22000.51 as a workaround, but using that today results in it not displaying UWP apps because Microsoft updated the backend, it seems.

**Comment by CthRio** [comment] 2023-03-18 17:11
I understand. I'm looking forward to the updated EP, come on!

**Comment by valinet** [comment] 2023-03-18 17:14
> I understand. I'm looking forward to the updated EP, come on!

Me too. I was hoping someone else already figured it out by now. Pfff....

**Comment by CthRio** [comment] 2023-03-18 17:35
To be honest, Microsoft's update is too sudden for users who use custom UI.  :(

> > I understand. I'm looking forward to the updated EP, come on!
> 
> Me too. I was hoping someone else already figured it out by now. Pfff....

**Comment by dicamarques14** [comment] 2023-04-11 10:24
Well i'm facing the same issue, I have Kitty ( a program to manage SSH connections) and I can't pin it to the start menu... I also have it already showing in the `shell:AppsFolder` like mentioned here: https://github.com/valinet/ExplorerPatcher/issues/1187#issuecomment-1498472024

**Comment by djcholapin** [comment] 2023-04-18 11:03
> The fix may be to stop using old versions of `StartTileData.dll` and `AppResolver.dll`, and instead use the OS inbox versions. The problem with this is, as it the long standing case of pining tiles from File Explorer, that pining/unpining to the Windows 10 Start menu doesn't work properly:
> 
> * Right click app -> Pin to Start does not work. Alternative: drag tile from app list to the tile area
> * Right click tile -> Unpin from Start does not even appear. The menu fails to determine correctly whether the tile is pinned. Alternative: none
> * Same actions from File Explorer: not working.

Is there any chance we could get that modification through here, or any available tutorial in what to modify in the files, in order to make it work that way, whilst a fix is found ? I think for most of us, one the start menu is setup, then you just forget about it and would only rarely occasionaly unpin apps.

I suppose - at least in my own case - I'd rather :
- Have full use of the start menu using all the apps, and if I need to unpin apps, just move them down for when the fix happens
as opposed to :
- Get a semi empty menu, having to type down every time I need to use an app, until the fix happens

I understand it can't be released in the official channel since it would actually be a flaw, vs incomplete for the other case, but for some of use (that are non tech saavy) who would like to use it that way in the meantime, is there any way we could implement that temporary solution by ourselves ?

**Comment by topia** [comment] 2023-04-18 11:33
Unfortunately, that is not an easy workaround. Please refer to his next reply: https://github.com/valinet/ExplorerPatcher/issues/1108#issuecomment-1474915811

The root problem is the incompatibility between (bundled but not enabled) Windows 10 start menu implementation and the latest version of those DLLs.

**Comment by luisl173** [comment] 2023-04-23 20:25
For some reason, dxgi.dll in `C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy` seems to be the problematic DLL. After renaming it, ALL the UWP apps come back but right-clicking on any app will crash the menu
![image](https://user-images.githubusercontent.com/108156867/233864161-fead433c-8162-47d3-9853-106ed2adf737.png)
The same file on `C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy` seems to break something on the WiFi flyout too, leaving it like this:
![image](https://user-images.githubusercontent.com/108156867/233863815-0a82f49c-7fdd-45b7-9129-6d019be2debb.png)
Renaming the file or deleting it instantly fixes the problem and there's no issues as everything works as expected
![image](https://user-images.githubusercontent.com/108156867/233863961-3864d2b0-d2d3-4a5f-921b-85570137c1c8.png)

**Comment by djcholapin** [comment] 2023-04-25 17:52
Indeed it does make everything come back, and you can drag and drop apps to the start menu all over again. However as you mentionned : 

- The menu crashes when you right clic
- Also, the live tile functionality is no longer working

Maybe there is something related, it was nice to see that they could still be displayed back, but let's see.

**Comment by luisl173** [comment] 2023-04-27 16:33
> Indeed it does make everything come back, and you can drag and drop apps to the start menu all over again. However as you mentionned :
> 
> * The menu crashes when you right clic
> * Also, the live tile functionality is no longer working
> 
> Maybe there is something related, it was nice to see that they could still be displayed back, but let's see.

Another issue that i forgot to mention on the dxgi.dll thing is that you can't reposition the start menu to the center of the screen and change its appearance to make it rounded

**Comment by arcyc** [comment] 2023-05-19 14:26
> The fix may be to stop using old versions of `StartTileData.dll` and `AppResolver.dll`, and instead use the OS inbox versions. The problem with this is, as it the long standing case of pining tiles from File Explorer, that pining/unpining to the Windows 10 Start menu doesn't work properly:
> 
> * Right click app -> Pin to Start does not work. Alternative: drag tile from app list to the tile area
> * Right click tile -> Unpin from Start does not even appear. The menu fails to determine correctly whether the tile is pinned. Alternative: none
> * Same actions from File Explorer: not working.

I think given the choice of having all apps in the start menu vs. ability to pin apps, showing all apps would be the higher order bit

**Comment by valinet** [comment] 2023-05-19 14:42
It’s kind of hard to write a changelog of “I fixed the UWP apps not appearing but it rather brakes pinning apps”. My priority is to fix it properly when I will have the time and energy to do it; in the mean time, I am more than happy should anyone choose to look on it and maybe fix it themselves - the code is all available in the repo. Furthermore, this also allows you to easily compile a version with any kind of “fix” you want, like what you suggested. I personally am against pushing half worked updates.

**Comment by Lyhtande** [comment] 2023-05-28 15:48
> The fix may be to stop using old versions of `StartTileData.dll` and `AppResolver.dll`, and instead use the OS inbox versions.

Hello valinet,
where would I get old version of  `StartTileData.dll` and `AppResolver.dll` from?

**Comment by pyrates999** [comment] 2023-05-29 06:01
Hi @Lyhtande, you wouldn't get those files.  You need to wait until this is fixed.

**Comment by Lyhtande** [comment] 2023-05-29 09:19
> Hi @Lyhtande, you wouldn't get those files. You need to wait until this is fixed.
Thanks for the info :) It is strange, because the UWP apps work on different Windows 11 installations (all with the latest Windows updates). Only on my main PC I made the mistake to switch to the Windows 11 start menu and then back to the Windows 10 start menu in the Explorer Patcher settings. Since then live tiles and UWP apps have disappeared on this Windows installation.

**Comment by KDBalashevich** [comment] 2023-06-02 17:11
Hello @Lyhtande If you wish, you can copy this files (StartTileData.dll and AppResolver.dll) from Windows\System32 to folder of ExplorerPatcher (C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy in my case) and rename them to AppResolverLegacy.dll and StartTileDataLegacy.dll there (I would suggest to backup original AppResolverLegacy.dll and StartTileDataLegacy.dll). This will fix UWP apps, but brake pinning.

**Comment by KDBalashevich** [comment] 2023-06-02 19:14
> I would also like to do this @KDBalashevich but in the ExplorerPatcher Folder ("C:\Program Files\ExplorerPatcher"), there is no AppResolverLegacy.dll and StartTileDataLegacy.dll for me to backup... meaning that the software is not using those... correct? But I still have the same blank Win32 icons issue... What am I doing wrong? ![image](https://user-images.githubusercontent.com/67206487/242952700-92880295-8be1-4ec2-b15c-603ef40154b4.png)

@yodaluca23 I, probably, was not completely clear. You do not need the folder of ExplorerPatcher itself, but the folder it uses for this dlls. I am not shure if it is always the same, but in my case it was C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy. If it is not, you can find it using windows search for file AppResolverLegacy.dll.

**Comment by yodaluca23** [comment] 2023-06-02 19:16
> > I would also like to do this @KDBalashevich but in the ExplorerPatcher Folder ("C:\Program Files\ExplorerPatcher"), there is no AppResolverLegacy.dll and StartTileDataLegacy.dll for me to backup... meaning that the software is not using those... correct? But I still have the same blank Win32 icons issue... What am I doing wrong? ![image](https://user-images.githubusercontent.com/67206487/242952700-92880295-8be1-4ec2-b15c-603ef40154b4.png)
> 
> 
> 
> @yodaluca23 I, probably, was not completely clear. You do not need the folder of ExplorerPatcher itself, but the folder it uses for this dlls. I am not shure if it is always the same, but in my case it was C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy. If it is not, you can find it using windows search for file AppResolverLegacy.dll.

Ohhh ok, I thought that was the file path I was supposed to get the new DLLs from. Then where should I get the fixed new DLLs?

**Comment by KDBalashevich** [comment] 2023-06-02 19:20
@yodaluca23 C:\Windows\System32. However they are not completely "fixed". While fixing this issue they brake pinning.

**Comment by yodaluca23** [comment] 2023-06-02 19:36
Ok, @KDBalashevich so I did that, rebuilt the icon cache, and restarted, but the icons are still missing...

**Comment by KDBalashevich** [comment] 2023-06-02 19:49
@yodaluca23 it seems that you have a different kind of issue then.

**Comment by svta-7125** [comment] 2023-06-04 12:32
For the time being, you can try to use the address toolbar and bring it before the pinned icons. It's still a very ugly solution.
![image](https://github.com/valinet/ExplorerPatcher/assets/117646988/ac0b81e8-1e8e-4e84-a69d-fb8172d608d8)
The taskbar is at an abnormal size due to the address bar.

**Comment by djcholapin** [comment] 2023-06-12 22:37
As a temporary workaround, just throwing this out there : Is it possible to implement a toggle in Explorer patcher / Start Menu, deactivated by default, that mentions "**Forced display of Non-Win32 App in Start menu**". With a small description below like "_Activating this option will remove your ability to pin/unpin an app from the Start Menu, and to display the context menu. Untoggled to recover those options, this will also remove any Non-Win32 App's tile from the start menu_"

When the toggle is on, OS inbox versions of StartTileData.dll and AppResolver.dll are used. When the toggle is off, old versions of StartTileData.dll and AppResolver.dll are still in use.

I know it's not an ideal scenario, but that will avoid people to start messing around replacing DLL's back and forth, and give us the option, without actually breaking any functionality, since the toggle would be deactivated by default.

Personnaly I would never have the need to unpin an app one my start menu is set, and the only times I would use the context menu, would be to run as an administrator or open the location's folder. Which I can easily do, on those rare occasions, using the start menu instead of the tiles. I feel it would be a good compromise, as still allowing to go back if we do need to, and it keeps existing functionalities as they are.

Just a though.

**Comment by FedericoD3** [comment] 2023-06-21 16:09
> ... Alternative: drag tile from app list to the tile area ...

> ... I also have it already showing in the shell:AppsFolder ...

Worked for me after some hoop-jumping:

- My problem was mainly with notepad and calculator, and those are not shown in my Windows10-styled Start Menu (without performing a search, and then the tiles area dissappear) and neither does _Accessories_ folder from which to drag them to the tile area.
- Enter the shell:AppsFolder trick: there werw Notepad and Calculator. Right-click > Pin to Start don't work from there either, but Right-click > Create shortcut (on the desktop) does. Then I moved the shortcuts to %AppData%\Microsoft\Windows\Start Menu\Programs and then the shortcud did appear en my Start Menu, BUT with their icons replaced with empty squares.
- I could succesfully pin and/or drag those shortcuts on the Start Menu to the tiles area despite the missing icons, move them to their customized groups and they started their apps as intended.
- More hoops regarding the icons: I could right-click > properties on both Notepad and Calculator icons in %AppData%\Microsoft\Windows\Start Menu\Programs and re-assign their icons. Calculator is in its usual place in C:\Windows\System32\calc.exe but the one in C:\Windows\System32\notepad.exe is the old-style icon (found the modern one in C:\Program Files\WindowsApps\Microsoft.WindowsNotepad_11.2304.26.0_x64__8wekyb3d8bbwe\Notepad\Notepad.exe after playing with C:\Program Files\WindowsApps permissions)

Now all is ~~workarounded~~ well.

Rant: Why does Microsoft make this so convoluted and remove useful features like star menu tiles and grouping? Linux desktop environments are no better.

**Comment by Vipin2003** [comment] 2023-06-21 16:24
For Pinning Apps : Just Drag&Drop the app to the Tile Area.

For Unpinning Items : R-Click on group name and click "Unpin Group from Start"

**Comment by djcholapin** [comment] 2023-07-03 09:54
I'm not very keen into messing up with win32 DLLs. A future windows update could mess the whole thing up again, and if that happens after months / years, you can loose sight of the DLL that has been removed.

**Comment by Amrsatrio** [comment] 2023-10-06 00:14
Fixed in the latest prerelease. Note that the first time an object in explorer is pinned, this may happen:
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/8bd959c2-f303-4993-b01a-76259f57500c)

In this case you can unpin it and pin again which will always work. I try to find a fix for this.

**Closed by Amrsatrio** 2023-10-06 00:14 UTC
Labels: bug, investigating

**Comment by Amrsatrio** [comment] 2023-10-06 09:38
I've pushed a new prerelease that has flawless Pin to Start/Unpin from Start in Explorer and Start Menu. Just the Search window left because EP isn't loaded there.

**Comment by valinet** [comment] 2023-10-06 15:07
What's the plan with loading in the Search app? As far as I remember, I was experimenting with this at some point, long ago, idk if there are commits on the matter, when I was manually adjusting its position because I did not know any better at the time. Basically, EP has to drop beside it in some form (maybe `dxgi.dll`, maybe `wincorlib.dll` or something else...) from `ep-setup`, and then just minimally inject and patch whatever is required.

As a heads up, make sure to never import common controls in EP other than dynamically, because as soon as that is linked at compile time, the DLL breaks and doesn't work in all these processes it injects - I know this from a long time ago when I was experiencing with `TaskDialogIndirect` in `GUI.c`. Code is still there now, not used anymore, only `TaskDialogIndirect` is obtained at runtime using `GetProcAddress`.

**Comment by Amrsatrio** [comment] 2023-10-06 15:15
Not really, right now my plans are bringing back the old control center and trying to get the Win10 start menu animation back. And then supporting Canary builds (check #general in our discord)

**Comment by valinet** [comment] 2023-10-06 15:20
Sounds lovely, good luck with all of that!
