### ISSUE TITLE
show/hide system tray icons not working

### ISSUE THREAD

**Issue by CryptoNarf** [valinet/ExplorerPatcher#1936] opened 2023-08-25 13:30 UTC
After installing ExplorerPatcher the option to turn off or on the display of system tray icons in the lower right corner stops working. Reinstalling a program does not fix anything. This makes it annoying for things like discord/telegram as you don't see the icon with message status anymore.

![Screenshot 2023-08-25 152710](https://github.com/valinet/ExplorerPatcher/assets/102581164/ac61775f-a5cf-4511-bb04-965375efc51b)
![Screenshot 2023-08-25 152745](https://github.com/valinet/ExplorerPatcher/assets/102581164/662a6d76-76fd-4103-bb6c-7531c27e3fb3)

**Comment by pyrates999** [comment] 2023-08-25 14:38
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.

**Comment by CryptoNarf** [comment] 2023-08-25 21:22
I noticed that one, but I thought that was about the notifications popping up by the little windows box? I'm talking more about the icons not showing in the system tray. Some software programs don't even appear in the list (like telegram) to turn on/off.

**Comment by CryptoNarf** [comment] 2023-08-25 21:24
closing

**Closed** 2023-08-25 21:24 UTC
