### ISSUE TITLE
explorerpacher not work

### ISSUE THREAD

**Issue by pivov** [valinet/ExplorerPatcher#3752] opened 2024-09-29 15:25 UTC
after latest windows update explorerPacher is ton working. Whole start menu is not opening and also taskbar not responding.
Windows update:
2024-09 Cumulative update preview for Windows 11 Version 23H2 for x64-based systems (KB5043145)

**Comment by milesprower2293** [comment] 2024-09-29 16:58
Open powershell as an administrator and put this

Add-MpPreference -ExclusionPath "C:\Program Files\ExplorerPatcher"
Add-MpPreference -ExclusionPath "$env:APPDATA\ExplorerPatcher"
Add-MpPreference -ExclusionPath "C:\Windows\dxgi.dll"
Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
Add-MpPreference -ExclusionPath "C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy"

and reinstall EP

**Comment by pivov** [comment] 2024-09-29 17:59
![efect_1](https://github.com/user-attachments/assets/56be014c-bbfe-4727-8bd7-f84cb9c1c363)
unfortunately is not working, in enclosed file you can find screenshot of error massage

**Comment by pivov** [comment] 2024-09-29 18:32
I added manually exclusions from windows viruses protection:
![exclusions](https://github.com/user-attachments/assets/b9d911fb-4cb8-44a0-b545-5221a1ac3f7c)

**Comment by pivov** [comment] 2024-09-29 18:32
still not work.

**Comment by Amrsatrio** [comment] 2024-09-29 18:39
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3667

**Comment by Amrsatrio** [comment] 2024-09-29 18:40
Unfortunately 10 start menu does not work on your system. Switch back to 11 start menu or rollback and freeze your updates.

**Closed by Amrsatrio** 2024-09-29 18:39 UTC

**Comment by pivov** [comment] 2024-09-29 18:43
Is there a fix planned for this?

**Comment by Amrsatrio** [comment] 2024-09-29 18:44
Yes. I tried messing around myself to fix this and got it working again.

**Comment by pivov** [comment] 2024-09-29 18:51
great, thanx :)

**Comment by pyrates999** [comment] 2024-09-29 23:36
> ![efect_1](https://private-user-images.githubusercontent.com/183296696/371879682-56be014c-bbfe-4727-8bd7-f84cb9c1c363.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NTMyMDksIm5iZiI6MTcyNzY1MjkwOSwicGF0aCI6Ii8xODMyOTY2OTYvMzcxODc5NjgyLTU2YmUwMTRjLWJiZmUtNDcyNy04YmQ3LWY4NGNiOWMxYzM2My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQyMzM1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjJkNjA4YjNjOTE1N2YwNDdjZDYxNzJmMjZjMWI1ZGJiZjA1Y2ZkMjU2MjliMjkyZWRlNGZiN2RmNzc3NDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lM1YztRXz6-jZn77iz4bz5W02BzOmrO9ShM8htf2n3A) unfortunately is not working, in enclosed file you can find screenshot of error massage

The powershell commands must run with elevated privileges.

**Comment by pivov** [comment] 2024-09-30 08:04
thx, it is done as you suggested but still don't work.

**Comment by Amrsatrio** [comment] 2024-09-30 08:19
@pyrates999 No need to troubleshoot further. The issue is in my code.

**Comment by pivov** [comment] 2024-09-30 08:32
yes, no changes. not work.
