### ISSUE TITLE
"This PC" keeps randomly opening

### ISSUE THREAD

**Issue by THGhost** [valinet/ExplorerPatcher#1817] opened 2023-08-10 13:41 UTC
On the latest version, 22621.1992.56.1 using Windows 11 22H2 22621.2283, "This PC" keeps popping up at seemingly random intervals. I'll be right in the middle of something and then boom, there it is. For no reason whatsoever. Besides this and the ongoing [Task View Button and Alt+Tab issues](https://github.com/valinet/ExplorerPatcher/issues/1809) and the occasional crash/Explorer restart, every else is working fine for me.

Sorry if this is a duplicate issue. I didn't see anyone else mention it. If this is a duplicate issue then please delete this and link me to the appropriate page. Thanks.

**Comment by pyrates999** [comment] 2023-08-10 13:52
Please show a screen shot of what you mean.

**Comment by THGhost** [comment] 2023-08-10 13:52
> Please show a screen shot of what you mean.

Really? It's pretty self-explanatory. The "This PC" windows opens by itself. That's it.

**Comment by j-ribs** [comment] 2023-08-10 19:57
I never really pieced it together that this would be causing it. But yeah this same thing happens to me too.

**Comment by pyrates999** [comment] 2023-08-11 10:44
The "This PC" icon on the desktop opens itself like you had double clicked on it?

**Comment by j-ribs** [comment] 2023-08-13 06:24
Sometimes its not specificaly the "This PC" window, but its some explorer window just kind of forces itself to become selected and brings it to the front of everything.
If i already have an explorer window open, it will just do that one.

I dont have much more to go off of, ill pay attention more the next time it happens.

**Comment by pyrates999** [comment] 2023-08-13 22:09
Try uninstalling explorer patcher, do a reboot, and see if it is still happening.

**Comment by THGhost** [comment] 2023-08-14 01:08
For me it is just the "This PC" window, with all of my drives listed that pops up in front of everything, with absolutely no warning.

[This post](https://github.com/valinet/ExplorerPatcher/issues/1792#issuecomment-1673072835) appears to have fixed it for me though. I shall report back if it ever happens again.

**Comment by THGhost** [comment] 2023-08-20 14:29
> For me it is just the "This PC" window, with all of my drives listed that pops up in front of everything, with absolutely no warning.
> 
> [This post](https://github.com/valinet/ExplorerPatcher/issues/1792#issuecomment-1673072835) appears to have fixed it for me though. I shall report back if it ever happens again.

Since following the steps in this post, "This PC" has not reared its ugly head once.

**Comment by THGhost** [comment] 2023-08-31 14:20
The most recent update has unfortunately made this issue return. I have repeated the steps in the post I linked to above. Hopefully that will fix it again. Please look into fixing this permanently.

**Comment by pyrates999** [comment] 2023-09-01 07:42
Did you try uninstalling EP to see if it still happens?

**Comment by THGhost** [comment] 2023-09-04 03:07
That does appear to have fixed it this time. Strange.

**Comment by kingskyline** [comment] 2023-09-04 12:35
Uninstalling EP fixes the issue for me also , reinstalling works again for a few hours then the dreaded "This PC" window opens again using "ep_setup.exe" again "as a Repair installer kind of" makes the issue go away for another few hours  , repeat steps to fix again , until this is fixed , keep "ep_setup.exe" on your desktop , soon as it happens , repair with .exe will work as a temp fix

**Comment by kingskyline** [comment] 2023-09-04 13:31
ill give that a try , saying that ive not seen it pop up since the last time i clicked restart on the symbols thing

**Comment by THGhost** [comment] 2023-09-04 13:46
It just came back multiple times. Reinstalling yet again.

**Comment by pyrates999** [comment] 2023-09-05 07:06
Just realized you haven't posted some needed info.

Please post windows version and build.  You can find this by running winver.
Please confirm that explorer patcher version is 22621.1992.56.3.

Please include what settings you changed in explorer patcher properties application.

**Comment by THGhost** [comment] 2023-09-06 13:07
> Just realized you haven't posted some needed info.
> 
> Please post windows version and build. You can find this by running winver. Please confirm that explorer patcher version is 22621.1992.56.3.
> 
> Please include what settings you changed in explorer patcher properties application.

![Winver](https://github.com/valinet/ExplorerPatcher/assets/32550606/86444cd8-dd52-4648-88ce-03f91e9eb45b)

![1](https://github.com/valinet/ExplorerPatcher/assets/32550606/804386b4-6eaf-4ad1-bbf1-666b1b15fecd)
![2](https://github.com/valinet/ExplorerPatcher/assets/32550606/e1582d3b-d03d-484c-8b01-40ec9952e286)
![3](https://github.com/valinet/ExplorerPatcher/assets/32550606/6efd71a2-1ab5-4904-9c02-60a43c7961eb)
![4](https://github.com/valinet/ExplorerPatcher/assets/32550606/14ad9ef8-4b1d-4c77-8ccd-b5544edc128e)
![5](https://github.com/valinet/ExplorerPatcher/assets/32550606/d2924048-a686-4911-887a-23f6fcbeca04)
![6](https://github.com/valinet/ExplorerPatcher/assets/32550606/8ff84ea7-2e59-4bc5-9bac-9774e2456f40)
![7](https://github.com/valinet/ExplorerPatcher/assets/32550606/383b1e75-c237-4148-bd26-50bc73ff3533)
![8](https://github.com/valinet/ExplorerPatcher/assets/32550606/f413f43e-8bef-4c99-a1b8-41c1c5ffa11d)
![9](https://github.com/valinet/ExplorerPatcher/assets/32550606/c4ca2757-57e9-41e0-b4f3-c7a38ec5acf4)
![10](https://github.com/valinet/ExplorerPatcher/assets/32550606/3a4029a8-5334-415a-a1be-19997885af80)

**Comment by pyrates999** [comment] 2023-09-07 10:46
I would untick the **disable the windows 11 context menu**.

**Comment by THGhost** [comment] 2023-09-09 17:59
> I would untick the **disable the windows 11 context menu**.

At first I thought, "Must I? I have my Windows 10 context menu just the way I like it." But after a couple of days using the Windows 11 context menu, it's not so bad. The "Show more options" option also brings up my Windows 10 context menu, so all the programs I have there are just 1 extra click away. Haven't encountered "This PC" randomly appearing once so far.

**Comment by Poopooracoocoo** [comment] 2023-09-23 03:55
Should be resolved now. Leave a comment or open a new issue if you're still seeing issues. Make sure to include your Windows OS Build and ExplorerPatcher version.

**Comment by THGhost** [comment] 2023-10-06 14:19
This has come back with a vengeance now. "This PC" pops up every single time I use Alt + Tab repeatedly to compare images/video as part of my workflow. Currently using version 22621.2361.58.1 which I know isn't the latest version, but it simply refused to update and I can't figure out how to uninstall it. Is there no possible way to fix this once and for all?

**Comment by pyrates999** [comment] 2023-10-08 11:34
Please post windows version and build.  You can find this by running winver.
The explorer patcher version you said you're running is 22621.2361.58.1.  Please update to 22621.2361.58.3.

Please include what settings you changed in explorer patcher properties application.

**Comment by THGhost** [comment] 2023-10-08 14:27
Like I said, I can't update to the latest version because it won't let me. My OS build is in my first post. No settings have been changed since the screenshots I posted.

**Comment by pyrates999** [comment] 2023-10-09 04:41
> Like I said, I can't update to the latest version because it won't let me. My OS build is in my first post. No settings have been changed since the screenshots I posted.

There was a September update released.  I suggest you install that: https://support.microsoft.com/en-gb/topic/september-12-2023-kb5030219-os-build-22621-2283-8b9ba74f-fdde-4c75-b049-77cf214f4a66

If you're not able to because this is a work pc and they haven't authorized the update yet, I suggest you don't install EP since it requires administrative privileges.

**Comment by THGhost** [comment] 2023-10-09 23:38
I have finally managed to get it to update after a reboot. I shall report back if "This PC" pops up again.

**Comment by THGhost** [comment] 2023-10-15 22:06
It's still happening. Just not as much.

**Comment by pyrates999** [comment] 2023-10-16 02:03
See this article: https://www.howtogeek.com/884624/youre-not-alone-windows-11-is-randomly-opening-file-explorer/

**Comment by THGhost** [comment] 2023-10-16 03:42
> See this article: https://www.howtogeek.com/884624/youre-not-alone-windows-11-is-randomly-opening-file-explorer/

Thanks for the link. Glad I'm not the only one! So it's not caused by ExplorerPatcher then? I only started getting it after I started using it. I guess me starting to use it and the bug surfacing just happened to coincide?

**Comment by pyrates999** [comment] 2023-10-16 06:13
yeah, just a coincidence I think.

**Comment by Amrsatrio** [comment] 2023-11-16 20:32
Is this fixed with the latest prerelease? I've disabled the tabs feature flag and it should restore Explorer behavior to pre-22H2 when a non-Windows 11 control interface is used.

**Comment by Amrsatrio** [comment] 2023-11-20 20:43
Seems like this is fixed. Until build 23570.

**Closed by Amrsatrio** 2023-11-20 20:43 UTC

**Comment by THGhost** [comment] 2023-11-20 20:46
> Is this fixed with the latest prerelease? I've disabled the tabs feature flag and it should restore Explorer behavior to pre-22H2 when a non-Windows 11 control interface is used.

I haven't encountered it happening for a while, so fingers crossed that it 🤞

**Comment by vmid** [comment] 2024-09-21 04:22
After reading the above discussion, I'm confused whether this is just a Win 11 bug or if it relates to Explorer Patcher.
I recently started experiencing this bug on my fully updated system. 
Windows version: 23H2 (OS Build 22631.4169)
EP version: 22621.3880.66.6

New window of File Explorer "This PC" opens (see reproduction scenario below).
The howtogeek link above says that it's simply an issue of File Explorer stealing focus, and that this bug does not open new window. In my case, new window of "This PC" definitely opens. 

Once it started happening, I'm able to reproduce this bug with the following scenario:
Preconditions: 
a) only one monitor is connected (not sure if important).
b) doesn't matter whether there's already an open File Explorer window or not.
c) Chrome with a Youtube video is opened.

Steps:
1. Expand a Youtube video to fullscreen (I click the fullscreen icon in the video bar with my mouse).
2. Wait ~15 sec.
3. Either exit fullscreen (click the same icon or press Esc), or press Alt+Tab.

Result: 
new "This PC" window opens. 
Each time the steps above are repeated, yet another new "This PC" window opens. 
Same result with a Prime Video fullscreen video.
Not able to reproduce with Firefox using these steps, only with Chrome. Chrome was updated to the latest version (129.0.6668.59 (Official Build) (64-bit)).

Right now, before any reboots, the steps above lead to a new FE window opening every time without fail (just need to wait ~15 sec after the previous window appeared).

Sometimes a new "This PC" window opens in other scenarios, too (e.g. once it opened while I was typing this comment, without any fullscreen shenanigans or pressing Alt or Tab). I haven't looked deeply into what other scenarios could be reproduced.

**Comment by pyrates999** [comment] 2024-09-21 10:59
This is a long standing bug with windows 11.  See this long forum post about it: https://answers.microsoft.com/en-us/windows/forum/all/windows-11-most-recently-opened-explorer-window/26e097bd-1eba-4462-99bd-61597b5195a0

**Comment by jewellui** [comment] 2024-11-30 18:30
I'm having the same issue, I had Windows 11 for about two weeks without this issue, then installed EP and this started maybe two days after. 

Could be a coincidence, I see lots of people on Windows 11 having this issue. Seems something must trigger it to start though.

**Comment by THGhost** [comment] 2024-11-30 18:40
I recently did a clean install of W11 and now I can't even get EP to install anymore 😂
