### ISSUE TITLE
Pin to Start does not work on Windows 11 x64 version 23H2

### ISSUE THREAD

**Issue by Edowndotdown** [valinet/ExplorerPatcher#4057] opened 2024-12-19 16:54 UTC
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [X] I do not have "register as shell extension" enabled
- [X] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

Latest Version

### Repro Windows Versions

Windows 11 23H2 22631.4602

### 3rd party tweak software installed

Wallpaper Engine

### Describe the bug

Right-click on an application or shortcut in start menu.

Select "Pin to Start" from the context menu.

### Expected outcome

The selected application or shortcut should appear as a tile in the Start Menu.

### Actual outcome

The application or shortcut does not appear in the Start Menu.

### Additional info

The issue persists after restarting.

Additional Question: 
When can we expect the Windows 7 Start Menu and Taskbar?

**Comment by mustafatoktas** [comment] 2024-12-19 17:53
You wrote in great detail. Congratulations. I am also experiencing the same problem.

**Comment by Amrsatrio** [comment] 2024-12-19 19:20
Unfortunately a duplicate of https://github.com/valinet/ExplorerPatcher/issues/3984.

@mustafatoktas Yeah, I'm enforcing this style to make sure people can't just rant in the issues section. And so that they have to provide more details instead of wasting my time waiting for important info.

**Closed by Amrsatrio** 2024-12-19 19:20 UTC
