### ISSUE TITLE
most recent windows update broke all start menu related things

### ISSUE THREAD

**Issue by putnamto** [valinet/ExplorerPatcher#1364] opened 2023-04-23 18:07 UTC
after the recent windows 11 update my start menu no longer comes up, hitting the start button on keyboard causes explorer to crash, same as clicking on the start logo.

i unninstalled the update and now i have stock start menu with none of the added features of EP, reinstalling EP does nothing, and also right clicking my taskbar crashes explorer.

**Comment by Mohsyn** [comment] 2023-04-23 19:53
+1

**Comment by pyrates999** [comment] 2023-04-23 22:16
Check that the symbols have been downloaded via notifications and then restart windows explorer using the task manager.

**Comment by putnamto** [comment] 2023-04-24 01:24
nothing in windows notifications, and right clicking the taskbar causes explorer to crash.

**Comment by pyrates999** [comment] 2023-04-24 04:57
if you got a recent release, it has code that when windows explorer crashes 3 times, it disables the integration that explorer patcher does.  Then uninstall it and download and install the latest release.

**Comment by Mohsyn** [comment] 2023-04-24 05:05
> if you got a recent release, it has code that when windows explorer crashes 3 times, it disables the integration that explorer patcher does. Then uninstall it and download and install the latest release.

Explorer is not crashing in my case (or maybe if it is crashing then it is certainly not visible)
patcher works otherwise because it changes taskbar orientation etc. only start key is broken.
install uninstall does not help. only way i could make it work was uninstalling the windows update then restore settings.

**Comment by miklik72** [comment] 2023-04-24 05:54
+1
I have the same problem, Click on Start menu icon or push Win key are not working and restarting EP regularly.
Also lates patch 55.2.

**Comment by jangrewe** [comment] 2023-08-01 14:04
I finally got the 22H2 yesterday (Ryzen or some other hardware previously blocked it), and after finishing the upgrade, i now have the same problem and need to use Win+Space to launch stuff.

**Comment by pyrates999** [comment] 2023-08-01 21:35
> I finally got the 22H2 yesterday (Ryzen or some other hardware previously blocked it), and after finishing the upgrade, i now have the same problem and need to use Win+Space to launch stuff.

Please post windows version and build.
Please post explorer patcher version.

**Comment by jangrewe** [comment] 2023-08-01 21:37
Sorry, i think this was unrelated to Explorer Patcher. 

I googled some more, and it seems to be that the Windows Search indexing is the cause. Did some permission fixes on `C:\ProgramData\Microsoft\Search` and restarting the service, then it keyboard input was possible again.

**Comment by pyrates999** [comment] 2023-08-01 21:42
Please close this then.

**Comment by jangrewe** [comment] 2023-08-02 07:07
I don't think i can, that would be up to @putnamto .

**Comment by putnamto** [comment] 2023-08-02 10:16
Words

**Closed** 2023-08-02 10:16 UTC
