### ISSUE TITLE
Apps pinned to start: Some Icons are just empty boxes.

### ISSUE THREAD

**Issue by mgradmann** [valinet/ExplorerPatcher#1332] opened 2023-04-15 16:45 UTC
Some of the apps pinned to my start menu (Win10 start menu via EP) are represented by mere grey tiles instead of the appropriate icon, see screenshot. Seem to be always the same apps. And it's the same on different machines with Windows 11 Home edition.
Sometimes the icons show up on Startup, but vanish soon afterwards. I know approximately where they are in the grid, but it's still disorientating,

The seven apps in the screenshot are (from upper left):
Windows Notepad, Windows Calculator, MS Paint, Spotify, MyAsus, Asus Armory Crate, Dolby Access.

![Start_Menu_Missing_Icons](https://user-images.githubusercontent.com/58299124/232238523-a92e3109-69ea-467f-b8a4-8ce81c5494a2.png)

**Comment by ChobitsChii** [comment] 2023-04-16 00:01
I have the same problem on Windows 11 Pro 22H2 (22621.1555). And after deleting, i can not pin it again to start menu.

**Comment by Vipin2003** [comment] 2023-04-16 09:21
It's a Win10 Star Menu bug that it doesn't show Win32 UWP Apps....it is known bug and dev's are working to fix this.

Check #1108. Please Close this issue as duplicate of #1187

**Comment by mgradmann** [comment] 2023-04-16 11:39
> 

As far as I can tell, the tickets you quoted refer to apps not showing up in the start menu at all. This here is a different problem: The apps are in the start menu, but are not labeled with their respective icons.

**Comment by mgradmann** [comment] 2023-04-16 11:59
> I have the same problem on Windows 11 Pro 22H2 (22621.1555). And after deleting, i can not pin it again to start menu.

Well, I can pin them, bus some don't show an icon. However, I also noticed that when I search an app in the start menu by typing its name, I can choose the option to pin it, but the tile doesn't appear. When I search it manually from the app list in the start menu, it works.
The two processes open different context menus. Searching an app by typing opens a menu in my system language (Italian, pinning doesn't work). Manually browsing the list opens an English one (pinning works).

**Comment by Vipin2003** [comment] 2023-04-16 12:46
I understand ur problem...the apps which are pre-installed or manually installed by you like notepad,calc,spotify,etc all are UWP apps. If you haven't installed apps from ms store, doesn't mean that they are not UWP apps. Apps installed with App Installer are all UWP Apps and there is a issue with UWP apps currently.

**Comment by Vipin2003** [comment] 2023-04-16 12:48
A way to manually pin apps:

- Press WIN + R and run shell:AppsFolder, it will open a Applications folder in explorer.

- Open folder C:\Users\<your name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs.

- Just drag a app to Programs folder.

It will create a shortcut in Programs folder, and the app(shortcut) is shown at app list now.
The icon is not shown properly, you need to manually change the shortcut icon.
Pin to start menu.
To change shortcut icon, you need locate the app's real location. Task Manager will help.

- Run the app -> find it in task manager -> right-click and select open file location

A problem is you will see two same apps in win11 style app list.

**Closed** 2023-04-16 14:10 UTC
