### ISSUE TITLE
TaskBar Weather Icon Clipping on Screen's Right Side

### ISSUE THREAD

**Issue by Fiu77** [valinet/ExplorerPatcher#3093] opened 2024-04-05 13:02 UTC
My TaskBar is located on the right side of the screen. The weather icon and text does not fit on it, as seen in the pictures where the text is hanging off the screen. Is there any way I can fix or customize its appearance?

Single line option:
![image](https://github.com/valinet/ExplorerPatcher/assets/25255381/d65ccf01-11a1-403c-8c62-1ebbbc982456)

Two line option:
![image](https://github.com/valinet/ExplorerPatcher/assets/25255381/4a952552-0a9c-4f89-8141-a586082f18f9)

**Comment by pyrates999** [comment] 2024-04-06 06:31
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2710

please close this.

**Closed** 2024-04-07 14:36 UTC
