### ISSUE TITLE
[ExplorerPatcher 22621.3296.64.1] Explorer remains on new XAML version despite changing Control Interface settings to "classic Address Bar"

### ISSUE THREAD

**Issue by Kenst1092** [valinet/ExplorerPatcher#3039] opened 2024-03-22 09:57 UTC
Title says it all. See screenshot for my EP settings
![image](https://github.com/valinet/ExplorerPatcher/assets/20787137/f5e73a50-eb88-4b1c-8900-5c16d2ef0d0f)

I do not remember my previous Windows 11 build, but Explorer reverted to the classic address bar version after setting EP Control Interface setting to "Windows 11 Command Bar (classic Address Bar)". Now, in build 22621.3296, it remains stuck on the new XAML-ified version of the Explorer interface, where the command bar cannot retain Mica material.

It's more of a visual nuisance than it is a dealbreaking issue. Any assistance would be appreciated.

**Comment by pyrates999** [comment] 2024-03-22 12:35
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2701

Please close this.

**Closed** 2024-03-22 12:43 UTC
