### ISSUE TITLE
How do I disable the action center in windows 10 taskbar?

### ISSUE THREAD

**Issue by GuestTheGamer** [valinet/ExplorerPatcher#3123] opened 2024-04-11 02:33 UTC
I'm trying to make my windows 11 laptop look like Windows 8. Can anyone help me?

My Windows version is 22631.3447
![Screenshot 2024-04-11 103304](https://github.com/valinet/ExplorerPatcher/assets/142704139/f9e50081-694d-4c21-b9b9-f2261cfab7d5)

**Comment by SandTechStuff** [comment] 2024-04-11 02:37
Under taskbar in the ExplorerPatcher properties there should be an option titled something along the lines of "turn system icons on or off". It should open a control panel applet and you can disable the action center.

**Comment by pyrates999** [comment] 2024-04-11 13:42
Issues are for bugs only.  Please post this in discussions.

**Comment by yanwcyanwc** [comment] 2024-04-12 03:01
I think it may be a bug? As I can't seem to find that option as suggested by SandTechStuff above. I am new, but the reason I join is for this exact same reason. 

![Screenshot 2024-04-12 125638](https://github.com/valinet/ExplorerPatcher/assets/166779776/729fc4b9-0983-462c-b24d-8a2d49e291ee)

**Comment by SandTechStuff** [comment] 2024-04-12 05:43
It’s called “customize system icons in the notification area” in taskbar properties. It should be there. 
![image](https://github.com/valinet/ExplorerPatcher/assets/164842290/2248214e-79a7-405a-96c3-1b7f22eb891c)
(Random ExplorerPatxher image from a search)

**Comment by Amrsatrio** [comment] 2024-04-12 13:41
Closing since this is not a bug. If Turn system icons on or off to hide the action center button doesn't work, feel free to reopen.

**Closed by Amrsatrio** 2024-04-12 13:41 UTC

**Comment by marcofs** [comment] 2024-04-18 19:24
The icon reappears when the explorer restarts
