### ISSUE TITLE
Damn you Microsoft

### ISSUE THREAD

**Issue by impeeza** [valinet/ExplorerPatcher#3561] opened 2024-08-14 05:36 UTC
Sinces last week ExplorerPatcher is clasified as a threat not just a tool

![image](https://github.com/user-attachments/assets/27476998-ccf1-44e9-9169-624d9baad2f5)

**Comment by RickyZhu-420** [comment] 2024-08-14 08:37
Now downloads via edge will be disrupted, and ep_setup.exe will be directly removed without Allow on device option.
VirusTotal here also gives negative news.
![image](https://github.com/user-attachments/assets/eb6fddc2-f9f4-4196-b886-3fe2691bf673)

**Comment by pyrates999** [comment] 2024-08-14 11:29
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

Set windows defender to exclude the following:
1. C:\Program Files\ExplorerPatcher
2. %APPDATA%\ExplorerPatcher
3. Directory that you downloaded ep_setup.exe to

Future updates to EP won't be flagged then.

**Closed** 2024-08-14 20:32 UTC

**Comment by impeeza** [comment] 2024-08-14 20:52
%ProgramFiles%\ExplorerPatcher
