### ISSUE TITLE
Rightclicking on taskbar makes File explorer restart

### ISSUE THREAD

**Issue by isaacboentoro** [valinet/ExplorerPatcher#1874] opened 2023-08-20 10:01 UTC
Windows 11 22H2 Build 22621.2134
Latest EP Build
Symbols downloaded (Win+X returns proper functionality)
Issue only occurs in Win11 taskbar mode for some reason
Would be great if anyone could suggest me a fix for this (tried uninstalling, restarting, deleting regkeys, restarting, reinstalling ep then waiting for symbols to download and restarting again) or suggest alternative that brings back win10 start menu + context menu. That's all I need

**Comment by pyrates999** [comment] 2023-08-20 11:30
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Closed** 2023-08-21 04:57 UTC
