### ISSUE TITLE
Hi since the last update of W11 (i suppose 3 weeks ago) , i have problems with EP. taskbar is not only dark, app's icons are visible but the dropdown menu  of EP (for choosing options) is entirely empty, just one remains: the shorcut for windows's page of  taskbar's option...) so impossible to change options. Also, impossible ton include folder in the taskbar... and icons on the right (hour, sound... ) appears only if pointed by the mouse i reinstall a lot of time, with differents way, no succes. i used i thing the latest version of EP: ...64.2. So Thanks very much from France for your help.

### ISSUE THREAD

**Issue by Gillesdu38** [valinet/ExplorerPatcher#3062] opened 2024-03-28 21:40 UTC
Hi since the last update of W11 (i suppose 3 weeks ago) , i have problems with EP. taskbar is not only dark, app's icons are visible but the dropdown menu  of EP (for choosing options) is entirely empty, just one remains: the shorcut for windows's page of  taskbar's option...) so impossible to change options. Also, impossible ton include folder in the taskbar... and icons on the right (hour, sound... ) appears only if pointed by the mouse i reinstall a lot of time, with differents way, no succes. i used i thing the latest version of EP: ...64.2. So Thanks very much from France for your help.

![EP](https://github.com/valinet/ExplorerPatcher/assets/143354621/26f4722f-1d59-4d5d-993f-b3fbff688a36)

_Originally posted by @Gillesdu38 in https://github.com/valinet/ExplorerPatcher/discussions/622#discussioncomment-8933182_

**Comment by Amrsatrio** [comment] 2024-03-28 23:32
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2560

**Closed by Amrsatrio** 2024-03-28 23:32 UTC
