### ISSUE TITLE
Explorer patcher doesn't change to windows 10 style

### ISSUE THREAD

**Issue by you-wata** [valinet/ExplorerPatcher#3808] opened 2024-10-16 10:02 UTC
I'm using Windows 11 24H2, but when I start it, it stays on the Windows 11 taskbar and doesn't change to Windows 10 style. It will also be detected by Windows Defender. What should I do? I'm doing the exclusion settings.(Sorry in Japanese)

<img width="523" alt="スクリーンショット 2024-10-16 190206" src="https://github.com/user-attachments/assets/cba9d2b8-010b-4d7d-a53f-5a917a139d54">

**Comment by Amrsatrio** [comment] 2024-10-16 10:12
> it stays on the Windows 11 taskbar and doesn't change to Windows 10 style
Yes, that is the expected behavior on 24H2. We will never make it default to EP's Windows 10 taskbar. Additionally, the Windows 10 taskbar has been removed in 24H2.

> It will also be detected by Windows Defender.
Have you added the exclusions? Have you run the script in https://github.com/valinet/ExplorerPatcher/releases in PowerShell as Admin?

**Comment by you-wata** [comment] 2024-10-16 13:35
I set the exclusion, but it is still detected by Windows Defender. I looked up how to exclude it in detail, but I still don't know how to do it. Sorry, but could you please explain it in detail?

**Comment by you-wata** [comment] 2024-10-16 13:37
Also, what does 66.6 mean? Please let me know.

**Comment by Amrsatrio** [comment] 2024-10-16 14:29
66.6 is the latest version of ExplorerPatcher currently, found here: https://github.com/valinet/ExplorerPatcher/releases

Please check the Exclusions page in the Windows security page to ensure that you have added the exclusions properly. Open Windows Security app (Windows セキュリティ) > Virus & threat protection (ウイルスと脅威の防止) > Under Virus & threat protection settings (ウイルスと脅威の防止の設定) > Scroll to the bottom > Add or remove exclusions (除外の追加または削除).

If you have these, then you can ignore further detections.

![image](https://github.com/user-attachments/assets/226d6a1f-6cc0-4c2d-9798-8f35312a4cf9)

**Comment by pyrates999** [comment] 2024-10-16 22:20
Even after I had added the directory, `C:\Program Files\ExplorerPatcher\`, I still had to specifically exclude the file `C:\Program Files\ExplorerPatcher\ep_weather_host_stub.dll`.  Because windows defender gave me a warning and removed it still.  So after adding that exclusion, then I reinstalled EP.

**Comment by Amrsatrio** [comment] 2024-10-19 05:50
Closing due to no follow-up response.

**Closed by Amrsatrio** 2024-10-19 05:50 UTC
