### ISSUE TITLE
Windows 11 Build 22621.2134 Crashes with latest EP update

### ISSUE THREAD

**Issue by m7d2** [valinet/ExplorerPatcher#1842] opened 2023-08-13 01:34 UTC
As the title says

**Comment by Chrisnetika** [comment] 2023-08-13 04:32
Same.. it is really bad the crashes with latest update
Getting it alot when i open folders with media ie; pics/music

**Comment by pyrates999** [comment] 2023-08-13 06:12
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

**Comment by Girofox** [comment] 2023-08-13 08:41
What is interesting is that not everyone has so many crashes with EP on that build.

**Comment by arikanorh** [comment] 2023-08-15 07:58
![image](https://github.com/valinet/ExplorerPatcher/assets/17791032/826e25f5-d8d7-45e9-993a-3f9bb747d8e8)

**Comment by phyco1991** [comment] 2023-08-17 14:43
See https://github.com/valinet/ExplorerPatcher/discussions/1702#discussioncomment-6690573 for a working fix

**Comment by Poopooracoocoo** [comment] 2023-08-22 11:46
Duplicate of #1798

**Closed by Poopooracoocoo** 2023-08-22 11:46 UTC

**Comment by m7d2** [comment] 2023-08-24 21:43
Issue is still present in latest update of EP
