### ISSUE TITLE
Clicking on Windows 10 start's profile picture doesn't do anything (Windows 11)

### ISSUE THREAD

**Issue by GuestTheGamer** [valinet/ExplorerPatcher#3056] opened 2024-03-26 09:22 UTC
add it

**Comment by pyrates999** [comment] 2024-03-26 09:26
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by GuestTheGamer** [comment] 2024-03-26 09:40
![Screenshot 2024-03-26 173936](https://github.com/valinet/ExplorerPatcher/assets/142704139/edb9207b-c561-4fc4-bd2f-100229223e48)

**Comment by pyrates999** [comment] 2024-03-26 10:09
You've got 3 notifications in your windows taskbar.  Please respond to them.  They might tell you what you need to do to fix this.

**Comment by Amrsatrio** [comment] 2024-03-26 18:31
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2977

**Closed by Amrsatrio** 2024-03-26 18:31 UTC
