### ISSUE TITLE
windows start menu wrecked again with today's download

### ISSUE THREAD

**Issue by robtgmann** [valinet/ExplorerPatcher#3609] opened 2024-08-29 23:48 UTC
I am wanting windows 10 style start menu and I've had it until yesterday. Current is showing things I didn't pin, apps are in a separate list.  I prefer table to apps I pin to the right, all apps to the left.  I have tried reinstalling older ep-setup.exe file, importing the previous setting file, uninstalling before every trial but nothing I have done has changed the start menu this download has caused.  I am running Windows 11 pro 23H2 Build 22631.4112.

**Comment by pyrates999** [comment] 2024-08-29 23:55
Install latest pre-release: https://github.com/valinet/ExplorerPatcher/releases

**Comment by ManyullynSword** [comment] 2024-08-30 11:08
> I am wanting windows 10 style start menu and I've had it until yesterday. Current is showing things I didn't pin, apps are in a separate list. I prefer table to apps I pin to the right, all apps to the left. I have tried reinstalling older ep-setup.exe file, importing the previous setting file, uninstalling before every trial but nothing I have done has changed the start menu this download has caused. I am running Windows 11 pro 23H2 Build 22631.4112.

I'm also having the same issue, no matter how I reinstall the latest pre-release version of Explorer Patcher, there is no option for the style of the start menu in the properties column.

**Comment by pyrates999** [comment] 2024-08-30 12:49
what do you mean style of the start menu?  Can you show a screen shot of the setting you're referring to in the EP properties application.

**Comment by robtgmann** [comment] 2024-08-30 14:53
I can't get to this on for about 6 hours. I'm under a lot of time pressure right now. And, I'm embarrassed to say that I know how to create a screenshot on my computer but I don't know how to paste it into GitHub. So if you could remind me - -. But the thing I was referring to is very simple. On previous issues the page labeled start menu says that Windows 10 is the default. That line of type is missing from the version you just downloaded. Does that help. I'll get back to this later. Also you gave me a link to something you'd prefer me to download. Once I'm on that page how do I find the download? I really am earnest but still a newbie. Thanks for your help
-- 
Robert Goldmann 
Please excuse my brevity.


-------- Original Message --------

**Comment by Ganu28** [comment] 2024-08-30 15:45
The option is nowhere to be found 
<img width="598" alt="image" src="https://github.com/user-attachments/assets/84b0b72e-b5fb-4944-8e0c-e88511cca8b3">

**Comment by pyrates999** [comment] 2024-08-30 21:44
I am not referring to the EP properties application.  You are to do this in your web browser.

**Comment by Amrsatrio** [comment] 2024-08-31 06:40
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3603

**Closed by Amrsatrio** 2024-08-31 06:40 UTC
