### ISSUE TITLE
Explorer crashes when Right Click on file

### ISSUE THREAD

**Issue by czerno6og** [valinet/ExplorerPatcher#2402] opened 2023-11-05 15:08 UTC
Explorer crashes when I Right Click on any files to pull up context menu.  i have tried uninstalling and the context menu works fine. Reinstall the program and explorer crashes again when i right click on file. I rebooted computer and it still occurs.

![image](https://github.com/valinet/ExplorerPatcher/assets/67464447/2a7e33fc-f4ab-4ed1-819c-0e82dfdc4b1a)

![image](https://github.com/valinet/ExplorerPatcher/assets/67464447/d39bcf6a-1e4b-48b2-a3da-653d0efc37af)

**Comment by Amrsatrio** [comment] 2023-11-05 15:17
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218

**Closed by Amrsatrio** 2023-11-05 15:17 UTC
