### ISSUE TITLE
New version is detected as a Virus on Windows 11

### ISSUE THREAD

**Issue by PierreTweakers** [valinet/ExplorerPatcher#3691] opened 2024-09-13 06:54 UTC
New version is detected as a Virus on Windows 11

**Comment by sh4rkman** [comment] 2024-09-13 07:07
![20240913_09h06m_iVIC3WNNVFZ](https://github.com/user-attachments/assets/6bda5f23-ef60-4908-a479-1834d5c607ac)

**Comment by arnehaese** [comment] 2024-09-13 08:29
Same here :/

**Comment by GrosPoney** [comment] 2024-09-13 08:44
Same since last Win11 update

**Comment by Armitage1982** [comment] 2024-09-13 08:56
Detected as a 
**HackTool:Win32/Patcher!MTB**
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=HackTool%3AWin32%2FPatcher!MTB&threatid=2147744922

Of course it is! How do you want to patch something without a patcher.
Pretty funny when you consider all the recent mess with CrowdStrike.

So False positive.
When it's not Google & Chrome playing _the savior_, it's Microsoft who's doing the heavy lifting.

_First thing to secure something without making your users install weird stuff is simply stop doing shit in the first place and listen to them._

**Comment by pyrates999** [comment] 2024-09-13 09:00
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

See the release notes here for the powershell script you can run that excludes all the directories necessary in windows defender: https://github.com/valinet/ExplorerPatcher/releases

The powershell script you must run with elevated privileges.

Future updates to EP won't be flagged then.

You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

if you get the error: 0x800106ba, it means Windows Defender is not active. You may have another antivirus program active.

**Comment by KunjanChauhan** [comment] 2024-09-13 11:03
> You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.

Not a good idea at all since the "Downloads" folder is used for downloading all types of files!  Perhaps you meant a folder created specifically for downloading EP into.

**Comment by pyrates999** [comment] 2024-09-13 11:12
> > You can also set windows defender to exclude the directory that you manually download EP to so you can install it without windows defender blocking it.
> 
> Not a good idea at all since the "Downloads" folder is used for downloading all types of files! Perhaps you meant a folder created specifically for downloading EP into.

that's what they meant.

**Closed** 2024-09-13 15:13 UTC
