### ISSUE TITLE
Win 11 taskbar has transparent background following Windows update

### ISSUE THREAD

**Issue by shelmers** [valinet/ExplorerPatcher#2998] opened 2024-03-14 01:44 UTC
I installed "2024-03 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5035853)" earlier today and my taskbar remained on the left side of my primary monitor. That's good news.

The unusual thing is that the background of the taskbar is now transparent, which is a bit strange! I haven't found a setting in either Windows or EP to set the taskbar background color or transparency.

Have I missed a setting or do I need to get accustomed to a transparent taskbar?

**Comment by CCarletto80** [comment] 2024-03-14 04:47
Yes: that has happened to me as well with the new update.

**Comment by r1atsa1a** [comment] 2024-03-14 05:13
same to me

**Comment by Cyberdr3am** [comment] 2024-03-14 05:41
same here

**Comment by gorillale** [comment] 2024-03-14 06:55
Thank you for correction!

**Comment by tryskacz** [comment] 2024-03-14 07:15
Can confirm, new version of EP fixed Win11 transparent background after KB5035853 update

**Comment by Amrsatrio** [comment] 2024-03-14 09:01
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2975

**Closed by Amrsatrio** 2024-03-14 09:01 UTC

**Comment by shelmers** [comment] 2024-03-14 13:31
Sorry that I didn't find #2975 before posting my issue -- but thanks for the quick fix! 

I can confirm that the taskbar no longer has a transparent background.
