### ISSUE TITLE
White border arround Taskbar items 

### ISSUE THREAD

**Issue by yesrab** [valinet/ExplorerPatcher#3899] opened 2024-11-08 11:54 UTC
there is thick border arround the taskbar items on the right side and clicking on the far right doesn't peek the desktop 

![image](https://github.com/user-attachments/assets/98efda22-9d02-4bc4-ab27-667ddc2d59f7)

**Comment by pyrates999** [comment] 2024-11-08 12:47
Go to the windows search bar
Type "Advanced"
Click on "View advanced system settings"
Click on the performance settings button
Choose the Visual Effects tab, unless already shown.
Untick and then re-tick the "Show translucent selection rectangle" box.
And without a restart your color should be back.

If you want to change the color and dont know how, here is how:
Open your run command or Win + R
Type in "regedit"
HKEY current user ->
Control Panel ->
Colors ->
Hilight and or HotTrackingColor

duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2323

Please close this

**Comment by Amrsatrio** [comment] 2024-11-08 18:29
![image](https://github.com/user-attachments/assets/46d3f673-290b-4578-b218-b74b741ffffb)

Is this off?

Do you have another tweak software installed?

**Comment by yesrab** [comment] 2024-11-09 05:40
> ![image](https://private-user-images.githubusercontent.com/20662640/384483364-46d3f673-290b-4578-b218-b74b741ffffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzExMzAsIm5iZiI6MTczMTEzMDgzMCwicGF0aCI6Ii8yMDY2MjY0MC8zODQ0ODMzNjQtNDZkM2Y2NzMtMjkwYi00NTc4LWIyMTgtYjc0Yjc0MWZmZmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA1NDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MDdmOTI2ZjJmZDNhMWIyMDFlZjE0MmNhNTQxYTg2MWEzYWFlZmI1MmZkZmI4NTFmY2EwOWY2NzZmNzA4MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4jWa5iWS-hCPC8lQ5xIysK59gzQggDnToW6DPfJi3LY)
> 
> Is this off?
> 
> Do you have another tweak software installed?

no that is not off

**Comment by yesrab** [comment] 2024-11-09 05:47
> to enable or disable: https://answers.microsoft.com/en-us/windows/forum/all/selection-box-on-windows-being-only-a-white-border/4f8deaa3-24ad-4bed-bbca-b26f7f63d4dd
> 
> ```
> Selection` Box on windows (being only a white border)
> So ever since i got windows, my selection box has been a white dotted outline. I looked around and the other solutions haven't helped. BUT! i found on that does for those that have the same problem.
> 
> Go to the windows search bar
> Type "Advanced"
> Click on "View advanced system settings"
> Click on the performance settings button
> Choose the Visual Effects tab, unless already shown.
> Untick and then re-tick the "Show translucent selection rectangle" box.
> And without a restart your color should be back.
> 
> If you want to change the color and dont know how, here is how:
> Open your run command or Win + R
> Type in "regedit"
> HKEY current user ->
> Control Panel ->
> Colors ->
> Hilight and or HotTrackingColor
> ```
> 
> duplicate of: #2323
> 
> Please close this

Untick and then re-tick the "Show translucent selection rectangle" box didnt work

**Comment by Amrsatrio** [comment] 2024-11-09 08:08
> no that is not off

Set this to off.

**Closed by Amrsatrio** 2024-11-09 08:08 UTC
Labels: Can't Repro

**Comment by yesrab** [comment] 2024-11-09 08:38
this fixed it thanks
