### ISSUE TITLE
Is this intentional? Pinning to start menu on Win 10 start menu style does not work

### ISSUE THREAD

**Issue by BenjiBenji69** [valinet/ExplorerPatcher#1284] opened 2023-04-09 23:27 UTC
forgive me for bothering, but is the pinning of apps or program to start menu on Win 10 style outside of apps list
 seems to be not working, was that intentional so as it doesn't pin also on Win 11 start or just a bug for the latest build?

**Comment by dicamarques14** [comment] 2023-04-11 10:15
I think this is related to #1108

**Comment by djcholapin** [comment] 2023-04-18 11:06
As far as I know, it has always acted this way with Explorer Patcher. You can only pin apps that are on the app list. Therefore, if you are missing apps, the only way is to manually add a shortcut in the Start Menu folder. As for the windows store app, they are meant to all be there, but as dicamarques14 mentionned, since the last microsft 11 update, there has been a change that has prevented those apps to be displayed in the list menu. So we are all waiting for a fix for that.

**Comment by pyrates999** [comment] 2023-05-16 09:13
This looks to be the same as https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:17
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:17 UTC
