### ISSUE TITLE
Windows 10 start menu gone.

### ISSUE THREAD

**Issue by Piedro2438** [valinet/ExplorerPatcher#3620] opened 2024-08-31 15:11 UTC
After an update, the Windows start button shows the Windows 11 start menu!
Tried to install the Windows 10 view with the latest ExplorerPatcher. This did not work. Did I do something wrong? Windows 11 Pro version 23H2 build 22631.4112 is installed on the PC.

**Comment by Winminn** [comment] 2024-08-31 17:18
我的ExplorerPatcher版本是22621.3527.65.5

我的windows 11  Pro 从[23H2 build 22631.4037 ]更新到[23H2 build 22631.4112] 之后，不显示windows 10的菜单设置
![image](https://github.com/user-attachments/assets/44ef3190-c79c-44c6-955a-3890804c79c3)

**Comment by Winminn** [comment] 2024-08-31 17:20
我只更新了补丁 KB5041587 ，就出现了这个问题

**Comment by Winminn** [comment] 2024-08-31 17:28
[https://github.com/valinet/ExplorerPatcher/issues/3603#issuecomment-2317317630](url)

**Comment by Amrsatrio** [comment] 2024-08-31 17:32
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3603

**Comment by Amrsatrio** [comment] 2024-08-31 17:33
Because it is gone and required a new method. The new method only came out in 66.x. However 66.4 was flagged by MS as malware so we're not making it a release.

**Closed by Amrsatrio** 2024-08-31 17:32 UTC
