### ISSUE TITLE
Right clicking Start Botton Issue

### ISSUE THREAD

**Issue by SalmonXVR** [valinet/ExplorerPatcher#3846] opened 2024-10-25 15:13 UTC
I recently downloaded the latest version of Explorer Patcher. I've noticed that when trying to right click on the Windows Start Button it doesn't function. The functionality seems stuck. Hopefully I'm the only the one who've realised that.

**Comment by pyrates999** [comment] 2024-10-25 15:28
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3844

please close this.

**Closed** 2024-10-26 00:14 UTC

**Comment by Aldarxt** [comment] 2024-10-26 23:14
I fixed the right click start by uninstalling KB5044380 update from windows 11.  I have 9 laptops, 6 are 12 years old running win 11 the rest are newer and 8 of them have explorer patcher running. After uninstalling KB5044380 the problem went away like it never was there. ep_setup.exe 22621.3880.66.6
