### ISSUE TITLE
Keyboard shortcuts such as Alt+Tab and the Windows Key do not work since the latest OS Build

### ISSUE THREAD

**Issue by thatmaxplayle** [valinet/ExplorerPatcher#1699] opened 2023-07-27 16:19 UTC
Since updating my machine last night to 22H2 build 22521.2070 I am now unable to use keybaord shortcuts such as Win + R for Run, Windows Key alone and Alt + Tab. The application keeps notifying me of additional OS symbols that have been downloaded, although right-clicking the taskbar just crashes Windows Explorer. 

Not really sure where to go from here.
Cheers,
Max

**Comment by manu-st** [comment] 2023-07-27 16:53
I have the same issue. The Explorer patcher console reports the following when doing Windows + Tab key:

Error in sub_1800135EC on RoGetActivationFactory.

Here is the full output:

```
funchook create 1
Running on Windows 11, OS Build 10.0.22621.2070.
Loaded symbols
Setup ntdll functions done
Setup user32 functions done
Patched taskbar transparency in newer OS builds
Setup explorer functions done
Setup uxtheme functions done
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup explorerframe functions done
Setup windows.storage functions done
[IME] Context menu patch status: 1
Setup inputswitch functions done
Setup windowsudk.shellcommon functions done
Setup peopleband functions done
Installed hooks.
Play startup sound thread...
Signal shell ready...
Started "Signal shell ready" thread.
Open Start on monitor thread
Started "Open Start on current monitor" thread.
EP Service Window thread
Initialized taskbar centering module.
[Positioning] Added settings for monitor 0000000001140D27 : 0
[Positioning] Added settings for monitor 0000000000AF0357 : 0
[Positioning] Added settings for monitor 0000000000CC0E71 : 0
Progman: 327990
Progman hook: 985901
>>> Signal shell ready.
Setup sndvolsso functions done
Ended "Signal shell ready" thread.
Started "Play startup sound" thread.
Ended "Play startup sound" thread.
0 0
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Install updates automatically".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "22622.1992.56.1.b50a7e3beffb83cf"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.1992.56.1.b50a7e3beffb83cf" (valid).
[Updates] Local version obtained from hash is 22622.1992.56.1.
[Updates] No updates are available.
Error in sub_1800135EC on RoGetActivationFactory.
```

**Comment by pyrates999** [comment] 2023-07-27 20:47
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by manu-st** [comment] 2023-07-27 21:59
Makes sense but once in a while you can install a preview for some other reasons, and unfortunately there is no easy way to uninstall them. In any case, my report here was to help, I fully understand why this is not working and I can live with that.

**Comment by Vipin2003** [comment] 2023-07-28 03:43
You can uninstall any update using classic "Uninstall updates" feature. But, currently if you open it, it will throw you to settings app. Install SAB over EP once and again try the classic thing. This time, it will open in CP. Because SAB restored that classic applet.

I think that @valinet should try to restore this classic thing too because there are many users who switches b/w different builds. It will help those users to easily uninstall their preview updates. The user doesn't need to install SAB again and again.

**Comment by pyrates999** [comment] 2023-07-28 06:36
I've never heard of SAB.  Can you link me to it as I'd like to enable the classic control panel for dealing with checking with windows updates.

**Comment by grimmute** [comment] 2023-07-28 11:34
> That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8
> 
> Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

Can you stop posting this on every issue thread here?

While it is a valid solution to update the uninstall itself, you are assuming people choose to install this. I know I didn't and I don't have the "Get the latest updates as soon as available" toggle enabled.

**Comment by sunsetsnow** [comment] 2023-07-28 14:20
If it's worth anything, I have a similar problem since updating.

"Similar" in that Alt+Tab works but Win+Tab doesn't. And if I *try* to Win+Tab, then Alt+Tab *stops* working until I restart File Explorer via ExplorerPatcher's Properties dialog. And for what it's worth, I had "Get the latest updates as soon as available" checked, but I'm *not* in the Windows Insider Program either. But I guess I will uncheck "Get the latest updates as soon as available" for now if it's going to break EP.

**Comment by pyrates999** [comment] 2023-07-28 16:57
> > That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8
> > Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> Can you stop posting this on every issue thread here?
> 
> While it is a valid solution to uninstall the update itself, you are assuming people choose to install this. I know I didn't and I don't have the "Get the latest updates as soon as available" toggle enabled.

It's still the answer and is apparently useful.

**Comment by asiro85** [comment] 2023-08-08 20:20
WINDOWS+TAB still not working on build 22621.2134. ALT+TAB works until WINDOWS+TAB is pressed. After that, both don't work. Restarting explorer.exe only fixes ALT+TAB

**Comment by pyrates999** [comment] 2023-08-08 21:08
Did you check that symbols were downloaded? https://github.com/valinet/ExplorerPatcher/wiki/Symbols

You need to restart file explorer after symbols are downloaded.

**Comment by pyrates999** [comment] 2023-08-09 20:48
Try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install the latest explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

**Comment by pyrates999** [comment] 2023-08-12 10:23
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

**Closed** 2023-08-13 16:53 UTC
