### ISSUE TITLE
Missing context menu while RMB on windows icon.

### ISSUE THREAD

**Issue by kamykson** [valinet/ExplorerPatcher#3843] opened 2024-10-24 17:06 UTC
Hello. 
I'm used to using rmb on start/windows button on taskbar. Normally it shows context menu with shortcuts. I have windows 11 23h2 and EP up to date. Since couple of days RMB doesn't work. I didn't change anything in windows nor EP. When I started troubleshooting this problem, I noticed that the problem disappears when taskbar style is set to default (win11 style) while I normally use win 10 style. Is it a bug or new stupid feature?

**Comment by cpresco** [comment] 2024-10-24 20:39
Your issue description sounds like the issue that I reported with #3844. 

I'd recommend checking if KB5045935 has been installed via Windows Update and if yes either rolling back to a recent System Restore Point or trying to uninstall KB5045935 then rebooting.

I'd also recommend disabling "Get the latest updates as soon as they're available" in Settings app>Windows Update if you have that enabled.

**Comment by pyrates999** [comment] 2024-10-24 22:30
please check if you have the latest pre-release installed: https://github.com/valinet/ExplorerPatcher/releases

**Comment by kamykson** [comment] 2024-10-24 22:43
@cpresco: I wish, but this appears to not be the case. 
The newest update I have is KB5044380, latest framework update I have KB5044033. I still tried to uninstall it... Win11 makes me nuts! It showed me uninstalling process, this update vanished from updates to uninstall list but remains in the installed list! Can you tell me how did you find out about this update causing problems? Maybe I can find somewhere, is any other still messing with EP? 

@pyrates999 I've just installed it succesfully but it changed nothing.

**Comment by pyrates999** [comment] 2024-10-24 22:47
Then please wait for a developer to respond.

**Comment by cpresco** [comment] 2024-10-25 20:06
@kamykson I highly recommend enabling System Restore Points in Windows 11 if you don't have that enabled. I understand that won't help you in this specific situation but in the future having a System Restore Point available to roll back to can be invaluable when trying to recover from something that has stopped functioning especially after a Windows Update has been installed.

**Comment by milesprower2293** [comment] 2024-10-26 00:31
Duplicate of #3837

**Closed by milesprower2293** 2024-10-26 00:31 UTC
