### ISSUE TITLE
After the Windows update KB5044284 (OS build 26100.2033/24H2), the Windows 10-style Start menu cannot be displayed.

### ISSUE THREAD

**Issue by mc30207** [valinet/ExplorerPatcher#3798] opened 2024-10-14 10:03 UTC
As mentioned at the beginning, after the Windows update KB5044284, the Windows 10-style Start menu cannot be displayed, but the Windows 11-style Start menu works fine. My computer is a Surface Laptop 7 with Snapdragon X Plus, running Windows 11 ARM version 26100.2033 24H2. After rolling back the system to version 26100.1882 24H2, it works properly. I hope this issue can be resolved.

**Comment by mc30207** [comment] 2024-10-14 11:06
> Please post explorer patcher version.
> 
> What language your windows 11 24h2 in?

The version of ExplorerPatcher I am currently using is 22621.3880.66.6. The Windows system language is Traditional Chinese.

**Comment by pyrates999** [comment] 2024-10-14 11:25
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3667

please close this.

**Closed** 2024-10-14 11:42 UTC
