### ISSUE TITLE
Visual bug on sound and date. Pls fix it, OCD annoyance!!

### ISSUE THREAD

**Issue by lazostat** [valinet/ExplorerPatcher#2333] opened 2023-10-21 12:03 UTC
![Screenshot 2023-10-21 150238](https://github.com/valinet/ExplorerPatcher/assets/148628917/f126f1f3-be36-4929-ae99-bb464f42ad67)
![Screenshot 2023-10-21 150207](https://github.com/valinet/ExplorerPatcher/assets/148628917/597b789c-c5ac-4630-91ad-921777563049)

**Comment by Amrsatrio** [comment] 2023-10-21 12:33
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1448

**Closed by Amrsatrio** 2023-10-21 12:33 UTC
