### ISSUE TITLE
Weird issue with the notifications pane overlapping the taskbar in os build 22621.2134

### ISSUE THREAD

**Issue by MinerAC4** [valinet/ExplorerPatcher#1854] opened 2023-08-15 16:10 UTC
Not exactly sure why this is happening, but the notifications panel just randomly started overlapping the taskbar. Not sure if this is normal, but I'm pretty sure it didn't used to do that.
**Edit:** I just noticed that the action center also has this behavior now too.
![image](https://github.com/valinet/ExplorerPatcher/assets/99057951/eb02ed74-2380-4bae-b3c8-659138e01357)
![image](https://github.com/valinet/ExplorerPatcher/assets/99057951/f52a8abd-9339-4002-b9c9-19e120f27946)

**Comment by pyrates999** [comment] 2023-08-15 22:35
Do you have multiple monitors attached?  Does this happen when it wakes up from sleep mode?

**Comment by yolarrydabomb** [comment] 2023-08-17 21:28
Same issue I notice it after I update to 22621.1992.56.1. No sleep mode, I even rebooted the system and retry and still overlay the taskbar
However I do have 2 monitors. 
![2023-08-17_17-24-33](https://github.com/valinet/ExplorerPatcher/assets/13090096/2692dafa-f487-4a4d-866c-a6eaa4da78b0)

**Comment by pyrates999** [comment] 2023-08-18 11:25
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1759

Please close this one.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:04
Closing as duplicate of #1759

**Closed by Poopooracoocoo** 2023-08-22 10:04 UTC
