### ISSUE TITLE
Customize notification area icons not working correctly

### ISSUE THREAD

**Issue by vondav** [valinet/ExplorerPatcher#2955] opened 2024-03-08 09:20 UTC
In notification area I want to set for some icon option "Show icon and notification", but it does not work.

Steps to reproduce: 
1. Open Explorer Patcher settings -> Taskbar -> Customize notification area icon

![image](https://github.com/valinet/ExplorerPatcher/assets/57345800/eb556b14-6f02-454d-a90e-a70d5e1096a0)

3. In window **Notification Area Icons** set for some icon option **Show icon  and notification**

![image](https://github.com/valinet/ExplorerPatcher/assets/57345800/903ec3bc-5216-4d8c-b375-55b6668b8323)

4. Confirm with **OK** button.

Selected icon is still in collapsed area.

System:
Edition	Windows 11 Business
Version	23H2
OS build	22631.3155

Explorer Patcher version:
22621.2861.62.2

P.S. I really like Explorer Patcher

**Comment by pyrates999** [comment] 2024-03-08 11:11
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.

**Closed** 2024-03-08 14:18 UTC
