### ISSUE TITLE
[Feature Request] Windows 10 start menu pinned tile style transparent (default) and background color

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#1730] opened 2023-07-31 10:01 UTC
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1673

<div type='discussions-op-text'>

<sup>Originally posted by **XuanChen1234** July 26, 2023</sup>
Many many thanks, Valinet. 
If it is not planned yet, I hope this will be a thing in the next update.
![屏幕截图 2023-07-28 110951](https://github.com/valinet/ExplorerPatcher/assets/140480110/a6778cab-0e24-4674-a80c-55e6be7a2356)
</div>

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:43
Duplicate of #1673

**Closed by Poopooracoocoo** 2023-08-22 10:43 UTC
