### ISSUE TITLE
Is latest pre release malware?

### ISSUE THREAD

**Issue by Atticuss320** [valinet/ExplorerPatcher#3611] opened 2024-08-30 01:45 UTC
https://tria.ge/240830-b3q9yasfkl/behavioral2

**Comment by pyrates999** [comment] 2024-08-30 12:44
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3228

Please close this.

MS just doesn't like EP and has added it to windows defender, even though it is not a virus and not a hack tool.

Also set windows defender to exclude the following:

1. %ProgramFiles%\ExplorerPatcher
2. %APPDATA%\ExplorerPatcher
3. Directory that you downloaded ep_setup.exe to

Future updates to EP won't be flagged then.

**Closed** 2024-08-31 06:40 UTC
