### ISSUE TITLE
Latest round of windows 11 updates broke Explorer Patcher again

### ISSUE THREAD

**Issue by alandsidel** [valinet/ExplorerPatcher#2439] opened 2023-11-14 23:02 UTC
Today I installed several Windows 11 updates:

- 2023-11 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for x64 (KB5032007)
- Cumulative Update for Windows 11... (KB5032190)
- .NET 6.0.25 Security Update for x64 Client (KB5032883)

One of these caused an incompatibility with EP, resulting in the start menu being unable to open either through the windows key, ctrl-esc, or the mouse.  I had to uninstall EP to get control of Explorer back.

Mondays, eh?

**Comment by aemsx** [comment] 2023-11-14 23:05
same here. windows has just been updated to build 22621.2715. also windows 11 context menu seems to crash the explorer / ep.

**Comment by Amrsatrio** [comment] 2023-11-15 00:40
Please revert to 22621.2506 or 22621.2428 and pause for 5 weeks for the time being. I'll investigate shortly.

**Comment by Amrsatrio** [comment] 2023-11-15 00:57
Have you tried checking the "Disable the Windows 11 context menu?" in EP Properties > Explorer? Because with that enabled, I have no issues even with the start menu. Everything worked as they were.

**Comment by Amrsatrio** [comment] 2023-11-15 01:02
I'm using the Windows 7 command bar here.

![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/6d4c39c7-1991-49bf-bd19-391dc446d8d2)

**Comment by Amrsatrio** [comment] 2023-11-15 01:08
> same here. windows has just been updated to build 22621.2715. also windows 11 context menu seems to crash the explorer / ep.

Regarding Windows 11 context menus, it has been this way since 22621.2134+. I still haven't found a proper fix for this yet. https://github.com/valinet/ExplorerPatcher/issues/2218

**Comment by Amrsatrio** [comment] 2023-11-15 01:10
Maybe the only way I can figure this out is by updating a number of my PCs and laptops to 2716... I suspect this has something to do with feature flags that broke EP for some reason

**Comment by Amrsatrio** [comment] 2023-11-15 01:11
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/bbe721c1-0b12-4f74-84f7-4a7db59a6312)
If you can download ViVeTool and run this command, it might be helpful for me.

**Comment by alandsidel** [comment] 2023-11-15 01:14
> ![image](https://user-images.githubusercontent.com/20662640/282973366-bbe721c1-0b12-4f74-84f7-4a7db59a6312.png) If you can download ViVeTool and run `vivetool /query > output.txt` and sending the output.txt, it might be helpful for me.

As requested!

[output.txt](https://github.com/valinet/ExplorerPatcher/files/13358839/output.txt)

**Comment by Amrsatrio** [comment] 2023-11-15 01:26
So your issue is only start menu refusing to open? Or did your Explorer crash when trying to open it?

**Comment by Amrsatrio** [comment] 2023-11-15 01:32
So your issue is only start menu refusing to open? Or did your Explorer crash when trying to open it? Did you see any Error lines with Applicaton Error as the source?

<img width="554" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/c24bd45e-aaf5-42a9-ba12-f8e5d6a1f737">

That is the screenshot from someone else in our Discord that is experiencing an Explorer crash which I could not reproduce as well.

**Comment by alandsidel** [comment] 2023-11-15 01:32
> So your issue is only start menu refusing to open? Or did your Explorer crash when trying to open it?

Explorer wasn't crashing, but the start menu wasn't opening it.  The task manager and task bar were fine.  I ended and restarted the explorer process from task manager manually once to see if it would fix anything, no dice.  The key shortcuts to open the start menu did "nothing" and clicking on it just showed the circular spinner for a moment.

Can't spend any more time on this right now, but if you need further debugging stuff I'll do what I can in 12h or so.

**Comment by Amrsatrio** [comment] 2023-11-15 01:33
Yep. I'll wait till then. Maybe the first page of the full screened console output will help.

**Comment by tbcam88** [comment] 2023-11-15 09:24
Yeah, the KB5032190 update seems responsible, serious lag when opening explorer windows etc.

I uninstalled and things have reverted to normal - hopefully we get a fix! 👌

**Comment by Amrsatrio** [comment] 2023-11-15 09:27
@tbcam88 Which File Explorer control interface are you using?

**Comment by tbcam88** [comment] 2023-11-15 09:36
> @tbcam88 Which File Explorer control interface are you using?

![Untitled](https://github.com/valinet/ExplorerPatcher/assets/19891537/d4995916-cbc2-4d8a-a6b9-833450577124)

The above, typically.

**Comment by Amrsatrio** [comment] 2023-11-15 09:38
I mean, this part.
<img width="906" alt="image" src="https://github.com/valinet/ExplorerPatcher/assets/20662640/27199dd0-8a8b-4d19-8018-ff65f1f0dc07">

The Windows 11 command interface has known issues to be breaking with ExplorerPatcher installed, atleast there are two reports. One on 2361, and another one on 2715. Strangely I could not reproduce those issues.

**Comment by aemsx** [comment] 2023-11-15 09:43
> Have you tried checking the "Disable the Windows 11 context menu?" in EP Properties > Explorer? Because with that enabled, I have no issues even with the start menu. Everything worked as they were.

Yes, this is a workaround but does not fix the issue

> Regarding Windows 11 context menus, it has been this way since 22621.2134+. I still haven't found a proper fix for this yet. #2218

It 100% woked in the build I had before (Win 10 taskbar + Win 11 context menu) - not sure which one i had but I guess it was 22621.2506 or 22621.2428. It just stopped after the windows updates that were installes last night.

Also symbols can't be downloaded anymore - guess they're just not existing yet.

**Comment by Amrsatrio** [comment] 2023-11-15 09:44
So you really want to use the Windows 11 right click with non-Windows 11 command bar?

**Comment by aemsx** [comment] 2023-11-15 09:46
> So you really want to use the Windows 11 right click with non-Windows 11 command bar?

It's not vital - but if there is an option for it within EP it should work. Otherwise the option should be removed I guess.

**Comment by Amrsatrio** [comment] 2023-11-15 09:47
Yeah that is my plan. I want to remove it rather than making it not crash under non-Windows 11 command bar.

**Comment by tbcam88** [comment] 2023-11-15 09:49
> I mean, this part. <img alt="image" width="906" src="https://user-images.githubusercontent.com/20662640/283071627-27199dd0-8a8b-4d19-8018-ff65f1f0dc07.png">
> 
> The Windows 11 command interface has known issues to be breaking with ExplorerPatcher installed, atleast there are two reports. One on 2361, and another one on 2715. Strangely I could not reproduce those issues.
> 
> Just saying, the Windows 11 command bar especially the one with modern navigation bar inherently has serious lagging issues even when EP is not installed.
> 
> Maybe you can record a video of the issue you're experiencing?

It isn't purely with windows explorer itself - apps (notepad etc.) were all opening with similar delay too. I killed the EP executable first and foremost to ensure this was the root of the conflict, doing so resumed normal functionality. I then immediately uninstalled KB5032190 and things returned as they were before the update was applied earlier this morning.

We'll need to wait a for a new version of EP I imagine.

**Comment by Amrsatrio** [comment] 2023-11-15 09:50
EP does not run as its own executable. Even if you have EP registered as shell extension, it won't be injected into the Notepad app because it is a UWP app. Which means there might be other tweak software that you installed, that happened to conflict with EP. Are there any?

**Comment by tbcam88** [comment] 2023-11-15 10:13
> EP does not run as its own executable. Even if you have EP registered as shell extension, it won't be injected into the Notepad app because it is a UWP app. Which means there might be other tweak software that you installed, that happened to conflict with EP. (Wallpaper Engine is considered one.) Are there any?
> 
> I seriously experience no issues with the latest update on my laptop whose customization software is only EP. This way, diagnosing the issue to make a proper fix can take a long time which is until I see the issue in person.

Sorry, I should have made my wording clearer. I force restarted explorer multiple times which in turn causes EP to end its instance and not reboot. This resumed normal Windows functionality. I then rolled back KB5032190 to see if this resumed normal EP functionally which it has.

No, nothing else was installed/tweaked. As I say the issue arose immediately after the KB5032190 install and has been rectified after rolling it back. Nothing else has been done to my system between now and then.

**Comment by alandsidel** [comment] 2023-11-15 12:32
>> Explorer wasn't crashing, but the start menu wasn't opening it. The task manager and task bar were fine. I ended and restarted the explorer process from task manager manually once to see if it would fix anything, no dice. The key shortcuts to open the start menu did "nothing" and clicking on it just showed the circular spinner for a moment.

>> Can't spend any more time on this right now, but if you need further debugging stuff I'll do what I can in 12h or so.

> Yep. I'll wait till then. Maybe the first page of the full screened console output will help. I have assignments due really shortly now so I can't investigate deeply for now.

What console output do you mean here?  Will provide it today if possible.

**Comment by pyrates999** [comment] 2023-11-15 13:35
> > > Explorer wasn't crashing, but the start menu wasn't opening it. The task manager and task bar were fine. I ended and restarted the explorer process from task manager manually once to see if it would fix anything, no dice. The key shortcuts to open the start menu did "nothing" and clicking on it just showed the circular spinner for a moment.
> 
> > > Can't spend any more time on this right now, but if you need further debugging stuff I'll do what I can in 12h or so.
> 
> > Yep. I'll wait till then. Maybe the first page of the full screened console output will help. I have assignments due really shortly now so I can't investigate deeply for now.
> 
> What console output do you mean here? Will provide it today if possible.

Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by alandsidel** [comment] 2023-11-15 13:41
> > > > Explorer wasn't crashing, but the start menu wasn't opening it. The task manager and task bar were fine. I ended and restarted the explorer process from task manager manually once to see if it would fix anything, no dice. The key shortcuts to open the start menu did "nothing" and clicking on it just showed the circular spinner for a moment.
> > 
> > 
> > > > Can't spend any more time on this right now, but if you need further debugging stuff I'll do what I can in 12h or so.
> > 
> > 
> > > Yep. I'll wait till then. Maybe the first page of the full screened console output will help. I have assignments due really shortly now so I can't investigate deeply for now.
> > 
> > 
> > What console output do you mean here? Will provide it today if possible.
> 
> Open up the properties application for explorer patcher, go to advanced, and click on enable console.

Ah, no can do as it's not installed now.  Might be able to do this later.  Probably best to just set up a VM to test this stuff if @Amrsatrio can't do so himself.

**Comment by Amrsatrio** [comment] 2023-11-15 16:17
If the start menu was crashing then at least a crash log from event viewer related to StartMenuExperienceHost.exe might help.

**Comment by alandsidel** [comment] 2023-11-15 17:59
> If the start menu was crashing then at least a crash log from event viewer related to StartMenuExperienceHost.exe might help.

Attached several error logs from the event viewer detailing the crash.  The only real difference between them is that it seems to alternate back and forth regarding the exception.  Half of them are access violations (0xc0000005) and the other half are user callback exceptions (0xc000041d).  They seem to come in pairs with the access violation first, then the callback exception a second or two later.  This probably coincides with the "spinner" time starting and ending after hitting the WIN key or clicking it with the mouse.  2s sounds about right.

Rename .txts to .xml, github won't allow direct XML attachments.
[crash01.txt](https://github.com/valinet/ExplorerPatcher/files/13367808/crash01.txt)
[crash02.txt](https://github.com/valinet/ExplorerPatcher/files/13367809/crash02.txt)
[crash03.txt](https://github.com/valinet/ExplorerPatcher/files/13367810/crash03.txt)
[crash04.txt](https://github.com/valinet/ExplorerPatcher/files/13367811/crash04.txt)
[crash06.txt](https://github.com/valinet/ExplorerPatcher/files/13367812/crash06.txt)

**Comment by Amrsatrio** [comment] 2023-11-15 18:03
The crashes happen in StartDocked.dll, which is the Windows 11 start menu. Still though strangely it doesn't crash on my laptop that I just updated.

**Comment by alandsidel** [comment] 2023-11-15 20:55
I've just installed the latest release, and it seems to be working fine.  The setup file is a different size from the last one I'd installed, so I presume it was a somewhat older version.  I last updated shortly after the OSD bug was fixed, as that also afflicted me.

The md5 hash of the last installer I used prior to the latest one is `d56736c633d0b5db571501e77830251a`

**Comment by Amrsatrio** [comment] 2023-11-16 07:39
I was about to tell you to update but I forgot for some reason, sorry 😂

Closing this issue then due to user error.

**Closed by Amrsatrio** 2023-11-16 07:39 UTC
Labels: Can't Repro
