### ISSUE TITLE
'Properties' not showing up in taskbar context menu

### ISSUE THREAD

**Issue by AstudilloMarillo** [valinet/ExplorerPatcher#2779] opened 2024-02-04 10:58 UTC
Also, the Windows 11 startbutton style is not showing.
This happened after I pressed the 'Restore default settings' option.
Importing my previous settings doesn't work.
Uninstalling and reinstalling ExplorerPatcher doesn't work.

_edit:_ the advanced option _'Do not change the taskbar context menu (e.g. do not display the "Properties" item)'_ is disabled.

This is the output of the console when restarting File Explorer:

Running on Windows 10, OS Build 10.0.19045.3930.
Loaded symbols
Setup user32 functions done
Setup explorer functions done
Setup uxtheme functions done
Failed to hook CLauncherTipContextMenu::ShowLauncherTipContextMenu(). rv = -1
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup sndvolsso functions done
Setup shell32 functions done
Setup windows.storage functions done
Setup peopleband functions done
Installed hooks.
Open Start on monitor thread
EP Service Window thread
Started "Open Start on current monitor" thread.
Initialized taskbar centering module.
Progman: 1638678
Progman hook: 1706535
0 0
[sws] Wallpaper RECT -2560 0 5120 3360
[sws] Refreshing theme: 1
[sws] Refreshing theme: 1
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll
[Updates] Checking against hash "22622.2861.62.2.c2b7c0292fff8608"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.2861.62.2.c2b7c0292fff8608" (valid).
[Updates] Local version obtained from hash is 22622.2861.62.2.
[Updates] No updates are available.

**Comment by pyrates999** [comment] 2024-02-04 12:40
Run this to access the EP properties application: `rundll32 C:\Windows\dxgi.dll,ZZGUI`

Then see here for how to enable it: https://github.com/valinet/ExplorerPatcher/wiki/About-advanced-settings#hide-the-program-settings-item-properties-from-the-taskbar-context-menu

**Comment by AstudilloMarillo** [comment] 2024-02-04 12:44
> Run this to access the EP properties application: `rundll32 C:\Windows\dxgi.dll,ZZGUI`
> 
> Then see here for how to enable it: https://github.com/valinet/ExplorerPatcher/wiki/About-advanced-settings#hide-the-program-settings-item-properties-from-the-taskbar-context-menu

I forgot to add this to my original message, but that option is actually correctly disabled. 
I'll edit my original message to reflect that.

**Comment by pyrates999** [comment] 2024-02-04 12:55
Try the following:

1. in the EP properties application, click on **restart file explorer**
2. open up task manager and kill explorer.exe and then run task manager again and run explorer.exe

If still not working, please show the following:

1. screen shot of settings in Advanced in the EP properties application
3. screen shot of you right clicking on the taskbar where **Properties** is not there

**Comment by AstudilloMarillo** [comment] 2024-02-04 13:02
No luck, so here's the screenshot:

![image](https://github.com/valinet/ExplorerPatcher/assets/136191659/1514d9dd-e823-4cc9-945c-78e2fac577e2)

**Comment by Amrsatrio** [comment] 2024-02-04 14:33
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1371

**Closed by Amrsatrio** 2024-02-04 14:33 UTC
