### ISSUE TITLE
Most recent (Feb 21 2024) patch is detected as virus by windows defender.

### ISSUE THREAD

**Issue by AtmaDarkwolf** [valinet/ExplorerPatcher#2894] opened 2024-02-22 04:43 UTC
As topic. Am hoping just a mistake with code, will not update and wait on fix.(have never had it do this before, may be recent windows/Microsoft 'fuck you' to anyone attempting to make windows/file explorer useful)

**Comment by spafil** [comment] 2024-02-22 05:56
Waiting for a "clean" update as Windows Defender got all hot and bothered with this one.

**Comment by pniaps** [comment] 2024-02-22 07:06
Duplicated #2873

**Comment by Amrsatrio** [comment] 2024-02-22 09:28
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2873

**Closed by Amrsatrio** 2024-02-22 09:28 UTC
