### ISSUE TITLE
Crash when I right click on Win11 taskbar

### ISSUE THREAD

**Issue by Cansburg** [valinet/ExplorerPatcher#1994] opened 2023-09-04 17:30 UTC
Right-clicking on the win11 taskbar causes File Explorer to restart, repeat this several times and this window will pop up:
![image](https://github.com/valinet/ExplorerPatcher/assets/50489292/86005273-abdc-48ef-bb79-feac708a1db4)
No problem on win10 taskbar.

Enable console show me this code:
![image](https://github.com/valinet/ExplorerPatcher/assets/50489292/18e70ef0-931e-45d7-9b85-b5e0dadeaebe)
```
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\WINDOWS\dxgi.dll[Updates] Checking against hash "22622.1992.56.3.6ea877454191d206"
[Updates] Update URL: https://github.com/zetaloop/ExplorerPatcher/releases/latest/download/ep_setup.exe
```

Currently on version 22621.1992.56.3 
Windows 11 Pro build 22H2 22621.2134

**Comment by Poopooracoocoo** [comment] 2023-09-04 19:00
Duplicate of #1805

**Closed by Poopooracoocoo** 2023-09-04 19:00 UTC
