### ISSUE TITLE
Some new Windows 11 disappear

### ISSUE THREAD

**Issue by meto20** [valinet/ExplorerPatcher#1190] opened 2023-03-24 08:37 UTC
Hi there, 

I'm using this Explorer patch to restore the old version of windows 10 of the taskbar and the menu as well. 
But after trying and updating it two times I've detected that all newly released apps in windows 11 disappear from the start menu and from the app list as well. I must search about them manually to see them. 

Could you please solve this issue in the next release?
Regards,
Meto

**Comment by topia** [comment] 2023-03-24 08:45
duplicate of #1108. If someone investigates the details, it'll be resolved.

**Comment by Poopooracoocoo** [comment] 2023-03-26 10:18
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-03-26 10:18 UTC
