### ISSUE TITLE
How do i get rid of this white line

### ISSUE THREAD

**Issue by CasanovaSan** [valinet/ExplorerPatcher#3513] opened 2024-07-28 18:43 UTC
So I've installed explorer patcher because i missed the windows 10 taskbar, and i have remade my start menu on how it used to be before, but now there is one thing that absolutely irritates me, and it's this white line
![image](https://github.com/user-attachments/assets/9dead3d8-4a56-468a-8d51-f3a997b0c1f5)
![image](https://github.com/user-attachments/assets/c9e90b63-0d47-4286-a329-d5407709ae9c)
![image](https://github.com/user-attachments/assets/2934b6cd-0572-46c4-85d8-7e5ef34b31ad)

**Comment by pyrates999** [comment] 2024-07-28 21:41
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2323

Please close this

**Closed** 2024-07-28 23:07 UTC
