### ISSUE TITLE
System notifications and the calendar overlap with the taskbar

### ISSUE THREAD

**Issue by jed84** [valinet/ExplorerPatcher#1947] opened 2023-08-26 23:40 UTC
Issue: System notifications and the calendar overlap with the taskbar

ExplorerPatcher v.22621.1992.56.3
Win 11 v.22621.2134

Notification/Taskbar overlap:
![256964266-893dcbc6-a7de-4e32-81f0-3edf9c2dc96f](https://github.com/valinet/ExplorerPatcher/assets/47121522/17ca666d-d8c5-4c34-83d4-c140528b2c0a)

Calendar/Taskbar overlap:
![obraz](https://github.com/valinet/ExplorerPatcher/assets/47121522/bce16962-d331-415d-a673-27b1c81fed3a)

**Comment by Poopooracoocoo** [comment] 2023-08-27 03:08
Duplicate of #1788

**Closed by Poopooracoocoo** 2023-08-27 03:08 UTC
