### ISSUE TITLE
Weather keeps turning into People after a few minutes

### ISSUE THREAD

**Issue by helloboy4000** [valinet/ExplorerPatcher#3090] opened 2024-04-04 16:49 UTC
Anytime I have the Weather on, it will stay as weather for only a few minutes before turning into a People thing. What do I do?

**Comment by pyrates999** [comment] 2024-04-04 22:53
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2010

please close this.

**Closed** 2024-04-05 00:55 UTC
