### ISSUE TITLE
" open with " and "change defualt program" not working

### ISSUE THREAD

**Issue by ehsas1** [valinet/ExplorerPatcher#3772] opened 2024-10-07 21:17 UTC
hello
After installing this software, the open with option and chnage default program do not work for me
I click on open with to open with other programs, it doesn't work if I change the default program.
Even the double-click option to open is disabled.

Deleting the software did not solve the problem

**Comment by ehsas1** [comment] 2024-10-08 14:41
> I encountered that on windows 10. A windows update was installed and needed a reboot to fix it.

I have installed the latest update for ltsc 24 h2 version
There is no more update for me
How to get and install the latest update?

**Comment by pyrates999** [comment] 2024-10-08 15:37
I said windows update, not update for EP.  All that was needed was for my computer to reboot to install the windows update for it.

**Comment by ehsas1** [comment] 2024-10-08 15:46
> I said windows update, not update for EP. All that was needed was for my computer to reboot to install the windows update for it.

I don't have any Windows updates
How do I update it now? By downloading the file from this link?
https://www.catalog.update.microsoft.com/Search.aspx?q=cumulative%20update%20windows%2011

**Comment by pyrates999** [comment] 2024-10-08 23:49
Just reboot your computer.

**Comment by ehsas1** [comment] 2024-10-09 04:36
> Just reboot your computer.

No, the problem has not been solved by rebooting

**Comment by ehsas1** [comment] 2024-10-10 17:58
> EP

what is "EP " bro?
i dont khnow

**Comment by pyrates999** [comment] 2024-10-10 23:27
EP = Explorer Patcher.

**Comment by Amrsatrio** [comment] 2024-11-03 19:38
Is the problem still present with latest EP, Windows, and everything else?

**Comment by Amrsatrio** [comment] 2024-11-05 16:43
Closing due to irreproducibility on 22631.4391. If it persists after uninstalling EP then something else might be interfering with it.

**Closed by Amrsatrio** 2024-11-05 16:43 UTC
