### ISSUE TITLE
Start menu bug in Windows 11

### ISSUE THREAD

**Issue by xapatv** [valinet/ExplorerPatcher#2478] opened 2023-11-20 21:10 UTC
![Screenshot 2023-11-20 175915](https://github.com/valinet/ExplorerPatcher/assets/108148667/77b3eaca-49b8-43fc-a40d-acd0794f829a)

When I open the start menu the first pinned icon ("This PC" in the pic) have this weird white border. It started happening around 1 month ago.

I only use ExplorerPatcher to remove the "Recommended" section in Windows 11 Start menu, I didnt changed any other setting.

**Comment by Amrsatrio** [comment] 2023-11-20 21:17
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1448

No idea if this can be fixed.

**Closed by Amrsatrio** 2023-11-20 21:17 UTC

**Comment by pyrates999** [comment] 2023-11-21 01:12
If you want to disable that whitebar:

1. Go to the windows search bar
2. Type "Advanced"
3. Click on "View advanced system settings"
4. Click on the performance settings button
5. Choose the Visual Effects tab, unless already shown.
6. Untick and then re-tick the "Show translucent selection rectangle" box.
7. And without a restart your color should be back.

**Comment by alex-enginity** [comment] 2024-04-05 19:43
Your reply is not addresing the issue. Even though this is part of the functionality of windows that some stupid jerk decided to just leave there so nobody can disable it, ExplorerPatcher is injecting the underlaying white box on top of the first icon even if you NEVER open the start menu with the keyboard. This is clearly a bug.

Ways to reproduce it:

    set the Start Menu to Windows 11
    click the Start menu several times with your mouse and then click on something else
    Next time you try to open the start menu WITH THE MOUSE the start menu will appear with the first icon highlighted.

Ways to reproduce this on standard W11

    click on the start menu
    press TAB key
    the first icon will be highlighted.

This is a bug because ExplorerPatcher seems to be ASSUMING that I'm pressing TAB when I press the start menu with the mouse, which is clearly unintended.

For me, this renders the whole program unusable, please fix this.

**Comment by pyrates999** [comment] 2024-04-06 06:44
Please do not post the same message on duplicate issues.  Posting it on the original issue that is still open will suffice.
