### ISSUE TITLE
systray gone after windows 11 cumulative update 

### ISSUE THREAD

**Issue by azubkov** [valinet/ExplorerPatcher#3480] opened 2024-07-15 09:48 UTC
hello 
after win 11 updates + restart no tray icons are available. 
Updated ExplorerPatch to latest - no help. 
Pls see pics. 
Thx! 
![image](https://github.com/user-attachments/assets/f924a571-db32-4b1d-9517-1e1c94e0ed87)
![image](https://github.com/user-attachments/assets/00eeaaa2-6e7d-46ee-8dc5-de8f2571a5a8)

**Comment by pyrates999** [comment] 2024-07-15 10:35
duplicate of: https://github.com/valinet/ExplorerPatcher/discussions/2363

please close this.

Try updating to the latest pre-release if you want the windows 10 taskbar still.  Not sure if it has the system tray implemented, and there is a known bug where settings doesn't work: https://github.com/valinet/ExplorerPatcher/issues/3461

**Closed** 2024-07-15 10:38 UTC
