### ISSUE TITLE
try update\install version 22621.1992.56.3

### ISSUE THREAD

**Issue by aharond** [valinet/ExplorerPatcher#1922] opened 2023-08-24 10:18 UTC
hello
i tried update the latest version on my win 11 with version  22621.1992.56.3 and my task iexplore loop restart.
try remove and install same behavior's.
currently uninstall it.
![image](https://github.com/valinet/ExplorerPatcher/assets/23188419/023633a1-355d-4963-8626-569ae09ccced)

please provide solution

**Comment by Jim7760** [comment] 2023-08-24 11:12
Same problem here as well with Explorer Patcher version 22621.1992.56.3
Windows 11 version 22H2 build 22621.2134
Opening either the Recycle Bin or File Explorer causes crash and restart.

**Comment by pyrates999** [comment] 2023-08-24 11:32
That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by kvanbiesen** [comment] 2023-08-24 12:27
> That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692
> 
> Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.

i have 22621.2215 installed and crashing also fo me. Did not install the preview version of the windows addon

**Comment by CompSciOrBust** [comment] 2023-08-24 12:33
> That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692

@pyrates999 you keep saying this to everyone despite numerous people telling you that they are not on a preview update. At any point while writing a response to the 21+ issues that you have commented have you considered that your information may be incorrect?
![image](https://github.com/valinet/ExplorerPatcher/assets/54033033/c4750fb7-cf8f-49c5-a7ae-020ca6dd47b5)

**Comment by Poopooracoocoo** [comment] 2023-08-24 12:56
Duplicate of #1798

**Closed by Poopooracoocoo** 2023-08-24 12:56 UTC

**Comment by pyrates999** [comment] 2023-08-24 14:11
> > That is a preview update: https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692
> 
> @pyrates999 you keep saying this to everyone despite numerous people telling you that they are not on a preview update. At any point while writing a response to the 21+ issues that you have commented have you considered that your information may be incorrect? ![image](https://user-images.githubusercontent.com/54033033/262972791-c4750fb7-cf8f-49c5-a7ae-020ca6dd47b5.png)

My evidence that it is a preview update is because Microsoft calls it a preview update.

**Comment by CompSciOrBust** [comment] 2023-08-24 15:07
> My evidence that it is a preview update is because Microsoft calls it a preview update.

They may call it a preview update but it is clearly being rolled out to users who are not subscribed to the preview branch

**Comment by pyrates999** [comment] 2023-08-24 15:13
Everyone is offered "preview" updates.  But unless you enable the option in the settings app named "Get the latest updates as soon as available", they are not automatically installed.  You only get the prompt to download and install them.

Only regular updates are still automatically installed.

**Comment by kvanbiesen** [comment] 2023-08-24 15:15
Yup, pyrates is right, it shows it to everyone but it doesnt install them
automatically but most people see update and click it anyways....

**Comment by kvanbiesen** [comment] 2023-08-24 15:20
This is how it looks. 
![image](https://github.com/valinet/ExplorerPatcher/assets/7585853/29d3ef52-4cf4-4ee3-a59e-6c44a7812b5e)

**Comment by pyrates999** [comment] 2023-08-25 14:13
All you gotta do is install it.

**Comment by pyrates999** [comment] 2023-08-25 14:14
All you gotta do is not click on that **download and install** button.  It's not that hard.
