### ISSUE TITLE
"Customize notification area icons" does not save setting (new mail -> envelope)

### ISSUE THREAD

**Issue by kleinerSpinner** [valinet/ExplorerPatcher#2319] opened 2023-10-17 12:03 UTC
After one of the last updates, I noticed that the symbol for "new mail" in the systray (notification area) always vanishes after a few seconds. I checked in File Explorer (ExplorerPatcher), and the setting is "Only notifications". 
I changed it to "Symbol and notifications" and restarted ExplorerPatcher and Windows several times, but it always loses the setting.
This is very annoying, as the "new mail"-symbol is very important in a working environment.

**Comment by pyrates999** [comment] 2023-10-17 22:30
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

**Comment by kleinerSpinner** [comment] 2023-10-18 07:41
Microsoft Windows Version 22H2 (Build 22621.2283)
ExplorerPatcher Version 22621.2361.58.4
Taskbar -> Customize notification area icons -> Microsoft Outlook, You have new unread mail (the German equivalent) -> from "Notifications only" to "Symbol and notifications"
Setting is not saved.

**Comment by pyrates999** [comment] 2023-10-18 09:56
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.

**Closed** 2023-10-18 10:54 UTC
