### ISSUE TITLE
Windows/Desktop switching no longer working

### ISSUE THREAD

**Issue by Sayoung1984** [valinet/ExplorerPatcher#1801] opened 2023-08-09 01:35 UTC
ExplorerPather 22621.1922.56.1
Win11 22621.2070 WFEP 1000.22659.1000.0

Alt+Tab not working
Win+Tab not working
Task view button on Taskbar not workinig

**Comment by SiteSplat** [comment] 2023-08-09 02:23
Works fine for me.
Pretty sure that is because you have installed the preview update that messed everything up. 
See this post: https://github.com/valinet/ExplorerPatcher/issues/1788#issuecomment-1666792334

remove that win update preview and you should be ok again.

**Comment by getify** [comment] 2023-08-09 03:36
I was force updated (not some optional preview update that I chose) for windows 11 today (Tue Aug 8), and now all alt+tab and taskview/desktop switching is broken. When I uninstall Explorer Patcher, all those windows features work again. I then reinstalled Explorer Patcher and they broke again.

As far as I can tell, I do not have the windows update that is referenced in that link.

<img width="644" alt="win11-updates" src="https://github.com/valinet/ExplorerPatcher/assets/150330/b1c8c05a-dd14-4564-9260-3d6efe63885e">

**Comment by Sayoung1984** [comment] 2023-08-09 03:43
> preview update

No, not preview update. I've sepcifically put the version number on. 
And yes, same issue as getify, on both desktop PC (NV gpu) /laptop (AMD intergrated GPU)

**Comment by kastoestoramadus** [comment] 2023-08-09 06:59
Win+Tab not working and breaks explorer. Needs restart.
Without using it Alt+Tab works.
I'm using up to date Windows 11, Dell Inspiron 5521.

**Comment by exodus444** [comment] 2023-08-09 10:01
> Win+Tab not working and breaks explorer process. Needs restart. Without using it Alt+Tab works. I'm using up to date Windows 11, Dell Inspiron 5521.

Confirming it

**Comment by rdeforest** [comment] 2023-08-09 14:42
Switching to the Win 11 taskbar and downgrading to Win 10 (suggested on #1802) are not options for me. The _only_ feature I use EP for is moving the task bar to the top of the screen.

**Comment by rdeforest** [comment] 2023-08-10 10:11
> > Switching to the Win 11 taskbar and downgrading to Win 10 (suggested on #1802) are not options for me. The _only_ feature I use EP for is moving the task bar to the top of the screen.
> 
> Try this: https://www.tomshardware.com/how-to/windows-11-taskbar-move-to-top

That method stopped working a long time ago and is how I ended up installing EP.

**Comment by SiteSplat** [comment] 2023-08-10 10:25
Start11 app allows you to move the taskbar if Im nit mistaken... I would
check that out if that's the only option you use...

**Comment by olaviinha** [comment] 2023-08-10 11:57
Confirming that **win+tab** & **alt+tab** no longer work, if `Taskbar style: Windows 10`. Task View (win+tab) doesn't work via taskbar button either.

- ❌ Suggested [Reinstall + reg key removals fix](https://github.com/valinet/ExplorerPatcher/issues/1802#issuecomment-1670989271) for stability issues -> no effect on this problem.
- 🚫 Suggested [switch back to "Windows 11 taskbar"](https://github.com/valinet/ExplorerPatcher/issues/1801#issuecomment-1670704653) — well, this does fix the problem at hand, but as already stated, disables a bunch of other preferences (that I too use EP for).

You can restore alt+tab _functionality_ by changing Window switcher style to `Simple Window Switcher`. No effect on win+tab.

If anybody has a fix after which WIN+TAB works when `Taskbar style: Windows 10`, that would be great.

**Comment by pauljackman2023** [comment] 2023-08-10 14:18
After the windows update on 10/08/23 the windows 10 taskview has stopped working on my PC. It works in windows 11 mode but I cannot have ungrouped windows with labels in windows 11 mode. below is my current windows build info & device info

Edition Windows 11 Home
Version 22H2
Installed on ‎21/‎09/‎2022
OS build 22621.2134
Experience Windows Feature Experience Pack 1000.22659.1000.0

Device name HP-Laptop
Processor AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx 2.30 GHz
Installed RAM 16.0 GB (13.9 GB usable)

System type 64-bit operating system, x64-based processor
Pen and touch Pen and touch support with 10 touch points

**Comment by voomdoon** [comment] 2023-08-11 05:08
new occurrence of https://github.com/valinet/ExplorerPatcher/issues/525

**Comment by keith0305** [comment] 2023-08-12 08:45
Happens to me. Need a fix or workaround asap.

**Comment by pyrates999** [comment] 2023-08-12 10:23
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

**Comment by getify** [comment] 2023-08-12 14:33
This isn't merely a duplicate, because the issue is NOT only for those with insider builds or preview updates. As #1798 also shows, this crash is now affecting those with the latest main windows 11 update release.

**Comment by pyrates999** [comment] 2023-08-13 00:31
It started with a preview update, that was then replaced with a regular update.  So yes, it is a duplicate.

**Comment by Sayoung1984** [comment] 2023-08-13 04:43
Update, I also found the system brightness / audio volume indicator went missing. I seems EP broke some Windows GUI layer.

**Comment by vichaunter** [comment] 2023-08-13 08:09
> The issues were resolved on my Windows 11 after deleting the keys `IsUndockedAssetAvailable` (located at `HKEY_CURRENT_USER\Software\ExplorerPatcher\twinui.pcshell`) and `OSBuild` (located at `HKEY_CURRENT_USER\Software\ExplorerPatcher`). After that, I restarted EP and about 3 minutes later I received a notification of symbols being downloaded. After that, I restarted EP again and had no more problems.

Actually this worked partially, just delete that 2, open the explorer patcher properties, click on restart, and started working properly alt tab, but if you press win+tab then stops working again

**Comment by getify** [comment] 2023-08-13 13:49
> It started with a preview update, that was then replaced with a regular update. So yes, it is a duplicate.

well, the issue you linked to as this being a duplicate of, has not really acknowledged that this is now related to the full release windows update. so anyone who reads that thread and tries to follow advice -- or your dismissal of "don't use preview updates" -- is not getting accurate/relevant/timely information from THAT thread as compared to here.

so unless/until THAT thread has such information added, I will continue to disagree with you this thread is merely a duplicate. THIS THREAD is presently adding more current and relevant information for people who are running across this problem now. it's not really relevant that THAT thread (in its current form) was helpful 2-3 weeks ago for a different (related) problem.

**Comment by pyrates999** [comment] 2023-08-19 09:27
You are not helping by keeping duplicate issues opened.

**Comment by war59312** [comment] 2023-08-22 17:50
Only breaks on me if:

Windows 11 22H2 OS Build 22621.2134 (Aug 2023 updates: KB5029263 )

Taskbar style: Windows 10 (this alone is break volume popup, as in new popup when changing volume now)
Show Task view button enabled
I click on Task View, now alt tab is broken.
If I restart explore this happens all over again. So for now, just not using task view.

**Comment by pyrates999** [comment] 2023-08-23 12:25
> Only breaks on me if:
> 
> Windows 11 22H2 OS Build 22621.2134 (Aug 2023 updates: KB5029263 )
> 
> Taskbar style: Windows 10 (this alone is break volume popup, as in new popup when changing volume now) Show Task view button enabled I click on Task View, now alt tab is broken. Also breaks if I do Windows Key + Tab. If I restart explore this happens all over again. So for now, just not using task view.

The alt+tab and winkey+tab not working has already been reported here: https://github.com/valinet/ExplorerPatcher/issues/1687

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

This needs to be closed.

**Comment by Sayoung1984** [comment] 2023-08-24 06:25
> > Only breaks on me if:
> > Windows 11 22H2 OS Build 22621.2134 (Aug 2023 updates: KB5029263 )
> > Taskbar style: Windows 10 (this alone is break volume popup, as in new popup when changing volume now) Show Task view button enabled I click on Task View, now alt tab is broken. Also breaks if I do Windows Key + Tab. If I restart explore this happens all over again. So for now, just not using task view.
> 
> The alt+tab and winkey+tab not working has already been reported here: #1687
> 
> Work around: set to use windows 11 taskbar instead of windows 10 taskbar.
> 
> This needs to be closed.

Switching to Win10 taskbar is the reason most people using EP on Win11, and now it's having issues. Close the report won't make it be fixed.

**Comment by Alexibad** [comment] 2023-08-24 09:05
Like getify I experience the issue after Windows updates
2023-08 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for x64 (KB5028948)
2023-08 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5029263)
(I also had "2023-08 .NET 6.0.21 Security Update for x64 Client (KB5029688)" at the same time, but getify does not mention this.)

Can confirm the description of olaviinha, espcecially WIN+TAB works except for Windows Switcher Windows 11 style

**Comment by mwdle** [comment] 2023-09-11 17:13
Thank you for reopening, This issue is affecting main branch windows users and should not be closed as it is not a duplicate of other issues posts.

**Comment by Poopooracoocoo** [comment] 2023-09-11 17:33
> Thank you for reopening, This issue is affecting main branch windows users and should not be closed as it is not a duplicate of other issues posts.

Looks like a dupe of #1687 to me :/

**Comment by mwdle** [comment] 2023-09-11 18:10
> Looks like a dupe of #1687 to me :/

Sorry I didnt give #1687 a proper readthrough. This issue definitely seems to be a dupe of #1687, I agree.

**Closed** 2023-09-11 18:36 UTC
