### ISSUE TITLE
language icon disappear

### ISSUE THREAD

**Issue by jw0785** [valinet/ExplorerPatcher#2935] opened 2024-03-03 22:37 UTC
Version 22621.3007.63.2

Windows 11 Pro for Workstations 22635.2915

language icon on the taskbar routinely disappears after certain times switch layout with win+space

![image](https://github.com/valinet/ExplorerPatcher/assets/143842176/e99ec4ab-5ed8-4ec1-b1ea-578ace673ab4)
![image](https://github.com/valinet/ExplorerPatcher/assets/143842176/9d779408-06c3-4792-9662-482d478274d3)
![image](https://github.com/valinet/ExplorerPatcher/assets/143842176/2a57be2d-aee4-42a3-85a9-09e305c664e3)
![image](https://github.com/valinet/ExplorerPatcher/assets/143842176/3e9122d6-8dbc-4af6-8a27-8a15d78a14f8)

**Comment by pyrates999** [comment] 2024-03-03 23:29
Please post windows version and build.  You can find this by running winver.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Amrsatrio** [comment] 2024-03-04 08:52
Please show your list of languages in Windows settings. Also, please describe the steps to reproduce this issue. I have English (US) and Japanese as my languages and I've never experienced this issue. The language switcher button is always visible all the time.

**Comment by Amrsatrio** [comment] 2024-03-09 12:27
Closing because issues on the language switcher are mostly a Windows issue.

**Closed by Amrsatrio** 2024-03-09 12:27 UTC

**Comment by teslasystemsx** [comment] 2024-04-19 01:13
I can confirm the issue. As you said before, the language bar disappears, when using RDP client. But the problem is that it doesn't appears after minimizing or closing RDP client. On standard taskbar it reappears normally, but on EP it's not. You need to regularly use 'restart explorer' to make it visible again.
