### ISSUE TITLE
End Task Button on Taskbar Not Functioning Properly

### ISSUE THREAD

**Issue by RahulPorel** [valinet/ExplorerPatcher#3474] opened 2024-07-13 12:07 UTC
I have encountered an issue where the "End Task" button on the taskbar is not working as expected. When I click the "End Task" button, the targeted application does not close. This issue occurs with all applications except the Settings app, where the "End Task" button works correctly.

Here's the screenshots:

![image](https://github.com/user-attachments/assets/2b44842c-ef51-45d9-adf7-9760175748aa)

![Screenshot (47)](https://github.com/user-attachments/assets/5b91eec1-61a1-4242-8c47-b1a1387a97b1)

**Comment by pyrates999** [comment] 2024-07-13 12:20
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2812

please close this.

**Closed** 2024-07-13 12:29 UTC
