### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by OmarAlbek** [valinet/ExplorerPatcher#1991] opened 2023-09-04 07:34 UTC
after the latest win11 update, it keeps restarting the file explorer until it crashes and asks me to uninstall the program or wait for an update.

**Comment by pyrates999** [comment] 2023-09-04 10:34
I think this is a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1687

Please close this one.

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

**Closed** 2023-09-04 11:52 UTC
