### ISSUE TITLE
Automatically hide taskbar + Top taskbar location

### ISSUE THREAD

**Issue by detektrius** [valinet/ExplorerPatcher#3189] opened 2024-04-27 08:22 UTC
![chrome_cv5wgIOdRQ](https://github.com/valinet/ExplorerPatcher/assets/138068338/e47d467f-d187-41eb-8fbb-7d7fc1646e08)
The program is incorrectly located in full screen mode at top taskbar location with automatically hide
Сorner preference: floating menu - insane
![chrome_Lz5JtUPcQP](https://github.com/valinet/ExplorerPatcher/assets/138068338/c9cf843e-bbb7-4a5d-9041-61bb7d62430b)

**Comment by pyrates999** [comment] 2024-04-27 08:35
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

**Comment by detektrius** [comment] 2024-04-27 08:43
> Please post windows version and build. You can find this by running winver. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.
> 
> Please include any other software you have installed that modifies the UI of windows.

Windows 11 Pro 23h2
![winver_vx8ePYD4dH](https://github.com/valinet/ExplorerPatcher/assets/138068338/36344662-0eec-45f6-b6bf-6c53aa7f8405)
![rundll32_xflau21zwD](https://github.com/valinet/ExplorerPatcher/assets/138068338/2c03f101-2f7f-400f-9867-00313a4a670c)
![rundll32_glGC9CipAv](https://github.com/valinet/ExplorerPatcher/assets/138068338/af357584-ef83-440f-8764-345d1c8467a2)
![rundll32_Sd2lGo9bZ0](https://github.com/valinet/ExplorerPatcher/assets/138068338/4ebf712e-45f5-400d-bca1-e00335a13d3b)

**Comment by detektrius** [comment] 2024-04-27 08:57
Oh, and in fullscreen start, the taskbar can automatically hide and you can't bring it back by hovering the mouse over the top.

**Comment by detektrius** [comment] 2024-04-27 09:00
from programms i have "Niesoft shell" and... all

**Comment by pyrates999** [comment] 2024-04-27 09:02
Uninstall Niesoft Shell, reboot, and then see if it is still happening.

**Comment by detektrius** [comment] 2024-04-27 09:07
> Uninstall Niesoft Shell, reboot, and then see if it is still happening.

Done
Same problem

**Comment by pyrates999** [comment] 2024-04-27 12:25
did reinstalling windows and installing EP again fix it?

**Comment by detektrius** [comment] 2024-04-27 14:50
> did reinstalling windows and installing EP again fix it?

no

**Comment by pyrates999** [comment] 2024-04-27 15:35
Let's try in the EP properties application, go to **About** and click on **Restore default settings**.  Then reboot.

Then reapply your settings in EP properties application.

**Comment by detektrius** [comment] 2024-04-28 06:38
Problem in uninstalled StartAllBack

Now I need to put win11's taskbar on top... But that's another impossible question

**Comment by detektrius** [comment] 2024-04-28 09:23
i don't now how this 
i find only how fix it - 
1. off Automatically hide taskbar
2. restart explorer - optoion
done
Result -
![JjujIk5j9K](https://github.com/valinet/ExplorerPatcher/assets/138068338/900ddb3c-9bff-4333-9238-091c077aa87d)
I'll still be looking for a way to reproduce the glitch.

**Comment by detektrius** [comment] 2024-04-28 13:42
The glitch comes back after every Explorer reboot with "Automatically hide taskbar" enabled

**Comment by Amrsatrio** [comment] 2024-04-29 01:20
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2744

**Closed by Amrsatrio** 2024-04-29 01:20 UTC

**Comment by detektrius** [comment] 2024-04-29 06:14
> Duplicate of #2744
Moron

[Vipin2003] commented [on Feb 7] • > I think it is fixed in latest PR. Please close the Issue

I have 22631.3085 and latest version explorer patcher and I am still reproducing this bug

**Comment by Amrsatrio** [comment] 2024-04-29 09:02
Same issue. Thing is the start menu positioning doesn't respect the taskbar dimensions when autohide is on. I have no plans of fixing this for now but would like the issues list to be clean.

**Comment by detektrius** [comment] 2024-04-29 09:49
> Same issue. Thing is the start menu positioning doesn't respect the taskbar dimensions when autohide is on. I have no plans of fixing this for now but would like the issues list to be clean.

Understand. Good luck
