### ISSUE TITLE
Win+Tab and Alt+Tab issue

### ISSUE THREAD

**Issue by stransh** [valinet/ExplorerPatcher#1687] opened 2023-07-27 00:54 UTC
Win+Tab and Alt+Tab not working after the last update

Using Windows 10 taskbar
Windows 11 22H2
OS Build 22621.2134

**Edit:**
**Workarounds:**
- As a workaround, you can use the Windows 11 taskbar instead but it'll introduce another issue. Right clicking the taskbar will crash Windows Explorer (https://github.com/valinet/ExplorerPatcher/issues/1805). You can work around it by going to ExplorerPatcher's properties, the advanced page and disabling "Do not change the taskbar context menu". You can access ExplorerPatcher's properties from your Start Menu or Windows Search. 
   - If you want to separate taskbar items and show labels, you can use Windhawk, Start11 or StartAllBack (you can disable the custom Start Menus with the latter two)
- If you don't need Task View, you could alternatively use a different alt+tab experience such as Simple Window Switcher. 
- If you still want to use the Windows 10 taskbar and use virtual desktops, you can use [SylphyHornPlus11](https://github.com/hwtnb/SylphyHornPlusWin11) or [VirtualDesktopHelper](https://github.com/dankrusi/WindowsVirtualDesktopHelper) or [VirtualDesktopAccessor](https://github.com/Ciantic/VirtualDesktopAccessor) to use keyboard shortcuts.

**Comment by jamietudor** [comment] 2023-07-27 08:28
Same problem here.

**Comment by pyrates999** [comment] 2023-07-27 10:21
Please post windows version and build.
Please post explorer patcher version.

**Comment by jamietudor** [comment] 2023-07-27 10:23
Windows 22H2 OS Build 22621.2070
ExplorerPatcher 22621.1992.56.1

**Comment by pyrates999** [comment] 2023-07-27 10:24
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

**Comment by jamietudor** [comment] 2023-07-27 10:25
OK. When will explorerpatcher support the updated - after it's released to general?

**Comment by bitroniq** [comment] 2023-07-27 11:05
Latest Win11 Pro + Latest Exploer Patcher

Same issues
1. Task View doesn't work
2. sliders (volume etc) doesn't work
3. Alt+TAB doesn't work (after trying Task View)

**Comment by pyrates999** [comment] 2023-07-27 20:39
> OK. When will explorerpatcher support the update - after it's released to general?

Preview updates will never be supported.

Updates are done in the following way:

1. preview update version of update is released, which has no public symbols to download
2. normal update version of update is then released under a new kb, which will then have public symbols for download.



> Latest Win11 Pro + Latest Exploer Patcher
> 
> OS Version: 10.0.22621 N/A Build 22621
> 
> Same issues
> 
> 1. Task View doesn't work
> 2. sliders (volume etc) doesn't work
> 3. Alt+TAB doesn't work (after trying Task View)

What's the number after 22621?

**Comment by bitroniq** [comment] 2023-07-27 20:51
It's not a preview update!

I only install stable updates

![image](https://github.com/valinet/ExplorerPatcher/assets/1032724/33834137-85e4-4d2b-80d4-f5ba142818fd)

![image](https://github.com/valinet/ExplorerPatcher/assets/1032724/e9d76d62-355e-41a3-8608-f1848a6a00c9)

**Comment by pyrates999** [comment] 2023-07-27 20:52
Microsoft says it is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

**Comment by bitroniq** [comment] 2023-07-27 20:54
Well, somehow in Europe they pushed this to a stable channel. As you can see I don't allow installing/upgrading anything considered as preview/insider/etc.

**Comment by stransh** [comment] 2023-07-28 01:10
Just in any case - in the first post I mentioned EP update not windows one

**Comment by pyrates999** [comment] 2023-07-28 06:33
> Well, somehow in Europe they pushed this to a stable channel. As you can see I don't allow installing/upgrading anything considered as preview/insider/etc.

Check before you install an update then.  Updates are released generally on the second Tuesday of every month.  If an update is released after this, check it before installing to make sure it is not a preview update.

Go here to check that you haven't enabled automatic install of preview updates: https://winaero.com/windows-11-now-allows-you-to-automatically-install-preview-updates/

**Comment by AJPNetworks** [comment] 2023-07-28 09:21
Hello, I'm having this same issue and i dont usually update my pc.  Just updated explorer patcher and this time for me its win+tab thats broken, which i use day to day so this might be an issue.  I can post my current windows build and what not

![image](https://github.com/valinet/ExplorerPatcher/assets/127406648/adf3038d-e76b-45a4-90df-35c5bde220a2)

also for quick reference, the previous builds people are showing in this issue, are not preview builds or otherwise, a non-stable build, as well as mine

![image](https://github.com/valinet/ExplorerPatcher/assets/127406648/d3988777-61c9-4de3-92bc-4b2b8d71485f)

**Comment by AJPNetworks** [comment] 2023-07-28 09:27
Correction, it does appear that the -2070 released 2 days ago, is a preview build, they dont say it is or is not in this last picture i posted, its implying that it is not a preview build, however, I am not on a preview build

**Comment by pyrates999** [comment] 2023-07-28 16:37
Just an FYI. From: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

Symbols are usually NOT made available for the following types of builds:

- builds shipped via the Beta and Release Preview channel of the Windows Insider Program
- "C" and "D" stable OS builds - these are builds labeled as "Preview" and offered via Windows Update in the second part of a month, representative of what will generally arrive on the next Patch Tuesday; these are optional, the user has to explicitly click "Download and install" to have them applied on their computer, they are never automatically installed by Windows Update

If you installed this preview update, you should uninstall it and then try the following:

1. uninstall explorer patcher
2. delete the registry key: "Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher"
3. reboot
4. install the latest explorer patcher
5. verify you get a notification that symbols have been downloaded
6. restart windows explorer using either the task manager or in the properties window of explorer patcher
7. reboot

Then apply your settings again in explorer patcher to see if it fixes it.

**Comment by AJPNetworks** [comment] 2023-07-29 02:34
Like I said earlier, I am not on preview build and I never am on one, I verified and showed you.  Is this issue getting worked on?  This is not a preview build issue.

**Comment by jamietudor** [comment] 2023-07-30 08:08
I don't personally like uninstalling Windows cumulative updates as I don't trust the effect on long-term stability. 

So if I just wait for the next cumulative update to install around patch Tuesday, 8th August, presumably it'll start working again after that?

**Comment by AJPNetworks** [comment] 2023-07-30 14:06
> I don't personally like uninstalling Windows cumulative updates as I don't trust the effect on long-term stability.
> 
> So if I just wait for the next cumulative update to install around patch Tuesday, 8th August, presumably it'll start working again after that?

Honestly, maybe..Im on a stable update that worked with the previous ExplorerPatcher update, but updating only the patcher broke it.  I cant move windows from desktop to desktop now, killing my productivity.  And no, i too dont like uninstalling updates, except for this explorerpatcher one, might have to uninstall it

**Comment by BraINstinct0** [comment] 2023-07-30 15:14
FYI: the alt-tab works, but whenever win-tab is applied, alt-tab will stop working too.

**Comment by AJPNetworks** [comment] 2023-07-31 14:42
For those of you with this issue..i found that doing the uninstall and reinstalling the [22621.1555.55.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.1_a95a688) version works.  Keep in mind I am on 22621.1992 and this is not a guaranteed work for the latest release, just what I found works for me as a stall on windows updates.

**Comment by SESNut** [comment] 2023-08-01 08:10
i uninstalled both the preview update and went to [22621.1555.55.1](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1555.55.1_a95a688) and it would still stop working if i used task view. I just set it to windows 10 task switcher for now so I could at least have something that works.

**Comment by pyrates999** [comment] 2023-08-01 10:18
Insider builds and preview updates are not supported due to debug symbols not being available to download, and explorer patcher requires them to function.

So check if symbols were downloaded: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

You can check using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  If it shows it can't download symbols, your version of windows is not supported.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by jamietudor** [comment] 2023-08-09 14:44
Looks like the same bug is affecting the mainstream release. I've removed EP and the reg key and re-installed: the problem remains.

**Comment by spersad** [comment] 2023-08-14 05:29
Anythoughts on how to fix this? I am having the same problem. Even re-insalled Win11 again but that did not work. I am not able to remove the 22H2 version at all. Thank you.

**Comment by pyrates999** [comment] 2023-08-14 06:42
Unfortunately, you need to wait until it is fixed in explorer patcher.

**Comment by spersad** [comment] 2023-08-14 15:56
> 

Thanks for getting back to me. @valinet sorry to bother you but do you have a sense of when this may be fixed? I have become super dependent on your cool tool. :)

Thank you.

**Comment by averagejooe** [comment] 2023-08-15 15:56
Heya I also found win tab is broken and if it is pressed in any way it will break alt tab. Hope it could be fixed. I am using Win 11 22H2 (Build 22621.2134) Idk if this is preview or not, I literaly just upgraded to win11 some days ago and I don't recall manually updating it.

**Comment by malmkgithub** [comment] 2023-08-16 00:39
Same here OS:22621.2134 (pretty sure this is an official window update, not a preview one)
Patcher version: 22621.1992.56.1

Alt+tab is fine in normal usage but when you press win+tab, it won't do anything then alt+tab will also do nth.
You must restart window Explorer to fix alt+tab(make it usable), but win+tab will crash it again. So for now, don't use win+tab until it is fixed.

**Comment by brian6932** [comment] 2023-08-16 09:42
Win + N doesn't open notifs anymore either

**Comment by kwinz** [comment] 2023-08-17 05:45
```Microsoft Windows [Version 10.0.22621.2134]
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2022-‎10-‎20
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0```

with latest ExplorerPatcher.

Win+Tab is broken, as is Alt+Tab.
Setting `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer` AltTabSettings to DWORD:1 at least brings the legacy Windows NT Tab Switcher back. But I still can't switch between desktops.

So basically with the current situation I can either not switch between multiple desktops. Or I uninstall ExplorerPatcher and have Windows force me to group all open Chrome browser Windows into one single icon. Either is painful. I hope this gets fixed soon.

**Comment by Diablo-D3** [comment] 2023-08-18 10:44
I can confirm this bug exists.

Windows 11 221H2 22621.2134
EP 22621.1992.56.1

**Comment by Ralfviii** [comment] 2023-08-18 11:34
Same here: 
Win 11: 10.0.22621 Build 22621
EP:  22621.1992.56.1

**Comment by zwassall-globus** [comment] 2023-08-18 22:42
I ran into this issue. Didn't opt in to any update previews.

I managed to successfully restore functionality by uninstalling the pair of Windows updates that had just been installed:

1. KB5028948
2. KB5029263

These are the 3rd and 5th updates pictured below:

![capture_2023-08-18_18-16-21](https://github.com/valinet/ExplorerPatcher/assets/106610128/42ec1a47-6877-43b2-ba01-8d7f0c020790)

I didn't check what OS build I was on before uninstalling these updates, but I'm guessing it was 22621.2134, like many others having the issue have reported. After uninstalling these two updates, I'm back down to OS build 22621.1992, which lines up with EP version 22621.1992.56.1.

It's not ideal from a security standpoint to run an outdated OS build, but assuming it'll only be for a short while until this issue is resolved, it's worth it to me to keep my EP tweaks.

**Comment by martwenty** [comment] 2023-08-19 15:06
Some issue here. I am quite sure about the cause. I installed yesterday night two last updates KB5029263, KB502894 and then after the restart the problem came out.
Coming back to W11 taskbar style alt+tab and MS+tab started to work again (but I miss never combine icon on taskbar).
But after opening EP few times from the right click + properties on the taskbar, now EP is crashing after every right click on the taskbar. I've just remove and install again EP but it presents same crash issue. win and desktop switching are working.

build 22621.2134
EP 22621.1992.56.1

@kwinz About "never combine icon" you can use StartAllBack , free for 100 days.

**Comment by AdasOsorus** [comment] 2023-08-20 12:45
Follow-up of :https://github.com/valinet/ExplorerPatcher/issues/1868
This morning, I reinstall ExplorerParcher and VirtualDesktop work correctly.
The only thing I did, 
1) reboot before installing ExplorerParcher 
2) Customize my 3 virtual desktop bakground with a different image and set in "fit mode"; I know there is no link between ExplorerParcher and this action, but it can trigger something for the programmer.
so there is my configs:
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/b78b44f9-4e8f-447e-8c3f-9ad8eebfee1c)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/c71ff346-ad95-48a7-a886-ad36644108bb)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/a26b2d93-6121-4b38-a68c-7691ca0b424b)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/561315ea-f1db-442a-a961-0ee1bbb1f393)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/1aee67ed-1923-47f3-a10c-0e9f178bcb2f)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/2bdd8be1-2ab0-4da9-a688-5a141ba09060)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/a9b0c592-47b2-4598-8139-f41a25d35e52)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/1e3f8b4d-44cc-4003-a217-b794a41664e2)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/0fd6763e-5845-40e1-beee-163a6ad2cef5)
![image](https://github.com/valinet/ExplorerPatcher/assets/41906277/aded05e1-cb20-454d-8976-8ab5d08dc301)

**Comment by pyrates999** [comment] 2023-08-20 22:01
> Some issue here. I am quite sure about the cause. I installed yesterday night two last updates KB5029263, KB502894 and then after the restart the problem came out. Coming back to W11 taskbar style alt+tab and MS+tab started to work again (but I miss never combine icon on taskbar). But after opening EP few times from the right click + properties on the taskbar, now EP is crashing after every right click on the taskbar. I've just remove and install again EP but it presents same crash issue. win and desktop switching are working.
> 
> build 22621.2134 EP 22621.1992.56.1
> 
> @kwinz About "never combine icon" you can use StartAllBack , free for 100 days.

That crash was mentioned here: https://github.com/valinet/ExplorerPatcher/issues/1828

**Comment by christophe-glanum** [comment] 2023-08-21 12:59
Same here : the alt-tab works, but whenever win-tab is applied, alt-tab will stop working too.

And the win-tab doesn't work !

Windows 11 : 22H2 22621.2134
EP : 22621.1992.56.1

**Comment by edludke** [comment] 2023-08-21 13:49
Hi, rolling back the windows patch was not an issue on my personal laptop but it has now hit my corporate managed one which won't allow me to roll back OS patches. I hope this is a top priority issue. I'd hate to go back to Windows crap, crippled explorer behavior - but I _heavily_ depend upon the multi-desktop feature and the ability to move windows between them. Please, please, please make this a top priority. And know that your work on this excellent project is _very_ much appreciated. M$ should buy your code for big bucks and fire whoever made the decision to nerf explorer and the start bar.

**Comment by pyrates999** [comment] 2023-08-22 12:14
> Hi, rolling back the windows patch was not an issue on my personal laptop but it has now hit my corporate managed one which won't allow me to roll back OS patches. I hope this is a top priority issue. I'd hate to go back to Windows crap, crippled explorer behavior - but I _heavily_ depend upon the multi-desktop feature and the ability to move windows between them. Please, please, please make this a top priority. And know that your work on this excellent project is _very_ much appreciated. M$ should buy your code for big bucks and fire whoever made the decision to nerf explorer and the start bar.

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

**Comment by pyrates999** [comment] 2023-08-22 12:53
> > I ran into this issue. Didn't opt in to any update previews.
> > I managed to successfully restore functionality by uninstalling the pair of Windows updates that had just been installed:
> > ```
> > 1. KB5028948
> > 
> > 2. KB5029263
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These are the 3rd and 5th updates pictured below:
> > ![capture_2023-08-18_18-16-21](https://user-images.githubusercontent.com/106610128/261723678-42ec1a47-6877-43b2-ba01-8d7f0c020790.png)
> > I didn't check what OS build I was on before uninstalling these updates, but I'm guessing it was 22621.2134, like many others having the issue have reported. After uninstalling these two updates, I'm back down to OS build 22621.1992, which lines up with EP version 22621.1992.56.1.
> > It's not ideal from a security standpoint to run an outdated OS build, but assuming it'll only be for a short while until this issue is resolved, it's worth it to me to keep my EP tweaks.
> 
> The problem started because of these updates, but after uninstalling them it didn't fix for me, now windows + tab just crashes explorer instead of doing nothing sadly
> 
> Edit: Restarting explorer was not working, but I just relaunched the installer after this and it fixed everything.

Work around: set to use windows 11 taskbar instead of windows 10 taskbar.

**Comment by AdasOsorus** [comment] 2023-08-22 14:27
While waiting for the resolution with ExplorerPatcher, this is the Temporary Workaround I made:
__1) Uninstall ExplorerPatcher
__2) Use https://www.startallback.com/
[This is not a publicity for another tool...just the Workarround I'm using while waiting for ExplorerPatcher's TaskBar Win-10 function to work again].

Thank you to all ExplorerPatcher programmers... you do a great job!
Mystic

**Comment by Toudahl** [comment] 2023-08-23 12:55
The issue also affects the following versions
OS Build: 22621.2134
ExplorerPatcher version: 22621.1992.56.2

[This is not a preview build](https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8)

**Comment by dmitrybarabash** [comment] 2023-08-23 13:47
> The issue also affects the following versions OS Build: 22621.2134 ExplorerPatcher version: 22621.1992.56.2

All the same.

**Comment by grimmute** [comment] 2023-08-23 15:39
Still reproducible on EP 22621.1992.56.3.

**Comment by dmitrybarabash** [comment] 2023-08-24 11:28
> Still reproducible on EP 22621.1992.56.3.

I can confirm.

**Comment by pyrates999** [comment] 2023-08-24 11:36
> The issue also affects the following versions OS Build: 22621.2134 ExplorerPatcher version: 22621.1992.56.2
> 
> @pyrates999 - [22621.2134 is not a preview build](https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8)

I never said it was.

**Comment by Toudahl** [comment] 2023-08-24 11:38
> > The issue also affects the following versions OS Build: 22621.2134 ExplorerPatcher version: 22621.1992.56.2
> > @pyrates999 - [22621.2134 is not a preview build](https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8)
> 
> I never said it was.

No, but you have been very focused on the topic - so I checked, so you didn't have to.

**Comment by getify** [comment] 2023-08-24 14:49
@Poopooracoocoo please go through and hide (mark as off-topic, whatever) any of the earlier messages near the top of this thread that indicate that this issue is related to the preview windows update (as it was originally), especially those which wrongly indicate that the "solution" is just to not use preview updates. *That* information is misleading *now*, as this thread is currently being used/referred to.

Since there was an insistence (despite objections from some of us) to close that other issue as a duplicate of this one, then THIS one needs to make it clear when people show up -- not just when they read down thread 75+ messages! -- that the issue is affecting the main windows update release AND that it's affecting the latest build of EP.

**Comment by codeBodger** [comment] 2023-08-26 01:23
If someone knows what part of the code deals with keyboard shortcuts, I'd be happy to take a look.  It would seem to me (though this might change after looking at the code) that the easiest solution is to simply allow the standard Windows 11 Task View to open upon win+tab.

**Comment by melMass** [comment] 2023-08-26 20:01
I just found a fix for this to keep the Windows 10 Taskbar! 

You need to change the `Window Switcher` to Windows 10 and restart the explorer:

<p align=center>
<img width=450 src="https://github.com/valinet/ExplorerPatcher/assets/7041726/88214a03-9339-49e5-bf04-7e944c3e0242"/>
</p>

**Comment by ducanh-le** [comment] 2023-08-26 21:41
> 

Nope. Tested and win-tab still not working for me. Nothing change.

**Comment by ducanh-le** [comment] 2023-08-26 21:42
> I just found a fix for this to keep the Windows 10 Taskbar!
> 
> You need to change the `Window Switcher` to Windows 10 and restart the explorer:
> 
> <img alt="" width="450" src="https://user-images.githubusercontent.com/7041726/263495138-88214a03-9339-49e5-bf04-7e944c3e0242.png">

Nope. Tested and win-tab still not working for me. Nothing change.

**Comment by melMass** [comment] 2023-08-26 22:47
> Nope. Tested and win-tab still not working for me. Nothing change.

Yep my bad, explorer crashes on win + tab, I only use alt tab personally but just hit it by mistake and it crashed, so I retried a few times to confirm it and it crashes each time.

As I just need to change the position of the taskbar I'm using the suggestion from earlier in the issue, I like it:
> __2) Use [startallback.com](https://www.startallback.com/)

**Comment by getify** [comment] 2023-08-27 04:55
Thanks for making it easy for me to decide to uninstall and not use this software anymore. With such poor issue triage/governance and people handling, I definitely want nothing more from this project to ever touch my computer. I look forward to this comment itself being marked "off topic" as well, so that you can hide how terribly you handle people (like me) who are just trying to help to make this make sense to those who show up and are as confused as I was. That's certainly a great way to encourage good will from the community.

**Comment by Poopooracoocoo** [comment] 2023-08-27 05:34
... I did what you asked and hid the off-topic, outdated and resolved messages 😭 the issue itself has the key information. Good thing this software is free. I just wanted to try and cut down on the issues to help the maintainer. I completely understand why he, and many other open source maintainers, get frustrated. I don't get what I did wrong. I did exactly as you asked of me.

**Comment by Toudahl** [comment] 2023-08-27 07:03
> ... I did what you asked and hid the off-topic, outdated and resolved messages 😭 the issue itself has the key information. Good thing this software is free. I just wanted to try and cut down on the duplicate issues to help the maintainer. I completely understand why he, and many other open source maintainers, get frustrated. I don't get what I did wrong with this issue. I did exactly as you asked of me. Ideally this issue would have been closed back when it was a preview update but I don't always have much motivation/time to keep up with triaging issues in this repo. I know I've made many mistakes but I've tried to amend them. And as for other issues, I'm trying my best.

Well, *his* comment was *obviously* not off topic. Only all the others.

/s

**Comment by getify** [comment] 2023-08-27 07:29
@Poopooracoocoo it appeared that the *opposite* had happened: that *my* comment asking for improved triaging was hidden, and yet it seemed that the earlier messages I felt *should* have been hidden were not. I jumped to conclusions assuming this was a (rather rude) rejection of my request, and it seems I was completely wrong in that interpretation. I apologize for overreacting and for adding to the noise here.

**Comment by Arecsu** [comment] 2023-08-28 11:48
> > Work around: set to use windows 11 taskbar instead of windows 10 taskbar.
> 
> Yeah, but… having to switch back and forth between the two taskbar styles just to be able to press Win+Tab is quite cumbersome (I'd rather go back to Windows 10 than start using Win11's taskbar in its current state).
> 
> (workaround: avoid Win+Tab whenever possible, use Ctrl+Win+Left/Right to switch between desktops)

Hmmm somehow of a half workaround. While it does switch desktops faster, it's not possible to move windows between desktops 😞

**Comment by Diablo-D3** [comment] 2023-08-28 21:12
It also isn't possible to "show window on all desktops" without the win-tab task switcher.

In some ways, Windows is an incomplete experience due to lack of so many shortcuts.

**Comment by Poopooracoocoo** [comment] 2023-08-29 00:09
> It also isn't possible to "show window on all desktops" without the win-tab task switcher.
> 
> In some ways, Windows is an incomplete experience due to lack of so many shortcuts.

[SylphyHornPlus11]( https://github.com/hwtnb/SylphyHornPlusWin11) could help you there

**Comment by SenrirenTokyo** [comment] 2023-08-29 04:10
Same issue here, latest build of Windows 11, freshly installed from Win 10. Setting taskbar style to windows 11 fixed it, but i vastly prefer the windows 10 one! i hope this (amazing btw) program gets updated soon.
and btw m8, thank you for your hard work. this is an amazing, amazing program you have put together and i love it.

**Comment by AnityEx** [comment] 2023-08-30 01:28
i hope it gets fixed! im also having this issue!

**Comment by roflcopter4** [comment] 2023-08-30 04:03
I've spent like 12 hours staring at this codebase and all I can conclude is **[REDACTED - TOO RUDE]**. I've fixed it to compile under clang, but not actually gotten anywhere near this problem. The code is nigh unreadable.

**Comment by dmitrybarabash** [comment] 2023-08-30 07:03
Guys who contribute to this project, just say please that you are looking for a solution. I do love EP but Windows is almost impossible to use without Alt+Tab, Win+Tab, Win+A and Win+N.

**Comment by ericralph** [comment] 2023-08-30 20:50
While we wait for an EP fix, I just found a truly usable workaround thanks to someone mentioning another third-party app! If you install [SylphyHornPlusWin11](https://github.com/hwtnb/SylphyHornPlusWin11) in addition to EP, you'll be able to use customizable keyboard shortcuts to move windows between desktops even while EP's Windows 10 taskbar is enabled. AFAIK, task view is still broken; but you can at least create, reorder, and rename desktops in Sylphy's settings.

**Comment by r-rikka** [comment] 2023-08-31 08:54
Thank you for your support.
I have confirmed that Win+Tab is not working.
Alt+Tab is working when select the simple window switcher.

I am patiently waiting for the issue to be solved. EP is very nice tool ! 
thanks !

**Comment by Ashtonio** [comment] 2023-09-03 00:36
Pretty much the same with me, Alt+Tab not working and the little notification bars not showing (volume at the top right for example). Below is what I'm on if that helps? 

On OS Build 22621.2215
Explorer Patcher: 22621.1992.56.3

**Comment by SenrirenTokyo** [comment] 2023-09-03 00:52
I solved it by downgrading back to Windows 10 because Windows 11 is utterly horrid.

**Comment by BraINstinct0** [comment] 2023-09-04 00:39
https://github.com/valinet/ExplorerPatcher/issues/1687#issuecomment-1657198102
In addition to the above,

1. Alt-tab works
2. Win-tab does not
3. After a failed Win-tab, Alt-tab will also not work
4. In case of situation 3, Restart explorer -- After that, alt-tab will work again.

Not a solution, but for those stuck in Win11+EP, this is the workaround I found always working.

**Comment by VarunAgw** [comment] 2023-09-05 11:22
Free workaround: https://www.ntwind.com/software/alttabter.html

**Comment by daviddgz** [comment] 2023-09-08 11:15
Just came here to report the same issue:

> 1. Alt-tab works
> 2. Win-tab does not
> 3. After a failed Win-tab, Alt-tab will also not work
> 4. In case of situation 3, Restart explorer -- After that, alt-tab will work again.

This started to happen yesterday after KB4023057 has installed:

Win 11 pro 22621.2215 - no preview updates are being installed.
EP 22621.2993.56.3

I've tried:

1. Reinstalling and clearing 
```
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ExplorerPatcher
Computer\HKEY_CURRENT_USER\Software\ExplorerPatcher

```
2. Disabling feature ID 26008830 with 

`ViVeTool.exe /disable /id:26008830`

Nothing worked. I use the task view and VDs quite often so I think I will unistall EP for now and keep an eye on this thread for a fix.

**Comment by mpawelski** [comment] 2023-09-11 08:44
> [#1687 (comment)](https://github.com/valinet/ExplorerPatcher/issues/1687#issuecomment-1657198102) In addition to the above,
> 
>     1. Alt-tab works
> 
>     2. Win-tab does not
> 
>     3. After a failed Win-tab, Alt-tab will also not work
> 
>     4. In case of situation 3, Restart explorer -- After that, alt-tab will work again.
> 
> 
> Not a solution, but for those stuck in Win11+EP, this is the workaround I found always working.

Same behavior for me. Also when I click "Task View" icon it also breaks Alt-tab (just like Win-Tab) and I have to restart ExplorerPatcher.

OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22621 Build 22621

**Comment by Amrsatrio** [comment] 2023-09-17 04:58
@daviddgz They removed "26008830" aka "STTest" in 22621.2134. It is what EP uses to workaround this issue in 22621.1413, therefore this among other issues like volume popup not showing and Windows 11 flyouts overlapping the Windows 10 taskbar, happened again.

I'm afraid to say that a moderate amount of effort is needed to properly and completely fix this on 22621.2134+.

**Comment by hakan-demirli** [comment] 2023-09-17 11:51
@Amrsatrio StartIsBack and other commercial tools still function correctly. I assume someone can just find the correct calls by examining those commercial apps under IDA Pro or x84dbg ?

**Comment by felikjunvianto** [comment] 2023-09-17 16:07
I was thinking to rollback first to last known version that has both functionality works. Does anyone have a record of that?

**Comment by PyroZorion** [comment] 2023-09-17 20:44
> While waiting for the resolution with ExplorerPatcher, this is the Temporary Workaround I made: __1) Uninstall ExplorerPatcher __2) Use https://www.startallback.com/ [This is not a publicity for another tool...just the Workarround I'm using while waiting for ExplorerPatcher's TaskBar Win-10 function to work again].
> 
> Thank you to all ExplorerPatcher programmers... you do a great job! Mystic

But Startallback is with paid.

**Comment by pyrates999** [comment] 2023-09-17 23:36
> > While waiting for the resolution with ExplorerPatcher, this is the Temporary Workaround I made: __1) Uninstall ExplorerPatcher __2) Use https://www.startallback.com/ [This is not a publicity for another tool...just the Workarround I'm using while waiting for ExplorerPatcher's TaskBar Win-10 function to work again].
> > Thank you to all ExplorerPatcher programmers... you do a great job! Mystic
> 
> But Startallback is with paid.

Yes, not all software is free.

**Comment by Diablo-D3** [comment] 2023-09-18 01:02
> > > While waiting for the resolution with ExplorerPatcher, this is the Temporary Workaround I made: __1) Uninstall ExplorerPatcher __2) Use https://www.startallback.com/ [This is not a publicity for another tool...just the Workarround I'm using while waiting for ExplorerPatcher's TaskBar Win-10 function to work again].
> > > Thank you to all ExplorerPatcher programmers... you do a great job! Mystic
> > 
> > 
> > But Startallback is with paid.
> 
> Yes, not all software is free.

The ultimate bug.

**Comment by PyroZorion** [comment] 2023-09-18 14:21
> > > While waiting for the resolution with ExplorerPatcher, this is the Temporary Workaround I made: __1) Uninstall ExplorerPatcher __2) Use https://www.startallback.com/ [This is not a publicity for another tool...just the Workarround I'm using while waiting for ExplorerPatcher's TaskBar Win-10 function to work again].
> > > Thank you to all ExplorerPatcher programmers... you do a great job! Mystic
> > 
> > 
> > But Startallback is with paid.
> 
> Yes, not all software is free.

I know, I said it because a payment program does not seem an alternative comparable to a free program.

**Comment by Amrsatrio** [comment] 2023-09-18 14:27
@hakan-demirli I found the functions related to the placement bug, myself. Also figured out way to patch them in order to fix the placements. Might gonna push a PR if it works flawlessly on both 1992 and 2283.

**Comment by hakan-demirli** [comment] 2023-09-18 19:01
@Amrsatrio  
I uploaded it to different platforms in case some goes down:

**File.io:**
https://file.io/wEUuvRGn6X0F

**Github:** (change the extension pdf->dll. really github 🙄?)
[twinui.pcshell.pdf](https://github.com/valinet/ExplorerPatcher/files/12652291/twinui.pcshell.pdf)

**Anonym:**
https://anonymfile.com/o46l/twinuipcshell.dll

I hope sharing a windows dll for 'educational' purposes won't violate github TOS.

**Comment by pyrates999** [comment] 2023-09-19 11:37
> > > > While waiting for the resolution with ExplorerPatcher, this is the Temporary Workaround I made: __1) Uninstall ExplorerPatcher __2) Use https://www.startallback.com/ [This is not a publicity for another tool...just the Workarround I'm using while waiting for ExplorerPatcher's TaskBar Win-10 function to work again].
> > > > Thank you to all ExplorerPatcher programmers... you do a great job! Mystic
> > > 
> > > 
> > > But Startallback is with paid.
> > 
> > 
> > Yes, not all software is free.
> 
> I know, I said it because a payment program does not seem an alternative comparable to a free program.

Then perhaps EP should also be a paid program.

**Comment by Amrsatrio** [comment] 2023-09-19 18:54
@hakan-demirli https://github.com/valinet/ExplorerPatcher/pull/2097

**Comment by wb7664** [comment] 2023-09-20 16:44
> [#1687 (comment)](https://github.com/valinet/ExplorerPatcher/issues/1687#issuecomment-1657198102) In addition to the above,
> 
> 1. Alt-tab works
> 2. Win-tab does not
> 3. After a failed Win-tab, Alt-tab will also not work
> 4. In case of situation 3, Restart explorer -- After that, alt-tab will work again.
> 
> Not a solution, but for those stuck in Win11+EP, this is the workaround I found always working.

Also, clicking the Task View button fails and has effect of a failed Win-tab attempt.

**Comment by Diablo-D3** [comment] 2023-09-21 15:23
They haven't announced the return of the small taskbar, even though they did say it'd be back in time for the next Win11 version.

For all their convincing that the new taskbar was just a normal conventional WinUI3 program, a lot of _absolutely no real work_ is happening on it.

**Comment by Amrsatrio** [comment] 2023-09-22 11:00
Sorry for being off topic but, is there a Discord or something which we can use to communicate about stuff related to EP in real time without pinging everyone involved in the issue?

**Comment by valinet** [comment] 2023-09-22 19:54
> Sorry for being off topic but, is there a Discord or something which we can use to communicate about stuff related to EP in real time without pinging everyone involved in the issue?
> 
> Anyways, I've built a release of my fork with the fixes. Those who can't wait till Valinet accepts my PR may download my automatically built releases [here](https://github.com/Amrsatrio/ExplorerPatcher/releases) and let me know of any issues. The issues mentioned in this thread except Win11 taskbar right click crashing should be fixed properly with my build.

Hi

I just now had time to take a look - as you hinted to, the multitude of emails I receive make it hard to discern useful stuff from less useful stuff, so to say. For the past few days, I haven't really looked, unfortunately, so I missed them and only caught up with it now, sorry.

The commits look REALLY promising, even more, they look AWESOME! THANK YOU very much, the patches look great and are a great contribution for which I would like to express my direct, honest and kindest gratitude. Thank you.

If you're interested, I'd very much enjoy to add you as a maintainer for this project, so you can make contributions directly on `master`. Let me know if you fancy that. It seems to me that your help could be very useful for this project and the community, and that can only bring me joy, so I salute that.

Regarding Discord, if you think it would be useful and want to maintain such channel, I have nothing against an 'official' channel like that which I could advertise in the README on the main page of the project, as yet another way to engage with the community.

I will finish looking through the commits shortly and will merge them with the my branch and push an updated version.

Thanks again

**Comment by valinet** [comment] 2023-09-23 01:01
I have merged the changes into `master`, thanks again.

**Comment by Amrsatrio** [comment] 2023-09-23 01:06
Thank you so much Valinet for finally looking at my stuff! And yes, I made them awesome so that others (who know how to reverse x86-64 programs) can understand what's going on so they can potentially update them on their own.

Of course, an access to `master` would be very appreciated since, as an avid EP user from 22000 days (and a Win11 taskbar hater no matter what they added into it), I will assure you that I can make quick changes to the fixes that I know how they work.

And about Discord, I'll have a second chance at thinking about creating that because I'm also limited in time but, being able to use Win11 with Win10 taskbar is my top priority.

**Closed** 2023-09-23 01:25 UTC

**Comment by Amrsatrio** [comment] 2023-09-25 18:25
Should **major** aka **reaking** issues like this happen again, or just want to vibe together, here's a new Discord where you can report them on and expect an instant response (I hope): https://discord.gg/gsPcfqHTD2 ♥️

**Comment by klodoma** [comment] 2023-10-31 15:20
Thank you for fixing this!!!!
