### ISSUE TITLE
Top Location taskbar

### ISSUE THREAD

**Issue by Gordinkski** [valinet/ExplorerPatcher#3619] opened 2024-08-31 09:17 UTC
When taskbar is located at the top, right click flyouts are not showing. They seem to be displaying upwards. Other positions for Taskbar are fine. 
I have Windows 11 23H2 build 22631.4112 and ExplorerPatcher version 22621.3880.66.4.

**Comment by Amrsatrio** [comment] 2024-08-31 10:00
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3615

**Closed by Amrsatrio** 2024-08-31 10:00 UTC

**Comment by Gordinkski** [comment] 2024-08-31 14:11
I have tried everything suggested to correct this without success. please note that I am using the latest available release of ExplorerPatcher

**Comment by Amrsatrio** [comment] 2024-08-31 14:13
@Gordinkski 22631.4112 changed something in the jump lists, breaking the patches to fix it. Don't worry. I am working on it right now.
![image](https://github.com/user-attachments/assets/b4f21f98-bb5d-4c57-912b-f21fa4570672)

**Comment by Gordinkski** [comment] 2024-08-31 14:26
Many thanks..
