### ISSUE TITLE
Windows shrink to top 1/4 of screen upon waking monitor

### ISSUE THREAD

**Issue by vulcan78** [valinet/ExplorerPatcher#3272] opened 2024-05-13 18:10 UTC
If I put my monitor to sleep or if it goes to sleep per the sleep timer in the power plan when I wake the monitor all of the open windows are squished into the top 1/4 of the screen with the only remedy being to restart File Explorer / Explorer Patcher. I have a 32:9 panel, not sure if this is a culprit, 7680x2160. 

Windows 23H2 22631.3447

I just installed the latest version of Explorer Patcher today again, forgetting that this was the particular issue that existed about 2 months ago when I initially tried it.

**Comment by pyrates999** [comment] 2024-05-13 20:46
Does this happen if you uninstall EP?

**Comment by Amrsatrio** [comment] 2024-06-24 08:12
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2086

**Closed by Amrsatrio** 2024-06-24 08:12 UTC
