### ISSUE TITLE
Taskbar and Start menu

### ISSUE THREAD

**Issue by nikostheofanoudis** [valinet/ExplorerPatcher#2110] opened 2023-09-21 01:02 UTC
Right click on taskbar restarts file explorer and icons randomly appeared on recommend section after disabling it. Windows 11, AMD Ryzen 5 3600, 16gb ram

**Comment by ridong** [comment] 2023-09-21 01:39
I got the same bug

**Comment by pyrates999** [comment] 2023-09-21 12:14
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2051

Please close this one.

Possible fixes:

1. In ExplorerPatcher Properties, go to Advanced and untick **Do not change the taskbar context menu** - there should be an X beside it
2. In ExplorerPatcher Properties, go to File Explorer and untick **Disable the windows 11 context menu**
3. In ExplorerPatcher Properties, go to Taskbar and set **Taskbar style** to **Windows 11**

**Closed** 2023-09-21 18:54 UTC
