### ISSUE TITLE
AllowModernSearchBox doesn't work

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [valinet/ExplorerPatcher#17] opened 2021-09-05 20:15 UTC
The new version 22449.1000.0.18 works perfectly to patch Explorer and load classic Taskbar with the pre-configured Settings.ini. I am on Windows 11 22449.1000. And the change to revert to the classic search is very welcome - I was gonna ask for it but then I thought I've made so many feature requests in last couple of days, maybe I should give you some rest :D

The Advanced Query Syntax completion is why I like the old box. It's easy to select a date range for example in the classic one.

While the old one is working perfectly, just for testing I set AllowModernSearchBox=1. It appears like as in the picture below:
![SearchBox](https://user-images.githubusercontent.com/46422834/132140204-7814efcf-ce6d-4ac6-a927-b3eef9ce8952.png)

But when I actually click it or press Ctrl+E to focus it, it disappears and the text cursor indicator appears somewhere on top near the Ribbon tabs. Is it because I've enabled the Ribbon using the latest Winaero Tweaker tweak? If I type in it, the new search works but box remains in the wrong position.

Btw, another change to Explorer when they changed the search box was that they made the Address bar thicker. It used to be much less taller in earlier Windows 10 releases and Windows 7/8.1. Is there a way to revert to the thinner address bar? It is useful on 16:9 laptops where the tall address bar pushes custom toolbars further down reducing the area to list files.

Thanks for this awesome version. The change to revert the search should have been optional by Microsoft since they couldn't build a combined version with the new changes.

**Comment by valinet** [comment] 2021-09-05 20:27
Hi

Yeah, I noticed that as well, that visual glitch was what filled the glass for me and I took the time to see where the old search box gets enabled from, as it clearly works in Control Panel-based Explorer windows, for example. Although I use Everything Search, every now and then I click there and it annoyed me to see it go crazy like that.

Anyway, should that be considered a bug? I mean, the software provides an alternative =)) And idk, I'd test to see whether it does that when only the classic taskbar is enabled. if it still happens, maybe it simply is a bug of Explorer in this configuration and there isn't much I can do about it (although fixing the logon delay, the context menu, the legacy search bar etc would prove the contrary =))). What I mean is I don't know if it really is necessary to bother fixing that. Does anyone use it? It was crappy af to begin with...

It's the same situation with the broken network and battery applets, [Battery Mode](https://en.bmode.tarcode.ru/) does such a much better job and the network icon is useless anyway besides an indicator and switching WiFis which you can still do from control center, so... it is anyway useless because it opens the crappy Settings app instead of "Network and Sharing Center"... so yeah, I haven't bothered looking into them too much, tbh, I don't even know in what DLL they are.

**Comment by valinet** [comment] 2021-09-05 20:31
Also, if you want more vertical space, why not disable the ribbon altogether? That frees a lot of space. Do you really use the ribbon, most of the commands are shortcuts already or in the context menu. That's how I used to rock Explorer in Windows 10, now I left the new command bar on because I find it a good compromise between space taken and actually showing some useful stuff. Although, again, those commands are already available in the context menu, most of them.

**Comment by valinet** [comment] 2021-09-05 20:36
Just tested now with ExplorerPatcher off, the "modern search box" still craps out for me. I'd say it's a bug in this build (22000.176). Or idk, I don't care that much to be honest, I cannot expect that to be bug free since it was designed as an experience that showcases bugs, I think =)))

**Comment by Gaurav-Original-ClassicShellTester** [comment] 2021-09-05 20:55
The Modern Search box of Explorer craps out and behaves this way if dxgi.dll of ExplorerPatcher is present in MicrosoftWindows.Client.CBS_cw5n1h2txyewy :D If the DLL is only there in %windir% and the Start Menu Experience folder, it works correctly.

Anyway I would definitely use Explorer with your fantastic tweak enabled but I feel it should be fixed, although the new search box has really crappy behavior. Can't Ctrl+E to select all text again in it, the X doesn't clear text. Have to press Alt+Left to go back from the search.

I too prefer Everything Search most of the times (assigned to my Ctrl+Shift+E) :D

I use Battery Mode too :D I saw it covered on gHacks and told Sergey to include it in the Restore Classic Start/Taskbar article. :D

Well here's what I do save space vertically. I tried disabling the Ribbon and bringing back the Windows 7 Command Bar and used it like that for few days. However I realized that with the Ribbon enabled but minimized, it saves more space than the Explorer Command Bar (which can't be minimized) :D I keep Ribbon minimized and I never use the Ribbon, I treat it like a menu bar for occasional use case. Instead, I have my own custom toolbars - the Classic Explorer bar of Classic Shell/Open Shell with all custom power users commands and below that, I always have StExBar.

![MyExplorer](https://user-images.githubusercontent.com/46422834/132141169-5f013f30-99d2-45f7-9240-af05025b1b86.png)

**Comment by valinet** [comment] 2021-09-05 21:07
The Explorer command bar can easily be taken out altogether by editing the theme file: https://www.askvg.com/how-to-make-folder-band-auto-hidden-in-windows-vista/. Wherever it says "28" in the instructions there, for Windows 10, use "34". And that gives rid of the command bar altogether. That's how I used to have Explorer before the new Mica effect toolbar was introduced in .65:

![image](https://user-images.githubusercontent.com/6503598/132141476-01fdfddf-939b-45ab-9339-357588a35f73.png)

**Comment by Gaurav-Original-ClassicShellTester** [comment] 2021-09-05 22:02
Yes I know the Command Bar can be removed entirely but I want to keep some system provided UI :) since my custom toolbar doesn't cover all use cases, only has the most commonly needed by me commands. Besides I need the Quick Access Toolbar to put some commands from the "Search" tab of the Ribbon (specifically Date Modified, Kind, Size filters, and quick toggles for searching current folder vs subfolders and File contents.) It's the fat address bar that wastes space since 1903? I think?

**Comment by valinet** [comment] 2021-09-05 22:04
> The Modern Search box of Explorer craps out and behaves this way if dxgi.dll of ExplorerPatcher is present in MicrosoftWindows.Client.CBS_cw5n1h2txyewy :D If the DLL is only there in %windir% and the Start Menu Experience folder, it works correctly.
> 
> Anyway I would definitely use Explorer with your fantastic tweak enabled but I feel it should be fixed (needs to be fixed only for MicrosoftWindows.Client.CBS_cw5n1h2txyewy), although I admit the new search box has really crappy behavior. Clicking the X sometimes doesn't clear the text (if you've clicked the arrow or pressed Enter to search), doesn't take us back from the search and lots of such annoyances/unpredictable behaviors.

Okay, thanks, that's valuable information to know. I think I have a slight idea why it does that.

Later edit without actually hitting the "comment" button initially: yes, I was right, the info you provided set me on the right track. Apparently, the "modern search box" is somehow hosted in some thing that is loaded from `C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy`; probably that's why it bugs out and flickers so much, it is some first gen XAML island stuff or something like that. It is modern in the sense that it is yet again some managed code added to Explorer for no apparent reason. The new thing just presents a list with items it filters that it takes ages to generate, while the old one you typed and it searched instantly, like the Start menu in Windows 7 used to do.

Yeah, whatever, I prefer the old one, and I fixed the problem that was making the new one go out of its place. I hook `CJupiterWindow::StaticCoreWindowSubclassProc` and in there I mess with the x and y of the window in order for search to appear at the left, as I ddi not find any better place to do so for `SearchHost.exe`. But, indeed, i have to somehow do it only for the Windows search interface, not for that box in Explorer too. The fix was to look a bit at the position of the window. Until something better, it will do, it works just fine. Of course, better stuff to hook into when in `SearchBox.exe` would be better, some flag that just makes it left align automatically like in `StartMenuExperienceHost.exe` would be ideal. If someone would also take the time to look on the DLLs in search, it would be way more than ideal.

Anyway, it is fixed (uploaded in place in Releases), I will close this one.

**Closed by valinet** 2021-09-05 22:04 UTC

**Comment by Gaurav-Original-ClassicShellTester** [comment] 2021-09-05 22:12
Fixed indeed completely. Thank you so much :D You are one awesome developer!
