### ISSUE TITLE
Taskbar restarts

### ISSUE THREAD

**Issue by JoeSquawks** [valinet/ExplorerPatcher#1982] opened 2023-09-03 02:12 UTC
When I right-click the windows 11 taskbar, it restarts. I can't change any explorer patcher settings or do anything. It also doesn't show up in my installed apps and I can't download updates or even redownload it.

**Comment by amyers735** [comment] 2023-09-03 02:35
Experiencing the same thing so came to github issues for more info.  This is a duplicate of #1952 I think.

**Comment by bcnb99** [comment] 2023-09-03 04:29
you'd need to use old version of explorerpatcher or something

**Comment by Poopooracoocoo** [comment] 2023-09-03 13:39
You need to state your OS build and EP version.

Duplicate of #1952

> you'd need to use old version of explorerpatcher or something

No, you'd need to uninstall KB50292633

**Closed by Poopooracoocoo** 2023-09-03 13:39 UTC
