### ISSUE TITLE
When using Control Interface "Windwos 10 Ribbon" explroer window size is not saved on each explorer window.

### ISSUE THREAD

**Issue by kardo22** [valinet/ExplorerPatcher#2393] opened 2023-11-03 13:42 UTC
First of all big thanks to everyone working on this, i have a new computer and without this i wouldn't be able to use it, the new file explorer is completely unworkable and ruins my workflow completely, i hate what they are doing at microsoft.

When using the classic windows 10 ribbon (because god knows the 11 one is unusable, especially the breadcrumb that is completely broken) the file explorer does not seem to save the window size or position when closed.

How to recreate the issue:
Enable Control Interface Windows 10 Ribbon
Open a single file explorer window
Resize it as you see fit
Go to view - options - view - press "Apply to folders" | this should make all explorer windows have the same size/view setting as the one you are working with now.
Now close the window.
Open window again, its the default size, no settings were applied.

**Comment by Amrsatrio** [comment] 2023-11-04 04:34
Glad to see this software making you happy, but sorry that this has been reported before. Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2243

**Closed by Amrsatrio** 2023-11-04 04:34 UTC
