### ISSUE TITLE
Right-clicking Windows 11 taskbar crashes explorer.exe on Windows 11 Build 22621.2134 (KB5029263)

### ISSUE THREAD

**Issue by xSnakyy** [valinet/ExplorerPatcher#1826] opened 2023-08-11 17:20 UTC
On start I get "Error in sub_1800135EC on RoGetActivationFactory" in the console. I assume it's the new windows 11 update as older versions don't work either. 

**Edit**: Workaround: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by archz2** [comment] 2023-08-11 17:31
It is crashing without right clicking also. I think the new Windows 11 version bricked it. I have been facing issues since noon today ever since I updated Windows.

**Comment by YaliHorde** [comment] 2023-08-11 20:14
yup... same here.. Avoid using this program.. I have a newly installed Win 11 and this software needs to get a PROPER update before I use this software again.

**Comment by SomethingOriginal** [comment] 2023-08-12 00:29
I am having the same issue. Checked the console, it appears to be "Error in sub_1800135EC on RoGetActivationFactory." when the taskbar crashes. Hope this helps.

**Comment by Hevgen** [comment] 2023-08-12 03:29
Same issue before and after update of Windows. 

From windows log:
Fault bucket 2292732376704829456, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: explorer.exe
P2: 10.0.22621.2070
P3: 2bd7252c
P4: dxgi.dll
P5: 22621.1992.56.1
P6: 64c11ec0
P7: c0000005
P8: 000000000001099d

**Comment by archz2** [comment] 2023-08-12 07:19
Crash has gone for me. I received one pop-up from Explorer Patcher in the bottom right of my screen that said either downloading new icons or downloading new thumbnails. 

After that, everything has been normal. 

I suggest uninstalling and re-installing using the method here
https://github.com/valinet/ExplorerPatcher/issues/1825#issuecomment-1675051326

 Then, hopefully, you'll get the same pop-up that I got and there will be no more crashes. Refer my previous post here.

**Comment by pyrates999** [comment] 2023-08-12 10:30
I find with explorer patcher installed and applications are crashing as I try to open them, a reboot fixes it.

**Comment by vittbol** [comment] 2023-08-12 11:49
> Crash has gone for me. I received one pop-up from Explorer Patcher in the bottom right of my screen that said either downloading new icons or downloading new thumbnails.
> 
> After that, everything has been normal.
> 
> I suggest uninstalling and re-installing using the method here [#1825 (comment)](https://github.com/valinet/ExplorerPatcher/issues/1825#issuecomment-1675051326)
> 
> Then, hopefully, you'll get the same pop-up that I got and there will be no more crashes. Refer my previous post here.

I did it, but it still crashing

**Comment by pyrates999** [comment] 2023-08-13 00:29
Did you get the notification for symbols being downloaded and then reboot?

**Comment by vittbol** [comment] 2023-08-13 01:26
> Did you get the notification for symbols being downloaded and then reboot?

I didnt :(

**Comment by pyrates999** [comment] 2023-08-13 06:09
If you have any third party firewall running, disable it while installing explorer patcher and then check if the symbols are downloaded by checking for the notifications.

You can also check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.  It will tell you if it is trying to download the symbols and if it's able to or not.

**Comment by Girofox** [comment] 2023-08-13 08:35
For anyone with the right clicking issue enabling

- `✔️ Do not change the taskbar context menu`

definitely helps, in my case the right clicking issue crash happens when I switch to `Windows 11` taskbar style, and when I revert it to `Windows 10` style, even with the correct symbols downloaded. You can find explorer patcher settings via Windows search typing just "explorerpatcher"

![image](https://github.com/valinet/ExplorerPatcher/assets/43116061/880cce71-89a4-436e-82a5-310028420c71)

**Comment by Sunrise-Sea** [comment] 2023-08-14 18:12
I am having the same log in the console. These documentations from Microsoft seem to confirm that this is an OS issue.

https://learn.microsoft.com/en-us/windows/win32/api/roapi/nf-roapi-rogetactivationfactory
https://learn.microsoft.com/en-us/windows/win32/api/activation/nn-activation-iactivationfactory
https://learn.microsoft.com/en-us/windows/win32/api/activation/nf-activation-iactivationfactory-activateinstance

It mentions here that they modified some APIs of the taskbar so another source that can confirm

https://blogs.windows.com/windows-insider/2023/08/02/announcing-windows-11-insider-preview-build-22621-2129-and-22631-2129/

It may be  because my _Windows version_ is **22621.2134** and _explorerPatcher_ is **22621.1992.56.1** and I never got a notification for symbols being downloaded for my current Windows version hence my deduction would be

**Comment by pyrates999** [comment] 2023-08-15 12:18
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

**Comment by Poopooracoocoo** [comment] 2023-08-22 11:52
Duplicate of #1805

**Closed by Poopooracoocoo** 2023-08-22 11:52 UTC
