### ISSUE TITLE
Bug or feature? Very thin taskbar.

### ISSUE THREAD

**Issue by xSimone** [valinet/ExplorerPatcher#3993] opened 2024-12-01 06:29 UTC
![image](https://github.com/user-attachments/assets/ad61ad58-f803-4ba3-9b1e-0292c417298b)

Some reason the taskbar is really thin after a reboot.

Win11 latest fresh install as of a week ago.

Position: Top
Size: Small

**Comment by pyrates999** [comment] 2024-12-01 11:07
Right click on it and untick Lock taskbar.  Then you can resize it.  Right click on it and tick Lock taskbar.

**Comment by xSimone** [comment] 2024-12-02 04:14
Unlocking made it fix itself. I want to keep it locked however. 

An easy simple bandaid for now, thank you.

**Comment by xSimone** [comment] 2024-12-02 04:14
> Unlocking made it fix itself. I want to keep it locked however.
> 
> An easy simple bandaid for now, thank you.


Unlocking made it fix itself. I want to keep it locked however.

An easy simple bandaid for now, thank you.

**Comment by pyrates999** [comment] 2024-12-02 08:56
If it happens every time you reboot, please post that here.

**Comment by pyrates999** [comment] 2024-12-02 09:18
Right click on the taskbar and tick `Lock taskbar` will lock it if it doesn't have a tick mark beside it yet.

**Comment by xSimone** [comment] 2024-12-03 02:59
So right now it happens with games that change the resolution of my screen, currently I'm sporting a 1600P screen and playing some older games.

**Comment by xSimone** [comment] 2024-12-03 06:09
![image](https://github.com/user-attachments/assets/5377eeee-783c-43a3-8364-e05ac8777be6)

Hmm did it again after a reboot but I am not sure when it began. I didn't keep track of it. 

Didn't play any games. Will keep on it until I find what triggers it hopefully.

**Comment by xSimone** [comment] 2024-12-03 06:10
.. I kind of like how thin it is though but yeah things clipping.

**Comment by xSimone** [comment] 2024-12-03 06:10
![image](https://github.com/user-attachments/assets/24b3f36f-167e-408e-8ad6-ed9000d7d41a)


.. I kind of like how thin it is though but yeah things clipping.

The top right looks real nice.

**Comment by pyrates999** [comment] 2024-12-03 11:13
did the games change the resolution being outputted to the monitor?

**Comment by xSimone** [comment] 2024-12-03 14:43
> did the games change the resolution being outputted to the monitor?

I believe so yes.

Also, snapping is thinking that the toolbar is at the bottom, leaving a space, and going under the taskbar at the top at times.

Unlocking and clicking it fixes this too so far.

![image](https://github.com/user-attachments/assets/60a33f6b-75ed-4c70-baf7-3a22667b2f7c)

**Comment by pyrates999** [comment] 2024-12-03 19:28
Ok, thanks.  Please wait for a developer to respond.

**Comment by xSimone** [comment] 2024-12-04 11:49
> Ok, thanks. Please wait for a developer to respond.

Hi, the slim bar happens it seems when I leave my Laptop alone and it goes to sleep. Waking it up seems to cause it.

**Comment by xSimone** [comment] 2024-12-04 14:35
Right now alt tabbed from a game, it thinks the explorer bar is still bottom of the screen, which is why it hides under it when above.

**Comment by Amrsatrio** [comment] 2024-12-09 04:45
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3796

**Closed by Amrsatrio** 2024-12-09 04:45 UTC
