### ISSUE TITLE
Windows Explorer on Windows 11 crashes by right click on the desktop, if Explorer Patcher is installed.

### ISSUE THREAD

**Issue by ymalich** [valinet/ExplorerPatcher#2503] opened 2023-11-25 12:39 UTC
Windows Explorer crashes if I try to open the context menu on the desktop, if Explorer Patcher is installed.
Right click on the taskbar opens the context menu without issues. 

I've tested with versions 22621.2506.60.1, 22621.2428.59.1
Windows 11 build 22621.2715.

https://github.com/valinet/ExplorerPatcher/assets/52053585/dcb9664c-64b3-48f2-9b5e-35fa84bae732

**Comment by Amrsatrio** [comment] 2023-11-25 12:43
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218

**Closed by Amrsatrio** 2023-11-25 12:43 UTC
