### ISSUE TITLE
The taskbar context menu no longer appears

### ISSUE THREAD

**Issue by cronostorie** [valinet/ExplorerPatcher#1989] opened 2023-09-04 06:51 UTC
I just reinstalled ExplorerPatcher 22621.1992.56.3.
The installation runs without problems.
After installation, however, when I right-click on the taskbar, after a few seconds of waiting, it seems that the taskbar crashes and I don't see the context menu that usually appears.
Everything remains as before.

My OS is:
Edition: Windows 11 Enterprise
Version: 22H2
Build: 22621.2134
Windows Feature Experience Pack 1000.22659.1000.0

**Comment by pyrates999** [comment] 2023-09-04 10:33
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Closed** 2023-09-04 13:48 UTC
