### ISSUE TITLE
[226xx.4391+] [261xx.2130+] Start10 crashes when right clicking an item with jump list

### ISSUE THREAD

**Issue by Roslinger** [valinet/ExplorerPatcher#3842] opened 2024-10-24 16:24 UTC
https://github.com/user-attachments/assets/bd999190-6497-40c7-ae19-3ea677827cfb

Windows 11 Pro 24H2 26012.2130

**Comment by pyrates999** [comment] 2024-10-24 22:29
Please post windows version and build.  You can find this by running winver.  Please include if you are running x86-64 or Arm.  And what language your windows is in.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.  If you can, please change it to english first.

Please include any other software you have installed that modifies the UI of windows.

Do you have another antivirus installed?

please check latest dump file related to the affected exe in %LOCALAPPDATA%\CrashDumps

then rename the file extension to .txt and upload it to here

**Comment by Amrsatrio** [comment] 2024-10-26 00:23
I might not be able to fix this, unfortunately. Windows 10 start menu is currently on life support. Expect it to stop working anytime.

**Comment by YaeSakuraQvQ** [comment] 2024-10-26 13:35
> I might not be able to fix this, unfortunately. Windows 10 start menu is currently on life support. Expect it to stop working anytime.

24H2 26100.2161 got same bug

u can try right click on app with custom tab to reproduce (such as chrome, calculater, snipping tool, microsoft store)

**Comment by Roslinger** [comment] 2024-10-27 10:02
> Please post windows version and build. You can find this by running winver. Please include if you are running x86-64 or Arm. And what language your windows is in. Please post explorer patcher version.
> 
> Please include what settings you changed in explorer patcher properties application. These should be screen shots. If you can, please change it to english first.
> 
> Please include any other software you have installed that modifies the UI of windows.
> 
> Do you have another antivirus installed?
> 
> please check latest dump file related to the affected exe in %LOCALAPPDATA%\CrashDumps
> 
> then rename the file extension to .txt and upload it to here

![grafik](https://github.com/user-attachments/assets/f04bd4da-ab51-444f-ad88-7107cdea07fb)

https://easyupload.io/vrrira

No antivirus other than defender which doenst show any threads.
No additional Software other than Recify11

![grafik](https://github.com/user-attachments/assets/bff68168-afdb-4c78-b9c2-49260dadc0b3)
![grafik](https://github.com/user-attachments/assets/f250014b-fb81-4894-97ff-f1d28f4e0190)
![grafik](https://github.com/user-attachments/assets/e83e2733-0cab-4a8f-bf25-f20be2ba0d98)
![grafik](https://github.com/user-attachments/assets/2f91f9bf-6ddb-46fb-9589-91b7e9637708)
![grafik](https://github.com/user-attachments/assets/d13e7430-46d1-439e-aa95-c102fd57d5d5)
![grafik](https://github.com/user-attachments/assets/2ee7bc68-9b0d-4be6-859c-01270260cafc)
![grafik](https://github.com/user-attachments/assets/0e43b14a-f8ea-4b00-87e2-e752e24d4648)
![grafik](https://github.com/user-attachments/assets/0a502054-9b80-4de6-99f3-79148804abde)
![grafik](https://github.com/user-attachments/assets/4cfe156e-6356-4fe3-b666-2b994af0e7b7)
![grafik](https://github.com/user-attachments/assets/d71aec22-e222-4c1b-a67a-f069e4d9bea9)

Hope this helps. Grettings from Germany!

**Comment by pyrates999** [comment] 2024-10-27 10:41
you're on an insider preview build: https://blogs.windows.com/windows-insider/2024/10/18/announcing-windows-11-insider-preview-build-26120-2130-dev-channel/

**Comment by Roslinger** [comment] 2024-10-27 15:10
i know

**Comment by pyrates999** [comment] 2024-10-27 23:05
does it happen in the last update of windows 11 24h2?

**Comment by xuangeyouneihan** [comment] 2024-10-28 08:44
23H2 22631.4391 got the same bug

```
Running on Windows 11, OS Build 10.0.22631.4391.
Loaded symbols
Setup user32 functions done
CAppResolverCacheBuilder::_AddUserPinnedShortcutToStart() = 4A260
ITrayUIHost = 3E8468
explorer.exe!TrayUI_CreateInstance() = 1D9B0C
Setup explorer functions done
Setup uxtheme functions done
Failed to hook CLauncherTipContextMenu::ShowLauncherTipContextMenu(). rv = 7
[SMA] matchVtable = 79B1E8
[SMA] matchSingleViewShellExperienceFields = 10C74D
[SMA] matchAnimationHelperFields = 10C78C, +0x240, +0x260
[SMA] matchTransitioningToCortanaField = 425424, +0x2C8
[SMA] CStartExperienceManager::GetMonitorInformation() = F2E58
[SMA] CExperienceManagerAnimationHelper::Begin() = 73575C
[SMA] CExperienceManagerAnimationHelper::End() = 2C2D62
[SMA] matchHideA in CStartExperienceManager::Hide() = 2200D
[SMA] matchHideB in CStartExperienceManager::Hide() = 2204D
[SMA] Advertising successful animations patching.
Setup twinui.pcshell functions done
Setup combase functions done
Setup twinui functions done
Setup stobject functions done
Setup bthprops functions done
Setup pnidui functions done
Setup shell32 functions done
Setup windows.storage functions done
Setup inputswitch functions done
Setup peopleband functions done
Installed hooks.
Open Start on monitor thread
EP Service Window thread
Started "Open Start on current monitor" thread.
Initialized taskbar centering module.
Progman: 593624
Progman hook: 33163515
0 0
[EnsureXAML] 78 ms.
[Updates] Starting daemon.
[Updates] Configured update policy on this system: "Check for updates but let me choose whether to download and install them".
[Updates] Path to module: C:\Windows\dxgi.dll
[Updates] Using hardcoded hash.
[Updates] Checking against hash "22622.3880.66.7.43dda865949845aa"
[Updates] Update URL: https://github.com/valinet/ExplorerPatcher/releases/latest/download/ep_setup.exe
[Updates] Hash of remote file is "22622.3880.66.6.57999ff163192946" (valid).
[Updates] Local version obtained from hash is 22622.3880.66.7.
[Updates] No updates are available.
```

**Comment by TW527E** [comment] 2024-10-30 15:51
Windows 11 IoT Enterprise LTSC 24H2 26100.2161 Having same problem
but
- Firefox
- Arc Browser
- Edge Browser
- Zen Browser
- BC Uninstaller
- Xbox APP
- Calculator
- Microsoft Store
- Windows Explorer
- Windows Terminal
and so many apps also be like this
(but Tor Browser doesn't be like this, IDK why)
even I right click they in app list will crash too 😭

[StartMenuExperienceHost.exe.44596.zip](https://github.com/user-attachments/files/17574537/StartMenuExperienceHost.exe.44596.zip)

**Comment by shenhaipaopaoa** [comment] 2024-10-31 01:01
Only the last few versions have appeared

**Comment by Amrsatrio** [comment] 2024-11-01 19:21
Identified the issue. JumpViewUI.dll had some changes. Probably fixable this week but this means the latest known good JumpViewUI.dll need to be packed into ep_setup.exe.

**Comment by bernhy** [comment] 2024-11-02 08:29
> Identified the issue. JumpViewUI.dll had some changes. 

Thank you very much, yes this really fixes this issue.

**Comment by Amrsatrio** [comment] 2024-11-02 12:32
![482BEA08-E867-4832-B773-AEFFACD04770](https://github.com/user-attachments/assets/84d14663-4dbc-4d74-9c38-02c3de48bb43)

22621.4111 JumpViewUI.dll seems to work both on latest x64 22H2/23H2 preview and a relatively outdated ARM64 24H2 build.

**Comment by Amrsatrio** [comment] 2024-11-02 13:27
@bernhy If you takeown and swap JumpViewUI.dll in the filesystem, the taskbar jump lists will not work anymore. I suggest to revert your changes.

**Comment by Amrsatrio** [comment] 2024-11-02 13:49
67.1 prerelease is live. Let me know if it works.

**Comment by TW527E** [comment] 2024-11-02 14:13
![Clip_2024-11-02_22-12-22](https://github.com/user-attachments/assets/a957e96c-8e32-4361-9358-8a7a628c14a2)
🥳 IT WORKS!

**Comment by xuangeyouneihan** [comment] 2024-11-02 14:30
At least it works for me 🎉🎉🎉

![图片](https://github.com/user-attachments/assets/bbcf2804-3a25-48cc-ba36-8cf0e6bdafa2)

**Comment by bernhy** [comment] 2024-11-02 16:43
> @bernhy If you takeown and swap JumpViewUI.dll in the filesystem, the taskbar jump lists will not work anymore. I suggest to revert your changes.

@Amrsatrio Hm, what can I say, for me swapping the dll in the fs worked. 67.1 prerelease instead doesnt change anything, with the original dll its still crashing. Has there anything to be configured to get it work?

**Comment by bernhy** [comment] 2024-11-02 16:46
Damn, ok thats it. I confirm, current version works.
Thank you very much

**Comment by Amrsatrio** [comment] 2024-11-03 14:46
67.1 has been promoted to release. Closing this issue.

**Closed by Amrsatrio** 2024-11-03 14:46 UTC
Labels: fixed, Start10, Crash, High Priority
