### ISSUE TITLE
language only has one but shows two and can't remove

### ISSUE THREAD

**Issue by decba78b** [valinet/ExplorerPatcher#4049] opened 2024-12-17 06:22 UTC
### Before reporting your issue

- [X] I have confirmed that this issue does not happen when ExplorerPatcher is not installed
- [ ] I do not have "register as shell extension" enabled
- [ ] I have tried my best to check existing issues

### Repro ExplorerPatcher versions

ExplorerPatcher67.1

### Repro Windows Versions

Windows 23H2 22631.4602

### 3rd party tweak software installed

TranslucentTB

### Describe the bug

my language only using chinese and it is default, but when I using ExplorerPatcher, there will be added English and I can't remove it

### Expected outcome

![PixPin_2024-12-17_14-10-52](https://github.com/user-attachments/assets/cfb5dbcb-3138-48c8-a863-343df0028913)

### Actual outcome

![PixPin_2024-12-17_14-04-59](https://github.com/user-attachments/assets/c0346279-0a9b-4822-a7c4-a035820cac48)

### Additional info

I noticed that if I use the last one "Window switcher", it will add an unremoveable english language.

**Comment by Amrsatrio** [comment] 2024-12-17 07:15
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1347

**Closed by Amrsatrio** 2024-12-17 07:15 UTC
