### ISSUE TITLE
[Feature Request] Windows 10 style search home

### ISSUE THREAD

**Issue by XuanChen1234** [valinet/ExplorerPatcher#1734] opened 2023-07-31 10:10 UTC
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/1672

<div type='discussions-op-text'>

<sup>Originally posted by **XuanChen1234** July 26, 2023</sup>
![show-search-highlights](https://github.com/valinet/ExplorerPatcher/assets/140480110/38a2eb79-97fc-4d40-9d67-e2110abd520b)
Many many thanks, Valinet.
If it is not planned yet, I hope this will be a thing in the next update.
</div>

**Comment by pyrates999** [comment] 2023-08-01 10:04
Issues are for bugs only, not feature requests.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:44
Duplicate of #1672

**Closed by Poopooracoocoo** 2023-08-22 10:44 UTC
