### ISSUE TITLE
when i want to internet search something it says "didint found any result"

### ISSUE THREAD

**Issue by matttmag** [valinet/ExplorerPatcher#2974] opened 2024-03-12 14:03 UTC

**Comment by pyrates999** [comment] 2024-03-13 13:11
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by matttmag** [comment] 2024-03-13 16:59
it was my computer i think i restarted my pc and it works now

**Comment by pyrates999** [comment] 2024-03-13 22:16
Please close this then and try to troubleshoot more before assuming it is caused by EP.

**Closed** 2024-03-14 09:06 UTC
