### ISSUE TITLE
THE BATTERY IS BROKEEN

### ISSUE THREAD

**Issue by apixhed** [valinet/ExplorerPatcher#3958] opened 2024-11-23 04:59 UTC
![Screenshot 2024-11-23 115805](https://github.com/user-attachments/assets/fe31f07f-b1c4-44cb-85ae-dfad8be443da)
its broken

**Comment by milesprower2293** [comment] 2024-11-23 06:39
Duplicate of: #3640

**Closed by milesprower2293** 2024-11-23 06:39 UTC
