### ISSUE TITLE
Live tiles doesn't work if wide or large

### ISSUE THREAD

**Issue by Steperman5692** [valinet/ExplorerPatcher#3112] opened 2024-04-08 22:04 UTC
So basically if if I enlarge an app that support live tiles like Weather; it only works with scale medium not wide or large. (This is the windows 10 start menu)
Before:
![Screenshot 2024-04-09 004955](https://github.com/valinet/ExplorerPatcher/assets/132756638/ee52a8d2-9106-448e-8e8c-8a07b253f124)
After:
![Screenshot 2024-04-09 005428](https://github.com/valinet/ExplorerPatcher/assets/132756638/bfd6bec1-9423-4b4b-b4f5-308534a65d88)
![Screenshot 2024-04-09 005814](https://github.com/valinet/ExplorerPatcher/assets/132756638/d7814d6f-140f-4fbd-99f2-528b518cf878)

**Comment by pyrates999** [comment] 2024-04-08 22:12
Live tiles have always been unstable in 22621 onwards. We have no plans of fixing it as Microsoft has removed the Windows 10 start menu in 26xxx builds.

Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1621

Please close this.

**Comment by Amrsatrio** [comment] 2024-04-10 03:20
![image](https://github.com/valinet/ExplorerPatcher/assets/20662640/bcd2ac10-ecf9-487f-995a-b892bcfa8cad)
Works on me?? 22621.3296

**Comment by bbmaster123** [comment] 2024-04-10 19:44
working for me too, wide and large, 22631.3447
I don't use it but I'll leave it on for a few days and see if anything happens

**Comment by pyrates999** [comment] 2024-04-11 13:32
You haven't told us the version and build number of your windows.

**Comment by Steperman5692** [comment] 2024-04-12 12:20
Oh yeah btw its build 22631.3447 (Windows 11 23H2)

**Comment by pyrates999** [comment] 2024-04-12 12:56
As I said:

Live tiles have always been unstable in 22621 onwards. We have no plans of fixing it as Microsoft has removed the Windows 10 start menu in 26xxx builds.

Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1621

Please close this.

**Comment by chuck00000** [comment] 2024-04-14 11:07
![Screenshot 2024-04-14 185749](https://github.com/valinet/ExplorerPatcher/assets/98159699/c35543be-ba84-404f-9302-906a9885d1d5)
![Screenshot 2024-04-14 190346](https://github.com/valinet/ExplorerPatcher/assets/98159699/1afe4768-8a4f-46a6-98fd-960bc9c80370)


Works well in  latest build 26100, try open the weather app several times

**Closed** 2024-04-26 13:46 UTC

**Comment by BourgeoisDirk** [comment] 2025-02-23 14:54
I am having this issue after having to re-install ExplorerPatcher and load my config.

My Win11 wished to Update to 24H2, but would throw an error that it is not possible with ExplorerPatcher installed.
Live Tiles in the Win10 Start Menu were working fine, apps would show their Notification count, weather App would show it's stuff, all worked fine.
I Uninstalled ExplorerPatcher, let Windown run it's update, then restarted.
Installed ExplorerPatcher again, and loaded my config.

Everything seemed fine, except that my tiles are no longer Live.
Weather tile isn't showing anything but the icon (like in the picture from this post), apps notification counts (like WhatsApp) no longer work either.
Is there a fix or work-around for this ?
