### ISSUE TITLE
not remembering window size & position

### ISSUE THREAD

**Issue by clutchmaster420** [valinet/ExplorerPatcher#3268] opened 2024-05-12 15:30 UTC
i cant be believe one of the most CRITICAL function of file explorer does not work in this software its been almost a year and hasnt been PATCH!

**Comment by Amrsatrio** [comment] 2024-05-12 15:59
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2243

**Closed by Amrsatrio** 2024-05-12 15:59 UTC
