### ISSUE TITLE
bug: disable rounded corners for applications doesn't work

### ISSUE THREAD

**Issue by HowXu** [valinet/ExplorerPatcher#3979] opened 2024-11-28 09:23 UTC
Windows 11 24H2 26100.2314
EP 22621.4317.67.1

When you restart Explorer with the disable window rounding option enabled, it will take at least ten seconds for the taskbar to appear normally, and disabling window rounding will not work, so the option will automatically change to ×

**Comment by Amrsatrio** [comment] 2024-11-28 12:29
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3555

**Closed by Amrsatrio** 2024-11-28 12:29 UTC
