### ISSUE TITLE
Weather seems broken

### ISSUE THREAD

**Issue by nexusV2** [valinet/ExplorerPatcher#3728] opened 2024-09-22 09:19 UTC
Hi,

actually EP is only showing the Peoples icon.
I´m using Version 22621.3880.66.6 / Win 10 taskbar style.
Win 11 build 22631.4169

"Thank you, I appreciate your work every day!"

**Comment by pyrates999** [comment] 2024-09-22 12:12
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2010

please close this.

and weather is not yet supported on the windows 10 (ExplorerPatcher) taskbar: https://github.com/valinet/ExplorerPatcher/issues/3546

**Comment by Amrsatrio** [comment] 2024-09-22 12:29
Duplicate of #2010

**Comment by nexusV2** [comment] 2024-09-22 13:23
It´s not the same until today everything worked fine and I had never this issue before, using it continausly for at least 2 years.
Also it occured together with a reset of EP to left aligned Win 11 style, so I had to reimport my EP settings from a backup.

**Comment by Amrsatrio** [comment] 2024-09-22 13:25
Okay then, sorry. I will look into it when I have the chance. I just realized that I changed something in the Weather code to accomodate the new compiler which has stricter rules when compiling C code.

**Comment by nexusV2** [comment] 2024-09-23 08:46
When did you change that, the last release seems 2 weeks ago but the weather disappeared 2 days ago?
To which version shall I downgrade?

**Comment by pyrates999** [comment] 2024-09-23 08:49
Downgrading EP is not advised if you're running windows 11 as the current release of EP is required for running on the current release of windows 11.

**Comment by Jazzzed** [comment] 2024-09-23 10:46
Have you tried this?

https://github.com/valinet/ExplorerPatcher/issues/3674#issuecomment-2344725859

**Comment by nexusV2** [comment] 2024-09-23 10:53
> Have you tried this?
> 
> [#3674 (comment)](https://github.com/valinet/ExplorerPatcher/issues/3674#issuecomment-2344725859)

Yes, but no success with 22621.3880.66.6.
Just seems to work for  22621.3880.66.5

**Comment by pyrates999** [comment] 2024-09-23 10:55
All I can say is try going through this guide: https://github.com/valinet/ExplorerPatcher/wiki/Weather

**Comment by nexusV2** [comment] 2024-09-24 13:34
Please be more specific. How is a guide supposed to help with this?
https://github.com/valinet/ExplorerPatcher/issues/3728#issuecomment-2366787945

**Comment by pyrates999** [comment] 2024-09-24 22:34
Please wait until this is fixed then.

**Comment by Jazzzed** [comment] 2024-09-26 19:17
The weather widget works fine for me with the Win10 taskbar.

EP version 22621.3880.66.6
Windows 22631.4169

**Comment by DocSilly** [comment] 2024-09-28 06:56
Win 11 build 22631.4169
EP version 22621.3880.66.6

Looks more like Windows Defender started to strike back with yesterdays virus defs
![defender weather dll](https://github.com/user-attachments/assets/141c52a3-6f80-4371-890a-ece77a066b17)

**Comment by Amrsatrio** [comment] 2024-09-28 06:58
@DocSilly The instructions for exclusions tell you to exclude the C:\Program Files\ExplorerPatcher folder since MS will sooner or later flag the individual DLLs...

**Comment by nexusV2** [comment] 2024-09-28 17:14
> The weather widget works fine for me with the Win10 taskbar.
> 
> EP version 22621.3880.66.6 Windows 22631.4169
> 
> ![EP](https://private-user-images.githubusercontent.com/125325036/371287561-060b30ed-97e2-455a-b50c-9da90c1149a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDMwOTksIm5iZiI6MTcyNzU0Mjc5OSwicGF0aCI6Ii8xMjUzMjUwMzYvMzcxMjg3NTYxLTA2MGIzMGVkLTk3ZTItNDU1YS1iNTBjLTlkYTkwYzExNDlhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQxNjU5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjQwMDY2ZjkzMDIyOTM2MmRhMjhiNzRmN2Q3MzEyNTNjYWQ3MjNmNWRlODgzYjVlZWQzZDcyZWI5M2FmMDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uPwdqUxNvFkk6xCy4l-rE_M4SBd-64yHIY-SzXbyb-Q)

Strange, even when it was still working, I always had the Google overlay on top when displaying it. like I thought everyone has.
So for me, it was actually only the weather display directly in the taskbar that was interesting.
Maybe you just have sufficient image editing skills...^^

**Comment by Jazzzed** [comment] 2024-09-28 21:38
>Maybe you just have sufficient image editing skills...^^

Conspiracy theories? Wipe the drool off your keyboard.

**Comment by nexusV2** [comment] 2024-09-29 08:27
> > Maybe you just have sufficient image editing skills...^^
> 
> Conspiracy theories? Wipe the drool off your keyboard.

That can't happen because my keyboard is wrapped in aluminum foil.

**Comment by nexusV2** [comment] 2024-09-29 08:49
@Amrsatrio
Since when is the weather widget overlay issue fixed?

I noticed that when deleting the weather widget data, an error alert appears. Could this have something to do with the missing widget, because Defender is still blocking some EP directories, although everything is working fine, except for the weather widget?

I have allowed the following files/directories and excluded threats:

    download/..../explorer patcher/ep_setup.exe
    download/..../explorer patcher/
    HackTool
    /EplorerPatcher!MTB

**Comment by nexusV2** [comment] 2024-09-29 11:14
Finally went back to version 22621.3880.66.5, where the weather widget started working again, but the update function wasn't. So I manually updated to the current 22621.3880.66.6, and now everything is running fine again.
Thanks to everyone who participated.

**Closed** 2024-10-01 10:21 UTC
