### ISSUE TITLE
Windows 11 22H2 22621.2283 & EP V22621.2361.58.4 - File Explorer/Taskbar and most features dosen't work after unknown software installed

### ISSUE THREAD

**Issue by GitPopcorn** [valinet/ExplorerPatcher#2260] opened 2023-10-07 04:47 UTC
At first I think all the configurations under `File Explorer` were out of work, but then I found it the context-menu disabling still work.

I have enable the console but not found any error message responsible for this.

I have uninstall and install and reboot for serveral times. I'm certain it's not something about wrong installation.

I have uninstall the Stardock Start11 to avoid some unknown conflict, but it still did not work.

Just don't know why it does not affect...

Here is my settings:
![Snipaste_2023-10-07_12-43-50](https://github.com/valinet/ExplorerPatcher/assets/31797624/4e1ba3ef-270e-4514-92ab-b785e334c957)

And here is the console output, will it just said the "GUI" thread start.
![Snipaste_2023-10-07_12-41-26](https://github.com/valinet/ExplorerPatcher/assets/31797624/d8ade108-56da-4e34-8e4f-f582cdac783c)

**Comment by GitPopcorn** [comment] 2023-10-07 05:13
Be doubt of compatibility issue, I tried downgrade EP to `22621.2283.57.2` to suit my OS version `22621.2283`, purely uninstallation before installing it.
Sadly, it still shows the Windows 11 styled command bar.
I starts to doubt that what's wrong with my system... I init it serveral days ago. I could say that there is no many factors to prevent EP from working...

**Comment by Amrsatrio** [comment] 2023-10-07 06:59
Try disabing "launch explorer in a separate process", and of course, update EP to the latest one.

**Comment by GitPopcorn** [comment] 2023-10-07 07:07
> Try disabling "launch folders in a separate process" or something in Folder Options, and of course, update EP to the latest one.

Thanks for you reply, but I did disable the explorer option "launch folders in a separate process".

And for the EP, I have tried the latest version `22621.2361.58.4` and older one `22621.2283.57.2`, but neither worked.

I wonder if there were some way to detect which part of enviroment has caused this.

**Comment by pyrates999** [comment] 2023-10-08 11:48
can you show an example of what you mean?

**Comment by GitPopcorn** [comment] 2023-10-08 12:36
> can you show an example of what you mean?

Sry, but I don't know how to create a minimum reproducible sample or sandbox either...
All the behaviors I got is that the modification to file explorer command bar control interface is just not unenforced, no more informations...

**Comment by pyrates999** [comment] 2023-10-09 04:35
Then it may not be possible.  You'll have to wait and see if someone knows about this.

**Comment by GitPopcorn** [comment] 2023-10-09 04:50
> Then it may not be possible. You'll have to wait and see if someone knows about this.

Ok, I will continue to do some test under clean Windows 11 installation after I finish a complete backup.

**Comment by GitPopcorn** [comment] 2023-10-09 18:27
> Then it may not be possible. You'll have to wait and see if someone knows about this.

Finally I got a successful test result after reset the system...

It seems to be responsbile for the product `Stardock Start11`. This time I installed EP firstly and got the correct changes of explorer control style.

Maybe this issue could be closed.

**Comment by GitPopcorn** [comment] 2023-10-09 18:28
Issue closed

**Comment by GitPopcorn** [comment] 2023-10-09 20:41
D**m it! It just lose control to all the components when I install all the software back, and I'm to tired to found it at first time so I have lost the best chance to know who finally did this. The `Stardoc Start11` just worked well with EP. I don't know which f****d s**t was torturing me at early morning to take my time of sleep for almost 30 hours!

It may be caused by:

- TrayStatus, a tray icon plugin
- .NET 7 runtime,  brought by TrayStatus
- Office 365
- Office Tab, a office plugin
- Onetastic, a OneNote plugin
- OneNoteGEM, a OneNote plugin
- Visio 2019 Pro

...

**Comment by Amrsatrio** [comment] 2023-10-09 20:45
I can only try to fix if it can be reproduced... Sorry for your situation though.

**Comment by GitPopcorn** [comment] 2023-10-09 20:59
> I can only try to fix if it can be reproduced with clear steps... Sorry for your situation though.

Sry for that, I was just too helpless about this, I'll try to figure it out tomorrow or next day, I just can't hold my consciousness now...

**Comment by GitPopcorn** [comment] 2023-10-09 21:26
> I can only try to fix if it can be reproduced with clear steps... Sorry for your situation though.

By the way The target I suspect the most is `OneNoteGem`, which provide a similar feature to switch from new ribbon to a classic one for OneNote 2021.

I think it must have modified some important common *.dll to achieve it, and never recover the librabries back after that. So my PE can not take affect no matter how I unstall or install: only feature related to system native settings will affect after that. All others used a symbol broken.

The evidence is that the `Switch to classic ribbon` feature can never be uninstall or rollback once you install it. No mattern uninstall the `OneNoteGem`, or the `Microsoft 365`, it will just appear again after you re-install it.

Here is the introduction of this feature:

[How to Switch Between the Classic Ribbon and the Simplified Ribbon Layout in OneNote 2021?](http://wwww.onenotegem.com/a/faq/win-office-onenote/2023/0521/switch-classic-simplified-ribbon.html)

**Comment by pyrates999** [comment] 2023-10-10 04:19
Check what happens when using the console in explorer patcher.  Open up the properties application for explorer patcher, go to advanced, and click on enable console.

**Comment by Amrsatrio** [comment] 2023-10-26 03:24
I assume that you have identified the cause of this issue. Since this is specific to your programs, I will be closing this issue.

**Closed by Amrsatrio** 2023-10-26 03:24 UTC
Labels: Can't Repro
