### ISSUE TITLE
Disable recommended section not working.

### ISSUE THREAD

**Issue by N0tAvai1able** [valinet/ExplorerPatcher#3748] opened 2024-09-29 12:16 UTC
![image](https://github.com/user-attachments/assets/4d5e5d8e-17b6-4b16-8e45-59627466fb44)
![image](https://github.com/user-attachments/assets/3e88b4ef-0737-439b-a3e6-80cb4ca70d6b)
![image](https://github.com/user-attachments/assets/c1b74add-cfdf-47d3-85d7-a9c436e56c77)

as you can see through these images that the recommended disabler is not working. i have tried restarting file explorer too.

**Comment by pyrates999** [comment] 2024-09-29 13:48
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3313

please close this and comment there with what you found.

**Closed** 2024-09-29 16:49 UTC
