### ISSUE TITLE
Unable to display dynamic tiles

### ISSUE THREAD

**Issue by Xuan080731** [valinet/ExplorerPatcher#2777] opened 2024-02-04 02:33 UTC
![Uploading 螢幕擷取畫面 2024-02-04 103154.png…]()

**Comment by pyrates999** [comment] 2024-02-04 03:51
unable to view image.

**Comment by pyrates999** [comment] 2024-02-04 03:51
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.  These should be screen shots.

Please include any other software you have installed that modifies the UI of windows.

**Comment by Xuan080731** [comment] 2024-02-04 07:01
> 無法查看圖像。

![スクリーンショット 2024-02-04 125001](https://github.com/valinet/ExplorerPatcher/assets/68540734/7c6d02e9-3563-408a-9ddb-7c4bcd8a589e)
![image](https://github.com/valinet/ExplorerPatcher/assets/68540734/82df5c28-f951-4541-af39-2f327a3695b0)
![スクリーンショット 2024-02-04 125001](https://github.com/valinet/ExplorerPatcher/assets/68540734/24ba8e1a-e1f7-4ffe-8a6b-72adfe6bc79c)
Edition	Windows 11 Home
Version	23H2
Installed on	‎2023/‎12/‎6
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0
![image](https://github.com/valinet/ExplorerPatcher/assets/68540734/428b899b-1ae7-4235-97d2-2e0145de930f)

**Comment by pyrates999** [comment] 2024-02-04 08:18
Please post the version of EP that you installed.  You can find out by going to about in the EP properties application.

You also seem to be running a preview update for windows 11: https://support.microsoft.com/en-au/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028

If this issue started showing up after you installed it, I would uninstall it and not install preview updates in the future.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

This is also a duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1621

Please close this.

**Comment by Amrsatrio** [comment] 2024-02-04 10:49
Live tiles have always been unstable in 22621 onwards. We have no plans of fixing it as Microsoft has removed the Windows 10 start menu in 26xxx builds.

**Closed by Amrsatrio** 2024-02-04 10:49 UTC
