### ISSUE TITLE
Taskbar items disappear after opening laptop lid

### ISSUE THREAD

**Issue by stanciupaul** [valinet/ExplorerPatcher#1458] opened 2023-05-16 08:34 UTC
Open taskbar items disappear after opening laptop lid when an external monitor is connected. The ExplorerPatcher then needs to be restarted in order for the items to reappear on the taskbar.

`Version 22621.1555.55.1`

**Comment by pyrates999** [comment] 2023-05-16 09:15
Do you mean windows explorer needs to be restarted?  Have you tried rebooting first and then seeing if this happens again?

**Comment by heckradr** [comment] 2023-05-16 09:19
I can confirm that. That also occurs if you switch your monitors with a KVM switch. The taskbar is empty and when you press ALT+TAB (switch windows) the items reappear in the taskbar.

**Comment by stanciupaul** [comment] 2023-05-16 09:29
> Do you mean windows explorer needs to be restarted? Have you tried rebooting first and then seeing if this happens again?

No, I mean the ExplorerPatcher. Issues occurs since months ago, so yes, the computer was restarted :)

**Comment by pyrates999** [comment] 2023-05-16 19:59
Now can you try uninstalling explorer patcher and see if this still is happening.

**Comment by Amrsatrio** [comment] 2023-10-25 13:46
I don't experience this issue with my laptop (2560x1600 175%) when connected to an external display (2560x1440 125%).

Closing this since there seem to be no more responses.

**Closed by Amrsatrio** 2023-10-25 13:46 UTC
