### ISSUE TITLE
In the Windows 10 start menu style, MS Store apps don't show

### ISSUE THREAD

**Issue by zHackro** [valinet/ExplorerPatcher#1243] opened 2023-04-02 13:27 UTC
Basically, none of the MS Store apps (or MS Store itself) aren't anywhere in the all apps list, which is kind of annoying.
![image](https://user-images.githubusercontent.com/94539969/229355782-379c8ef2-50fb-476d-9f78-6ed73173ca46.png)

**Comment by Vipin2003** [comment] 2023-04-02 13:33
Already known...see #1108

**Comment by djcholapin** [comment] 2023-04-03 00:55
Discovering #1108 thanks toi your answer, I had started one as well in https://github.com/valinet/ExplorerPatcher/issues/1187. Best to continue conversation in the first topic. It's 2 weeks old so let's hope for a fix soon.

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:17
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:17 UTC
