### ISSUE TITLE
Explorer Crashing when trying to Right Click on Taskbar

### ISSUE THREAD

**Issue by studiobuttermedia** [valinet/ExplorerPatcher#1714] opened 2023-07-29 14:10 UTC
OS Build: 11 22H2 10.0.22621.2070.
Patcher Build: 22621.1992.56.1 (With Latest Symbols Downloaded and installed this morning 11 am GMT+7, July 29th)

Windows Last Updated: KB5028254 at 11pm, July 28th GMT+7 (Update Require 3 Restarts)
Previous Windows Build: 10.0.22621.1992

Problem: Right Clicking on the Taskbar resulting in a Crash, making Explorer restarting.

**Comment by KarkanAlzwayed** [comment] 2023-07-29 16:05
To add to this, in my case, this only happens when I have the taskbar style set to windows 11. It works fine on the windows 10 style.

**Comment by luciodaou** [comment] 2023-07-29 23:15
Duplicate of #1707

**Comment by Girofox** [comment] 2023-07-30 07:51
You can access EP settings without right-clicking too over start menu or Windows search, just search "explorerpatcher"

**Comment by Poopooracoocoo** [comment] 2023-08-22 11:18
KB5028254 and 22621.2070 was a preview update

**Closed by Poopooracoocoo** 2023-08-22 11:18 UTC
