### ISSUE TITLE
Notifications overlapping taskbar/system tray

### ISSUE THREAD

**Issue by mversion** [valinet/ExplorerPatcher#1788] opened 2023-08-06 09:31 UTC
Windows 11 OS Build: 10.0.22621.2134
ExplorerPatcher: 22621.1992.56.1

Notifications are overlapping the taskbar/system tray making the system tray icons unusable untill notifications are dismissed one by one.

I think this started a few versions back. Not a biggie, but when you have a host of notifications you can't just click on the notification icon on the system tray and get rid of all open notifications. Now you have to click each notification one by one.

![2023-08-06_19-23-57](https://github.com/valinet/ExplorerPatcher/assets/469980/c7ed3868-4e77-4201-9b44-29293240762e)

**Comment by pyrates999** [comment] 2023-08-06 09:37
That is a preview update: https://support.microsoft.com/en-us/topic/july-26-2023-kb5028254-os-build-22621-2070-preview-66161ea6-c106-43e9-bef5-8410ccbd34e8

Uninstall it if you want to use explorer patcher and don't install preview updates in the future: https://github.com/valinet/ExplorerPatcher/wiki/Symbols

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

**Comment by JPFlySolo** [comment] 2023-08-18 14:59
I have this issue too and I already have "Get the latest updates as soon as available" ticked off. This issue seemed to happen after I updated the latest version of the ExplorerPatcher. See screenshots below.

![image](https://github.com/valinet/ExplorerPatcher/assets/28690549/7f3f806e-c804-41bd-98d6-22ebdd8057b9)
![image](https://github.com/valinet/ExplorerPatcher/assets/28690549/914dd0fa-861c-4bcc-894d-c2db6fb5a1a5)
![image](https://github.com/valinet/ExplorerPatcher/assets/28690549/ece946bf-96a8-48d2-a3a0-ac9a59dc43ff)

**Comment by pyrates999** [comment] 2023-08-19 09:30
Could be related to this: https://github.com/valinet/ExplorerPatcher/issues/1759

**Comment by JPFlySolo** [comment] 2023-08-19 15:52
> @pyrates999 Could be related to this: #1759

Sounds right, hopefully it gets resolved soon...

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:28
Closing in favour of #1759

**Comment by valdearg** [comment] 2023-09-10 20:20
Any update on this? It's happened before, have we tried reverting that patch just in case? Anything we can do to help like logs or anything?

**Comment by pyrates999** [comment] 2023-09-11 05:15
Is this bug actually caused by EP?

**Comment by Poopooracoocoo** [comment] 2023-09-11 06:29
It's been here before when new builds on Windows had released that EP didn't support

**Comment by pyrates999** [comment] 2023-09-11 07:39
ah ok

**Comment by Amrsatrio** [comment] 2023-09-23 01:24
Fixed in 22621.2283.57.1.

**Closed by Amrsatrio** 2023-09-23 01:24 UTC

**Comment by PeakeIT** [comment] 2024-03-04 16:28
This is back in the preview update of KB5034848
More of an FYI since this is a preview patch.

**Comment by Amrsatrio** [comment] 2024-03-04 16:31
Please install 63.4 prerelease. I cannot make it into a release at the moment due to MS being wild in terms of flagging EP as virus if it gets spread.

**Comment by PeakeIT** [comment] 2024-03-04 16:34
Confirmed working again in 63.4 on preview patch KB5034848.
