### ISSUE TITLE
Unable to install latest Windows 11 Update when ExplorerPatcher is present

### ISSUE THREAD

**Issue by Erendis42** [valinet/ExplorerPatcher#3833] opened 2024-10-20 08:00 UTC
Needed to uninstall it to be able to continue (Windows 11, version 24H2)

**Comment by pyrates999** [comment] 2024-10-20 10:29
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3830

please close this.

**Comment by Erendis42** [comment] 2024-10-20 10:40
duplicate

**Closed** 2024-10-20 10:40 UTC
