### ISSUE TITLE
Setting File Explorer Control Interface to Windows 10 Ribbon Disables Remember Window Location

### ISSUE THREAD

**Issue by realAllonZ** [valinet/ExplorerPatcher#4006] opened 2024-12-05 21:24 UTC
> ExplorerPatcher 
> Version 22621.4317.67.1
> 
> Microsoft Windows 11 Pro
> OS Build 22631.4460

Not sure how long it has been happening but it was somewhat recently, maybe a month or so. 

Getting pretty annoyed with it, I did some research and found the statement below:

[Setting Explorer to something besides the W11 default window layout causes explorer windows to not save 🗗](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-file-explorer-windows-wont-remember/f597b6e3-fd15-4021-96d6-598191a4e31b#:~:text=setting%20explorer%20to%20something%20besides%20the%20w11%20default%20window%20layout%20causes%20explorer%20windows%20to%20not%20save.)

This made me believe that the issue could involve ExplorerPatcher.

I then started messing around with the settings and found that when I changed the File Explorer Control Interface setting to Windows 11 Command Bar (default), my file explorer window position could now be remembered.

```
Workaround to fix File Explorer window position if you want:

- File Explorer Control Interface Windows 10 Ribbon set
- File Explorer window always in same position

1. Toggle File Explorer Control Interface setting to Windows 11 Command Bar (default)
2. Restart File Explorer
3. Open File Explorer
4. Move File Explorer window to desired location
5. Close File Explorer window
6. Toggle File Explorer Control Interface setting back to Windows 10 Ribbon
7. Restart File Explorer

The File Explorer window should now always open in the desired location if/until this issue can be remedied.
```

**Comment by pyrates999** [comment] 2024-12-06 01:26
Makes sense since that is what MS intends for you to use in windows 11's file explorer.  So that's where the code was put to remember the position, and the other options that EP uses don't have it.

**Comment by Amrsatrio** [comment] 2024-12-09 04:43
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2243

**Closed by Amrsatrio** 2024-12-09 04:43 UTC
