### ISSUE TITLE
Start menu can't popup at the monitor where the mouse located

### ISSUE THREAD

**Issue by niodx** [valinet/ExplorerPatcher#3718] opened 2024-09-19 02:06 UTC
It always showed in main monitor, and I tried always shows in monitor #2, but still not working.

EP version: 22621.3880.66.6
WIN11 23H2 22631.4169

**Comment by milesprower2293** [comment] 2024-09-19 06:16
Duplicate of #1529, please close this

**Closed** 2024-09-19 06:32 UTC
