### ISSUE TITLE
right click on recycle bin cause windows explorer to restart

### ISSUE THREAD

**Issue by Punisherbio** [valinet/ExplorerPatcher#2673] opened 2024-01-10 10:01 UTC
right click on recycle bin cause windows explorer to restart

**Comment by pyrates999** [comment] 2024-01-10 10:27
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2218

please close this

**Comment by Amrsatrio** [comment] 2024-01-10 10:55
Duplicate of #2218

**Closed by Amrsatrio** 2024-01-10 10:55 UTC
