### ISSUE TITLE
Unpin shortcut from taskbar, but didn't delete the shortcut

### ISSUE THREAD

**Issue by HumanMus1c** [valinet/ExplorerPatcher#1210] opened 2023-03-29 07:25 UTC
If pin this app to taskbar again, it will make a copy rename with XXX(2)(3)

**Comment by redkurn** [comment] 2023-07-03 05:18
having a similar issue, but mine just won't unpin.

**Comment by pyrates999** [comment] 2023-07-03 06:19
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Amrsatrio** [comment] 2023-10-28 22:01
This doesn't happen with the recent builds of Windows 11 22H2 and EP. Closing this issue.

**Closed by Amrsatrio** 2023-10-28 22:01 UTC
