### ISSUE TITLE
Taskview has stopped working in windows 10 mode.

### ISSUE THREAD

**Issue by pauljackman2023** [valinet/ExplorerPatcher#1815] opened 2023-08-10 11:41 UTC
After the windows update on 10/08/23 the windows 10 taskview has stopped working on my PC. It works in windows 11 mode but I cannot have ungrouped windows with labels in windows 11 mode. below is my current windows build info & device info

Edition	Windows 11 Home
Version	22H2
Installed on	‎21/‎09/‎2022
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

Device name	HP-Laptop
Processor	AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx     2.30 GHz
Installed RAM	16.0 GB (13.9 GB usable)

System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

**Comment by guozhongxin** [comment] 2023-08-10 13:24
I got the same proplem too

**Comment by johnny-paradigm** [comment] 2023-08-10 13:47
Duplicate of #1801

**Comment by pyrates999** [comment] 2023-08-10 13:50
Please close this and comment on https://github.com/valinet/ExplorerPatcher/issues/1801

**Comment by pauljackman2023** [comment] 2023-08-10 14:18
closed, please use #1801

**Closed** 2023-08-10 14:18 UTC
