### ISSUE TITLE
Win11 24H2  - "Pin to start" is not working

### ISSUE THREAD

**Issue by vladtepesch** [valinet/ExplorerPatcher#3992] opened 2024-11-30 20:49 UTC
Selecting "Pin to Start" (is it called like this? in german win its called 'an "Start" anheften') does not work.

I only could manage to drag from left side to the Tiles area.
![grafik](https://github.com/user-attachments/assets/d2917fc4-c5d2-4c84-8dee-17f54eab11ca)

But I have not found a way to add Tiles from start search results or from shortcuts from explorer.

Is this bugged or how is it supposed to work?

**Comment by RepeatedKibbles** [comment] 2024-12-01 01:51
Same here

**Comment by pyrates999** [comment] 2024-12-01 03:46
Try pinning the exe instead of a shortcut to the exe.

**Comment by mustafatoktas** [comment] 2024-12-01 07:04
I am using 23h2. Pin to start does not work for me either.

**Comment by SimonKomenda** [comment] 2024-12-01 09:20
+1

**Comment by shenhaipaopaoa** [comment] 2024-12-02 07:43
Same here

**Comment by pyrates999** [comment] 2024-12-02 09:20
try what this comment did: https://github.com/valinet/ExplorerPatcher/issues/3991#issuecomment-2510479585

**Comment by shenhaipaopaoa** [comment] 2024-12-02 10:01
> try what this comment did: [#3991 (comment)](https://github.com/valinet/ExplorerPatcher/issues/3991#issuecomment-2510479585)试试这条评论是做什么的： [#3991 (comment)](https://github.com/valinet/ExplorerPatcher/issues/3991#issuecomment-2510479585)

Full-screen start menu. The shortcut in the All Programs column still doesn't show the "Pin to Start" option. However, it can be displayed in other options

**Comment by RagingDraugr** [comment] 2024-12-02 11:56
I'm having the same issue on Win11 23h2 and the latest version of EP 22621.4317.67.1. I can drag exes from the start menu to the pinned apps section but I can't unpin them by right clicking once I do so. A workaround I've found is to drag whatever tiles I want deleted from the pinned menu into it's own group, right click the group header and click "Unpin group from start" which removes the group and the tile along with it.

**Comment by Amrsatrio** [comment] 2024-12-09 04:50
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3984

**Closed by Amrsatrio** 2024-12-09 04:50 UTC
