### ISSUE TITLE
Cannot Right click apps or open start menu

### ISSUE THREAD

**Issue by OwONaw** [valinet/ExplorerPatcher#2030] opened 2023-09-09 15:12 UTC
I can right click the taskbar just fine, but not apps. I also cannot open the start menu in any way. I am really annoyed by this and it is not the first time it happened. I wish to know how to fix this issue or uninstall ExplorerPatcher.
Version 22621.1344.53.1
Windows 11 22H2

**Comment by pyrates999** [comment] 2023-09-09 21:37
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1828

Please close this one.

Possible fix: In ExplorerPatcher Properties, go to Advanced and tick "Do not change the taskbar context menu"

**Comment by ircserkan** [comment] 2023-09-09 21:39
> I can right click the taskbar just fine, but not apps. I also cannot open the start menu in any way. I am really annoyed by this and it is not the first time it happened. I wish to know how to fix this issue or uninstall ExplorerPatcher. Version 22621.1344.53.1 Windows 11 22H2

Hello @OwONaw 

ExplorerPatcher gave me the same error. When I made the Start Menu windows 10 from the ExplorerPatcher settings, the problem disappeared. I'm checking to see if there is an update. Now I found a solution like this. If you say I'm bored now and want to remove it. You can uninstall the application from the control panel.

**Closed** 2023-09-10 10:57 UTC
