### ISSUE TITLE
When taskbar is in vertical, user account/profile icon display is cropped

### ISSUE THREAD

**Issue by philithub** [valinet/ExplorerPatcher#3973] opened 2024-11-26 19:44 UTC
Clicking user account/profile icon shows: 'Username', 'Manage my account', and 'Sign Out'.
It displays correctly with horizontal taskbar but is cropped when vertical.

**Comment by milesprower2293** [comment] 2024-11-26 20:11
Duplicate of: #3464

**Closed by milesprower2293** 2024-11-26 20:11 UTC
