### ISSUE TITLE
Microsoft sore app fail to appear in start menu of explorerpatcher window 10 style.

### ISSUE THREAD

**Issue by Melktad** [valinet/ExplorerPatcher#1587] opened 2023-06-24 19:07 UTC
Microsoft store and app from Microsoft store are not appearing in start menu and cannot pinned to window 10.

**Comment by pyrates999** [comment] 2023-06-25 05:15
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/1108

**Comment by Vipin2003** [comment] 2023-06-25 10:13
Full solution : 

https://github.com/valinet/ExplorerPatcher/issues/1534#issuecomment-
1601017536

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:12
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:12 UTC
