### ISSUE TITLE
Crash and restart explorer with KB5029263 Build 22621.2134

### ISSUE THREAD

**Issue by MaybeAnge** [valinet/ExplorerPatcher#1911] opened 2023-08-23 17:40 UTC
Crash on last update: [22621.1992.56.3](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.1992.56.3_5bda71f)

**Comment by arcaeatairitsu** [comment] 2023-08-23 18:03
also crashes with KB5029351

**Comment by Edwin-Baranov** [comment] 2023-08-23 18:11
Latest version currently crashes as soon as I right click on taskbar

**Comment by VasiliyIsaichkin** [comment] 2023-08-23 18:23
Crash on 22621.2215

**Comment by nhnduy** [comment] 2023-08-23 19:06
> also crashes with KB5029351

Yes. It keeps crashing with Windows Update KB5029351.

**Comment by r00tl34k** [comment] 2023-08-23 19:24
Crash all time with the last release.

**Comment by Poopooracoocoo** [comment] 2023-08-23 20:47
Duplicate of #1798

**Closed by Poopooracoocoo** 2023-08-23 20:47 UTC
