### ISSUE TITLE
24h2 system icon battery won't trigger windows 10 flyout

### ISSUE THREAD

**Issue by jw0785** [valinet/ExplorerPatcher#3990] opened 2024-11-30 03:23 UTC
set Battery: Windows 10 flyout doesn't work.

**Comment by Panzimy** [comment] 2024-11-30 06:50
As said 24H2 is not fully supported and isn't recommended

**Comment by pyrates999** [comment] 2024-11-30 15:41
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3640

please close this.

**Closed** 2024-11-30 18:03 UTC
