### ISSUE TITLE
W11 23H2 File Explorer Not working, not found, cant install.

### ISSUE THREAD

**Issue by RyzeNGrind** [valinet/ExplorerPatcher#2945] opened 2024-03-06 21:57 UTC
I have tried to allow manually quarantined threat on malwarebytes and defender after it was detected as false positive. Since then, i guess I didn't notice but FileExplorer no longer works, is visible, and I cannot install it either, just tried rebooting and installing.

Microsoft Windows Version 23H2 OS Build 22631.3235

**Comment by pyrates999** [comment] 2024-03-07 08:09
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/2873

This is a false positive.

Update your windows defender signatures by going to settings -> updates & security -> windows security
Then click on virus & threat protection
Under virus & threat protection updates, click on check for updates
Then click on the button named check for updates

Then if it is still being detected as malicious, submit it as a false positive to Microsoft: https://www.microsoft.com/en-us/wdsi/filesubmission

**Closed** 2024-03-09 12:26 UTC
