### ISSUE TITLE
alt tab

### ISSUE THREAD

**Issue by Epixx512** [valinet/ExplorerPatcher#1912] opened 2023-08-23 18:06 UTC
alt tab doesnt work sometimes

**Comment by Darkenoid** [comment] 2023-08-23 18:31
Same here, it breaks when pressing start + tab.
Quick fix is to restart file explorer.

**Comment by Poopooracoocoo** [comment] 2023-08-23 20:46
Duplicate of #1687

**Closed by Poopooracoocoo** 2023-08-23 20:46 UTC
