### ISSUE TITLE
Rightclicking a file in File Explorer crashes newly updated ExplorerPatcher 22621.2428.59.1 dated 10-nov-2023

### ISSUE THREAD

**Issue by boonduck** [valinet/ExplorerPatcher#2422] opened 2023-11-10 20:10 UTC
### Discussed in https://github.com/valinet/ExplorerPatcher/discussions/2420

<div type='discussions-op-text'>

<sup>Originally posted by **boonduck** November 10, 2023</sup>
I just updated ExplorerPatcher to latest version 22621.2428.59.1 dated 10-nov-2023. 
Right after restarting, I fired up file Explorer and browsed to the download folder to locate a PDF.
I rightclicked the PDF and it took 3-5 seconds before Windows responded, where it usually takes only half a second to respond.
This time not with the contextmenu but with a crash and restart of Explorer, showing the desktop again.
After analysing the issue, I started to suspect ExplorerPatcher and uninstalled it in the usual way.
Without even rebooting I fired up File Explorer again and repeated rightclicking the PDF with now bringing up the contextmenu as expected.
Can you please solve this? Let me know if you need more information.

My config:
Windows version: Windows 11 version 22H2 (OS build 22621.2428)
ExplorerPatcher version: 22621.2428.59.1
No antivirus software installed other then the default Windows 11 one.

Thanks,
--boonduck
</div>

**Comment by pyrates999** [comment] 2023-11-10 22:52
Please include what settings you changed in explorer patcher properties application.

**Comment by boonduck** [comment] 2023-11-10 23:36
I didn't change any settings after ExplorerPatcher updated. But I guess ExplorerPatcher retains the properties I had already set? In that case I'll check what settings I had changed.

**Comment by boonduck** [comment] 2023-11-11 00:33
Just re-installed latest ExplorerPatcher version 22621.2428.59.1 on my Windows 11 machine. Did not change any setting and just assumed the default settings. Started File Explorer and navigated to the Download folder. Rightclicked on empty whitespace in the right panel and BOOM -- File Explorer crashes. Let me know if you need more information.

**Comment by boonduck** [comment] 2023-11-11 00:47
EventViewer > Application log reports:

```
Event ID 1000: Application Crashing Events
Faulting application name: explorer.exe, 10.0.22621.2428, time stamp: 0xaab5a73e
Faulting module name: ntdll.dll, 10.0.22621.2428, time stamp: 0x806d3ecf
Exception code: 0xc0000374
Fault offset: 0x000000000010c849
Faulting process ID: 0x0x1FFC
Faulting application start time: 0x0x1DA14373276F9E5
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll

```
I thought this might help.
--straycat

**Comment by Amrsatrio** [comment] 2023-11-11 03:23
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2218

**Closed by Amrsatrio** 2023-11-11 03:23 UTC
