### ISSUE TITLE
ep_setup.exe crashing after gray screen

### ISSUE THREAD

**Issue by derrickm1** [valinet/ExplorerPatcher#1285] opened 2023-04-10 03:42 UTC
Trying to install this and that is the result I get. I launch it as an admin, my screens go gray, file explorer crashes and I get an error message stating "This is most likely caused by one or more of the backup files from a previous update still being in use. Unlocking the files should fix this issue". What does this mean? How do I fix it?

**Comment by pyrates999** [comment] 2023-04-13 23:02
this appears to be a duplicate of https://github.com/valinet/ExplorerPatcher/issues/1307

**Closed** 2023-09-23 04:45 UTC
