### ISSUE TITLE
Can't use win10 taskbar when updated

### ISSUE THREAD

**Issue by win4r** [valinet/ExplorerPatcher#341] opened 2021-11-14 07:11 UTC
Can't use win10 taskbar when updated today.

**Comment by win4r** [comment] 2021-11-14 07:42
![屏幕截图 2021-11-14 154027](https://user-images.githubusercontent.com/42172631/141672201-163f52cd-f258-49aa-9a13-db46c7531d4b.png)
_``_
![屏幕截图 2021-11-13 145056](https://user-images.githubusercontent.com/42172631/141672215-e2823126-9a4a-4e3b-89f7-82641e93c78b.png)

**Comment by BraINstinct0** [comment] 2021-11-14 08:18
Duplicate of #334

**Comment by BraINstinct0** [comment] 2021-11-14 08:20
Currently either downgrading Windows to 22000.314/ temporarily disable ExplorerPatcher,
and waiting for ExplorerPatcher's next release(or, if possible, fix&make PR) is what I'd recommend. (valinet already knows the issue so probably it will be mitigated soon)

**Comment by valinet** [comment] 2021-11-14 19:23
Built-in support for 22000.346 release preview has been included in the latest version. I will close this issue now, as I consider it solved.

Thanks

**Closed by valinet** 2021-11-14 19:23 UTC
