### ISSUE TITLE
23H2 22631.3880 intercepts prerelease update 3880.66.3

### ISSUE THREAD

**Issue by phoenX80** [valinet/ExplorerPatcher#3506] opened 2024-07-25 06:54 UTC
EP was fine until I tried to update today coming from 22621.3527.65.5.
Windows intercepts with "cannot be executed ont his machine" without a bypass.
I have EP directory and the AppData directory whitelisted - anything else I can try or do I need to switch Windows build?
Regards
Peter

**Comment by J1GGY37** [comment] 2024-07-25 08:25
> EP was fine until I tried to update today coming from 22621.3527.65.5. Windows intercepts with "cannot be executed ont his machine" without a bypass. I have EP directory and the AppData directory whitelisted - anything else I can try or do I need to switch Windows build? Regards Peter

Download the exe and run as administrator (Disable AV) ... worked for me.

**Comment by phoenX80** [comment] 2024-07-25 10:29
If I download standard it's ok, but the prerelease version is then also caught. I did not try renaming yet etc.

**Comment by J1GGY37** [comment] 2024-07-25 10:44
> If I download standard it's ok, but the prerelease version is then also caught. I did not try renaming yet etc.

this exe worked for me : https://github.com/valinet/ExplorerPatcher/releases

**Comment by Amrsatrio** [comment] 2024-07-25 12:07
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3505

**Closed by Amrsatrio** 2024-07-25 12:07 UTC
