### ISSUE TITLE
Windows Explorer crashes when i right click on the taskbar on Windows 11. Explorer Patcher Version: Latest. Windows Version:22H2 1000.22659.1000.0.

### ISSUE THREAD

**Issue by GovenorKratos** [valinet/ExplorerPatcher#1919] opened 2023-08-24 04:51 UTC
Firstly, I would like to start off by thanking you for your hard work in making amazing apps like these. I've been using EP for about 6 months now, and it is something that i've found myself using on almost all of my windows machines.

Since about 2 weeks ago, whenever i right-click on the taskbar on the latest Windows 11 install, Windows explorer crashes and reloads (So i can't see the context menu). I've found no work-around for this and it's been happening for about 2 weeks now. I'm using the windows 11 taskbar with the windows 10 start menu (normal). This is my only tweak. I've tried using the windows 10 taskbar and that fixes my problem (although it's not as functional as the windows 11 taskbar e.g. Bluetooth).

**Comment by Girofox** [comment] 2023-08-24 07:12
To fix the right-click crashing you can uncheck `Do not change the taskbar context menu` in EP settings as a workaround.

<img width="485" alt="fix" src="https://github.com/valinet/ExplorerPatcher/assets/43116061/63a744fa-1fab-44bd-bbe4-f2eb788f21ce">

### Shortcut to EP settings in Windows Search bar:

<img width="485" alt="fix" src="https://github.com/valinet/ExplorerPatcher/assets/43116061/136bdf5e-e594-453b-b710-39ee15c6fe9f">

**Comment by Poopooracoocoo** [comment] 2023-08-24 08:29
Duplicate of #1805

**Closed by Poopooracoocoo** 2023-08-24 08:29 UTC
