### ISSUE TITLE
Weather display uses a lot of CPU

### ISSUE THREAD

**Issue by stardepp** [valinet/ExplorerPatcher#2880] opened 2024-02-21 12:22 UTC
If the weather display is activated in the taskbar, a lot of CPU is consumed and the fan turns up to full speed.
If you close the weather display, this error stops.

![Task-Manager-stgru 21-02-2024 13_17_18](https://github.com/valinet/ExplorerPatcher/assets/40627059/4ed42805-f284-4978-8816-ec01ec668af2)

**Comment by doterik** [comment] 2024-02-21 18:18
@twistios I can confirm that this seems to be a duplicate...
My problem also started about the time that issue was reported.

Hadn't meant to file an issue but stumbled on this one when I was searching for today’s virus warning, and not been able to upgrade.

**Comment by Amrsatrio** [comment] 2024-02-21 19:18
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2096

**Closed by Amrsatrio** 2024-02-21 19:18 UTC
