### ISSUE TITLE
Win 10 start menu in win 11 bug

### ISSUE THREAD

**Issue by SuchyYT** [valinet/ExplorerPatcher#1528] opened 2023-06-06 15:26 UTC
When I set my start menu in win 11 to win 10, not all apps are displayed. I see that apps that are downloaded from Microsoft store don't show up, and some apps that should be in their own folder aren't in their own folder. And some “apps” in start menu aren't even apps…

EDIT: The windows 10 start menu has his own start menu apps folder (I think):
![image](https://github.com/valinet/ExplorerPatcher/assets/86509908/7d27a6e7-c3f4-443f-99fa-537c792e5e3a)

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:14
Closing as duplicate of #1108

**Closed by Poopooracoocoo** 2023-08-22 10:14 UTC
