### ISSUE TITLE
Cant Change Notification Icons

### ISSUE THREAD

**Issue by RolmanIronman** [valinet/ExplorerPatcher#1835] opened 2023-08-12 14:43 UTC
In "Customize Notifications Area Icons" -> Cant Change Hide Icons Options. If change any option, not change anything, and to close window and reopend continue similir without change.

**Comment by pyrates999** [comment] 2023-08-13 00:36
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1454

Please close this one.

**Closed** 2023-09-25 15:57 UTC
