### ISSUE TITLE
right click Win11 Start menu not working 

### ISSUE THREAD

**Issue by ArtooS** [valinet/ExplorerPatcher#3876] opened 2024-11-03 09:18 UTC
I like having the small taskbar so I'm running  ExplorerPatcher  22621.3880.66.6 on win 11 Pro 24H2.  When I set the taskbar style to Windows 10 (ExplorerPatcher) and noticed that I can't bring up the context menu when you right click the Win11 Start button that give a shortcut way to settings such as Installed Apps, System, Device Manger, Terminal, Terminal (Admin), etc...

Did I miss seeing a setting that allows that context menu to show up when using the Windows 10 (ExplorerPatcher) taskbar style?

**Comment by pyrates999** [comment] 2024-11-03 09:46
install the pre-release: https://github.com/valinet/ExplorerPatcher/releases

it fixes when you try right clicking on the start menu button: https://github.com/valinet/ExplorerPatcher/issues/3837

**Comment by Amrsatrio** [comment] 2024-11-03 11:16
Duplicate of #3837

**Closed by Amrsatrio** 2024-11-03 11:16 UTC
