### ISSUE TITLE
shut down button isn't rounded when highlighting

### ISSUE THREAD

**Issue by GentlemanMC** [valinet/ExplorerPatcher#1879] opened 2023-08-21 03:09 UTC
floating start menu looks like this when highlighting the button
![image](https://github.com/valinet/ExplorerPatcher/assets/76640636/45ccfc60-02df-48e4-8d3c-d1c1b7d784ea)

and also this button is kinda offset and makes the window not rounded too
![image](https://github.com/valinet/ExplorerPatcher/assets/76640636/8a0de5a3-c744-407e-86a4-0f920e49ea0a)
when pressed
![image](https://github.com/valinet/ExplorerPatcher/assets/76640636/b049f7ba-70db-438f-b3be-252a6fac89db)

**Comment by pyrates999** [comment] 2023-08-21 03:23
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application you changed.

**Comment by GentlemanMC** [comment] 2023-08-21 03:45
windows 11 build 22621.2134
ep version: 22621.1992.56.1

and here are my ep settings (github wont let me upload the reg file i exported because the file type is not supported)

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ImportOK"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"OldTaskbar"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_TaskbarPosition"=dword:00000003
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_MMTaskbarPosition"=dword:00000003
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
"SearchboxTaskbarMode"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowTaskViewButton"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_AutoHideTaskbar"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"OrbStyle"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"OldTaskbarAl"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"MMOldTaskbarAl"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"TaskbarGlomLevel"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"MMTaskbarGlomLevel"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"TaskbarSmallIcons"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"SkinMenus"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"CenterMenus"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"FlyoutMenus"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7]
"TipbandDesiredVisibility"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowSecondsInSystemClock"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"HideControlCenterButton"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"TaskbarSD"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ReplaceNetwork"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Control Panel\Settings\Network]
"ReplaceVan"=dword:00000005
[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\MTCUVC]
"EnableMtcUvc"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ImmersiveShell]
"UseWin32TrayClockExperience"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ImmersiveShell]
"UseWin32BatteryFlyout"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"IMEStyle"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_RegisterAsShellExtension"=dword:00000000
[HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32]
@=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"LegacyFileTransferDialog"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UseClassicDriveGrouping"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_FileExplorerCommandUI"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DisableImmersiveContextMenu"=dword:00000000
[-HKEY_CURRENT_USER\Software\Classes\CLSID\{056440FD-8568-48e7-A632-72157243B55B}\InprocServer32]
@=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_DisableModernSearchBar"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ShrinkExplorerAddressBar"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"HideExplorerSearchBar"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"Start_ShowClassicMode"=dword:00000001
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"TaskbarAl"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_Start_MaximumFrequentApps"=dword:00000006
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StartPage]
"MonitorOverride"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_StartUI_ShowMoreTiles"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_StartUI_EnableRoundedCorners"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_ForceStartSize"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_NoStartMenuMorePrograms"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer]
"AltTabSettings"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_PeopleBand"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"LastSectionInProperties"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ClockFlyoutOnWinC"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ToolbarSeparators"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"PropertiesInWinX"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"NoMenuAccelerator"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DisableOfficeHotkeys"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DisableWinFHotkey"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
;"Virtualized_{D17F1E1A-5919-4427-8F89-A1A8503CA3EB}_DisableRoundedCorners"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DisableAeroSnapQuadrants"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"Start_PowerButtonAction"=dword:00000002
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DoNotRedirectSystemToSettingsApp"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DoNotRedirectProgramsAndFeaturesToSettingsApp"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DoNotRedirectDateAndTimeToSettingsApp"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"DoNotRedirectNotificationIconsToSettingsApp"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdatePolicy"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdatePreferStaging"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdateAllowDowngrades"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdateURL"=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"UpdateURLStaging"=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"AllocConsole"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"Memcheck"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"TaskbarAutohideOnDoubleClick"=dword:00000001
[HKEY_CURRENT_USER\Control Panel\Desktop]
"PaintDesktopVersion"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ClassicThemeMitigations"=dword:00000000
[-HKEY_CURRENT_USER\Software\Classes\CLSID\{1eeb5b5a-06fb-4732-96b3-975c0194eb39}\InprocServer32]
@=""
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"NoPropertiesInContextMenu"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"EnableSymbolDownload"=dword:00000001
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"PinnedItemsActAsQuickLaunch"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"RemoveExtraGapAroundPinnedItems"=dword:00000000
[HKEY_CURRENT_USER\Software\ExplorerPatcher]
"ExplorerReadyDelay"=dword:00000000
```

**Comment by pyrates999** [comment] 2023-08-21 03:56
Ok, but what settings did you change in the explorer patcher properties application or do you not remember?

**Comment by GentlemanMC** [comment] 2023-08-21 04:00
I remember some and here are they
Start menu mode: floating rounded corners
Taskbar mode: windows 10
Wifi flyout: windows 11
Remove actions center from taskbar enabled

**Comment by pyrates999** [comment] 2023-08-21 04:27
I think that's not been working since the May 2023 update.

**Comment by GentlemanMC** [comment] 2023-08-21 04:44
Any plans to fix?
It looks super out of place

**Comment by Poopooracoocoo** [comment] 2023-08-22 10:00
Duplicate of https://github.com/valinet/ExplorerPatcher/discussions/960

**Closed by Poopooracoocoo** 2023-08-22 10:00 UTC
