### ISSUE TITLE
Windows 10 start menu does not work in build 22635.4000

### ISSUE THREAD

**Issue by brjsp** [valinet/ExplorerPatcher#3512] opened 2024-07-27 13:15 UTC
Tested in the latest prerelease: https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.3_c843465

**Comment by FelixDombek** [comment] 2024-07-27 14:12
Does this also contain the issue that the redesigned "current user" menu that shipped with a recent Windows 11 upgrade appears cropped inside EP's Win 10 start menu, or is this a separate issue?
![image](https://github.com/user-attachments/assets/7a71d7b6-1d07-49e8-b1fb-9fff37ee3cbe)

**Comment by brjsp** [comment] 2024-07-27 14:14
@FelixDombek probably separate. Since the latest CU, the new start menu opens for me.

**Comment by Amrsatrio** [comment] 2024-07-27 16:18
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3481

I have a method prepared for this already -- don't worry. EP just needs to ship more files and I'm still figuring a way on how to pack them in the setup.

**Closed by Amrsatrio** 2024-07-27 16:18 UTC
