### ISSUE TITLE
Win 11 taskbar closing and opening & closing again & again endlessly 

### ISSUE THREAD

**Issue by CorpseSlayer** [valinet/ExplorerPatcher#2707] opened 2024-01-16 20:18 UTC
Everything was working just fine and i was pretty happy with ExplorerPatcher not sure exactly
what happen but everything started when i updated win 11 once was install and restarted i went
to input my PIN and as soon windows try to load the Windows Explorer it close & open automatically
over and over and over again endlessly it would even do it on Recovery Mode i am hoping that in future 
releases this has a safe way to disable the program when Windows Explorer is not compatible with the 
program after install thanks in advance..

Winver : Windows 11 23H2 (22631.3007)
Patcher version: Latest (The one in the download section)
I am a noob so i didn't had settings change, default settings
Yes i have a program call TranslucentTB make Taskbar Translucent.

**Comment by pyrates999** [comment] 2024-01-17 00:26
Please post windows version and build.  You can find this by running winver.
Please post explorer patcher version.

Please include what settings you changed in explorer patcher properties application.

Please include any other software you have installed that modifies the UI of windows.

**Comment by geepot** [comment] 2024-01-27 02:04
I have actually run into this issue before. Unfortunately, I have not found a way to reproduce it reliably so I haven't reported it. Always happens after a Windows update, but not every Windows update. The fix for me has been to pop up a command prompt with task manager and uninstall and reinstall ExplorerPatcher from the command line.

**Comment by Amrsatrio** [comment] 2024-02-16 12:11
Hi, does this issue still happen after updating to 22621/22631.3155?

If you were greeted with the OOBE (complete the setup of your device or that kind of wording) and during that moment EP repeatedly crashes, then I'm sure that it should never happen again with the latest prerelease.

**Comment by geepot** [comment] 2024-02-16 18:47
Windows just updated and I saw an update for EP come through and didn't hit any snags this time.

**Comment by Amrsatrio** [comment] 2024-03-17 14:31
Looks like OP's issue is something related to SCOOBE. I've fixed it in 64.1. Closing this issue.

**Closed by Amrsatrio** 2024-03-17 14:31 UTC
Labels: Can't Repro
