### ISSUE TITLE
(WIN11) Search box disapear when i press windows key

### ISSUE THREAD

**Issue by AlexBasura** [valinet/ExplorerPatcher#3137] opened 2024-04-15 07:26 UTC
https://github.com/valinet/ExplorerPatcher/assets/134896436/8548fe1f-05da-4bc0-ad46-72d869f686b3

**Comment by AlexBasura** [comment] 2024-04-15 07:28
don't take much priority of this error bc sometimes i use the win11 taskbar

**Comment by pyrates999** [comment] 2024-04-15 10:53
duplicate of: https://github.com/valinet/ExplorerPatcher/issues/3107

please close this as this isn't planned to be fixed due to windows 11 24h2 removing the windows 10 start menu code entirely.

**Closed** 2024-04-15 18:05 UTC
