### ISSUE TITLE
Unable to use 'alt+tab' and Task View button (or 'win+tab') to change between windows and desktops

### ISSUE THREAD

**Issue by matheusmo14** [valinet/ExplorerPatcher#2098] opened 2023-09-19 22:16 UTC
Hello!

For a few past weeks I'm unable to use 'alt+tab' and 'Task View' or 'win+tab' shortcut to change between desktops. Using 'ctrl+win+left/right' I can navigate between them. 

Windows 11 Home Single Language
Version	22H2
Comp.	22621.2283
Windows Feature Experience Pack 1000.22662.1000.0

Settings: 
Taskbar style: Windows 10 
Window switcher: Windows 11 (changing to Windows 10 or other, 'alt+tab' works but Task view/'win+tab' still don't)

I'm available to help with any other info needed.

**Comment by BraINstinct0** [comment] 2023-09-20 02:17
duplicate of #1687

**Closed** 2023-09-20 03:14 UTC
