### ISSUE TITLE
Taskbar Start Menu Changes Position When Searching

### ISSUE THREAD

**Issue by EebDude** [valinet/ExplorerPatcher#3097] opened 2024-04-06 15:14 UTC
When Task Bar Is Placed On Right Side And I open The Start Menu All Is normal. 

The Start Menu is Opened and is placed at the top Right as it should be, 

But the moment I start typing while it is opened The Start Menu moves itself to the bottom left . as If the Taskbar is placed 
<img width="743" alt="TBAR1" src="https://github.com/valinet/ExplorerPatcher/assets/86921019/7e502049-073e-48af-9321-1ad349734d1e">
<img width="1920" alt="Tbar 2" src="https://github.com/valinet/ExplorerPatcher/assets/86921019/87cf77e4-6557-4b8c-9760-100e834400dd">

**Comment by pyrates999** [comment] 2024-04-07 03:01
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

Please close this.

**Closed** 2024-04-07 14:05 UTC
