### ISSUE TITLE
explorer Functional error on explorer

### ISSUE THREAD

**Issue by let-biuld** [valinet/ExplorerPatcher#2832] opened 2024-02-16 08:27 UTC
Although I chose to use the old address bar of Windows11 in Windows1123H2 22631.3007, it doesn't work.

**Comment by let-biuld** [comment] 2024-02-16 08:29
Sorry, the title should be explorer patcher's function error on explorer.

**Comment by Amrsatrio** [comment] 2024-02-16 09:31
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/2701

**Closed by Amrsatrio** 2024-02-16 09:31 UTC
