### ISSUE TITLE
Search Window Misaligned When Taskbar Is Set to the Right Side on Windows 11

### ISSUE THREAD

**Issue by runningpig66** [valinet/ExplorerPatcher#3937] opened 2024-11-17 03:38 UTC
Hello ExplorerPatcher developers,

When I set the Windows 11 taskbar to the right side of the screen, clicking the search icon on the taskbar causes the search window to still appear in the bottom-left corner of the screen, as shown in the attached image. Could you please let me know how to resolve this issue?
![desktop](https://github.com/user-attachments/assets/cfca5e3b-f8f8-4e2e-9ab1-98c31fd46165)

Thank you!

**Comment by pyrates999** [comment] 2024-11-17 04:03
Duplicate of: https://github.com/valinet/ExplorerPatcher/issues/1803

Please close this.

**Closed** 2024-11-17 05:12 UTC
